In [116]:
import os
import pandas as pd
import json
from datetime import datetime

In [117]:
def transform_time(df, col="time"):
    format = '%Y-%m-%d %H:%M:%S.%f'
    if col == 'time':
        df['time'] = df['time'].apply(lambda x: datetime.strptime(x, format))
    else:
        df[col] = df[col].apply(lambda x: datetime.strptime(x, format))
    return df

def second_difference(d2, d1):
    format = '%Y-%m-%d %H:%M:%S.%f'
    d2 = datetime.strptime(d2, format)
    d1 = datetime.strptime(d1, format)
    return (d2 - d1).seconds

def minutes_difference(d2, d1):
    return second_difference(d2, d1) / 60

In [118]:
# Procedure Progress
procedure_progress_file = '03_procedure_progress.csv'
procedure_progress = pd.read_csv(os.path.join('output', 'intermediate', procedure_progress_file), sep='\t')
procedure_progress = transform_time(procedure_progress, 'time')
display(procedure_progress.head())

procedure_step_ids = procedure_progress['procedure_step_id'].unique()
procedure_step_ids.sort()

display(procedure_step_ids)
display(procedure_progress)

,Unnamed: 0,participant_id,participant_token,participant_state,procedure_progress_id,state,time,procedure_step_id,procedure_id,condition_id,text_id,questionnaire_id,pause_id,procedure_step,conditions_name,conditions_url,texts_title,questionnaires_url
0,49,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1802,start_step,2025-03-06 15:05:22.034989,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
1,50,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1803,end_step,2025-03-06 15:10:21.587074,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
2,51,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1804,start_step,2025-03-06 15:10:21.587074,319.0,58.0,NaN,566.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
3,53,1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,1808,start_step,2025-03-07 21:26:10.427271,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
4,54,1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,1811,end_step,2025-03-07 21:31:20.830539,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...

array([318., 319., 320., 321., 322., 371., 372., 373., 374., 375.])

,Unnamed: 0,participant_id,participant_token,participant_state,procedure_progress_id,state,time,procedure_step_id,procedure_id,condition_id,text_id,questionnaire_id,pause_id,procedure_step,conditions_name,conditions_url,texts_title,questionnaires_url
0,49,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1802,start_step,2025-03-06 15:05:22.034989,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
1,50,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1803,end_step,2025-03-06 15:10:21.587074,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
2,51,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1804,start_step,2025-03-06 15:10:21.587074,319.0,58.0,NaN,566.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
3,53,1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,1808,start_step,2025-03-07 21:26:10.427271,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
4,54,1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,1811,end_step,2025-03-07 21:31:20.830539,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,414,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2251,end_step,2025-08-25 07:28:54.337492,374.0,64.0,NaN,NaN,139.0,NaN,3.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
255,415,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2252,start_step,2025-08-25 07:28:54.337492,375.0,64.0,NaN,579.0,NaN,NaN,4.0,NaN,NaN,Next steps,NaN
256,416,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2253,end_step,2025-08-25 07:28:54.428583,375.0,64.0,NaN,579.0,NaN,NaN,4.0,NaN,NaN,Next steps,NaN
257,279,2463,38811499-e7ca-453e-a57b-86c5dcdee514,in_progress,2108,end_step,2025-08-06 09:48:28.139000,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN
258,345,2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,2176,end_step,2025-08-14 08:43:00.715000,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN

In [119]:
# method to read mongo database collection
def read_collection(file_path):

    # Step 1: Try reading as a JSON array
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError:
        # Step 2: If it's newline-delimited JSON
        with open(file_path, 'r', encoding='utf-8') as f:
            data = [json.loads(line) for line in f]

    # Step 3: Clean MongoDB special fields ($oid, $date, etc.)
    def extract_mongo_specials(obj):
        if isinstance(obj, dict):
            if "$oid" in obj:
                return obj["$oid"]
            if "$date" in obj:
                return obj["$date"]
            return {k: extract_mongo_specials(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [extract_mongo_specials(i) for i in obj]
        return obj

    cleaned_data = [extract_mongo_specials(doc) for doc in data]

    # Step 4: Flatten into DataFrame
    df = pd.json_normalize(cleaned_data)

    return df

In [120]:
# read agents collection
file_path = os.path.join('input/database', 'agent.json')
agents_df = read_collection(file_path)

# read tasks collection
task_path = os.path.join('input/database', 'task.json')
task_df = read_collection(task_path)

In [121]:
# parse generic event

def parse_json_field(event_df, json_field):
    #transform data from str values to dict values
    event_df[json_field + "_parsed"] = event_df[json_field].apply(json.loads)
    #build dataframe from dict values
    event_json_df = pd.json_normalize(event_df[json_field + "_parsed"])
    #reset indexes to concat the dataframes along axis 1 (1:1)
    event_df.reset_index(drop=True, inplace=True)
    event_json_df.reset_index(drop=True, inplace=True)
    return event_json_df

def parse_generic_event(generic_interactions, event = None):
    if event:
        if isinstance(event, list):
            event_df = generic_interactions[generic_interactions['event'].isin(event)]
        else:
            event_df = generic_interactions[generic_interactions['event'] == event]
    else:
        event_df = generic_interactions.copy()
    event_df = event_df[['id', 'time', 'participant_id', 'data', 'event', 'event_uuid', 'participant_token']]
    event_df['time'] = event_df['time'].astype(str)
    event_json_df = parse_json_field(event_df, 'data')
    return pd.concat([event_df, event_json_df], axis=1)

def parse_keyboard_event(keyboard_interactions):
    event_df = keyboard_interactions.copy()
    event_df['time'] = event_df['time'].astype(str)
    event_json_df = parse_json_field(event_df, 'meta_data')
    return pd.concat([event_df, event_json_df], axis=1)

In [122]:
participants_groups = {
    "1": {"users": [1379, 1380], "user_ids": ['67ce982f285fac3f07bcf5e7', '67ce9cb4285fac3f07bcf5ec'], "documents": ["67ce983b285fac3f07bcf5e8"]},
    "2": {"users": [1376, 1377], "user_ids": ['67cb6627285fac3f07bcf59b', '67cb6623285fac3f07bcf59a'], "documents": ["67c97527285fac3f07bcf587"]},
    "3": {"users": [1378, 1374], "user_ids": ['67cc9f69285fac3f07bcf5c8', '67cdfa30285fac3f07bcf5cc'], "documents": ["67c88f88285fac3f07bcf585"]},
    "4": {"users": [1383, 1384, 1385], "user_ids": ['67bc761a7a670b68746905a0', '67d444dd0b9539e69a3a86bb', '67bc43607a670b6874690577'], "documents": ["67d43b390b9539e69a3a86b9"]},
    "5": {"users": [1387, 1390], "user_ids": ['67d5d8120b9539e69a3a86d7', '67e18e95edfe680c1b0f169f'], "documents": ["67d5d8160b9539e69a3a86d8"]},
    "6": {"users": [1388, 1389], "user_ids": ['67d82dc4edfe680c1b0f1642', '67d82e0aedfe680c1b0f1643'], "documents": ["67d08e87285fac3f07bcf64b"]},
    "7": {"users": [2456, 2460], "user_ids": ['68835b0587cf5fec60dc8020', '6887b97087cf5fec60dc8060'], "documents": ["68833fd687cf5fec60dc801d"]},
    "8": {"users": [2453, 2455], "user_ids": ['687de5d187cf5fec60dc7fef', '6880e0f187cf5fec60dc7ffe'], "documents": ["6879e8fd87cf5fec60dc7fe1"]},
    "9": {"users": [2461, 2464, 2457], "user_ids": ['6888eec887cf5fec60dc8085', '688a52ad87cf5fec60dc8096', '688b1c7887cf5fec60dc80b0'], "documents": ["688364bf87cf5fec60dc8026"]},
    "10": {"users": [2459, 2465], "user_ids": ['6888bbce87cf5fec60dc8072', '688bdb6387cf5fec60dc80d0'], "documents": ["6877c26e87cf5fec60dc7fda"]},
    "11": {"users": [2463, 2475], "user_ids": ['6889e71f87cf5fec60dc8094', '68a75365ecc07d2944852275'], "documents": ["6889e57087cf5fec60dc8092"]},
    "12": {"users": [2468, 2469], "user_ids": ['6898407be90ffc190a96c287', '689c3c25e90ffc190a96c28b'], "documents": ["688c6add87cf5fec60dc80ef"]},
    "13": {"users": [2467, 2476], "user_ids": ['68a5a0bde90ffc190a96c2ff', '68a59766e90ffc190a96c2f4'], "documents": ["68907a6e87cf5fec60dc8107"]},
    "14": {"users": [2470, 2471], "user_ids": ['689e2181e90ffc190a96c2df', '689e22d5e90ffc190a96c2e0'], "documents": ["6896071ee90ffc190a96c285"]},
} 


participants_id = [1378, 1374, 1376, 1377, 1379, 1384, 1383, 1385, 1387, 1388, 1389, 1390, 1380]
participants_id_wo_directusers = [1378, 1374, 1376, 1377, 1379, 1387, 1388, 1389, 1390, 1380] #removed 1383 1384 1385
participants_id_study_extended = [2456, 2460, 2453, 2455, 2461, 2464, 2457, 2459, 2465, 2463, 2475, 2468, 2469, 2467, 2476, 2470, 2471]

# join lists
participants_id = participants_id + participants_id_study_extended
participants_id_wo_directusers = participants_id_wo_directusers + participants_id_study_extended

In [123]:
finished_participants_file = '03_finished_participants.csv'
finished_participants = pd.read_csv(os.path.join('output', 'intermediate', finished_participants_file), sep='\t')
display(finished_participants.head())

,Unnamed: 0.1,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
0,0,164,276174.0,cb251ecc-b22b-4ef9-af15-415f3ab90c25,Prototype,2025-03-07 21:32:17.982000,USER_AGENT,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,NaN
1,1,166,276176.0,17b21821-b077-4b06-9db8-b341d36d0301,Prototype,2025-03-07 21:33:27.678000,USER_LOGIN,"{""username"": ""wolfova"", ""participant_token"": ""...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'username': 'wolfova', 'participant_token': '...",NaN
2,2,171,276181.0,c55551a8-7950-417a-aa64-9c323aaee006,Prototype,2025-03-07 21:33:49.699000,DOCUMENT_JOIN,"{""user_id"": ""67cb6627285fac3f07bcf59b"", ""usern...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'user_id': '67cb6627285fac3f07bcf59b', 'usern...",67c97527285fac3f07bcf587
3,3,172,276182.0,65ca58d2-568f-4b16-af2d-718c2e633485,Prototype,2025-03-07 21:33:49.808000,DOCUMENT_VIEW,"{""user_id"": ""67cb6627285fac3f07bcf59b"", ""usern...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'user_id': '67cb6627285fac3f07bcf59b', 'usern...",67c97527285fac3f07bcf587
4,4,173,276183.0,20b1b819-a53b-4619-87e9-fe11dcba2855,Prototype,2025-03-07 21:33:59.815000,DOCUMENT_TEXT_UPDATE,"{""text"": ""<p>Write your text here</p>"", ""user_...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'text': '<p>Write your text here</p>', 'user_...",67c97527285fac3f07bcf587

In [124]:
# Convert to a list of rows
rows = []
for group_id, group in participants_groups.items():
    for i, user in enumerate(group["users"]):
        rows.append({
            "group_id": int(group_id),
            "user": user,
            "user_id": group["user_ids"][i],
            "document": group["documents"][0]
        })

# Create DataFrame our of participants_groups
groups_df = pd.DataFrame(rows)

display(groups_df)

    group_id  user                   user_id                  document
0          1  1379  67ce982f285fac3f07bcf5e7  67ce983b285fac3f07bcf5e8
1          1  1380  67ce9cb4285fac3f07bcf5ec  67ce983b285fac3f07bcf5e8
2          2  1376  67cb6627285fac3f07bcf59b  67c97527285fac3f07bcf587
3          2  1377  67cb6623285fac3f07bcf59a  67c97527285fac3f07bcf587
4          3  1378  67cc9f69285fac3f07bcf5c8  67c88f88285fac3f07bcf585
5          3  1374  67cdfa30285fac3f07bcf5cc  67c88f88285fac3f07bcf585
6          4  1383  67bc761a7a670b68746905a0  67d43b390b9539e69a3a86b9
7          4  1384  67d444dd0b9539e69a3a86bb  67d43b390b9539e69a3a86b9
8          4  1385  67bc43607a670b6874690577  67d43b390b9539e69a3a86b9
9          5  1387  67d5d8120b9539e69a3a86d7  67d5d8160b9539e69a3a86d8
10         5  1390  67e18e95edfe680c1b0f169f  67d5d8160b9539e69a3a86d8
11         6  1388  67d82dc4edfe680c1b0f1642  67d08e87285fac3f07bcf64b
12         6  1389  67d82e0aedfe680c1b0f1643  67d08e87285fac3f07bcf64b
13         7  2456  68835b0587cf5fec60dc8020  68833fd687cf5fec60dc801d
14         7  2460  6887b97087cf5fec60dc8060  68833fd687cf5fec60dc801d
15         8  2453  687de5d187cf5fec60dc7fef  6879e8fd87cf5fec60dc7fe1
16         8  2455  6880e0f187cf5fec60dc7ffe  6879e8fd87cf5fec60dc7fe1
17         9  2461  6888eec887cf5fec60dc8085  688364bf87cf5fec60dc8026
18         9  2464  688a52ad87cf5fec60dc8096  688364bf87cf5fec60dc8026
19         9  2457  688b1c7887cf5fec60dc80b0  688364bf87cf5fec60dc8026
20        10  2459  6888bbce87cf5fec60dc8072  6877c26e87cf5fec60dc7fda
21        10  2465  688bdb6387cf5fec60dc80d0  6877c26e87cf5fec60dc7fda
22        11  2463  6889e71f87cf5fec60dc8094  6889e57087cf5fec60dc8092
23        11  2475  68a75365ecc07d2944852275  6889e57087cf5fec60dc8092
24        12  2468  6898407be90ffc190a96c287  688c6add87cf5fec60dc80ef
25        12  2469  689c3c25e90ffc190a96c28b  688c6add87cf5fec60dc80ef
26        13  2467  68a5a0bde90ffc190a96c2ff  68907a6e87cf5fec60dc8107
27        13  2476  68a59766e90ffc190a96c2f4  68907a6e87cf5fec60dc8107
28        14  2470  689e2181e90ffc190a96c2df  6896071ee90ffc190a96c285
29        14  2471  689e22d5e90ffc190a96c2e0  6896071ee90ffc190a96c285

In [125]:
study_agents_merged = pd.merge(groups_df, agents_df, left_on=['document', 'user_id'], right_on=['document_id', 'author_id'], how='left')

study_agents_merged = study_agents_merged.dropna(subset=['_id'])
display(study_agents_merged.head(500))
study_agents_merged['modified'] = study_agents_merged['modified'].apply(lambda x: datetime.strptime(x, '%Y-%m-%dT%H:%M:%S.%fZ'))

display(study_agents_merged)

,group_id,user,user_id,document,_id,author_id,document_id,is_preset,modified,name,...,behavior.settings.text_operations,behavior.settings.context_trigger,behavior.settings.time_trigger.timeAfterTyping,behavior.settings.time_trigger.maxTimesPerDay,behavior.settings.time_trigger.eachMinutes,behavior.settings.time_trigger.timeOfDay,profile.sections.expertise,profile.sections.skills,profile.knowledge.notes,profile.sections.Characteristics
1,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8,67cea551285fac3f07bcf604,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8,False,2025-03-10T08:39:45.000Z,Bob,...,[ADDITION],None,2.0,,,[],[],"[Document structuring, Asses essay structure, ...",[],NaN
5,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cdfc85285fac3f07bcf5cf,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-09T20:39:33.000Z,Erika,...,[ADDITION],None,2.0,,,[],"[Literature Studies, Academic Editing, Essay W...","[Reading and Writing Essay, Professional Redac...",[],NaN
6,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cdfef4285fac3f07bcf5d3,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-09T20:49:56.000Z,AI Max,...,[ADDITION],None,2.0,,,[],"[Fact Validation, Historical Research]","[Data Verification, AI Factology]",[{'id': '2d0d2583-65b6-4ff2-8b76-c5aad1de0305'...,NaN
7,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cee0fd285fac3f07bcf60b,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-10T12:54:21.000Z,TextStructurer,...,[ADDITION],None,2.0,,,[],"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],NaN
8,4,1383,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,67d445d10b9539e69a3a86c1,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,False,2025-03-14T15:05:53.000Z,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
9,4,1383,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,67e691c850d39f32454bf30c,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,False,2025-03-28T12:10:48.000Z,Consistency Reviewer,...,[ADDITION],None,2.0,,,[],"[Scientific Paper writing, HCI researcher expe...","[logic, marketing, quality assurance]",[],NaN
10,4,1384,67d444dd0b9539e69a3a86bb,67d43b390b9539e69a3a86b9,67e5cb6450d39f32454bf2fa,67d444dd0b9539e69a3a86bb,67d43b390b9539e69a3a86b9,False,2025-03-27T22:04:20.000Z,ContentReviewer,...,[ADDITION],None,2.0,,,[],"[Human-Computer Interaction, Education, AI-ass...","[Spot logical faults, Creative thinking, Askin...",[],"[Emotional, Creative, Confident]"
11,4,1385,67bc43607a670b6874690577,67d43b390b9539e69a3a86b9,67d445e30b9539e69a3a86c3,67bc43607a670b6874690577,67d43b390b9539e69a3a86b9,False,2025-03-14T15:06:11.000Z,Best HCI Professor,...,[ADDITION],None,2.0,,,[],"[HCI, Teaching]","[Programming, Proof Reading, Supervision]",[],NaN
12,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d8810b9539e69a3a86da,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15T19:44:01.000Z,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
13,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d88b0b9539e69a3a86db,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15T19:44:11.000Z,TextStructurer,...,[ADDITION],None,2.0,,,[],"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],NaN
14,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d88f0b9539e69a3a86dc,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15T19:44:15.000Z,George,...,[ADDITION],None,2.0,,,[],[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
15,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d8cf0b9539e69a3a86df,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15T19:45:19.000Z,6ex teacher,...,[ADDITION],None,2.0,,,[],"[Sex education, jokes, Adult Education, Comedy...","[Comedy Timing, Expressive Teaching, Extend text]",[],NaN
17,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d82f6dedfe680c1b0f164a,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17T14:19:25.000Z,musie pupulikin,...,[ADDITION],None,2.0,,,[],"[Language Proficiency, Punctuation Awareness, ...","[Text Elaboration, Format text, Sentence Struc...",[],NaN
18,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d83410edfe680c1b0f1655,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17T14:39:12.000Z,Eureka,...,[ADDITION],None,2.0,,,[],"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],NaN
19,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d83558edfe680c1b0f165e,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17T14:44:40.000Z,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
20,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67d82fbfedfe680c1b0f164e,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-17T14:20:47.000Z,Bolshoi Lyoha,...,[ADDITION],None,2.0,,,[],"[Grammar Knowledge, Publication Formatting, So...",[Dynamic Citation selection],[],NaN
21,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67dd3e52edfe680c1b0f167a,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-21T10:24:18.000Z,George,...,[ADDITION],None,2.0,,,[],[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
22,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67dd412dedfe680c1b0f1687,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-21T10:36:29.000Z,ÜBERÜBERSETZER,...,[ADDITION],None,2.0,,,[],"[Linguistic Comprehension, Language Localizati...","[Interpret Language, Proofread Document, Text ...",[],NaN
23,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,6887772287cf5fec60dc8036,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,False,2025-07-28T13:12:02.000Z,The AI Expert,...,[ADDITION],None,2.0,,,[],"[artificial intelligence, english writing, edu...","[Writing Essays, Understanding Context, Text E...",[],NaN
24,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d,6888b66487cf5fec60dc806d,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d,False,2025-07-29T11:54:12.000Z,Fun facts,...,[ADDITION],None,2.0,,,[],"[history, statistics, facts]",[Adding coherent facts],[],NaN
25,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,687df2ff87cf5fec60dc7ff1,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-21T07:57:51.000Z,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism, Human Compute...","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
26,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e03f87cf5fec60dc7ffb,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23T13:14:39.000Z,LM PI Expert (2015),...,[ADDITION],None,2.0,,,[],[Expert in A lived informatics model of person...,"[Paper writing, Discussion Section, Data Inter...",[],NaN
27,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e0d087cf5fec60dc7ffd,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23T13:17:04.000Z,SBM PI Expert (2010),...,[ADDITION],None,2.0,,,[],[You are an expert in Stage based model of per...,"[Discussion section, Critique Discussion secti...",[],NaN
28,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e49587cf5fec60dc8009,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23T13:33:09.000Z,Interaction Designer,...,[ADDITION],None,2.0,,,[],"[AI in Healthcare, Interaction Design, Healthc...","[Scientific Writing, Communication in Healthca...",[{'id': 'bba2425c-43c5-4d8d-920c-993d894dd9e3'...,NaN
30,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,688bdddd87cf5fec60dc80d6,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,False,2025-07-31T21:19:25.000Z,AiDevelop,...,[ADDITION],None,2.0,,,[],"[Web Design, SEO Management, Backend Developme...","[Suggest and revise text, Find fact and add re...",[{'id': '24896ea6-d264-4194-a432-94640ea924d5'...,NaN
31,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026,688a6a2087cf5fec60dc80a2,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026,False,2025-07-30T18:53:20.000Z,George,...,[ADDITION],None,2.0,,,[],"[English Grammar and Syntax, Reading Comprehen...","[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
32,9,2457,688b1c7887cf5fec60dc80b0,688364bf87cf5fec60dc8026,688b7f6b87cf5fec60dc80b7,688b1c7887cf5fec60dc80b0,688364bf87cf5fec60dc8026,False,2025-07-31T14:36:27.000Z,Rephraser,...,[ADDITION],None,2.0,,,[],"[Semantic Understanding, Grammar Knowledge, Co...","[Paraphrasing, Simplify Sentence, Shorten text...",[],NaN
33,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,6888bd4b87cf5fec60dc8073,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-29T12:23:39.000Z,Eureka,...,[ADDITION],None,2.0,,,[],"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],NaN
34,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,6888c9af87cf5fec60dc8081,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-29T13:16:31.000Z,Purchasing,...,[ADDITION],None,2.0,,,[],"[Event Coordination, Strategic Planning]","[Planning, Organization, Portuguese Marketplac...",[],NaN
35,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,688bd9f587cf5fec60dc80cc,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-31T21:02:45.000Z,Organizer,...,[ADDITION],None,2.0,,,[],"[Event Management, Wedding Decor]","[Event Planning, Design Concepts]",[],NaN
36,10,2465,688bdb6387cf5fec60dc80d0,6877c26e87cf5fec60dc7fda,688e30ee87cf5fec60dc80f4,688bdb6387cf5fec60dc80d0,6877c26e87cf5fec60dc7fda,False,2025-08-02T15:38:22.000Z,Text Improver,...,[ADDITION],None,2.0,,,[],"[Linguistic Knowledge, Text Coherence, Narrati...","[Error Spotting, Grammar Correction]",[],NaN
37,11,2463,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,688b2aa687cf5fec60dc80b3,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,False,2025-07-31T08:34:46.000Z,Fact Checker,...,[ADDITION],None,2.0,,,[],[],[],[],NaN
38,11,2463,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,68931d9887cf5fec60dc810f,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,False,2025-08-06T09:17:12.000Z,Synthesizer,...,[ADDITION],None,2.0,,,[],"[Document Analysis, Topic Understanding, Resea...","[Reference Tracking, Critical Analysis, Draft ...",[],NaN
40,12,2468,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,689c50c4e90ffc190a96c292,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,False,2025-08-13T08:45:56.000Z,AI Sceptic Reviewer,...,[ADDITION],None,2.0,,,[],"[Artificial Intelligence, NLP, Large Language ...","[Reviewing, Critical Thinking]",[],NaN
41,12,2468,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,689c51e2e90ffc190a96c296,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,False,2025-08-13T08:50:42.000Z,References Nagger,...,[ADDITION],None,2.0,,,[],"[Computer Science, Public Sector]","[Reviewing, References, Citing]",[],NaN
42,12,2469,689c3c25e90ffc190a96c28b,688c6add87cf5fec60dc80ef,689c3da3e90ffc190a96c28f,689c3c25e90ffc190a96c28b,688c6add87cf5fec60dc80ef,False,2025-08-13T07:24:19.000Z,Nasty Nancy,...,[ADDITION],None,2.0,,,[],[Reviewing research proposals and scientific t...,[Reviewing. Find every little weak spot. Harsh...,[],NaN
43,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5a808e90ffc190a96c307,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20T10:48:40.000Z,Mr. Correct,...,[ADDITION],None,2.0,,,[],[Linguistik],[Korrekturlesen],[],NaN
44,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5acf4e90ffc190a96c309,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20T11:09:40.000Z,Proposal Brain,...,[ADDITION],None,2.0,,,[],"[Process Management, Compliance, Künstliche In...","[Schreiben von Forschungsanträgen, Denken wie ...",[],NaN
45,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5adb8e90ffc190a96c30b,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20T11:12:56.000Z,Shrek's Donkey,...,[ADDITION],None,2.0,,,[],"[Process Management, Compliance, Künstliche In...","[Fragen stellen mit dem Ziel, Lücken in besteh...",[],NaN
46,13,2476,68a59766e90ffc190a96c2f4,68907a6e87cf5fec60dc8107,68a59949e90ffc190a96c2f7,68a59766e90ffc190a96c2f4,68907a6e87cf5fec60dc8107,False,2025-08-20T09:45:45.000Z,Joker,...,[ADDITION],None,2.0,,,[],"[Sarcasm, Joke Improvisation, Nit-picking, humor]","[Nit-picking, criticism]",[],NaN
47,13,2476,68a59766e90ffc190a96c2f4,68907a6e87cf5fec60dc8107,68a5d73ee90ffc190a96c334,68a59766e90ffc190a96c2f4,68907a6e87cf5fec60dc8107,False,2025-08-20T14:10:06.000Z,Vervollständiger,...,[ADDITION],None,2.0,,,[],"[texte vervollständigen, deutsche sprache]","[texte vervollständigen, kontexte betrachten]",[],NaN
49,14,2471,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,689e2470e90ffc190a96c2e4,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,False,2025-08-14T18:01:20.000Z,Grammar,...,[ADDITION],None,2.0,,,[],"[Punctuation Knowledge, Content Structure, Spe...","[Proofreading, Text Correction, Cut text, Stor...",[],NaN
50,14,2471,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,689e24b5e90ffc190a96c2e6,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,False,2025-08-14T18:02:29.000Z,Fact Checker,...,[ADDITION],None,2.0,,,[],"[Information Verification, Fact Analysis, Sour...","[Source Assessment, Cross Referencing, Text ou...",[],NaN

,group_id,user,user_id,document,_id,author_id,document_id,is_preset,modified,name,...,behavior.settings.text_operations,behavior.settings.context_trigger,behavior.settings.time_trigger.timeAfterTyping,behavior.settings.time_trigger.maxTimesPerDay,behavior.settings.time_trigger.eachMinutes,behavior.settings.time_trigger.timeOfDay,profile.sections.expertise,profile.sections.skills,profile.knowledge.notes,profile.sections.Characteristics
1,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8,67cea551285fac3f07bcf604,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8,False,2025-03-10 08:39:45,Bob,...,[ADDITION],None,2.0,,,[],[],"[Document structuring, Asses essay structure, ...",[],NaN
5,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cdfc85285fac3f07bcf5cf,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-09 20:39:33,Erika,...,[ADDITION],None,2.0,,,[],"[Literature Studies, Academic Editing, Essay W...","[Reading and Writing Essay, Professional Redac...",[],NaN
6,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cdfef4285fac3f07bcf5d3,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-09 20:49:56,AI Max,...,[ADDITION],None,2.0,,,[],"[Fact Validation, Historical Research]","[Data Verification, AI Factology]",[{'id': '2d0d2583-65b6-4ff2-8b76-c5aad1de0305'...,NaN
7,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cee0fd285fac3f07bcf60b,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-10 12:54:21,TextStructurer,...,[ADDITION],None,2.0,,,[],"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],NaN
8,4,1383,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,67d445d10b9539e69a3a86c1,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,False,2025-03-14 15:05:53,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
9,4,1383,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,67e691c850d39f32454bf30c,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,False,2025-03-28 12:10:48,Consistency Reviewer,...,[ADDITION],None,2.0,,,[],"[Scientific Paper writing, HCI researcher expe...","[logic, marketing, quality assurance]",[],NaN
10,4,1384,67d444dd0b9539e69a3a86bb,67d43b390b9539e69a3a86b9,67e5cb6450d39f32454bf2fa,67d444dd0b9539e69a3a86bb,67d43b390b9539e69a3a86b9,False,2025-03-27 22:04:20,ContentReviewer,...,[ADDITION],None,2.0,,,[],"[Human-Computer Interaction, Education, AI-ass...","[Spot logical faults, Creative thinking, Askin...",[],"[Emotional, Creative, Confident]"
11,4,1385,67bc43607a670b6874690577,67d43b390b9539e69a3a86b9,67d445e30b9539e69a3a86c3,67bc43607a670b6874690577,67d43b390b9539e69a3a86b9,False,2025-03-14 15:06:11,Best HCI Professor,...,[ADDITION],None,2.0,,,[],"[HCI, Teaching]","[Programming, Proof Reading, Supervision]",[],NaN
12,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d8810b9539e69a3a86da,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15 19:44:01,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
13,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d88b0b9539e69a3a86db,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15 19:44:11,TextStructurer,...,[ADDITION],None,2.0,,,[],"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],NaN
14,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d88f0b9539e69a3a86dc,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15 19:44:15,George,...,[ADDITION],None,2.0,,,[],[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
15,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d8cf0b9539e69a3a86df,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15 19:45:19,6ex teacher,...,[ADDITION],None,2.0,,,[],"[Sex education, jokes, Adult Education, Comedy...","[Comedy Timing, Expressive Teaching, Extend text]",[],NaN
17,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d82f6dedfe680c1b0f164a,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17 14:19:25,musie pupulikin,...,[ADDITION],None,2.0,,,[],"[Language Proficiency, Punctuation Awareness, ...","[Text Elaboration, Format text, Sentence Struc...",[],NaN
18,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d83410edfe680c1b0f1655,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17 14:39:12,Eureka,...,[ADDITION],None,2.0,,,[],"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],NaN
19,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d83558edfe680c1b0f165e,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17 14:44:40,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
20,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67d82fbfedfe680c1b0f164e,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-17 14:20:47,Bolshoi Lyoha,...,[ADDITION],None,2.0,,,[],"[Grammar Knowledge, Publication Formatting, So...",[Dynamic Citation selection],[],NaN
21,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67dd3e52edfe680c1b0f167a,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-21 10:24:18,George,...,[ADDITION],None,2.0,,,[],[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
22,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67dd412dedfe680c1b0f1687,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-21 10:36:29,ÜBERÜBERSETZER,...,[ADDITION],None,2.0,,,[],"[Linguistic Comprehension, Language Localizati...","[Interpret Language, Proofread Document, Text ...",[],NaN
23,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,6887772287cf5fec60dc8036,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,False,2025-07-28 13:12:02,The AI Expert,...,[ADDITION],None,2.0,,,[],"[artificial intelligence, english writing, edu...","[Writing Essays, Understanding Context, Text E...",[],NaN
24,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d,6888b66487cf5fec60dc806d,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d,False,2025-07-29 11:54:12,Fun facts,...,[ADDITION],None,2.0,,,[],"[history, statistics, facts]",[Adding coherent facts],[],NaN
25,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,687df2ff87cf5fec60dc7ff1,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-21 07:57:51,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism, Human Compute...","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
26,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e03f87cf5fec60dc7ffb,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23 13:14:39,LM PI Expert (2015),...,[ADDITION],None,2.0,,,[],[Expert in A lived informatics model of person...,"[Paper writing, Discussion Section, Data Inter...",[],NaN
27,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e0d087cf5fec60dc7ffd,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23 13:17:04,SBM PI Expert (2010),...,[ADDITION],None,2.0,,,[],[You are an expert in Stage based model of per...,"[Discussion section, Critique Discussion secti...",[],NaN
28,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e49587cf5fec60dc8009,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23 13:33:09,Interaction Designer,...,[ADDITION],None,2.0,,,[],"[AI in Healthcare, Interaction Design, Healthc...","[Scientific Writing, Communication in Healthca...",[{'id': 'bba2425c-43c5-4d8d-920c-993d894dd9e3'...,NaN
30,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,688bdddd87cf5fec60dc80d6,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,False,2025-07-31 21:19:25,AiDevelop,...,[ADDITION],None,2.0,,,[],"[Web Design, SEO Management, Backend Developme...","[Suggest and revise text, Find fact and add re...",[{'id': '24896ea6-d264-4194-a432-94640ea924d5'...,NaN
31,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026,688a6a2087cf5fec60dc80a2,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026,False,2025-07-30 18:53:20,George,...,[ADDITION],None,2.0,,,[],"[English Grammar and Syntax, Reading Comprehen...","[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
32,9,2457,688b1c7887cf5fec60dc80b0,688364bf87cf5fec60dc8026,688b7f6b87cf5fec60dc80b7,688b1c7887cf5fec60dc80b0,688364bf87cf5fec60dc8026,False,2025-07-31 14:36:27,Rephraser,...,[ADDITION],None,2.0,,,[],"[Semantic Understanding, Grammar Knowledge, Co...","[Paraphrasing, Simplify Sentence, Shorten text...",[],NaN
33,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,6888bd4b87cf5fec60dc8073,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-29 12:23:39,Eureka,...,[ADDITION],None,2.0,,,[],"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],NaN
34,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,6888c9af87cf5fec60dc8081,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-29 13:16:31,Purchasing,...,[ADDITION],None,2.0,,,[],"[Event Coordination, Strategic Planning]","[Planning, Organization, Portuguese Marketplac...",[],NaN
35,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,688bd9f587cf5fec60dc80cc,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-31 21:02:45,Organizer,...,[ADDITION],None,2.0,,,[],"[Event Management, Wedding Decor]","[Event Planning, Design Concepts]",[],NaN
36,10,2465,688bdb6387cf5fec60dc80d0,6877c26e87cf5fec60dc7fda,688e30ee87cf5fec60dc80f4,688bdb6387cf5fec60dc80d0,6877c26e87cf5fec60dc7fda,False,2025-08-02 15:38:22,Text Improver,...,[ADDITION],None,2.0,,,[],"[Linguistic Knowledge, Text Coherence, Narrati...","[Error Spotting, Grammar Correction]",[],NaN
37,11,2463,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,688b2aa687cf5fec60dc80b3,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,False,2025-07-31 08:34:46,Fact Checker,...,[ADDITION],None,2.0,,,[],[],[],[],NaN
38,11,2463,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,68931d9887cf5fec60dc810f,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,False,2025-08-06 09:17:12,Synthesizer,...,[ADDITION],None,2.0,,,[],"[Document Analysis, Topic Understanding, Resea...","[Reference Tracking, Critical Analysis, Draft ...",[],NaN
40,12,2468,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,689c50c4e90ffc190a96c292,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,False,2025-08-13 08:45:56,AI Sceptic Reviewer,...,[ADDITION],None,2.0,,,[],"[Artificial Intelligence, NLP, Large Language ...","[Reviewing, Critical Thinking]",[],NaN
41,12,2468,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,689c51e2e90ffc190a96c296,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,False,2025-08-13 08:50:42,References Nagger,...,[ADDITION],None,2.0,,,[],"[Computer Science, Public Sector]","[Reviewing, References, Citing]",[],NaN
42,12,2469,689c3c25e90ffc190a96c28b,688c6add87cf5fec60dc80ef,689c3da3e90ffc190a96c28f,689c3c25e90ffc190a96c28b,688c6add87cf5fec60dc80ef,False,2025-08-13 07:24:19,Nasty Nancy,...,[ADDITION],None,2.0,,,[],[Reviewing research proposals and scientific t...,[Reviewing. Find every little weak spot. Harsh...,[],NaN
43,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5a808e90ffc190a96c307,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20 10:48:40,Mr. Correct,...,[ADDITION],None,2.0,,,[],[Linguistik],[Korrekturlesen],[],NaN
44,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5acf4e90ffc190a96c309,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20 11:09:40,Proposal Brain,...,[ADDITION],None,2.0,,,[],"[Process Management, Compliance, Künstliche In...","[Schreiben von Forschungsanträgen, Denken wie ...",[],NaN
45,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5adb8e90ffc190a96c30b,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20 11:12:56,Shrek's Donkey,...,[ADDITION],None,2.0,,,[],"[Process Management, Compliance, Künstliche In...","[Fragen stellen mit dem Ziel, Lücken in besteh...",[],NaN
46,13,2476,68a59766e90ffc190a96c2f4,68907a6e87cf5fec60dc8107,68a59949e90ffc190a96c2f7,68a59766e90ffc190a96c2f4,68907a6e87cf5fec60dc8107,False,2025-08-20 09:45:45,Joker,...,[ADDITION],None,2.0,,,[],"[Sarcasm, Joke Improvisation, Nit-picking, humor]","[Nit-picking, criticism]",[],NaN
47,13,2476,68a59766e90ffc190a96c2f4,68907a6e87cf5fec60dc8107,68a5d73ee90ffc190a96c334,68a59766e90ffc190a96c2f4,68907a6e87cf5fec60dc8107,False,2025-08-20 14:10:06,Vervollständiger,...,[ADDITION],None,2.0,,,[],"[texte vervollständigen, deutsche sprache]","[texte vervollständigen, kontexte betrachten]",[],NaN
49,14,2471,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,689e2470e90ffc190a96c2e4,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,False,2025-08-14 18:01:20,Grammar,...,[ADDITION],None,2.0,,,[],"[Punctuation Knowledge, Content Structure, Spe...","[Proofreading, Text Correction, Cut text, Stor...",[],NaN
50,14,2471,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,689e24b5e90ffc190a96c2e6,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,False,2025-08-14 18:02:29,Fact Checker,...,[ADDITION],None,2.0,,,[],"[Information Verification, Fact Analysis, Sour...","[Source Assessment, Cross Referencing, Text ou...",[],NaN

In [126]:
# Optional
# Filter agents that happened outside the study (outside of procedure step 320)
procedure_progress_groups = procedure_progress[(procedure_progress["procedure_step_id"] == 320) | (procedure_progress["procedure_step_id"] == 373)].groupby(['participant_id'])

# filter agents (only keep agents that happend throughout prototype usage
for name, group in procedure_progress_groups:   
    from_time = group["time"].iloc[0]
    to_time = group["time"].iloc[1]

    m1 = study_agents_merged['user'] == name[0]
    m2 = study_agents_merged['modified'] < from_time
    m3 = study_agents_merged['modified'] > to_time
    
    agents_created_after_study = study_agents_merged[m1 & (m2 | m3)]
    if len(agents_created_after_study) > 0:
        study_agents_merged = study_agents_merged.drop(agents_created_after_study.index)
        #display(study_agents_merged)

display(study_agents_merged)

# agent per document and group
study_agents = study_agents_merged[['group_id', 'user', 'document', '_id', 'document_id',
       'name', 'preset_id', 'role', 'summary', 'author_id',
       'profile.sections.expertise', 'profile.sections.skills',
       'profile.knowledge.notes', 'modified'
       ]]

study_agents = study_agents.drop_duplicates(subset=['document', "_id"])
display(study_agents)

,group_id,user,user_id,document,_id,author_id,document_id,is_preset,modified,name,...,behavior.settings.text_operations,behavior.settings.context_trigger,behavior.settings.time_trigger.timeAfterTyping,behavior.settings.time_trigger.maxTimesPerDay,behavior.settings.time_trigger.eachMinutes,behavior.settings.time_trigger.timeOfDay,profile.sections.expertise,profile.sections.skills,profile.knowledge.notes,profile.sections.Characteristics
1,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8,67cea551285fac3f07bcf604,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8,False,2025-03-10 08:39:45,Bob,...,[ADDITION],None,2.0,,,[],[],"[Document structuring, Asses essay structure, ...",[],NaN
5,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cdfc85285fac3f07bcf5cf,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-09 20:39:33,Erika,...,[ADDITION],None,2.0,,,[],"[Literature Studies, Academic Editing, Essay W...","[Reading and Writing Essay, Professional Redac...",[],NaN
6,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cdfef4285fac3f07bcf5d3,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-09 20:49:56,AI Max,...,[ADDITION],None,2.0,,,[],"[Fact Validation, Historical Research]","[Data Verification, AI Factology]",[{'id': '2d0d2583-65b6-4ff2-8b76-c5aad1de0305'...,NaN
7,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,67cee0fd285fac3f07bcf60b,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,False,2025-03-10 12:54:21,TextStructurer,...,[ADDITION],None,2.0,,,[],"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],NaN
8,4,1383,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,67d445d10b9539e69a3a86c1,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,False,2025-03-14 15:05:53,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
9,4,1383,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,67e691c850d39f32454bf30c,67bc761a7a670b68746905a0,67d43b390b9539e69a3a86b9,False,2025-03-28 12:10:48,Consistency Reviewer,...,[ADDITION],None,2.0,,,[],"[Scientific Paper writing, HCI researcher expe...","[logic, marketing, quality assurance]",[],NaN
10,4,1384,67d444dd0b9539e69a3a86bb,67d43b390b9539e69a3a86b9,67e5cb6450d39f32454bf2fa,67d444dd0b9539e69a3a86bb,67d43b390b9539e69a3a86b9,False,2025-03-27 22:04:20,ContentReviewer,...,[ADDITION],None,2.0,,,[],"[Human-Computer Interaction, Education, AI-ass...","[Spot logical faults, Creative thinking, Askin...",[],"[Emotional, Creative, Confident]"
11,4,1385,67bc43607a670b6874690577,67d43b390b9539e69a3a86b9,67d445e30b9539e69a3a86c3,67bc43607a670b6874690577,67d43b390b9539e69a3a86b9,False,2025-03-14 15:06:11,Best HCI Professor,...,[ADDITION],None,2.0,,,[],"[HCI, Teaching]","[Programming, Proof Reading, Supervision]",[],NaN
12,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d8810b9539e69a3a86da,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15 19:44:01,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
13,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d88b0b9539e69a3a86db,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15 19:44:11,TextStructurer,...,[ADDITION],None,2.0,,,[],"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],NaN
14,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d88f0b9539e69a3a86dc,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15 19:44:15,George,...,[ADDITION],None,2.0,,,[],[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
15,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,67d5d8cf0b9539e69a3a86df,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,False,2025-03-15 19:45:19,6ex teacher,...,[ADDITION],None,2.0,,,[],"[Sex education, jokes, Adult Education, Comedy...","[Comedy Timing, Expressive Teaching, Extend text]",[],NaN
17,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d82f6dedfe680c1b0f164a,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17 14:19:25,musie pupulikin,...,[ADDITION],None,2.0,,,[],"[Language Proficiency, Punctuation Awareness, ...","[Text Elaboration, Format text, Sentence Struc...",[],NaN
18,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d83410edfe680c1b0f1655,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17 14:39:12,Eureka,...,[ADDITION],None,2.0,,,[],"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],NaN
19,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,67d83558edfe680c1b0f165e,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,False,2025-03-17 14:44:40,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
20,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67d82fbfedfe680c1b0f164e,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-17 14:20:47,Bolshoi Lyoha,...,[ADDITION],None,2.0,,,[],"[Grammar Knowledge, Publication Formatting, So...",[Dynamic Citation selection],[],NaN
21,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67dd3e52edfe680c1b0f167a,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-21 10:24:18,George,...,[ADDITION],None,2.0,,,[],[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
22,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,67dd412dedfe680c1b0f1687,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,False,2025-03-21 10:36:29,ÜBERÜBERSETZER,...,[ADDITION],None,2.0,,,[],"[Linguistic Comprehension, Language Localizati...","[Interpret Language, Proofread Document, Text ...",[],NaN
23,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,6887772287cf5fec60dc8036,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,False,2025-07-28 13:12:02,The AI Expert,...,[ADDITION],None,2.0,,,[],"[artificial intelligence, english writing, edu...","[Writing Essays, Understanding Context, Text E...",[],NaN
24,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d,6888b66487cf5fec60dc806d,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d,False,2025-07-29 11:54:12,Fun facts,...,[ADDITION],None,2.0,,,[],"[history, statistics, facts]",[Adding coherent facts],[],NaN
25,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,687df2ff87cf5fec60dc7ff1,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-21 07:57:51,TextReviewer,...,[ADDITION],None,2.0,,,[],"[Text Review, Textual Criticism, Human Compute...","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,NaN
26,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e03f87cf5fec60dc7ffb,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23 13:14:39,LM PI Expert (2015),...,[ADDITION],None,2.0,,,[],[Expert in A lived informatics model of person...,"[Paper writing, Discussion Section, Data Inter...",[],NaN
27,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e0d087cf5fec60dc7ffd,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23 13:17:04,SBM PI Expert (2010),...,[ADDITION],None,2.0,,,[],[You are an expert in Stage based model of per...,"[Discussion section, Critique Discussion secti...",[],NaN
28,8,2453,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,6880e49587cf5fec60dc8009,687de5d187cf5fec60dc7fef,6879e8fd87cf5fec60dc7fe1,False,2025-07-23 13:33:09,Interaction Designer,...,[ADDITION],None,2.0,,,[],"[AI in Healthcare, Interaction Design, Healthc...","[Scientific Writing, Communication in Healthca...",[{'id': 'bba2425c-43c5-4d8d-920c-993d894dd9e3'...,NaN
30,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,688bdddd87cf5fec60dc80d6,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,False,2025-07-31 21:19:25,AiDevelop,...,[ADDITION],None,2.0,,,[],"[Web Design, SEO Management, Backend Developme...","[Suggest and revise text, Find fact and add re...",[{'id': '24896ea6-d264-4194-a432-94640ea924d5'...,NaN
31,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026,688a6a2087cf5fec60dc80a2,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026,False,2025-07-30 18:53:20,George,...,[ADDITION],None,2.0,,,[],"[English Grammar and Syntax, Reading Comprehen...","[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,NaN
32,9,2457,688b1c7887cf5fec60dc80b0,688364bf87cf5fec60dc8026,688b7f6b87cf5fec60dc80b7,688b1c7887cf5fec60dc80b0,688364bf87cf5fec60dc8026,False,2025-07-31 14:36:27,Rephraser,...,[ADDITION],None,2.0,,,[],"[Semantic Understanding, Grammar Knowledge, Co...","[Paraphrasing, Simplify Sentence, Shorten text...",[],NaN
33,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,6888bd4b87cf5fec60dc8073,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-29 12:23:39,Eureka,...,[ADDITION],None,2.0,,,[],"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],NaN
34,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,6888c9af87cf5fec60dc8081,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-29 13:16:31,Purchasing,...,[ADDITION],None,2.0,,,[],"[Event Coordination, Strategic Planning]","[Planning, Organization, Portuguese Marketplac...",[],NaN
35,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,688bd9f587cf5fec60dc80cc,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda,False,2025-07-31 21:02:45,Organizer,...,[ADDITION],None,2.0,,,[],"[Event Management, Wedding Decor]","[Event Planning, Design Concepts]",[],NaN
36,10,2465,688bdb6387cf5fec60dc80d0,6877c26e87cf5fec60dc7fda,688e30ee87cf5fec60dc80f4,688bdb6387cf5fec60dc80d0,6877c26e87cf5fec60dc7fda,False,2025-08-02 15:38:22,Text Improver,...,[ADDITION],None,2.0,,,[],"[Linguistic Knowledge, Text Coherence, Narrati...","[Error Spotting, Grammar Correction]",[],NaN
37,11,2463,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,688b2aa687cf5fec60dc80b3,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,False,2025-07-31 08:34:46,Fact Checker,...,[ADDITION],None,2.0,,,[],[],[],[],NaN
38,11,2463,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,68931d9887cf5fec60dc810f,6889e71f87cf5fec60dc8094,6889e57087cf5fec60dc8092,False,2025-08-06 09:17:12,Synthesizer,...,[ADDITION],None,2.0,,,[],"[Document Analysis, Topic Understanding, Resea...","[Reference Tracking, Critical Analysis, Draft ...",[],NaN
40,12,2468,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,689c50c4e90ffc190a96c292,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,False,2025-08-13 08:45:56,AI Sceptic Reviewer,...,[ADDITION],None,2.0,,,[],"[Artificial Intelligence, NLP, Large Language ...","[Reviewing, Critical Thinking]",[],NaN
41,12,2468,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,689c51e2e90ffc190a96c296,6898407be90ffc190a96c287,688c6add87cf5fec60dc80ef,False,2025-08-13 08:50:42,References Nagger,...,[ADDITION],None,2.0,,,[],"[Computer Science, Public Sector]","[Reviewing, References, Citing]",[],NaN
42,12,2469,689c3c25e90ffc190a96c28b,688c6add87cf5fec60dc80ef,689c3da3e90ffc190a96c28f,689c3c25e90ffc190a96c28b,688c6add87cf5fec60dc80ef,False,2025-08-13 07:24:19,Nasty Nancy,...,[ADDITION],None,2.0,,,[],[Reviewing research proposals and scientific t...,[Reviewing. Find every little weak spot. Harsh...,[],NaN
43,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5a808e90ffc190a96c307,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20 10:48:40,Mr. Correct,...,[ADDITION],None,2.0,,,[],[Linguistik],[Korrekturlesen],[],NaN
44,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5acf4e90ffc190a96c309,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20 11:09:40,Proposal Brain,...,[ADDITION],None,2.0,,,[],"[Process Management, Compliance, Künstliche In...","[Schreiben von Forschungsanträgen, Denken wie ...",[],NaN
45,13,2467,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,68a5adb8e90ffc190a96c30b,68a5a0bde90ffc190a96c2ff,68907a6e87cf5fec60dc8107,False,2025-08-20 11:12:56,Shrek's Donkey,...,[ADDITION],None,2.0,,,[],"[Process Management, Compliance, Künstliche In...","[Fragen stellen mit dem Ziel, Lücken in besteh...",[],NaN
49,14,2471,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,689e2470e90ffc190a96c2e4,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,False,2025-08-14 18:01:20,Grammar,...,[ADDITION],None,2.0,,,[],"[Punctuation Knowledge, Content Structure, Spe...","[Proofreading, Text Correction, Cut text, Stor...",[],NaN
50,14,2471,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,689e24b5e90ffc190a96c2e6,689e22d5e90ffc190a96c2e0,6896071ee90ffc190a96c285,False,2025-08-14 18:02:29,Fact Checker,...,[ADDITION],None,2.0,,,[],"[Information Verification, Fact Analysis, Sour...","[Source Assessment, Cross Referencing, Text ou...",[],NaN

,group_id,user,document,_id,document_id,name,preset_id,role,summary,author_id,profile.sections.expertise,profile.sections.skills,profile.knowledge.notes,modified
1,1,1380,67ce983b285fac3f07bcf5e8,67cea551285fac3f07bcf604,67ce983b285fac3f07bcf5e8,Bob,67cea551285fac3f07bcf603,Assistant,"The AI agent serves as an assistant, specializ...",67ce9cb4285fac3f07bcf5ec,[],"[Document structuring, Asses essay structure, ...",[],2025-03-10 08:39:45
5,3,1374,67c88f88285fac3f07bcf585,67cdfc85285fac3f07bcf5cf,67c88f88285fac3f07bcf585,Erika,67cdfc85285fac3f07bcf5ce,Essay Reviewer,"The AI agent serves as an Essay Reviewer, spec...",67cdfa30285fac3f07bcf5cc,"[Literature Studies, Academic Editing, Essay W...","[Reading and Writing Essay, Professional Redac...",[],2025-03-09 20:39:33
6,3,1374,67c88f88285fac3f07bcf585,67cdfef4285fac3f07bcf5d3,67c88f88285fac3f07bcf585,AI Max,67cdfef4285fac3f07bcf5d2,Fact Checker and Fact Provider,The AI agent serves as a Fact Checker and Fact...,67cdfa30285fac3f07bcf5cc,"[Fact Validation, Historical Research]","[Data Verification, AI Factology]",[{'id': '2d0d2583-65b6-4ff2-8b76-c5aad1de0305'...,2025-03-09 20:49:56
7,3,1374,67c88f88285fac3f07bcf585,67cee0fd285fac3f07bcf60b,67c88f88285fac3f07bcf585,TextStructurer,67b9b3e4adc01b1db6869c72,Text Structure and Format Specialist,The AI agent serves as a Text Structure and Fo...,67cdfa30285fac3f07bcf5cc,"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],2025-03-10 12:54:21
8,4,1383,67d43b390b9539e69a3a86b9,67d445d10b9539e69a3a86c1,67d43b390b9539e69a3a86b9,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67bc761a7a670b68746905a0,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-14 15:05:53
9,4,1383,67d43b390b9539e69a3a86b9,67e691c850d39f32454bf30c,67d43b390b9539e69a3a86b9,Consistency Reviewer,67e691c850d39f32454bf30b,Consistency Reviewer,"The AI agent serves as a Consistency Reviewer,...",67bc761a7a670b68746905a0,"[Scientific Paper writing, HCI researcher expe...","[logic, marketing, quality assurance]",[],2025-03-28 12:10:48
10,4,1384,67d43b390b9539e69a3a86b9,67e5cb6450d39f32454bf2fa,67d43b390b9539e69a3a86b9,ContentReviewer,67e5cb6450d39f32454bf2f9,Critical Reviewer with HCI and Education Exper...,The AI agent serves as a Critical Reviewer wit...,67d444dd0b9539e69a3a86bb,"[Human-Computer Interaction, Education, AI-ass...","[Spot logical faults, Creative thinking, Askin...",[],2025-03-27 22:04:20
11,4,1385,67d43b390b9539e69a3a86b9,67d445e30b9539e69a3a86c3,67d43b390b9539e69a3a86b9,Best HCI Professor,67d445e30b9539e69a3a86c2,This AI Assistant is the best HCI Professor in...,The AI agent is recognized as a leading profes...,67bc43607a670b6874690577,"[HCI, Teaching]","[Programming, Proof Reading, Supervision]",[],2025-03-14 15:06:11
12,5,1387,67d5d8160b9539e69a3a86d8,67d5d8810b9539e69a3a86da,67d5d8160b9539e69a3a86d8,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67d5d8120b9539e69a3a86d7,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-15 19:44:01
13,5,1387,67d5d8160b9539e69a3a86d8,67d5d88b0b9539e69a3a86db,67d5d8160b9539e69a3a86d8,TextStructurer,67b9b3e4adc01b1db6869c72,Text Structure and Format Specialist,The AI agent serves as a Text Structure and Fo...,67d5d8120b9539e69a3a86d7,"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],2025-03-15 19:44:11
14,5,1387,67d5d8160b9539e69a3a86d8,67d5d88f0b9539e69a3a86dc,67d5d8160b9539e69a3a86d8,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",67d5d8120b9539e69a3a86d7,[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-03-15 19:44:15
15,5,1387,67d5d8160b9539e69a3a86d8,67d5d8cf0b9539e69a3a86df,67d5d8160b9539e69a3a86d8,6ex teacher,67d5d8cf0b9539e69a3a86de,Teaches sex and makes stupid but funny jokes,The AI agent is primarily engaged in the field...,67d5d8120b9539e69a3a86d7,"[Sex education, jokes, Adult Education, Comedy...","[Comedy Timing, Expressive Teaching, Extend text]",[],2025-03-15 19:45:19
17,6,1388,67d08e87285fac3f07bcf64b,67d82f6dedfe680c1b0f164a,67d08e87285fac3f07bcf64b,musie pupulikin,67d82f6dedfe680c1b0f1649,check gramma,The AI agent is primarily responsible for chec...,67d82dc4edfe680c1b0f1642,"[Language Proficiency, Punctuation Awareness, ...","[Text Elaboration, Format text, Sentence Struc...",[],2025-03-17 14:19:25
18,6,1388,67d08e87285fac3f07bcf64b,67d83410edfe680c1b0f1655,67d08e87285fac3f07bcf64b,Eureka,67b9b221adc01b1db6869c70,Idea Generator,"The AI agent serves as an Idea Generator, spec...",67d82dc4edfe680c1b0f1642,"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],2025-03-17 14:39:12
19,6,1388,67d08e87285fac3f07bcf64b,67d83558edfe680c1b0f165e,67d08e87285fac3f07bcf64b,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67d82dc4edfe680c1b0f1642,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-17 14:44:40
20,6,1389,67d08e87285fac3f07bcf64b,67d82fbfedfe680c1b0f164e,67d08e87285fac3f07bcf64b,Bolshoi Lyoha,67d82fbfedfe680c1b0f164d,Proofreader,"The AI agent serves as a proofreader, speciali...",67d82e0aedfe680c1b0f1643,"[Grammar Knowledge, Publication Formatting, So...",[Dynamic Citation selection],[],2025-03-17 14:20:47
21,6,1389,67d08e87285fac3f07bcf64b,67dd3e52edfe680c1b0f167a,67d08e87285fac3f07bcf64b,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",67d82e0aedfe680c1b0f1643,[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-03-21 10:24:18
22,6,1389,67d08e87285fac3f07bcf64b,67dd412dedfe680c1b0f1687,67d08e87285fac3f07bcf64b,ÜBERÜBERSETZER,67dd412dedfe680c1b0f1686,Text translator,"The AI agent serves as a text translator, spec...",67d82e0aedfe680c1b0f1643,"[Linguistic Comprehension, Language Localizati...","[Interpret Language, Proofread Document, Text ...",[],2025-03-21 10:36:29
23,7,2456,68833fd687cf5fec60dc801d,6887772287cf5fec60dc8036,68833fd687cf5fec60dc801d,The AI Expert,6887772287cf5fec60dc8035,Author,The AI agent serves as an author with expertis...,68835b0587cf5fec60dc8020,"[artificial intelligence, english writing, edu...","[Writing Essays, Understanding Context, Text E...",[],2025-07-28 13:12:02
24,7,2460,68833fd687cf5fec60dc801d,6888b66487cf5fec60dc806d,68833fd687cf5fec60dc801d,Fun facts,6888b66487cf5fec60dc806c,Add interesting facts,The AI agent specializes in enriching document...,6887b97087cf5fec60dc8060,"[history, statistics, facts]",[Adding coherent facts],[],2025-07-29 11:54:12
25,8,2453,6879e8fd87cf5fec60dc7fe1,687df2ff87cf5fec60dc7ff1,6879e8fd87cf5fec60dc7fe1,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,687de5d187cf5fec60dc7fef,"[Text Review, Textual Criticism, Human Compute...","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-07-21 07:57:51
26,8,2453,6879e8fd87cf5fec60dc7fe1,6880e03f87cf5fec60dc7ffb,6879e8fd87cf5fec60dc7fe1,LM PI Expert (2015),6880e03f87cf5fec60dc7ffa,Lived Model of PI Expert,The AI agent serves as a Lived Model of PI Exp...,687de5d187cf5fec60dc7fef,[Expert in A lived informatics model of person...,"[Paper writing, Discussion Section, Data Inter...",[],2025-07-23 13:14:39
27,8,2453,6879e8fd87cf5fec60dc7fe1,6880e0d087cf5fec60dc7ffd,6879e8fd87cf5fec60dc7fe1,SBM PI Expert (2010),6880e0d087cf5fec60dc7ffc,Stage based model of personal informatics (201...,The AI agent is a specialist in the Stage base...,687de5d187cf5fec60dc7fef,[You are an expert in Stage based model of per...,"[Discussion section, Critique Discussion secti...",[],2025-07-23 13:17:04
28,8,2453,6879e8fd87cf5fec60dc7fe1,6880e49587cf5fec60dc8009,6879e8fd87cf5fec60dc7fe1,Interaction Designer,6880e49587cf5fec60dc8008,Coming up with INteraction Design Implications...,The AI agent is responsible for developing int...,687de5d187cf5fec60dc7fef,"[AI in Healthcare, Interaction Design, Healthc...","[Scientific Writing, Communication in Healthca...",[{'id': 'bba2425c-43c5-4d8d-920c-993d894dd9e3'...,2025-07-23 13:33:09
30,9,2461,688364bf87cf5fec60dc8026,688bdddd87cf5fec60dc80d6,688364bf87cf5fec60dc8026,AiDevelop,688bdddd87cf5fec60dc80d5,Website Developer,The AI agent is a Website Developer with exper...,6888eec887cf5fec60dc8085,"[Web Design, SEO Management, Backend Developme...","[Suggest and revise text, Find fact and add re...",[{'id': '24896ea6-d264-4194-a432-94640ea924d5'...,2025-07-31 21:19:25
31,9,2464,688364bf87cf5fec60dc8026,688a6a2087cf5fec60dc80a2,688364bf87cf5fec60dc8026,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",688a52ad87cf5fec60dc8096,"[English Grammar and Syntax, Reading Comprehen...","[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-07-30 18:53:20
32,9,2457,688364bf87cf5fec60dc8026,688b7f6b87cf5fec60dc80b7,688364bf87cf5fec60dc8026,Rephraser,688b7f6b87cf5fec60dc80b6,Rephrase a sentence or section,The AI agent is designed to rephrase sentences...,688b1c7887cf5fec60dc80b0,"[Semantic Understanding, Grammar Knowledge, Co...","[Paraphrasing, Simplify Sentence, Shorten text...",[],2025-07-31 14:36:27
33,10,2459,6877c26e87cf5fec60dc7fda,6888bd4b87cf5fec60dc8073,6877c26e87cf5fec60dc7fda,Eureka,67b9b221adc01b1db6869c70,Idea Generator,"The AI agent serves as an Idea Generator, spec...",6888bbce87cf5fec60dc8072,"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],2025-07-29 12:23:39
34,10,2459,6877c26e87cf5fec60dc7fda,6888c9af87cf5fec60dc8081,6877c26e87cf5fec60dc7fda,Purchasing,6888c9af87cf5fec60dc8080,Planner,"The AI agent serves as a Planner, specializing...",6888bbce87cf5fec60dc8072,"[Event Coordination, Strategic Planning]","[Planning, Organization, Portuguese Marketplac...",[],2025-07-29 13:16:31
35,10,2459,6877c26e87cf5fec60dc7fda,688bd9f587cf5fec60dc80cc,6877c26e87cf5fec60dc7fda,Organizer,688bd9f587cf5fec60dc80cb,Wedding planner,"The AI agent serves as a wedding planner, spec...",6888bbce87cf5fec60dc8072,"[Event Management, Wedding Decor]","[Event Planning, Design Concepts]",[],2025-07-31 21:02:45
36,10,2465,6877c26e87cf5fec60dc7fda,688e30ee87cf5fec60dc80f4,6877c26e87cf5fec60dc7fda,Text Improver,688e30ee87cf5fec60dc80f3,Improve writting flow,The AI agent is designed to enhance writing fl...,688bdb6387cf5fec60dc80d0,"[Linguistic Knowledge, Text Coherence, Narrati...","[Error Spotting, Grammar Correction]",[],2025-08-02 15:38:22
37,11,2463,6889e57087cf5fec60dc8092,688b2aa687cf5fec60dc80b3,6889e57087cf5fec60dc8092,Fact Checker,688b2aa687cf5fec60dc80b2,Checking facts for scientific evidence,The AI agent is primarily responsible for fact...,6889e71f87cf5fec60dc8094,[],[],[],2025-07-31 08:34:46
38,11,2463,6889e57087cf5fec60dc8092,68931d9887cf5fec60dc810f,6889e57087cf5fec60dc8092,Synthesizer,68931d9887cf5fec60dc810e,Reading and synthesizing papers about a specif...,The AI agent is designed to meticulously read ...,6889e71f87cf5fec60dc8094,"[Document Analysis, Topic Understanding, Resea...","[Reference Tracking, Critical Analysis, Draft ...",[],2025-08-06 09:17:12
40,12,2468,688c6add87cf5fec60dc80ef,689c50c4e90ffc190a96c292,688c6add87cf5fec60dc80ef,AI Sceptic Reviewer,689c50c4e90ffc190a96c291,"A DFG reviewer, sceptic of AI usage, especiall...",The AI agent serves as a DFG reviewer with a s...,6898407be90ffc190a96c287,"[Artificial Intelligence, NLP, Large Language ...","[Reviewing, Critical Thinking]",[],2025-08-13 08:45:56
41,12,2468,688c6add87cf5fec60dc80ef,689c51e2e90ffc190a96c296,688c6add87cf5fec60dc80ef,References Nagger,689c51e2e90ffc190a96c295,"Checks text for missing references, i.e., stat...",The AI agent is designed to review text and id...,6898407be90ffc190a96c287,"[Computer Science, Public Sector]","[Reviewing, References, Citing]",[],2025-08-13 08:50:42
42,12,2469,688c6add87cf5fec60dc80ef,689c3da3e90ffc190a96c28f,688c6add87cf5fec60dc80ef,Nasty Nancy,689c3da3e90ffc190a96c28e,Opposite reviewer,"The AI agent, known as the Opposite Reviewer, ...",689c3c25e90ffc190a96c28b,[Reviewing research proposals and scientific t...,[Reviewing. Find every little weak spot. Harsh...,[],2025-08-13 07:24:19
43,13,2467,68907a6e87cf5fec60dc8107,68a5a808e90ffc190a96c307,68907a6e87cf5fec60dc8107,Mr. Correct,68a5a808e90ffc190a96c306,Proofreader,"The AI agent serves as a proofreader, speciali...",68a5a0bde90ffc190a96c2ff,[Linguistik],[Korrekturlesen],[],2025-08-20 10:48:40
44,13,2467,68907a6e87cf5fec60dc8107,68a5acf4e90ffc190a96c309,68907a6e87cf5fec60dc8107,Proposal Brain,68a5acf4e90ffc190a96c308,Researcher,"The AI agent serves as a Researcher, specializ...",68a5a0bde90ffc190a96c2ff,"[Process Management, Compliance, Künstliche In...","[Schreiben von Forschungsanträgen, Denken wie ...",[],2025-08-20 11:09:40
45,13,2467,68907a6e87cf5fec60dc8107,68a5adb8e90ffc190a96c30b,68907a6e87cf5fec60dc8107,Shrek's Donkey,68a5adb8e90ffc190a96c30a,Reviewer,"The AI agent serves as a reviewer, specializin...",68a5a0bde90ffc190a96c2ff,"[Process Management, Compliance, Künstliche In...","[Fragen stellen mit dem Ziel, Lücken in besteh...",[],2025-08-20 11:12:56
49,14,2471,6896071ee90ffc190a96c285,689e2470e90ffc190a96c2e4,6896071ee90ffc190a96c285,Grammar,689e2470e90ffc190a96c2e3,Grammar Checker,"The AI agent serves as a Grammar Checker, spec...",689e22d5e90ffc190a96c2e0,"[Punctuation Knowledge, Content Structure, Spe...","[Proofreading, Text Correction, Cut text, Stor...",[],2025-08-14 18:01:20
50,14,2471,6896071ee90ffc190a96c285,689e24b5e90ffc190a96c2e6,6896071ee90ffc190a96c285,Fact Checker,689e24b5e90ffc190a96c2e5,Fact checking,The AI agent is primarily responsible for fact...,689e22d5e90ffc190a96c2e0,"[Information Verification, Fact Analysis, Sour...","[Source Assessment, Cross Referencing, Text ou...",[],2025-08-14 18:02:29

## Agents

In [127]:
# remove agents that have no creation event
agents_created = finished_participants[(finished_participants["event"] == "AGENT_SAVE") | (finished_participants["event"] == "AGENT_PRESET_USE")]
parsed_agents_created = parse_json_field(agents_created, "data")

# agents without creation events (excluding group 4)
remove_agents = ['67dd3e52edfe680c1b0f167a', '67dd412dedfe680c1b0f1687']
study_agents = study_agents[~study_agents["_id"].isin(remove_agents)]
display(study_agents)

study_agents.to_csv(os.path.join('output', 'intermediate', '03_study_agents.csv'), sep="\t")

/tmp/ipykernel_112605/962560954.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  event_df[json_field + "_parsed"] = event_df[json_field].apply(json.loads)

,group_id,user,document,_id,document_id,name,preset_id,role,summary,author_id,profile.sections.expertise,profile.sections.skills,profile.knowledge.notes,modified
1,1,1380,67ce983b285fac3f07bcf5e8,67cea551285fac3f07bcf604,67ce983b285fac3f07bcf5e8,Bob,67cea551285fac3f07bcf603,Assistant,"The AI agent serves as an assistant, specializ...",67ce9cb4285fac3f07bcf5ec,[],"[Document structuring, Asses essay structure, ...",[],2025-03-10 08:39:45
5,3,1374,67c88f88285fac3f07bcf585,67cdfc85285fac3f07bcf5cf,67c88f88285fac3f07bcf585,Erika,67cdfc85285fac3f07bcf5ce,Essay Reviewer,"The AI agent serves as an Essay Reviewer, spec...",67cdfa30285fac3f07bcf5cc,"[Literature Studies, Academic Editing, Essay W...","[Reading and Writing Essay, Professional Redac...",[],2025-03-09 20:39:33
6,3,1374,67c88f88285fac3f07bcf585,67cdfef4285fac3f07bcf5d3,67c88f88285fac3f07bcf585,AI Max,67cdfef4285fac3f07bcf5d2,Fact Checker and Fact Provider,The AI agent serves as a Fact Checker and Fact...,67cdfa30285fac3f07bcf5cc,"[Fact Validation, Historical Research]","[Data Verification, AI Factology]",[{'id': '2d0d2583-65b6-4ff2-8b76-c5aad1de0305'...,2025-03-09 20:49:56
7,3,1374,67c88f88285fac3f07bcf585,67cee0fd285fac3f07bcf60b,67c88f88285fac3f07bcf585,TextStructurer,67b9b3e4adc01b1db6869c72,Text Structure and Format Specialist,The AI agent serves as a Text Structure and Fo...,67cdfa30285fac3f07bcf5cc,"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],2025-03-10 12:54:21
8,4,1383,67d43b390b9539e69a3a86b9,67d445d10b9539e69a3a86c1,67d43b390b9539e69a3a86b9,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67bc761a7a670b68746905a0,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-14 15:05:53
9,4,1383,67d43b390b9539e69a3a86b9,67e691c850d39f32454bf30c,67d43b390b9539e69a3a86b9,Consistency Reviewer,67e691c850d39f32454bf30b,Consistency Reviewer,"The AI agent serves as a Consistency Reviewer,...",67bc761a7a670b68746905a0,"[Scientific Paper writing, HCI researcher expe...","[logic, marketing, quality assurance]",[],2025-03-28 12:10:48
10,4,1384,67d43b390b9539e69a3a86b9,67e5cb6450d39f32454bf2fa,67d43b390b9539e69a3a86b9,ContentReviewer,67e5cb6450d39f32454bf2f9,Critical Reviewer with HCI and Education Exper...,The AI agent serves as a Critical Reviewer wit...,67d444dd0b9539e69a3a86bb,"[Human-Computer Interaction, Education, AI-ass...","[Spot logical faults, Creative thinking, Askin...",[],2025-03-27 22:04:20
11,4,1385,67d43b390b9539e69a3a86b9,67d445e30b9539e69a3a86c3,67d43b390b9539e69a3a86b9,Best HCI Professor,67d445e30b9539e69a3a86c2,This AI Assistant is the best HCI Professor in...,The AI agent is recognized as a leading profes...,67bc43607a670b6874690577,"[HCI, Teaching]","[Programming, Proof Reading, Supervision]",[],2025-03-14 15:06:11
12,5,1387,67d5d8160b9539e69a3a86d8,67d5d8810b9539e69a3a86da,67d5d8160b9539e69a3a86d8,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67d5d8120b9539e69a3a86d7,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-15 19:44:01
13,5,1387,67d5d8160b9539e69a3a86d8,67d5d88b0b9539e69a3a86db,67d5d8160b9539e69a3a86d8,TextStructurer,67b9b3e4adc01b1db6869c72,Text Structure and Format Specialist,The AI agent serves as a Text Structure and Fo...,67d5d8120b9539e69a3a86d7,"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],2025-03-15 19:44:11
14,5,1387,67d5d8160b9539e69a3a86d8,67d5d88f0b9539e69a3a86dc,67d5d8160b9539e69a3a86d8,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",67d5d8120b9539e69a3a86d7,[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-03-15 19:44:15
15,5,1387,67d5d8160b9539e69a3a86d8,67d5d8cf0b9539e69a3a86df,67d5d8160b9539e69a3a86d8,6ex teacher,67d5d8cf0b9539e69a3a86de,Teaches sex and makes stupid but funny jokes,The AI agent is primarily engaged in the field...,67d5d8120b9539e69a3a86d7,"[Sex education, jokes, Adult Education, Comedy...","[Comedy Timing, Expressive Teaching, Extend text]",[],2025-03-15 19:45:19
17,6,1388,67d08e87285fac3f07bcf64b,67d82f6dedfe680c1b0f164a,67d08e87285fac3f07bcf64b,musie pupulikin,67d82f6dedfe680c1b0f1649,check gramma,The AI agent is primarily responsible for chec...,67d82dc4edfe680c1b0f1642,"[Language Proficiency, Punctuation Awareness, ...","[Text Elaboration, Format text, Sentence Struc...",[],2025-03-17 14:19:25
18,6,1388,67d08e87285fac3f07bcf64b,67d83410edfe680c1b0f1655,67d08e87285fac3f07bcf64b,Eureka,67b9b221adc01b1db6869c70,Idea Generator,"The AI agent serves as an Idea Generator, spec...",67d82dc4edfe680c1b0f1642,"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],2025-03-17 14:39:12
19,6,1388,67d08e87285fac3f07bcf64b,67d83558edfe680c1b0f165e,67d08e87285fac3f07bcf64b,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67d82dc4edfe680c1b0f1642,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-17 14:44:40
20,6,1389,67d08e87285fac3f07bcf64b,67d82fbfedfe680c1b0f164e,67d08e87285fac3f07bcf64b,Bolshoi Lyoha,67d82fbfedfe680c1b0f164d,Proofreader,"The AI agent serves as a proofreader, speciali...",67d82e0aedfe680c1b0f1643,"[Grammar Knowledge, Publication Formatting, So...",[Dynamic Citation selection],[],2025-03-17 14:20:47
23,7,2456,68833fd687cf5fec60dc801d,6887772287cf5fec60dc8036,68833fd687cf5fec60dc801d,The AI Expert,6887772287cf5fec60dc8035,Author,The AI agent serves as an author with expertis...,68835b0587cf5fec60dc8020,"[artificial intelligence, english writing, edu...","[Writing Essays, Understanding Context, Text E...",[],2025-07-28 13:12:02
24,7,2460,68833fd687cf5fec60dc801d,6888b66487cf5fec60dc806d,68833fd687cf5fec60dc801d,Fun facts,6888b66487cf5fec60dc806c,Add interesting facts,The AI agent specializes in enriching document...,6887b97087cf5fec60dc8060,"[history, statistics, facts]",[Adding coherent facts],[],2025-07-29 11:54:12
25,8,2453,6879e8fd87cf5fec60dc7fe1,687df2ff87cf5fec60dc7ff1,6879e8fd87cf5fec60dc7fe1,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,687de5d187cf5fec60dc7fef,"[Text Review, Textual Criticism, Human Compute...","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-07-21 07:57:51
26,8,2453,6879e8fd87cf5fec60dc7fe1,6880e03f87cf5fec60dc7ffb,6879e8fd87cf5fec60dc7fe1,LM PI Expert (2015),6880e03f87cf5fec60dc7ffa,Lived Model of PI Expert,The AI agent serves as a Lived Model of PI Exp...,687de5d187cf5fec60dc7fef,[Expert in A lived informatics model of person...,"[Paper writing, Discussion Section, Data Inter...",[],2025-07-23 13:14:39
27,8,2453,6879e8fd87cf5fec60dc7fe1,6880e0d087cf5fec60dc7ffd,6879e8fd87cf5fec60dc7fe1,SBM PI Expert (2010),6880e0d087cf5fec60dc7ffc,Stage based model of personal informatics (201...,The AI agent is a specialist in the Stage base...,687de5d187cf5fec60dc7fef,[You are an expert in Stage based model of per...,"[Discussion section, Critique Discussion secti...",[],2025-07-23 13:17:04
28,8,2453,6879e8fd87cf5fec60dc7fe1,6880e49587cf5fec60dc8009,6879e8fd87cf5fec60dc7fe1,Interaction Designer,6880e49587cf5fec60dc8008,Coming up with INteraction Design Implications...,The AI agent is responsible for developing int...,687de5d187cf5fec60dc7fef,"[AI in Healthcare, Interaction Design, Healthc...","[Scientific Writing, Communication in Healthca...",[{'id': 'bba2425c-43c5-4d8d-920c-993d894dd9e3'...,2025-07-23 13:33:09
30,9,2461,688364bf87cf5fec60dc8026,688bdddd87cf5fec60dc80d6,688364bf87cf5fec60dc8026,AiDevelop,688bdddd87cf5fec60dc80d5,Website Developer,The AI agent is a Website Developer with exper...,6888eec887cf5fec60dc8085,"[Web Design, SEO Management, Backend Developme...","[Suggest and revise text, Find fact and add re...",[{'id': '24896ea6-d264-4194-a432-94640ea924d5'...,2025-07-31 21:19:25
31,9,2464,688364bf87cf5fec60dc8026,688a6a2087cf5fec60dc80a2,688364bf87cf5fec60dc8026,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",688a52ad87cf5fec60dc8096,"[English Grammar and Syntax, Reading Comprehen...","[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-07-30 18:53:20
32,9,2457,688364bf87cf5fec60dc8026,688b7f6b87cf5fec60dc80b7,688364bf87cf5fec60dc8026,Rephraser,688b7f6b87cf5fec60dc80b6,Rephrase a sentence or section,The AI agent is designed to rephrase sentences...,688b1c7887cf5fec60dc80b0,"[Semantic Understanding, Grammar Knowledge, Co...","[Paraphrasing, Simplify Sentence, Shorten text...",[],2025-07-31 14:36:27
33,10,2459,6877c26e87cf5fec60dc7fda,6888bd4b87cf5fec60dc8073,6877c26e87cf5fec60dc7fda,Eureka,67b9b221adc01b1db6869c70,Idea Generator,"The AI agent serves as an Idea Generator, spec...",6888bbce87cf5fec60dc8072,"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],2025-07-29 12:23:39
34,10,2459,6877c26e87cf5fec60dc7fda,6888c9af87cf5fec60dc8081,6877c26e87cf5fec60dc7fda,Purchasing,6888c9af87cf5fec60dc8080,Planner,"The AI agent serves as a Planner, specializing...",6888bbce87cf5fec60dc8072,"[Event Coordination, Strategic Planning]","[Planning, Organization, Portuguese Marketplac...",[],2025-07-29 13:16:31
35,10,2459,6877c26e87cf5fec60dc7fda,688bd9f587cf5fec60dc80cc,6877c26e87cf5fec60dc7fda,Organizer,688bd9f587cf5fec60dc80cb,Wedding planner,"The AI agent serves as a wedding planner, spec...",6888bbce87cf5fec60dc8072,"[Event Management, Wedding Decor]","[Event Planning, Design Concepts]",[],2025-07-31 21:02:45
36,10,2465,6877c26e87cf5fec60dc7fda,688e30ee87cf5fec60dc80f4,6877c26e87cf5fec60dc7fda,Text Improver,688e30ee87cf5fec60dc80f3,Improve writting flow,The AI agent is designed to enhance writing fl...,688bdb6387cf5fec60dc80d0,"[Linguistic Knowledge, Text Coherence, Narrati...","[Error Spotting, Grammar Correction]",[],2025-08-02 15:38:22
37,11,2463,6889e57087cf5fec60dc8092,688b2aa687cf5fec60dc80b3,6889e57087cf5fec60dc8092,Fact Checker,688b2aa687cf5fec60dc80b2,Checking facts for scientific evidence,The AI agent is primarily responsible for fact...,6889e71f87cf5fec60dc8094,[],[],[],2025-07-31 08:34:46
38,11,2463,6889e57087cf5fec60dc8092,68931d9887cf5fec60dc810f,6889e57087cf5fec60dc8092,Synthesizer,68931d9887cf5fec60dc810e,Reading and synthesizing papers about a specif...,The AI agent is designed to meticulously read ...,6889e71f87cf5fec60dc8094,"[Document Analysis, Topic Understanding, Resea...","[Reference Tracking, Critical Analysis, Draft ...",[],2025-08-06 09:17:12
40,12,2468,688c6add87cf5fec60dc80ef,689c50c4e90ffc190a96c292,688c6add87cf5fec60dc80ef,AI Sceptic Reviewer,689c50c4e90ffc190a96c291,"A DFG reviewer, sceptic of AI usage, especiall...",The AI agent serves as a DFG reviewer with a s...,6898407be90ffc190a96c287,"[Artificial Intelligence, NLP, Large Language ...","[Reviewing, Critical Thinking]",[],2025-08-13 08:45:56
41,12,2468,688c6add87cf5fec60dc80ef,689c51e2e90ffc190a96c296,688c6add87cf5fec60dc80ef,References Nagger,689c51e2e90ffc190a96c295,"Checks text for missing references, i.e., stat...",The AI agent is designed to review text and id...,6898407be90ffc190a96c287,"[Computer Science, Public Sector]","[Reviewing, References, Citing]",[],2025-08-13 08:50:42
42,12,2469,688c6add87cf5fec60dc80ef,689c3da3e90ffc190a96c28f,688c6add87cf5fec60dc80ef,Nasty Nancy,689c3da3e90ffc190a96c28e,Opposite reviewer,"The AI agent, known as the Opposite Reviewer, ...",689c3c25e90ffc190a96c28b,[Reviewing research proposals and scientific t...,[Reviewing. Find every little weak spot. Harsh...,[],2025-08-13 07:24:19
43,13,2467,68907a6e87cf5fec60dc8107,68a5a808e90ffc190a96c307,68907a6e87cf5fec60dc8107,Mr. Correct,68a5a808e90ffc190a96c306,Proofreader,"The AI agent serves as a proofreader, speciali...",68a5a0bde90ffc190a96c2ff,[Linguistik],[Korrekturlesen],[],2025-08-20 10:48:40
44,13,2467,68907a6e87cf5fec60dc8107,68a5acf4e90ffc190a96c309,68907a6e87cf5fec60dc8107,Proposal Brain,68a5acf4e90ffc190a96c308,Researcher,"The AI agent serves as a Researcher, specializ...",68a5a0bde90ffc190a96c2ff,"[Process Management, Compliance, Künstliche In...","[Schreiben von Forschungsanträgen, Denken wie ...",[],2025-08-20 11:09:40
45,13,2467,68907a6e87cf5fec60dc8107,68a5adb8e90ffc190a96c30b,68907a6e87cf5fec60dc8107,Shrek's Donkey,68a5adb8e90ffc190a96c30a,Reviewer,"The AI agent serves as a reviewer, specializin...",68a5a0bde90ffc190a96c2ff,"[Process Management, Compliance, Künstliche In...","[Fragen stellen mit dem Ziel, Lücken in besteh...",[],2025-08-20 11:12:56
49,14,2471,6896071ee90ffc190a96c285,689e2470e90ffc190a96c2e4,6896071ee90ffc190a96c285,Grammar,689e2470e90ffc190a96c2e3,Grammar Checker,"The AI agent serves as a Grammar Checker, spec...",689e22d5e90ffc190a96c2e0,"[Punctuation Knowledge, Content Structure, Spe...","[Proofreading, Text Correction, Cut text, Stor...",[],2025-08-14 18:01:20
50,14,2471,6896071ee90ffc190a96c285,689e24b5e90ffc190a96c2e6,6896071ee90ffc190a96c285,Fact Checker,689e24b5e90ffc190a96c2e5,Fact checking,The AI agent is primarily responsible for fact...,689e22d5e90ffc190a96c2e0,"[Information Verification, Fact Analysis, Sour...","[Source Assessment, Cross Referencing, Text ou...",[],2025-08-14 18:02:29

Agent Counts, averages per group:
[A] How many agents, average per group

In [128]:
### count agents
doc_counts = study_agents['group_id'].value_counts()

print("Total agents: ", study_agents["_id"].dropna().count())

doc_counts_df = doc_counts.rename_axis('group_id').reset_index(name='count')

# group 2 had no agents, add group 2 with 0 
doc_counts_df.loc[len(doc_counts_df)] = [2, 0]

display(doc_counts_df)
doc_counts_df['count'].describe()

Total agents:  39

    group_id  count
0          4      4
1          5      4
2          6      4
3          8      4
4         10      4
5          3      3
6          9      3
7         12      3
8         13      3
9          7      2
10        11      2
11        14      2
12         1      1
13         2      0

count    14.000000
mean      2.785714
std       1.251373
min       0.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       4.000000
Name: count, dtype: float64

In [129]:
display(finished_participants[finished_participants["participant_id"] == 2460]["event"].value_counts())

event
DOCUMENT_TEXT_UPDATE                    48
MARKER_SELECT                           44
COMMENT_AGENT_STOP_TYPING               18
COMMENT_USER_DROPDOWN_SHOW              18
COMMENT_AGENT_START_TYPING              18
REPLY_AI                                18
COMMENT_ADD                             18
SUGGESTION_INSERT_AFTER                 14
TASK_CREATE                             13
TASKS_VIEW                              12
COMMENT_USER_DROPDOWN_HIDE              10
COMMENT_POST                            10
COMMENT_USER_DROPDOWN_SELECT            10
DOCUMENT_TEXT_PASTE                      9
COMMENT_TASK_ADD                         8
COMMENT_REPLY_APPROVE                    7
DOCUMENT_VIEW                            6
TASK_SHORTCUT_RUN                        6
CARD_ADD                                 5
TASKS_VIEW_CLOSE                         5
COMMENT_DELETE                           4
AGENT_CV_SECTION_VALUE_ADD               4
COMMENTS_REMOTE_ADD                      4
AGENTS_VIEW                              4
TASK_CREATED                             4
AGENT_ICON_CLICK                         4
CARD_CLOSE                               4
DOCUMENT_TEXT_COPY                       3
SUGGESTION_TAKE_OVER                     3
DOCUMENT_JOIN                            3
AGENT_CV_SECTION_GENERATED_VALUE_ADD     3
DOCUMENT_SAVE                            3
OPEN_AI_RESULT                           3
TASK_RUN                                 3
USER_LOGIN                               2
AGENT_ADD                                2
AGENT_CREATE                             2
AGENT_CV_SECTION_GENERATE                2
FINAL_PROCEED_TEXT                       2
AGENTS_VIEW_CLOSE                        2
USER_AGENT                               2
AGENT_SAVE                               1
T5_SUMMARY_AI_RESULT                     1
SUGGESTION_VIEWDETAIL                    1
AGENT_CV_SECTION_ADD                     1
AGENT_PROFILE_VIEW                       1
CARD_APPROVE                             1
Name: count, dtype: int64

Number of preset use + 1 from group 4 which don't have logs:

In [130]:
# number of preset use + 1 from group 4 which don't have logs
print("Agent preset use:")
len(finished_participants[finished_participants["event"] == "AGENT_PRESET_USE"]) + 1

Agent preset use:

10

In [131]:
# preset view events
agent_preset_view_df = finished_participants[finished_participants["event"] == "AGENT_PRESET_VIEW"]
display(agent_preset_view_df)
print("Agents preset views total: ", agent_preset_view_df["event"].count())

,Unnamed: 0.1,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
34,34,211,276221.0,52211ea8-8a4d-4d29-9533-e58325acfb1e,Prototype,2025-03-07 21:41:28.918000,AGENT_PRESET_VIEW,"{""user_id"": ""67cb6623285fac3f07bcf59a"", ""agent...",1377,2aac5afe-a3af-4135-a1a3-78adf87ae9d8,finished,"{'user_id': '67cb6623285fac3f07bcf59a', 'agent...",67c97527285fac3f07bcf587
1371,1373,1550,277564.0,5c399155-afed-48ec-8de1-eae9c41f7cfb,Prototype,2025-03-10 12:45:18.096000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
1372,1374,1551,277565.0,b5f976c3-d152-4341-9fcb-a30e28bc4eb8,Prototype,2025-03-10 12:45:20.755000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
1373,1375,1552,277566.0,01246a4e-72e7-46a9-94db-1ac6947a8da6,Prototype,2025-03-10 12:45:21.395000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
1374,1376,1553,277567.0,472b6113-78f2-44e4-a862-80e8dc7d6ade,Prototype,2025-03-10 12:45:22.227000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
1399,1401,1578,277592.0,822ad669-859d-4eea-a6c8-d3bcbab30410,Prototype,2025-03-10 12:54:17.201000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
1401,1403,1580,277594.0,334c1fff-19c6-456c-8fa2-23d03879c079,Prototype,2025-03-10 12:54:33.462000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
1403,1405,1582,277596.0,c379ec2c-79ba-463a-89d1-b41eb5c02c94,Prototype,2025-03-10 12:55:08.292000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
1404,1406,1583,277597.0,debcee40-9dee-4a2b-af6b-b2a59b3b176f,Prototype,2025-03-10 12:55:10.294000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
1405,1407,1584,277598.0,f672fb13-ad26-44ac-8d2f-cdc75e7ee00d,Prototype,2025-03-10 12:55:10.658000,AGENT_PRESET_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
2014,2018,2220,278234.0,71486b02-ea13-47d1-9b66-7d94222187e5,Prototype,2025-03-14 15:06:10.022000,AGENT_PRESET_VIEW,"{""user_id"": ""67d444dd0b9539e69a3a86bb"", ""agent...",1384,7d1fcfca-d63f-45e6-a0cf-06122aebe7c6,finished,"{'user_id': '67d444dd0b9539e69a3a86bb', 'agent...",67d43b390b9539e69a3a86b9
2052,2056,2286,278300.0,ffc79a3b-5cc3-49d9-a145-f6e9228d3ff8,Prototype,2025-03-15 19:43:48.142000,AGENT_PRESET_VIEW,"{""user_id"": ""67d5d8120b9539e69a3a86d7"", ""agent...",1387,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,finished,"{'user_id': '67d5d8120b9539e69a3a86d7', 'agent...",67d5d8160b9539e69a3a86d8
2058,2062,2292,278306.0,a67074ee-e36a-4a7e-93aa-228584fb1b03,Prototype,2025-03-15 19:44:02.643000,AGENT_PRESET_VIEW,"{""user_id"": ""67d5d8120b9539e69a3a86d7"", ""agent...",1387,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,finished,"{'user_id': '67d5d8120b9539e69a3a86d7', 'agent...",67d5d8160b9539e69a3a86d8
2059,2063,2293,278307.0,f08642a9-1654-4b86-854d-561a907d62ff,Prototype,2025-03-15 19:44:03.007000,AGENT_PRESET_VIEW,"{""user_id"": ""67d5d8120b9539e69a3a86d7"", ""agent...",1387,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,finished,"{'user_id': '67d5d8120b9539e69a3a86d7', 'agent...",67d5d8160b9539e69a3a86d8
2061,2065,2295,278309.0,9e7cac15-1a45-4bbe-a85c-47a80413597b,Prototype,2025-03-15 19:44:13.231000,AGENT_PRESET_VIEW,"{""user_id"": ""67d5d8120b9539e69a3a86d7"", ""agent...",1387,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,finished,"{'user_id': '67d5d8120b9539e69a3a86d7', 'agent...",67d5d8160b9539e69a3a86d8
2327,2331,2562,278576.0,1c1f78ca-1311-4f0a-bbc3-dbb7ab77d19a,Prototype,2025-03-17 14:19:22.688000,AGENT_PRESET_VIEW,"{""user_id"": ""67d82e0aedfe680c1b0f1643"", ""agent...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished,"{'user_id': '67d82e0aedfe680c1b0f1643', 'agent...",67d08e87285fac3f07bcf64b
2331,2335,2566,278580.0,536c43c6-9097-4692-bc35-a3bc07cf9927,Prototype,2025-03-17 14:19:27.894000,AGENT_PRESET_VIEW,"{""user_id"": ""67d82e0aedfe680c1b0f1643"", ""agent...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished,"{'user_id': '67d82e0aedfe680c1b0f1643', 'agent...",67d08e87285fac3f07bcf64b
2451,2455,2686,278700.0,1b58ca86-7d98-40b8-b43a-706c06868592,Prototype,2025-03-17 14:39:09.111000,AGENT_PRESET_VIEW,"{""user_id"": ""67d82dc4edfe680c1b0f1642"", ""agent...",1388,3b49f849-3081-4478-81ce-d65450662c47,finished,"{'user_id': '67d82dc4edfe680c1b0f1642', 'agent...",67d08e87285fac3f07bcf64b
2585,2589,2820,278834.0,aadc4038-4277-4537-a8d9-db30fd88f68f,Prototype,2025-03-17 14:44:36.246000,AGENT_PRESET_VIEW,"{""user_id"": ""67d82dc4edfe680c1b0f1642"", ""agent...",1388,3b49f849-3081-4478-81ce-d65450662c47,finished,"{'user_id': '67d82dc4edfe680c1b0f1642', 'agent...",67d08e87285fac3f07bcf64b
2935,3274,3546,279629.0,43740d98-92af-40a0-b40f-4997f32f5c8f,Prototype,2025-07-21 07:57:50.526000,AGENT_PRESET_VIEW,"{""user_id"": ""687de5d187cf5fec60dc7fef"", ""agent...",2453,e24dd41b-25cb-4503-a4b7-4919fc0e688f,finished,"{'user_id': '687de5d187cf5fec60dc7fef', 'agent...",6879e8fd87cf5fec60dc7fe1
2937,3276,3548,279631.0,baf41b68-87aa-4bf9-b22a-c1c7253ffc75,Prototype,2025-07-21 07:57:56.520000,AGENT_PRESET_VIEW,"{""user_id"": ""687de5d187cf5fec60dc7fef"", ""agent...",2453,e24dd41b-25cb-4503-a4b7-4919fc0e688f,finished,"{'user_id': '687de5d187cf5fec60dc7fef', 'agent...",6879e8fd87cf5fec60dc7fe1
2938,3277,3549,279632.0,6a2d4abe-a812-4161-a982-ff9b5f39b3fb,Prototype,2025-07-21 07:57:58.663000,AGENT_PRESET_VIEW,"{""user_id"": ""687de5d187cf5fec60dc7fef"", ""agent...",2453,e24dd41b-25cb-4503-a4b7-4919fc0e688f,finished,"{'user_id': '687de5d187cf5fec60dc7fef', 'agent...",6879e8fd87cf5fec60dc7fe1
2939,3278,3550,279633.0,3154f4e3-299a-4662-8ddf-0649a217d5f3,Prototype,2025-07-21 07:58:06.042000,AGENT_PRESET_VIEW,"{""user_id"": ""687de5d187cf5fec60dc7fef"", ""agent...",2453,e24dd41b-25cb-4503-a4b7-4919fc0e688f,finished,"{'user_id': '687de5d187cf5fec60dc7fef', 'agent...",6879e8fd87cf5fec60dc7fe1
3246,3585,3864,279947.0,a78e8865-e98b-49e1-be9c-0fdb6d1449f4,Prototype,2025-07-28 13:05:56.025000,AGENT_PRESET_VIEW,"{""user_id"": ""68835b0587cf5fec60dc8020"", ""agent...",2456,ee84f721-81d3-4914-b1a4-09de1502b0bc,finished,"{'user_id': '68835b0587cf5fec60dc8020', 'agent...",68833fd687cf5fec60dc801d
3247,3586,3865,279948.0,34a33bea-ac09-47d4-8074-578f1ec89aa6,Prototype,2025-07-28 13:06:01.409000,AGENT_PRESET_VIEW,"{""user_id"": ""68835b0587cf5fec60dc8020"", ""agent...",2456,ee84f721-81d3-4914-b1a4-09de1502b0bc,finished,"{'user_id': '68835b0587cf5fec60dc8020', 'agent...",68833fd687cf5fec60dc801d
4196,4535,4814,280897.0,13d65266-0856-4de9-911a-c0d1fa677024,Prototype,2025-07-29 12:23:28.661000,AGENT_PRESET_VIEW,"{""user_id"": ""6888bbce87cf5fec60dc8072"", ""agent...",2459,a1f051f1-f2f3-45e1-9274-7deb05f97604,finished,"{'user_id': '6888bbce87cf5fec60dc8072', 'agent...",6877c26e87cf5fec60dc7fda
4565,4904,5183,281266.0,03bb048b-3410-4d39-aeef-2b9973a015a7,Prototype,2025-07-30 18:53:15.047000,AGENT_PRESET_VIEW,"{""user_id"": ""688a52ad87cf5fec60dc8096"", ""agent...",2464,5a6b1f2c-f401-420f-b26d-46d9db679384,finished,"{'user_id': '688a52ad87cf5fec60dc8096', 'agent...",688364bf87cf5fec60dc8026
6052,6391,6670,282753.0,8d58453a-03e6-4aea-8c40-ceda1e2c4c60,Prototype,2025-08-13 09:51:48.245000,AGENT_PRESET_VIEW,"{""user_id"": ""689c3c25e90ffc190a96c28b"", ""agent...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,"{'user_id': '689c3c25e90ffc190a96c28b', 'agent...",688c6add87cf5fec60dc80ef

Agents preset views total:  28

Agent profile updates, from event logs:
[C]Collaboratively or not? E.g. how often was the agent edited by someone else
[D]Iteration: How often were agents edited after creating them?

In [132]:
# agent profile updates
agent_update_df = finished_participants[finished_participants["event"] == "AGENT_UPDATE"]
display(agent_update_df)

print("Total agent update events:", agent_update_df['id'].count())

parsed_agent_update_df = parse_json_field(agent_update_df, "data")
collaborator_agent_updates = parsed_agent_update_df[parsed_agent_update_df['agent.author_id'] != parsed_agent_update_df['user_id']]

print("Collaborators updated agent:", collaborator_agent_updates['user_id'].count())

,Unnamed: 0.1,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
443,445,622,276632.0,14dfb97a-2f1a-452e-aed1-60f0b2723fcf,Prototype,2025-03-09 21:29:24.834000,AGENT_UPDATE,"{""agent"": {""id"": ""67cdfef4285fac3f07bcf5d3"", ""...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'agent': {'id': '67cdfef4285fac3f07bcf5d3', '...",67c88f88285fac3f07bcf585
2424,2428,2659,278673.0,1339aafb-47de-4d70-badb-89cd2d7507e3,Prototype,2025-03-17 14:34:35.475000,AGENT_UPDATE,"{""agent"": {""id"": ""67d82fbfedfe680c1b0f164e"", ""...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished,"{'agent': {'id': '67d82fbfedfe680c1b0f164e', '...",67d08e87285fac3f07bcf64b
2664,2668,2899,278913.0,cfc87ef2-7b50-4f5d-997a-1782835ff795,Prototype,2025-03-17 14:59:50.363000,AGENT_UPDATE,"{""agent"": {""id"": ""67d82fbfedfe680c1b0f164e"", ""...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished,"{'agent': {'id': '67d82fbfedfe680c1b0f164e', '...",67d08e87285fac3f07bcf64b
2941,3280,3552,279635.0,0c965db9-f6a9-446c-8098-344b3e2d1f59,Prototype,2025-07-21 07:58:24.888000,AGENT_UPDATE,"{""agent"": {""id"": ""687df2ff87cf5fec60dc7ff1"", ""...",2453,e24dd41b-25cb-4503-a4b7-4919fc0e688f,finished,"{'agent': {'id': '687df2ff87cf5fec60dc7ff1', '...",6879e8fd87cf5fec60dc7fe1
4784,5123,5402,281485.0,80c42916-530f-4da7-a123-95ed6e7a86cd,Prototype,2025-07-31 14:32:35.594000,AGENT_UPDATE,"{""agent"": {""id"": ""688a6a2087cf5fec60dc80a2"", ""...",2457,14291cb8-c3c7-433e-9a0c-830cca8e4422,finished,"{'agent': {'id': '688a6a2087cf5fec60dc80a2', '...",688364bf87cf5fec60dc8026
5388,5727,6006,282089.0,833613b9-4e91-4ba9-b75e-03824e84268b,Prototype,2025-07-31 21:20:16.808000,AGENT_UPDATE,"{""agent"": {""id"": ""688bdddd87cf5fec60dc80d6"", ""...",2461,46820311-be03-4d2e-b993-90ac3bec3c92,in_progress,"{'agent': {'id': '688bdddd87cf5fec60dc80d6', '...",688364bf87cf5fec60dc8026

Total agent update events: 6
Collaborators updated agent: 1

/tmp/ipykernel_112605/962560954.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  event_df[json_field + "_parsed"] = event_df[json_field].apply(json.loads)

[E] Use of specific profile features (e.g. suggestions, CV, notes)
CV Generations, from event logs:

In [133]:
# events for generated sections in CV form
print("Agent profile section suggestions total: ")
display(finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_GENERATE"]["event"].count())

agent_profile_update_df = parse_generic_event(finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_GENERATE"])
print("Profile section suggestions counts:")
display(agent_profile_update_df["section"].value_counts())
display(agent_profile_update_df)

total_section_suggestions = len(sum(agent_profile_update_df['suggestions'].dropna().to_list(), []))
print(agent_profile_update_df['suggestions'].dropna().to_list())
print("total number of values suggested for sections: ", total_section_suggestions)

Agent profile section suggestions total:

56

Profile section suggestions counts:

section
skills       27
expertise    25
undefined     4
Name: count, dtype: int64

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,section,user_id,agent_id,username,document_id,suggestions,oldSuggestions,participant_token
0,276462.0,2025-03-09 20:34:11.966000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATE,aaa39609-dd91-45cb-9bfc-9315ab80b825,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Literature Studies, Academic Editing, Grammar...",[],93f70a37-e7d5-4bcf-adbc-d106ca47c27b
1,276466.0,2025-03-09 20:34:46.832000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_GENERATE,58682907-a0f5-4499-987a-e069c1921964,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Grammar Check, Punctuation Correction, Find f...","[Revise text, Summarization, Format text, Shor...",93f70a37-e7d5-4bcf-adbc-d106ca47c27b
2,276467.0,2025-03-09 20:34:54.646000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_GENERATE,7712da53-bf75-4810-9d07-e5aba95f7b30,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Citation Formatting, Thesis Structuring, Form...","[Grammar Check, Punctuation Correction, Find f...",93f70a37-e7d5-4bcf-adbc-d106ca47c27b
3,276500.0,2025-03-09 20:48:35.962000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_GENERATE,e4ab8385-3dab-4c81-b53b-e1f17c563ed1,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Data Verification, Credibility Assessment, Su...","[Revise text, Summarization, Format text, Shor...",93f70a37-e7d5-4bcf-adbc-d106ca47c27b
4,276503.0,2025-03-09 20:48:48.552000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATE,e14b6625-4aa5-4840-a11b-a1624056fe74,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Historical Research, Statistic Analysis, Fact...",[],93f70a37-e7d5-4bcf-adbc-d106ca47c27b
5,277479.0,2025-03-10 08:39:19.171000,1380,"{""section"": ""skills"", ""user_id"": ""67ce9cb4285f...",AGENT_CV_SECTION_GENERATE,c5492b21-a58c-4e5c-b7b8-b11fc93a8308,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'section': 'skills', 'user_id': '67ce9cb4285f...",skills,67ce9cb4285fac3f07bcf5ec,mocked-new-agent,mrnexeon,67ce983b285fac3f07bcf5e8,"[Document structuring, Organizing ideas, Ideat...","[Revise text, Summarization, Format text, Shor...",ecc027d0-42cd-42a1-bc2e-990b5516565b
6,277600.0,2025-03-10 12:56:40.368000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATE,54cf04a0-8de0-42ae-9f31-fd92d79d14a8,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[AI Implementation, Process Automation, Techno...",[],93f70a37-e7d5-4bcf-adbc-d106ca47c27b
7,278313.0,2025-03-15 19:45:00.732000,1387,"{""section"": ""expertise"", ""user_id"": ""67d5d8120...",AGENT_CV_SECTION_GENERATE,6ab169e8-9704-4007-a73c-fb144c184014,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'expertise', 'user_id': '67d5d8120...",expertise,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,"[Adult Education, Comedy Writing, Counseling]",[],5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
8,278317.0,2025-03-15 19:45:08.876000,1387,"{""section"": ""skills"", ""user_id"": ""67d5d8120b95...",AGENT_CV_SECTION_GENERATE,6fffabaa-444e-4cf4-94e7-2ffc02bf3865,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'skills', 'user_id': '67d5d8120b95...",skills,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,"[Comedy Timing, Expressive Teaching, Extend text]","[Revise text, Summarization, Format text, Shor...",5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
9,278549.0,2025-03-17 14:18:27.240000,1388,"{""section"": ""expertise"", ""user_id"": ""67d82dc4e...",AGENT_CV_SECTION_GENERATE,315c6ed1-9284-4c9c-bd39-c6da010aa452,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'expertise', 'user_id': '67d82dc4e...",expertise,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,"[Language Proficiency, Syntax Knowledge, Punct...",[],3b49f849-3081-4478-81ce-d65450662c47
10,278554.0,2025-03-17 14:18:44.545000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATE,7eb8ecbb-b216-4645-8887-b990be4a401c,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,"[Text Elaboration, Sentence Optimization, Form...","[Revise text, Summarization, Format text, Shor...",3b49f849-3081-4478-81ce-d65450662c47
11,278558.0,2025-03-17 14:18:53.674000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATE,cec3a722-effd-4814-bc59-4cac0670dc7d,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,"[Sentence Structuring, Text Debugging, Find fa...","[Sentence Optimization, Revise text, Summariza...",3b49f849-3081-4478-81ce-d65450662c47
12,278559.0,2025-03-17 14:18:46.779000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATE,88104496-0c3a-4438-bf0b-4bf6e027c90e,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,"[Citation Verification, Spelling Expert, Punct...",[],ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
13,278563.0,2025-03-17 14:19:03.028000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATE,7e086159-c1ed-406b-8c06-80bd111ae1b9,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,"[Proofreading, Text Editing, Summarization]","[Find fact and add reference, Revise text, Sum...",3b49f849-3081-4478-81ce-d65450662c47
14,278569.0,2025-03-17 14:19:04.121000,1389,"{""section"": ""skills"", ""user_id"": ""67d82e0aedfe...",AGENT_CV_SECTION_GENERATE,01f972c6-6ba8-4bc2-8de1-df54f334b455,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'skills', 'user_id': '67d82e0aedfe...",skills,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,"[Grammar Checking, Typo Identification, Genera...","[Revise text, Summarization, Format text, Shor...",ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
15,278588.0,2025-03-17 14:19:48.962000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATE,15769efc-761b-48db-b158-c37e4db4e547,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,"[Grammar Knowledge, Content Editing, Publicati...",[],ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
16,279950.0,2025-07-28 13:06:58.010000,2456,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,485aa975-3374-4f69-904b-5ac171786e99,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Grammar Proficiency, Proofreading Expert, Con...",[],ee84f721-81d3-4914-b1a4-09de1502b0bc
17,279951.0,2025-07-28 13:07:43.241000,2456,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,bcff6262-9910-4e5f-8065-01d1f08294b0,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Copy Editing, Publishing Know-how, Research S...","[Grammar Proficiency, Proofreading Expert, Con...",ee84f721-81d3-4914-b1a4-09de1502b0bc
18,279956.0,2025-07-28 13:09:39.918000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATE,85a5046c-f84e-466b-99df-e8bdb12e3e0b,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Text Editing, Grammar Correction, Ideation]","[Revise text, Summarization, Format text, Shor...",ee84f721-81d3-4914-b1a4-09de1502b0bc
19,279959.0,2025-07-28 13:09:45.693000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATE,5e9f5b5a-ce72-4a7f-9d03-99aa2d94364c,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Storytelling, Plagiarism Check, Translate]","[Ideation, Revise text, Summarization, Format ...",ee84f721-81d3-4914-b1a4-09de1502b0bc
20,279960.0,2025-07-28 13:09:52.233000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATE,afd2e4d5-b0e0-40b0-93cd-061e26fe211e,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Creative Writing, Topic Research, Question an...","[Storytelling, Plagiarism Check, Translate, Re...",ee84f721-81d3-4914-b1a4-09de1502b0bc
21,279967.0,2025-07-28 13:11:20.774000,2456,"{""section"": ""undefined"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,623c83b8-8ad5-44a1-ae18-ad2b5d46f101,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'undefined', 'user_id': '68835b058...",undefined,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Literature Synthesis, Content Creation, Poetr...",[],ee84f721-81d3-4914-b1a4-09de1502b0bc
22,279968.0,2025-07-28 13:11:30.605000,2456,"{""section"": ""undefined"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,e08dfccc-742d-4943-96a6-55a431295f0f,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'undefined', 'user_id': '68835b058...",undefined,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Ghostwriting, Fiction Writing, Drama Composit...","[Literature Synthesis, Content Creation, Poetr...",ee84f721-81d3-4914-b1a4-09de1502b0bc
23,279969.0,2025-07-28 13:11:36.052000,2456,"{""section"": ""undefined"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,96fdeed1-e7d9-44b8-9197-04ea09e6e6bc,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'undefined', 'user_id': '68835b058...",undefined,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Script Writing, Narrative Design, Poetic Comp...","[Ghostwriting, Fiction Writing, Drama Composit...",ee84f721-81d3-4914-b1a4-09de1502b0bc
24,280570.0,2025-07-28 18:03:30.794000,2460,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",AGENT_CV_SECTION_GENERATE,056b62ba-07b9-4b86-a9ae-39142fbef67c,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'skills', 'user_id': '6887b97087cf...",skills,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,"[Grammar Checking, Style Enhancement, Find fac...","[Revise text, Summarization, Format text, Shor...",4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
25,280576.0,2025-07-28 18:03:44.585000,2460,"{""section"": ""undefined"", ""user_id"": ""6887b9708...",AGENT_CV_SECTION_GENERATE,c1ce8587-1539-4698-9273-4ea83ee0a15f,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'undefined', 'user_id': '6887b9708...",undefined,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,"[Content Refinement, Text Optimization, Langua...",[],4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
26,280993.0,2025-07-29 13:15:53.659000,2459,"{""section"": ""expertise"", ""user_id"": ""6888bbce8...",AGENT_CV_SECTION_GENERATE,752910a4-3c11-4534-a737-2a9d16ad4426,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'expertise', 'user_id': '6888bbce8...",expertise,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,"[Project Management, Resource Allocation, Budg...",[],a1f051f1-f2f3-45e1-9274-7deb05f97604
27,280994.0,2025-07-29 13:16:01.851000,2459,"{""section"": ""expertise"", ""user_id"": ""6888bbce8...",AGENT_CV_SECTION_GENERATE,a05fa167-1a38-4d4c-a27c-b77f3e968c92,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'expertise', 'user_id': '6888bbce8...",expertise,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,"[Event Coordination, Strategic Planning, Time ...","[Project Management, Resource Allocation, Budg...",a1f051f1-f2f3-45e1-9274-7deb05f97604
28,280996.0,2025-07-29 13:16:14.548000,2459,"{""section"": ""skills"", ""user_id"": ""6888bbce87cf...",AGENT_CV_SECTION_GENERATE,313ec09d-6772-4ff0-a4c4-5f346e840fb7,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'skills', 'user_id': '6888bbce87cf...",skills,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,"[Budget Management, Vendor Negotiation, Questi...","[Revise text, Summarization, Format text, Shor...",a1f051f1-f2f3-45e1-9274-7deb05f97604
29,280999.0,2025-07-29 13:16:24.378000,2459,"{""section"": ""expertise"", ""user_id"": ""6888bbce8...",AGENT_CV_SECTION_GENERATE,76e4ac1e-2ff9-4e9c-a869-34915c0d1d2b,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'expertise', 'user_id': '6888bbce8...",expertise,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,"[Risk Analysis, Resource Allocation, Market Fo...",[Time Management],a1f051f1-f2f3-45e1-9274-7deb05f97604
30,281478.0,2025-07-31 14:31:55.263000,2457,"{""section"": ""expertise"", ""user_id"": ""688b1c788...",AGENT_CV_SECTION_GENERATE,dd573de7-cee4-4613-bef3-ad0a12e441b8,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'expertise', 'user_id': '688b1c788...",expertise,688b1c7887cf5fec60dc80b0,688a6a2087cf5fec60dc80a2,soumyashaw,688364bf87cf5fec60dc8026,"[Literature Understanding, Reading Comprehensi...",[],14291cb8-c3c7-433e-9a0c-830cca8e4422
31,281489.0,2025-07-31 14:35:36.012000,2457,"{""section"": ""expertise"", ""user_id"": ""688b1c788...",AGENT_CV_SECTION_GENERATE,8dc9e25c-d220-4e1c-a21c-b0f1cb6190b6,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'expertise', 'user_id': '688b1c788...",expertise,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,"[Semantic Understanding, Grammar Knowledge, Co...",[],14291cb8-c3c7-433e-9a0c-830cca8e4422
32,281493.0,2025-07-31 14:36:02.124000,2457,"{""section"": ""skills"", ""user_id"": ""688b1c7887cf...",AGENT_CV_SECTION_GENERATE,63addec4-5faa-494e-ab22-72f84cd124e8,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'skills', 'user_id': '688b1c7887cf...",skills,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,"[Paraphrasing, Simplify Sentence, Shorten text]","[Revise text, Summarization, Format text, Shor...",14291cb8-c3c7-433e-9a0c-830cca8e4422
33,281497.0,2025-07-31 14:36:15.641000,2457,"{""section"": ""skills"", ""user_id"": ""688b1c7887cf...",AGENT_CV_SECTION_GENERATE,43b23a59-f72a-42b2-bb7a-a82d8044865b,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'skills', 'user_id': '688b1c7887cf...",skills,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,"[Sentence Conversion, Text Reworking, Text out...","[Revise text, Summarization, Format text, Shor...",14291cb8-c3c7-433e-9a0c-830cca8e4422
34,282027.0,2025-07-31 21:17:27.413000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,2f2815b0-104f-489e-a7f5-18251ace6f01,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Web Design, SEO Management, E-commerce Develo...",[],46820311-be03-4d2e-b993-90ac3bec3c92
35,282031.0,2025-07-31 21:17:32.587000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,35309d43-42d4-458b-ac74-09a3fd4801b9,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Database Management, User Interface Design, M...",[],46820311-be03-4d2e-b993-90ac3bec3c92
36,282032.0,2025-07-31 21:17:36.516000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,e8398d02-9566-43f4-a20d-c0cf4768455b,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Backend Development, JavaScript Programming, ...","[Database Management, User Interface Design, M...",46820311-be03-4d2e-b993-90ac3bec3c92
37,282035.0,2025-07-31 21:17:41.942000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,a8a7e46b-1b59-4d70-bc28-313db29b32de,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Frontend Development, HTML Coding, CSS Styling]",[JavaScript Programming],46820311-be03-4d2e-b993-90ac3bec3c92
38,282038.0,2025-07-31 21:17:45.386000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,e80481ba-4bb0-4e2e-b927-1ed109194cf7,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[JavaScript Programming, Database Management, ...",[CSS Styling],46820311-be03-4d2e-b993-90ac3bec3c92
39,282042.0,2025-07-31 21:17:48.760000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,45511d9b-edcd-4914-b1c1-31516602b08d,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[CSS Styling, SSL Security, Mobile Development]",[],46820311-be03-4d2e-b993-90ac3bec3c92
40,282046.0,2025-07-31 21:17:55.493000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,0c6c75c8-3cc0-482e-a843-71a8aebd5271,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[WordPress Customization, PHP Programming, Hos...",[SSL Security],46820311-be03-4d2e-b993-90ac3bec3c92
41,282048.0,2025-07-31 21:18:00.834000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,3c45402d-fd6f-4ec4-bb21-6e6803858d25,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Content Management, App Development, Security...","[WordPress Customization, PHP Programming, Hos...",46820311-be03-4d2e-b993-90ac3bec3c92
42,282051.0,2025-07-31 21:18:06.480000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,1fd3822b-06a1-44bb-8898-ad5a381ef5b7,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[E-commerce Integration, Web Analytics, Mobile...","[Content Management, Security Compliance]",46820311-be03-4d2e-b993-90ac3bec3c92

[['Literature Studies', 'Academic Editing', 'Grammar Mastery'], ['Grammar Check', 'Punctuation Correction', 'Find fact and add reference'], ['Citation Formatting', 'Thesis Structuring', 'Format text'], ['Data Verification', 'Credibility Assessment', 'Summarization'], ['Historical Research', 'Statistic Analysis', 'Fact Validation'], ['Document structuring', 'Organizing ideas', 'Ideation'], ['AI Implementation', 'Process Automation', 'Technological Support'], ['Adult Education', 'Comedy Writing', 'Counseling'], ['Comedy Timing', 'Expressive Teaching', 'Extend text'], ['Language Proficiency', 'Syntax Knowledge', 'Punctuation Awareness'], ['Text Elaboration', 'Sentence Optimization', 'Format text'], ['Sentence Structuring', 'Text Debugging', 'Find fact and add reference'], ['Citation Verification', 'Spelling Expert', 'Punctuation Mastery'], ['Proofreading', 'Text Editing', 'Summarization'], ['Grammar Checking', 'Typo Identification', 'Generate text'], ['Grammar Knowledge', 'Content Editing', 'Publication Formatting'], ['Grammar Proficiency', 'Proofreading Expert', 'Content Development'], ['Copy Editing', 'Publishing Know-how', 'Research Skills'], ['Text Editing', 'Grammar Correction', 'Ideation'], ['Storytelling', 'Plagiarism Check', 'Translate'], ['Creative Writing', 'Topic Research', 'Question answering'], ['Literature Synthesis', 'Content Creation', 'Poetry Writing'], ['Ghostwriting', 'Fiction Writing', 'Drama Composition'], ['Script Writing', 'Narrative Design', 'Poetic Composition'], ['Grammar Checking', 'Style Enhancement', 'Find fact and add reference'], ['Content Refinement', 'Text Optimization', 'Language Enhancement'], ['Project Management', 'Resource Allocation', 'Budgeting'], ['Event Coordination', 'Strategic Planning', 'Time Management'], ['Budget Management', 'Vendor Negotiation', 'Question answering'], ['Risk Analysis', 'Resource Allocation', 'Market Forecasting'], ['Literature Understanding', 'Reading Comprehension', 'Essay Marking'], ['Semantic Understanding', 'Grammar Knowledge', 'Context Awareness'], ['Paraphrasing', 'Simplify Sentence', 'Shorten text'], ['Sentence Conversion', 'Text Reworking', 'Text outline'], ['Web Design', 'SEO Management', 'E-commerce Development'], ['Database Management', 'User Interface Design', 'Mobile Development'], ['Backend Development', 'JavaScript Programming', 'UI/UX Design'], ['Frontend Development', 'HTML Coding', 'CSS Styling'], ['JavaScript Programming', 'Database Management', 'Performance Optimization'], ['CSS Styling', 'SSL Security', 'Mobile Development'], ['WordPress Customization', 'PHP Programming', 'Hosting Management'], ['Content Management', 'App Development', 'Security Compliance'], ['E-commerce Integration', 'Web Analytics', 'Mobile Optimization'], ['Bug Fixing', 'Cross-Browser Compatibility', 'Revise text'], ['WordPress Customization', 'Responsive Design', 'Cut text'], ['Plugin Development', 'Server Configuration', 'Find fact and add reference'], ['CSS Debugging', 'JavaScript Testing', 'Translate'], ['SQL Integration', 'API Development', 'Summarization'], ['Debugging Code', 'Bootstrap Framework', 'Translate'], ['WordPress Integration', 'Responsive Design', 'Generate text'], ['PHP Development', 'Debugging Code', 'Cut text'], ['Code Testing', 'Web Security', 'Translate'], ['Syntax Analysis', 'Content Structure', 'Punctuation Knowledge'], ['Proofreading', 'Text Correction', 'Cut text'], ['Information Verification', 'Fact Analysis', 'Source Validation'], ['Source Assessment', 'Cross Referencing', 'Text outline']]
total number of values suggested for sections:  168

In [134]:
# group behavior for adding sections
agent_profile_update_merged_df = pd.merge(groups_df, agent_profile_update_df, left_on='user', right_on='participant_id', how='left')
agent_profile_update_merged_df = agent_profile_update_merged_df.dropna().drop_duplicates(subset=['event_uuid'])

display(agent_profile_update_merged_df)
print("number of generated sections by group")
print(agent_profile_update_merged_df["group_id"].value_counts())

,group_id,user,user_id_x,document,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,section,user_id_y,agent_id,username,document_id,suggestions,oldSuggestions,participant_token
1,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8,277479.0,2025-03-10 08:39:19.171000,1380.0,"{""section"": ""skills"", ""user_id"": ""67ce9cb4285f...",AGENT_CV_SECTION_GENERATE,c5492b21-a58c-4e5c-b7b8-b11fc93a8308,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'section': 'skills', 'user_id': '67ce9cb4285f...",skills,67ce9cb4285fac3f07bcf5ec,mocked-new-agent,mrnexeon,67ce983b285fac3f07bcf5e8,"[Document structuring, Organizing ideas, Ideat...","[Revise text, Summarization, Format text, Shor...",ecc027d0-42cd-42a1-bc2e-990b5516565b
5,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,276462.0,2025-03-09 20:34:11.966000,1374.0,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATE,aaa39609-dd91-45cb-9bfc-9315ab80b825,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Literature Studies, Academic Editing, Grammar...",[],93f70a37-e7d5-4bcf-adbc-d106ca47c27b
6,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,276466.0,2025-03-09 20:34:46.832000,1374.0,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_GENERATE,58682907-a0f5-4499-987a-e069c1921964,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Grammar Check, Punctuation Correction, Find f...","[Revise text, Summarization, Format text, Shor...",93f70a37-e7d5-4bcf-adbc-d106ca47c27b
7,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,276467.0,2025-03-09 20:34:54.646000,1374.0,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_GENERATE,7712da53-bf75-4810-9d07-e5aba95f7b30,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Citation Formatting, Thesis Structuring, Form...","[Grammar Check, Punctuation Correction, Find f...",93f70a37-e7d5-4bcf-adbc-d106ca47c27b
8,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,276500.0,2025-03-09 20:48:35.962000,1374.0,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_GENERATE,e4ab8385-3dab-4c81-b53b-e1f17c563ed1,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Data Verification, Credibility Assessment, Su...","[Revise text, Summarization, Format text, Shor...",93f70a37-e7d5-4bcf-adbc-d106ca47c27b
9,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,276503.0,2025-03-09 20:48:48.552000,1374.0,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATE,e14b6625-4aa5-4840-a11b-a1624056fe74,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[Historical Research, Statistic Analysis, Fact...",[],93f70a37-e7d5-4bcf-adbc-d106ca47c27b
10,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585,277600.0,2025-03-10 12:56:40.368000,1374.0,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATE,54cf04a0-8de0-42ae-9f31-fd92d79d14a8,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,"[AI Implementation, Process Automation, Techno...",[],93f70a37-e7d5-4bcf-adbc-d106ca47c27b
14,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,278313.0,2025-03-15 19:45:00.732000,1387.0,"{""section"": ""expertise"", ""user_id"": ""67d5d8120...",AGENT_CV_SECTION_GENERATE,6ab169e8-9704-4007-a73c-fb144c184014,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'expertise', 'user_id': '67d5d8120...",expertise,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,"[Adult Education, Comedy Writing, Counseling]",[],5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
15,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8,278317.0,2025-03-15 19:45:08.876000,1387.0,"{""section"": ""skills"", ""user_id"": ""67d5d8120b95...",AGENT_CV_SECTION_GENERATE,6fffabaa-444e-4cf4-94e7-2ffc02bf3865,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'skills', 'user_id': '67d5d8120b95...",skills,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,"[Comedy Timing, Expressive Teaching, Extend text]","[Revise text, Summarization, Format text, Shor...",5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
17,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,278549.0,2025-03-17 14:18:27.240000,1388.0,"{""section"": ""expertise"", ""user_id"": ""67d82dc4e...",AGENT_CV_SECTION_GENERATE,315c6ed1-9284-4c9c-bd39-c6da010aa452,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'expertise', 'user_id': '67d82dc4e...",expertise,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,"[Language Proficiency, Syntax Knowledge, Punct...",[],3b49f849-3081-4478-81ce-d65450662c47
18,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,278554.0,2025-03-17 14:18:44.545000,1388.0,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATE,7eb8ecbb-b216-4645-8887-b990be4a401c,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,"[Text Elaboration, Sentence Optimization, Form...","[Revise text, Summarization, Format text, Shor...",3b49f849-3081-4478-81ce-d65450662c47
19,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,278558.0,2025-03-17 14:18:53.674000,1388.0,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATE,cec3a722-effd-4814-bc59-4cac0670dc7d,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,"[Sentence Structuring, Text Debugging, Find fa...","[Sentence Optimization, Revise text, Summariza...",3b49f849-3081-4478-81ce-d65450662c47
20,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b,278563.0,2025-03-17 14:19:03.028000,1388.0,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATE,7e086159-c1ed-406b-8c06-80bd111ae1b9,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,"[Proofreading, Text Editing, Summarization]","[Find fact and add reference, Revise text, Sum...",3b49f849-3081-4478-81ce-d65450662c47
21,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,278559.0,2025-03-17 14:18:46.779000,1389.0,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATE,88104496-0c3a-4438-bf0b-4bf6e027c90e,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,"[Citation Verification, Spelling Expert, Punct...",[],ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
22,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,278569.0,2025-03-17 14:19:04.121000,1389.0,"{""section"": ""skills"", ""user_id"": ""67d82e0aedfe...",AGENT_CV_SECTION_GENERATE,01f972c6-6ba8-4bc2-8de1-df54f334b455,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'skills', 'user_id': '67d82e0aedfe...",skills,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,"[Grammar Checking, Typo Identification, Genera...","[Revise text, Summarization, Format text, Shor...",ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
23,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b,278588.0,2025-03-17 14:19:48.962000,1389.0,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATE,15769efc-761b-48db-b158-c37e4db4e547,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,"[Grammar Knowledge, Content Editing, Publicati...",[],ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
24,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,279950.0,2025-07-28 13:06:58.010000,2456.0,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,485aa975-3374-4f69-904b-5ac171786e99,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Grammar Proficiency, Proofreading Expert, Con...",[],ee84f721-81d3-4914-b1a4-09de1502b0bc
25,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,279951.0,2025-07-28 13:07:43.241000,2456.0,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,bcff6262-9910-4e5f-8065-01d1f08294b0,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Copy Editing, Publishing Know-how, Research S...","[Grammar Proficiency, Proofreading Expert, Con...",ee84f721-81d3-4914-b1a4-09de1502b0bc
26,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,279956.0,2025-07-28 13:09:39.918000,2456.0,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATE,85a5046c-f84e-466b-99df-e8bdb12e3e0b,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Text Editing, Grammar Correction, Ideation]","[Revise text, Summarization, Format text, Shor...",ee84f721-81d3-4914-b1a4-09de1502b0bc
27,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,279959.0,2025-07-28 13:09:45.693000,2456.0,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATE,5e9f5b5a-ce72-4a7f-9d03-99aa2d94364c,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Storytelling, Plagiarism Check, Translate]","[Ideation, Revise text, Summarization, Format ...",ee84f721-81d3-4914-b1a4-09de1502b0bc
28,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,279960.0,2025-07-28 13:09:52.233000,2456.0,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATE,afd2e4d5-b0e0-40b0-93cd-061e26fe211e,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Creative Writing, Topic Research, Question an...","[Storytelling, Plagiarism Check, Translate, Re...",ee84f721-81d3-4914-b1a4-09de1502b0bc
29,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,279967.0,2025-07-28 13:11:20.774000,2456.0,"{""section"": ""undefined"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,623c83b8-8ad5-44a1-ae18-ad2b5d46f101,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'undefined', 'user_id': '68835b058...",undefined,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Literature Synthesis, Content Creation, Poetr...",[],ee84f721-81d3-4914-b1a4-09de1502b0bc
30,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,279968.0,2025-07-28 13:11:30.605000,2456.0,"{""section"": ""undefined"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,e08dfccc-742d-4943-96a6-55a431295f0f,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'undefined', 'user_id': '68835b058...",undefined,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Ghostwriting, Fiction Writing, Drama Composit...","[Literature Synthesis, Content Creation, Poetr...",ee84f721-81d3-4914-b1a4-09de1502b0bc
31,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d,279969.0,2025-07-28 13:11:36.052000,2456.0,"{""section"": ""undefined"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_GENERATE,96fdeed1-e7d9-44b8-9197-04ea09e6e6bc,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'undefined', 'user_id': '68835b058...",undefined,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,"[Script Writing, Narrative Design, Poetic Comp...","[Ghostwriting, Fiction Writing, Drama Composit...",ee84f721-81d3-4914-b1a4-09de1502b0bc
32,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d,280570.0,2025-07-28 18:03:30.794000,2460.0,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",AGENT_CV_SECTION_GENERATE,056b62ba-07b9-4b86-a9ae-39142fbef67c,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'skills', 'user_id': '6887b97087cf...",skills,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,"[Grammar Checking, Style Enhancement, Find fac...","[Revise text, Summarization, Format text, Shor...",4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
33,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d,280576.0,2025-07-28 18:03:44.585000,2460.0,"{""section"": ""undefined"", ""user_id"": ""6887b9708...",AGENT_CV_SECTION_GENERATE,c1ce8587-1539-4698-9273-4ea83ee0a15f,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'undefined', 'user_id': '6887b9708...",undefined,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,"[Content Refinement, Text Optimization, Langua...",[],4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
36,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282027.0,2025-07-31 21:17:27.413000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,2f2815b0-104f-489e-a7f5-18251ace6f01,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Web Design, SEO Management, E-commerce Develo...",[],46820311-be03-4d2e-b993-90ac3bec3c92
37,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282031.0,2025-07-31 21:17:32.587000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,35309d43-42d4-458b-ac74-09a3fd4801b9,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Database Management, User Interface Design, M...",[],46820311-be03-4d2e-b993-90ac3bec3c92
38,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282032.0,2025-07-31 21:17:36.516000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,e8398d02-9566-43f4-a20d-c0cf4768455b,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Backend Development, JavaScript Programming, ...","[Database Management, User Interface Design, M...",46820311-be03-4d2e-b993-90ac3bec3c92
39,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282035.0,2025-07-31 21:17:41.942000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,a8a7e46b-1b59-4d70-bc28-313db29b32de,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Frontend Development, HTML Coding, CSS Styling]",[JavaScript Programming],46820311-be03-4d2e-b993-90ac3bec3c92
40,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282038.0,2025-07-31 21:17:45.386000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,e80481ba-4bb0-4e2e-b927-1ed109194cf7,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[JavaScript Programming, Database Management, ...",[CSS Styling],46820311-be03-4d2e-b993-90ac3bec3c92
41,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282042.0,2025-07-31 21:17:48.760000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,45511d9b-edcd-4914-b1c1-31516602b08d,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[CSS Styling, SSL Security, Mobile Development]",[],46820311-be03-4d2e-b993-90ac3bec3c92
42,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282046.0,2025-07-31 21:17:55.493000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,0c6c75c8-3cc0-482e-a843-71a8aebd5271,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[WordPress Customization, PHP Programming, Hos...",[SSL Security],46820311-be03-4d2e-b993-90ac3bec3c92
43,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282048.0,2025-07-31 21:18:00.834000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,3c45402d-fd6f-4ec4-bb21-6e6803858d25,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Content Management, App Development, Security...","[WordPress Customization, PHP Programming, Hos...",46820311-be03-4d2e-b993-90ac3bec3c92
44,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282051.0,2025-07-31 21:18:06.480000,2461.0,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATE,1fd3822b-06a1-44bb-8898-ad5a381ef5b7,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[E-commerce Integration, Web Analytics, Mobile...","[Content Management, Security Compliance]",46820311-be03-4d2e-b993-90ac3bec3c92
45,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282052.0,2025-07-31 21:18:24.208000,2461.0,"{""section"": ""skills"", ""user_id"": ""6888eec887cf...",AGENT_CV_SECTION_GENERATE,8a8817cd-6eda-4bcd-8c18-78dcf396a7f6,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'skills', 'user_id': '6888eec887cf...",skills,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Bug Fixing, Cross-Browser Compatibility, Revi...","[Revise text, Summarization, Format text, Shor...",46820311-be03-4d2e-b993-90ac3bec3c92
46,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282054.0,2025-07-31 21:18:45.634000,2461.0,"{""section"": ""skills"", ""user_id"": ""6888eec887cf...",AGENT_CV_SECTION_GENERATE,c87d4413-30b8-4fda-a19b-01d10b940413,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'skills', 'user_id': '6888eec887cf...",skills,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[WordPress Customization, Responsive Design, C...","[Bug Fixing, Cross-Browser Compatibility, Revi...",46820311-be03-4d2e-b993-90ac3bec3c92
47,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026,282055.0,2025-07-31 21:18:50.039000,2461.0,"{""section"": ""skills"", ""user_id"": ""6888eec887cf...",AGENT_CV_SECTION_GENERATE,123ffc54-33a2-40dc-a01c-92c299ceecf1,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'skills', 'user_id': '6888eec887cf...",skills,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,"[Plugin Development, Server Configuration, Fin...","[WordPress Customization, Responsive Design, C...",46820311-be03-4d2e-b993-90ac3bec3c92

number of generated sections by group
group_id
9     22
7     10
6      7
3      6
10     4
14     4
5      2
1      1
Name: count, dtype: int64

Applying CV suggestions, from event logs:

In [135]:
# events for applying suggestions in CV form

added_section_suggestions = finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_GENERATED_VALUE_ADD"]["event"].count()
print("Added generated section values: ", added_section_suggestions)
print("Percentage (added/total): ", added_section_suggestions / total_section_suggestions * 100)
agent_generated_section_values_df = parse_generic_event(finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_GENERATED_VALUE_ADD"])
print("Section: Expertise generations:")
display(agent_generated_section_values_df[agent_generated_section_values_df["section"] == "expertise"])
print("Section: Skills generations:")
display(agent_generated_section_values_df[agent_generated_section_values_df["section"] == "skills"])
display(agent_generated_section_values_df["section"].value_counts())
display(agent_generated_section_values_df[agent_generated_section_values_df["section"] == "expertise"]["participant_id"].value_counts())

Added generated section values:  78
Percentage (added/total):  46.42857142857143
Section: Expertise generations:

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,section,user_id,agent_id,username,document_id,section_value,participant_token
0,276463.0,2025-03-09 20:34:16.954000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,2591e9d2-67b5-4b0c-a355-a31c380fdcb0,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Literature Studies,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
1,276464.0,2025-03-09 20:34:21.477000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,fa7376a4-3569-4144-b5b1-7121821f1b15,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Academic Editing,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
3,276504.0,2025-03-09 20:48:52.749000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,580016cc-c82c-470a-adb3-56b06d7b3352,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Fact Validation,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
4,276505.0,2025-03-09 20:48:54.153000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,3eff226b-eac6-46a8-ad2f-d03ddae2b122,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Historical Research,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
6,277601.0,2025-03-10 12:56:43.426000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,583e75c8-1724-4346-bf42-08cf503acf1f,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Process Automation,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
7,277602.0,2025-03-10 12:56:44.842000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,d0d4bfbf-2e87-431b-bce6-e5c5c243b1dd,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Technological Support,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
8,278314.0,2025-03-15 19:45:03.657000,1387,"{""section"": ""expertise"", ""user_id"": ""67d5d8120...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,c62b2eb9-d4aa-42cf-bfa3-257de15bd702,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'expertise', 'user_id': '67d5d8120...",expertise,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,Adult Education,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
9,278315.0,2025-03-15 19:45:04.186000,1387,"{""section"": ""expertise"", ""user_id"": ""67d5d8120...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,aad46bb2-afac-42dc-9e8c-8dfd18df91f1,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'expertise', 'user_id': '67d5d8120...",expertise,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,Comedy Writing,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
10,278316.0,2025-03-15 19:45:05.178000,1387,"{""section"": ""expertise"", ""user_id"": ""67d5d8120...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,a80b85e7-e70b-4c15-9f6e-6f23d04f2130,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'expertise', 'user_id': '67d5d8120...",expertise,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,Counseling,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
14,278550.0,2025-03-17 14:18:33.764000,1388,"{""section"": ""expertise"", ""user_id"": ""67d82dc4e...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,664c0149-5db9-4b31-a94d-267bfa604573,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'expertise', 'user_id': '67d82dc4e...",expertise,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,Language Proficiency,3b49f849-3081-4478-81ce-d65450662c47
15,278552.0,2025-03-17 14:18:36.906000,1388,"{""section"": ""expertise"", ""user_id"": ""67d82dc4e...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,3da742bb-d7ec-4448-a0af-7f5968e701ac,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'expertise', 'user_id': '67d82dc4e...",expertise,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,Punctuation Awareness,3b49f849-3081-4478-81ce-d65450662c47
16,278553.0,2025-03-17 14:18:41.687000,1388,"{""section"": ""expertise"", ""user_id"": ""67d82dc4e...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,27f6dde8-3049-4907-91b4-9e93d4366de4,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'expertise', 'user_id': '67d82dc4e...",expertise,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,Syntax Knowledge,3b49f849-3081-4478-81ce-d65450662c47
21,278562.0,2025-03-17 14:18:53.377000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,cd427d52-d697-4b24-9a4c-f6a2373475a7,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Citation Verification,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
22,278564.0,2025-03-17 14:18:54.268000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,f119e0ff-584d-46c2-a5a3-0de298b28eda,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Spelling Expert,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
23,278565.0,2025-03-17 14:18:54.625000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,f5da4fd5-a684-4bc0-aeb3-c85764d91bef,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Punctuation Mastery,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
28,278589.0,2025-03-17 14:19:50.860000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,f65b20fd-62f6-424b-a768-1b7c4839cc8b,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Grammar Knowledge,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
29,278590.0,2025-03-17 14:19:52.522000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,0ad30895-614e-4462-9014-2621b80bbcbf,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Publication Formatting,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
37,280995.0,2025-07-29 13:16:05.740000,2459,"{""section"": ""expertise"", ""user_id"": ""6888bbce8...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,c875a606-1ab1-4159-9224-959ee2583955,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'expertise', 'user_id': '6888bbce8...",expertise,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,Event Coordination,a1f051f1-f2f3-45e1-9274-7deb05f97604
39,280998.0,2025-07-29 13:16:21.011000,2459,"{""section"": ""expertise"", ""user_id"": ""6888bbce8...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,a08bb776-4ced-443a-a42d-9e120d2ed290,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'expertise', 'user_id': '6888bbce8...",expertise,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,Strategic Planning,a1f051f1-f2f3-45e1-9274-7deb05f97604
40,281479.0,2025-07-31 14:31:57.023000,2457,"{""section"": ""expertise"", ""user_id"": ""688b1c788...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,af4eafb7-0a69-49b8-ae38-e1817b7c0823,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'expertise', 'user_id': '688b1c788...",expertise,688b1c7887cf5fec60dc80b0,688a6a2087cf5fec60dc80a2,soumyashaw,688364bf87cf5fec60dc8026,Reading Comprehension,14291cb8-c3c7-433e-9a0c-830cca8e4422
41,281480.0,2025-07-31 14:31:58.209000,2457,"{""section"": ""expertise"", ""user_id"": ""688b1c788...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,acce8f4e-5228-4148-aa3a-be47756bd068,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'expertise', 'user_id': '688b1c788...",expertise,688b1c7887cf5fec60dc80b0,688a6a2087cf5fec60dc80a2,soumyashaw,688364bf87cf5fec60dc8026,Literature Understanding,14291cb8-c3c7-433e-9a0c-830cca8e4422
42,281481.0,2025-07-31 14:31:59.453000,2457,"{""section"": ""expertise"", ""user_id"": ""688b1c788...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,f32c5035-0430-4639-8e99-38f4b326121e,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'expertise', 'user_id': '688b1c788...",expertise,688b1c7887cf5fec60dc80b0,688a6a2087cf5fec60dc80a2,soumyashaw,688364bf87cf5fec60dc8026,Essay Marking,14291cb8-c3c7-433e-9a0c-830cca8e4422
43,281490.0,2025-07-31 14:35:37.047000,2457,"{""section"": ""expertise"", ""user_id"": ""688b1c788...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,4ffd7ada-7448-4d2b-a02f-1af6d440d264,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'expertise', 'user_id': '688b1c788...",expertise,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Semantic Understanding,14291cb8-c3c7-433e-9a0c-830cca8e4422
44,281491.0,2025-07-31 14:35:37.752000,2457,"{""section"": ""expertise"", ""user_id"": ""688b1c788...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,2c73adce-bd9c-41cc-b408-f4846f94d443,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'expertise', 'user_id': '688b1c788...",expertise,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Grammar Knowledge,14291cb8-c3c7-433e-9a0c-830cca8e4422
45,281492.0,2025-07-31 14:35:38.211000,2457,"{""section"": ""expertise"", ""user_id"": ""688b1c788...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,4aeb0a34-273a-4e3c-9b64-ba2a83b392cb,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'expertise', 'user_id': '688b1c788...",expertise,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Context Awareness,14291cb8-c3c7-433e-9a0c-830cca8e4422
52,282028.0,2025-07-31 21:17:28.549000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,e1a7ce6e-9d62-48ed-af2f-834aa3f7cee4,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Web Design,46820311-be03-4d2e-b993-90ac3bec3c92
53,282029.0,2025-07-31 21:17:29.263000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,5512592e-b890-4b19-a148-90bb9f60f444,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,SEO Management,46820311-be03-4d2e-b993-90ac3bec3c92
54,282030.0,2025-07-31 21:17:29.887000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,1f1a393f-1fbe-4190-b49f-820089ed6372,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,E-commerce Development,46820311-be03-4d2e-b993-90ac3bec3c92
55,282033.0,2025-07-31 21:17:38.868000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,d9cbaf3f-aa48-4e80-ba0c-dd6541fc3b68,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Backend Development,46820311-be03-4d2e-b993-90ac3bec3c92
56,282034.0,2025-07-31 21:17:40.200000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,4ad1d94a-1f96-4542-87b7-172e0185476d,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,UI/UX Design,46820311-be03-4d2e-b993-90ac3bec3c92
57,282036.0,2025-07-31 21:17:42.755000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,a5d92096-7dec-4aa1-8044-4a9bcb9a759c,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Frontend Development,46820311-be03-4d2e-b993-90ac3bec3c92
58,282037.0,2025-07-31 21:17:43.807000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,c7e886b9-abfb-4d97-9a5b-11a40e95edfd,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,HTML Coding,46820311-be03-4d2e-b993-90ac3bec3c92
59,282039.0,2025-07-31 21:17:45.869000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,bb84ac51-7cd2-4b02-80e1-93da5389f1a7,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,JavaScript Programming,46820311-be03-4d2e-b993-90ac3bec3c92
60,282040.0,2025-07-31 21:17:46.527000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,34257f26-ebb6-4561-9f6f-e2b09b35230f,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Database Management,46820311-be03-4d2e-b993-90ac3bec3c92
61,282041.0,2025-07-31 21:17:47.028000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,e217d3a7-7e1a-4fd2-a447-82d05fabd422,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Performance Optimization,46820311-be03-4d2e-b993-90ac3bec3c92
62,282043.0,2025-07-31 21:17:50.800000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,b225ac1d-31a7-42b0-a514-a62b3820e7fe,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Mobile Development,46820311-be03-4d2e-b993-90ac3bec3c92
63,282044.0,2025-07-31 21:17:51.508000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,a343f1c5-1759-43f5-9e41-f96a7e836495,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,CSS Styling,46820311-be03-4d2e-b993-90ac3bec3c92
64,282049.0,2025-07-31 21:18:01.910000,2461,"{""section"": ""expertise"", ""user_id"": ""6888eec88...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,4f7f5880-1e90-4742-8895-f9bd16e2535b,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'expertise', 'user_id': '6888eec88...",expertise,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,App Development,46820311-be03-4d2e-b993-90ac3bec3c92
67,282886.0,2025-08-14 18:00:08.076000,2471,"{""section"": ""expertise"", ""user_id"": ""689e22d5e...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,e6d5d9ba-4cc2-445e-90e9-f9f200bc49a5,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'expertise', 'user_id': '689e22d5e...",expertise,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Punctuation Knowledge,41b03f59-088a-4ca7-b174-44980d1d8d78
68,282887.0,2025-08-14 18:00:10.817000,2471,"{""section"": ""expertise"", ""user_id"": ""689e22d5e...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,779d0d1b-9de3-4ec1-ab3e-8bea429fa679,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'expertise', 'user_id': '689e22d5e...",expertise,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Content Structure,41b03f59-088a-4ca7-b174-44980d1d8d78
72,282899.0,2025-08-14 18:01:58.787000,2471,"{""section"": ""expertise"", ""user_id"": ""689e22d5e...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,6e154e00-65c0-4c06-90ed-dd02daa329c1,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'expertise', 'user_id': '689e22d5e...",expertise,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Information Verification,41b03f59-088a-4ca7-b174-44980d1d8d78
73,282900.0,2025-08-14 18:02:00.044000,2471,"{""section"": ""expertise"", ""user_id"": ""689e22d5e...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,5c4419c2-6d1f-459f-92c4-10355808ff8e,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'expertise', 'user_id': '689e22d5e...",expertise,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Fact Analysis,41b03f59-088a-4ca7-b174-44980d1d8d78
74,282901.0,2025-08-14 18:02:01.072000,2471,"{""section"": ""expertise"", ""user_id"": ""689e22d5e...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,f985c052-bd89-406d-948f-ffba6e4ca5d1,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'expertise', 'user_id': '689e22d5e...",expertise,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Source Validation,41b03f59-088a-4ca7-b174-44980d1d8d78

Section: Skills generations:

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,section,user_id,agent_id,username,document_id,section_value,participant_token
2,276501.0,2025-03-09 20:48:37.757000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,1167eed7-111a-4bab-b8ae-375b05271d90,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Data Verification,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
5,277480.0,2025-03-10 08:39:20.990000,1380,"{""section"": ""skills"", ""user_id"": ""67ce9cb4285f...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,5d50b94c-63ac-4712-955e-004d595d87d3,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'section': 'skills', 'user_id': '67ce9cb4285f...",skills,67ce9cb4285fac3f07bcf5ec,mocked-new-agent,mrnexeon,67ce983b285fac3f07bcf5e8,Document structuring,ecc027d0-42cd-42a1-bc2e-990b5516565b
11,278318.0,2025-03-15 19:45:09.846000,1387,"{""section"": ""skills"", ""user_id"": ""67d5d8120b95...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,13b8052a-c8ca-4b20-8962-e870b95e1dcc,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'skills', 'user_id': '67d5d8120b95...",skills,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,Comedy Timing,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
12,278319.0,2025-03-15 19:45:10.399000,1387,"{""section"": ""skills"", ""user_id"": ""67d5d8120b95...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,99294267-64e6-4a75-ab9b-18a4e752ab98,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'skills', 'user_id': '67d5d8120b95...",skills,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,Expressive Teaching,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
13,278320.0,2025-03-15 19:45:11.582000,1387,"{""section"": ""skills"", ""user_id"": ""67d5d8120b95...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,40c9dd7c-4c19-4d83-bfc4-8631510119b3,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'skills', 'user_id': '67d5d8120b95...",skills,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,Extend text,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
17,278555.0,2025-03-17 14:18:48.696000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,f2fcd58e-6cad-472b-89e1-f299f6710e82,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,Text Elaboration,3b49f849-3081-4478-81ce-d65450662c47
18,278556.0,2025-03-17 14:18:50.229000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,ecc20de1-df9b-4d72-b710-7579c2ffe00b,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,Format text,3b49f849-3081-4478-81ce-d65450662c47
19,278560.0,2025-03-17 14:18:56.578000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,c011ac42-3bf1-4572-b98f-1c9bbc2fca65,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,Sentence Structuring,3b49f849-3081-4478-81ce-d65450662c47
20,278561.0,2025-03-17 14:18:59.435000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,4fe44900-a1eb-4dfc-bd44-fd8ffd6ec181,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,Text Debugging,3b49f849-3081-4478-81ce-d65450662c47
24,278566.0,2025-03-17 14:19:06.844000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,e549cc3b-f5d9-44cb-8635-369b28871ef8,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,Text Editing,3b49f849-3081-4478-81ce-d65450662c47
25,278571.0,2025-03-17 14:19:08.202000,1389,"{""section"": ""skills"", ""user_id"": ""67d82e0aedfe...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,2717b804-26da-438b-9670-812d38afae9f,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'skills', 'user_id': '67d82e0aedfe...",skills,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Typo Identification,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
26,278572.0,2025-03-17 14:19:09.328000,1389,"{""section"": ""skills"", ""user_id"": ""67d82e0aedfe...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,2aa22085-550d-4927-a02d-ae7e3a863025,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'skills', 'user_id': '67d82e0aedfe...",skills,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Grammar Checking,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
27,278573.0,2025-03-17 14:19:12.353000,1389,"{""section"": ""skills"", ""user_id"": ""67d82e0aedfe...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,bf0d2dcc-6616-48c3-9fdb-f2adba5bcfca,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'skills', 'user_id': '67d82e0aedfe...",skills,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Generate text,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
30,279957.0,2025-07-28 13:09:42.031000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,1f00ae06-0f31-4392-8362-3415ce9b9bbd,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,Text Editing,ee84f721-81d3-4914-b1a4-09de1502b0bc
31,279958.0,2025-07-28 13:09:42.713000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,b7c4d805-271a-498c-b1d1-f4db845827c5,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,Grammar Correction,ee84f721-81d3-4914-b1a4-09de1502b0bc
32,279961.0,2025-07-28 13:09:56.399000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,e3a8d4a2-8094-4e8f-b13c-d49402bfafea,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,Topic Research,ee84f721-81d3-4914-b1a4-09de1502b0bc
33,279962.0,2025-07-28 13:09:57.680000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,d4aafc7f-0803-4d17-a9af-ffe48d4f088a,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,Creative Writing,ee84f721-81d3-4914-b1a4-09de1502b0bc
34,280571.0,2025-07-28 18:03:33.105000,2460,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,8b1231b5-ab86-4a4e-a4f0-df8f2615e310,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'skills', 'user_id': '6887b97087cf...",skills,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,Grammar Checking,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
35,280572.0,2025-07-28 18:03:35.222000,2460,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,88d1da77-6b32-49f9-9a48-ee109249feff,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'skills', 'user_id': '6887b97087cf...",skills,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,Style Enhancement,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
36,280573.0,2025-07-28 18:03:36.972000,2460,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,b856590c-287e-4953-84dd-456e211441ce,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'skills', 'user_id': '6887b97087cf...",skills,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,Find fact and add reference,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
38,280997.0,2025-07-29 13:16:18.618000,2459,"{""section"": ""skills"", ""user_id"": ""6888bbce87cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,7e5edc31-6ecd-4f75-b8e3-3d8667e3ce79,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'skills', 'user_id': '6888bbce87cf...",skills,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,Budget Management,a1f051f1-f2f3-45e1-9274-7deb05f97604
46,281494.0,2025-07-31 14:36:03.503000,2457,"{""section"": ""skills"", ""user_id"": ""688b1c7887cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,8bfdeba0-7c5a-4979-aa38-5be4247e68e0,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'skills', 'user_id': '688b1c7887cf...",skills,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Paraphrasing,14291cb8-c3c7-433e-9a0c-830cca8e4422
47,281495.0,2025-07-31 14:36:04.086000,2457,"{""section"": ""skills"", ""user_id"": ""688b1c7887cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,03429815-82f0-4d92-8496-1cdf6c5bbcd5,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'skills', 'user_id': '688b1c7887cf...",skills,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Simplify Sentence,14291cb8-c3c7-433e-9a0c-830cca8e4422
48,281496.0,2025-07-31 14:36:04.800000,2457,"{""section"": ""skills"", ""user_id"": ""688b1c7887cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,dcf74d82-2126-49e6-b971-b962241a9ba1,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'skills', 'user_id': '688b1c7887cf...",skills,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Shorten text,14291cb8-c3c7-433e-9a0c-830cca8e4422
49,281498.0,2025-07-31 14:36:16.858000,2457,"{""section"": ""skills"", ""user_id"": ""688b1c7887cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,860263df-e8f2-4995-a434-c8600a5bc1d8,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'skills', 'user_id': '688b1c7887cf...",skills,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Sentence Conversion,14291cb8-c3c7-433e-9a0c-830cca8e4422
50,281499.0,2025-07-31 14:36:18.007000,2457,"{""section"": ""skills"", ""user_id"": ""688b1c7887cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,66bc5050-d2d8-4f97-9525-4e91077b1153,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'skills', 'user_id': '688b1c7887cf...",skills,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Text outline,14291cb8-c3c7-433e-9a0c-830cca8e4422
51,281500.0,2025-07-31 14:36:18.554000,2457,"{""section"": ""skills"", ""user_id"": ""688b1c7887cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,a4084c20-d841-4986-b8c8-9cb7bf4c5c8b,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'section': 'skills', 'user_id': '688b1c7887cf...",skills,688b1c7887cf5fec60dc80b0,mocked-new-agent,soumyashaw,688364bf87cf5fec60dc8026,Text Reworking,14291cb8-c3c7-433e-9a0c-830cca8e4422
65,282056.0,2025-07-31 21:18:55.227000,2461,"{""section"": ""skills"", ""user_id"": ""6888eec887cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,983aea6b-1f86-4fe3-aee1-fdba09b4a560,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'skills', 'user_id': '6888eec887cf...",skills,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Find fact and add reference,46820311-be03-4d2e-b993-90ac3bec3c92
66,282062.0,2025-07-31 21:19:09.568000,2461,"{""section"": ""skills"", ""user_id"": ""6888eec887cf...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,51451b98-9bf2-419d-8422-07bca2674026,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'skills', 'user_id': '6888eec887cf...",skills,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Generate text,46820311-be03-4d2e-b993-90ac3bec3c92
69,282891.0,2025-08-14 18:00:41.833000,2471,"{""section"": ""skills"", ""user_id"": ""689e22d5e90f...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,eb2f6fef-f0af-4b2e-9c8b-77703d2b5b18,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'skills', 'user_id': '689e22d5e90f...",skills,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Proofreading,41b03f59-088a-4ca7-b174-44980d1d8d78
70,282892.0,2025-08-14 18:00:42.949000,2471,"{""section"": ""skills"", ""user_id"": ""689e22d5e90f...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,e5cc7915-8b45-49c3-9fb6-d659c5d772d5,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'skills', 'user_id': '689e22d5e90f...",skills,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Text Correction,41b03f59-088a-4ca7-b174-44980d1d8d78
71,282893.0,2025-08-14 18:00:44.767000,2471,"{""section"": ""skills"", ""user_id"": ""689e22d5e90f...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,b67f7889-f9bf-4b87-ae39-2fb0ac18f038,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'skills', 'user_id': '689e22d5e90f...",skills,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Cut text,41b03f59-088a-4ca7-b174-44980d1d8d78
75,282903.0,2025-08-14 18:02:05.278000,2471,"{""section"": ""skills"", ""user_id"": ""689e22d5e90f...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,e8d6ac63-2883-44db-9b19-f2e65253f1fe,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'skills', 'user_id': '689e22d5e90f...",skills,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Source Assessment,41b03f59-088a-4ca7-b174-44980d1d8d78
76,282904.0,2025-08-14 18:02:06.242000,2471,"{""section"": ""skills"", ""user_id"": ""689e22d5e90f...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,c137ea0b-f291-4700-b171-83952a66620d,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'skills', 'user_id': '689e22d5e90f...",skills,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Cross Referencing,41b03f59-088a-4ca7-b174-44980d1d8d78
77,282905.0,2025-08-14 18:02:07.210000,2471,"{""section"": ""skills"", ""user_id"": ""689e22d5e90f...",AGENT_CV_SECTION_GENERATED_VALUE_ADD,0d4fee70-4d1f-4eec-b1c5-4a615721888c,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'skills', 'user_id': '689e22d5e90f...",skills,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Text outline,41b03f59-088a-4ca7-b174-44980d1d8d78

section
expertise    43
skills       35
Name: count, dtype: int64

participant_id
2461    13
1374     6
2457     6
1389     5
2471     5
1387     3
1388     3
2459     2
Name: count, dtype: int64

Manually added sections in CV form

In [136]:
# events for manually adding suggestions in CV form
print("Manually added section values, total: ")
manually_added_section_values = finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_VALUE_ADD"]
manually_added_section_values = parse_generic_event(manually_added_section_values)

print(manually_added_section_values["section"].count())
display(manually_added_section_values["section"].value_counts())
display(manually_added_section_values)

Manually added section values, total:
40

section
skills       21
expertise    19
Name: count, dtype: int64

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,section,user_id,agent_id,username,document_id,section_value,participant_token
0,276465.0,2025-03-09 20:34:26.958000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_VALUE_ADD,55d76975-ac46-4743-a75b-78c7790ebb50,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Essay Writing,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
1,276471.0,2025-03-09 20:35:54.905000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_VALUE_ADD,f548c978-37b0-43b4-b578-9941ed55dbd1,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Reading and Writing Essay,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
2,276472.0,2025-03-09 20:36:22.577000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_VALUE_ADD,443e18c0-78ce-4980-a3f6-2e94adc3e2b7,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Profeccional Redactor,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
3,276474.0,2025-03-09 20:36:38.729000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_VALUE_ADD,e6013b95-efbf-4428-8a7d-0b363b7c6a08,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Professional Redactor,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
4,276475.0,2025-03-09 20:39:06.431000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_VALUE_ADD,50cb2abc-f6fc-40a3-9bc2-0704a4b39ab8,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,English Grammar,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
5,276502.0,2025-03-09 20:48:39.324000,1374,"{""section"": ""skills"", ""user_id"": ""67cdfa30285f...",AGENT_CV_SECTION_VALUE_ADD,a936ac64-04d8-43a1-99f1-91541d297555,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'skills', 'user_id': '67cdfa30285f...",skills,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,AI Factology,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
6,277481.0,2025-03-10 08:39:30.291000,1380,"{""section"": ""skills"", ""user_id"": ""67ce9cb4285f...",AGENT_CV_SECTION_VALUE_ADD,af662003-ea69-4a9c-9f2d-029bd79a3b83,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'section': 'skills', 'user_id': '67ce9cb4285f...",skills,67ce9cb4285fac3f07bcf5ec,mocked-new-agent,mrnexeon,67ce983b285fac3f07bcf5e8,Asses essay structure,ecc027d0-42cd-42a1-bc2e-990b5516565b
7,277482.0,2025-03-10 08:39:34.258000,1380,"{""section"": ""skills"", ""user_id"": ""67ce9cb4285f...",AGENT_CV_SECTION_VALUE_ADD,06d5a6b8-503b-4791-bd81-8be7e521df95,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'section': 'skills', 'user_id': '67ce9cb4285f...",skills,67ce9cb4285fac3f07bcf5ec,mocked-new-agent,mrnexeon,67ce983b285fac3f07bcf5e8,argumentation,ecc027d0-42cd-42a1-bc2e-990b5516565b
8,277484.0,2025-03-10 08:39:37.524000,1380,"{""section"": ""skills"", ""user_id"": ""67ce9cb4285f...",AGENT_CV_SECTION_VALUE_ADD,52d6580b-bc51-49bb-b683-ecfe615fccb3,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'section': 'skills', 'user_id': '67ce9cb4285f...",skills,67ce9cb4285fac3f07bcf5ec,mocked-new-agent,mrnexeon,67ce983b285fac3f07bcf5e8,cohesion,ecc027d0-42cd-42a1-bc2e-990b5516565b
9,277603.0,2025-03-10 12:56:45.855000,1374,"{""section"": ""expertise"", ""user_id"": ""67cdfa302...",AGENT_CV_SECTION_VALUE_ADD,1244d1b8-f826-4656-a25a-5f6bf86b5663,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'section': 'expertise', 'user_id': '67cdfa302...",expertise,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Artificial Intelligence in Practice,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
10,278312.0,2025-03-15 19:44:57.797000,1387,"{""section"": ""expertise"", ""user_id"": ""67d5d8120...",AGENT_CV_SECTION_VALUE_ADD,56818cbc-0309-4aef-be84-6dfd7a1adfd6,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'section': 'expertise', 'user_id': '67d5d8120...",expertise,67d5d8120b9539e69a3a86d7,mocked-new-agent,Ilya School,67d5d8160b9539e69a3a86d8,"Sex education, jokes",5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc
11,278551.0,2025-03-17 14:18:26.919000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_VALUE_ADD,ec79f43a-4bf0-48eb-9145-8d5ab6246e4b,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Checks Sources,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
12,278557.0,2025-03-17 14:18:44.184000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_VALUE_ADD,f0421f92-560a-4c9b-83c9-61161f4c0731,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Grammar check,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
13,278570.0,2025-03-17 14:19:16.859000,1388,"{""section"": ""skills"", ""user_id"": ""67d82dc4edfe...",AGENT_CV_SECTION_VALUE_ADD,52fef3e3-8f99-4780-8b45-f5906498e357,3b49f849-3081-4478-81ce-d65450662c47,"{'section': 'skills', 'user_id': '67d82dc4edfe...",skills,67d82dc4edfe680c1b0f1642,mocked-new-agent,sanapht,67d08e87285fac3f07bcf64b,grammar check,3b49f849-3081-4478-81ce-d65450662c47
14,278575.0,2025-03-17 14:19:18.974000,1389,"{""section"": ""skills"", ""user_id"": ""67d82e0aedfe...",AGENT_CV_SECTION_VALUE_ADD,7e33cf93-45c0-4513-ba8a-835f185fba29,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'skills', 'user_id': '67d82e0aedfe...",skills,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Source checking,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
15,278591.0,2025-03-17 14:20:16.707000,1389,"{""section"": ""expertise"", ""user_id"": ""67d82e0ae...",AGENT_CV_SECTION_VALUE_ADD,969744a1-bd99-4c3b-a48f-68ae0f96d5a3,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'expertise', 'user_id': '67d82e0ae...",expertise,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Source Checking,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
16,278594.0,2025-03-17 14:20:34.459000,1389,"{""section"": ""skills"", ""user_id"": ""67d82e0aedfe...",AGENT_CV_SECTION_VALUE_ADD,9ea1e3eb-748c-4878-9fc7-161abf84a5f0,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'section': 'skills', 'user_id': '67d82e0aedfe...",skills,67d82e0aedfe680c1b0f1643,mocked-new-agent,Du-Al-Dos,67d08e87285fac3f07bcf64b,Dynamic Citation selection,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9
17,279634.0,2025-07-21 07:58:16.470000,2453,"{""section"": ""expertise"", ""user_id"": ""687de5d18...",AGENT_CV_SECTION_VALUE_ADD,5fd74618-0fb2-4f9b-bbff-3dc34ac43825,e24dd41b-25cb-4503-a4b7-4919fc0e688f,"{'section': 'expertise', 'user_id': '687de5d18...",expertise,687de5d187cf5fec60dc7fef,687df2ff87cf5fec60dc7ff1,pavithren,6879e8fd87cf5fec60dc7fe1,Human Computer Interaction,e24dd41b-25cb-4503-a4b7-4919fc0e688f
18,279908.0,2025-07-25 16:39:04.293000,2456,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_VALUE_ADD,6ba846eb-f7dd-4d5b-8547-0a5e5992563f,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,robotics,ee84f721-81d3-4914-b1a4-09de1502b0bc
19,279952.0,2025-07-28 13:08:04.790000,2456,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_VALUE_ADD,bf964acc-bb8c-4561-ba42-582c8c8b895b,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,artificial intelligence,ee84f721-81d3-4914-b1a4-09de1502b0bc
20,279953.0,2025-07-28 13:08:40.474000,2456,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_VALUE_ADD,166fe224-5851-4847-ae49-41a5a7951a3a,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,english writing,ee84f721-81d3-4914-b1a4-09de1502b0bc
21,279954.0,2025-07-28 13:09:11.857000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_VALUE_ADD,49de6e3f-f7ec-4ce6-9e64-0d076a15a5e3,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,Writing Essays,ee84f721-81d3-4914-b1a4-09de1502b0bc
22,279955.0,2025-07-28 13:09:37.047000,2456,"{""section"": ""skills"", ""user_id"": ""68835b0587cf...",AGENT_CV_SECTION_VALUE_ADD,46061f3e-b4d0-403b-b74a-24588aab855e,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'skills', 'user_id': '68835b0587cf...",skills,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,Understanding Context,ee84f721-81d3-4914-b1a4-09de1502b0bc
23,279963.0,2025-07-28 13:10:15.294000,2456,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_VALUE_ADD,11c94fb6-a80d-41d9-a751-050b086aecca,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,education,ee84f721-81d3-4914-b1a4-09de1502b0bc
24,279964.0,2025-07-28 13:10:23.573000,2456,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_VALUE_ADD,a9ca2610-8c9e-45bd-ba2f-5e0b90108a06,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,transportation,ee84f721-81d3-4914-b1a4-09de1502b0bc
25,279965.0,2025-07-28 13:10:37.543000,2456,"{""section"": ""expertise"", ""user_id"": ""68835b058...",AGENT_CV_SECTION_VALUE_ADD,e7e10f6f-d903-4eab-9e98-921fcdaf8310,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'section': 'expertise', 'user_id': '68835b058...",expertise,68835b0587cf5fec60dc8020,mocked-new-agent,Anass Q.,68833fd687cf5fec60dc801d,AI Ethics,ee84f721-81d3-4914-b1a4-09de1502b0bc
26,280724.0,2025-07-29 11:53:45.566000,2460,"{""section"": ""expertise"", ""user_id"": ""6887b9708...",AGENT_CV_SECTION_VALUE_ADD,fa10d865-1373-4825-85a7-64b3531952d1,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'expertise', 'user_id': '6887b9708...",expertise,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,history,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
27,280725.0,2025-07-29 11:53:51.723000,2460,"{""section"": ""expertise"", ""user_id"": ""6887b9708...",AGENT_CV_SECTION_VALUE_ADD,f3505db0-3fa2-4ce0-b0d3-5c21879c0d4f,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'expertise', 'user_id': '6887b9708...",expertise,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,statistics,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
28,280726.0,2025-07-29 11:53:54.737000,2460,"{""section"": ""expertise"", ""user_id"": ""6887b9708...",AGENT_CV_SECTION_VALUE_ADD,ab7a47fd-f8ea-4f1a-be61-57ac660186b7,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'expertise', 'user_id': '6887b9708...",expertise,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,facts,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
29,280727.0,2025-07-29 11:54:03.905000,2460,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",AGENT_CV_SECTION_VALUE_ADD,0daf65d2-cd72-465b-8873-c30b66dc3603,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'section': 'skills', 'user_id': '6887b97087cf...",skills,6887b97087cf5fec60dc8060,mocked-new-agent,Naira,68833fd687cf5fec60dc801d,Adding coherent facts,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50
30,280990.0,2025-07-29 13:14:17.953000,2459,"{""section"": ""skills"", ""user_id"": ""6888bbce87cf...",AGENT_CV_SECTION_VALUE_ADD,09657f83-f807-4010-a105-54b2232ea7fa,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'skills', 'user_id': '6888bbce87cf...",skills,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,Planning,a1f051f1-f2f3-45e1-9274-7deb05f97604
31,280991.0,2025-07-29 13:14:23.446000,2459,"{""section"": ""skills"", ""user_id"": ""6888bbce87cf...",AGENT_CV_SECTION_VALUE_ADD,405942fe-d72b-4387-a9d9-c06eb4208f7a,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'skills', 'user_id': '6888bbce87cf...",skills,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,Organization,a1f051f1-f2f3-45e1-9274-7deb05f97604
32,280992.0,2025-07-29 13:14:36.893000,2459,"{""section"": ""skills"", ""user_id"": ""6888bbce87cf...",AGENT_CV_SECTION_VALUE_ADD,897029c4-fa72-4b78-8127-008c8b4a17b2,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'section': 'skills', 'user_id': '6888bbce87cf...",skills,6888bbce87cf5fec60dc8072,mocked-new-agent,ainalinngeorges,6877c26e87cf5fec60dc7fda,Portuguese Marketplace,a1f051f1-f2f3-45e1-9274-7deb05f97604
33,282053.0,2025-07-31 21:18:42.687000,2461,"{""section"": ""skills"", ""user_id"": ""6888eec887cf...",AGENT_CV_SECTION_VALUE_ADD,dc0873e6-e38a-4b4a-894c-95b0e1239d6b,46820311-be03-4d2e-b993-90ac3bec3c92,"{'section': 'skills', 'user_id': '6888eec887cf...",skills,6888eec887cf5fec60dc8085,mocked-new-agent,vama00004,688364bf87cf5fec60dc8026,Suggest and revise text,46820311-be03-4d2e-b993-90ac3bec3c92
34,282572.0,2025-08-13 07:24:06.184000,2469,"{""section"": ""skills"", ""user_id"": ""689c3c25e90f...",AGENT_CV_SECTION_VALUE_ADD,b0c22be1-4885-4b6a-bf56-fc782b73741d,63e04882-b933-435f-b84b-7a638b9c5ae8,"{'section': 'skills', 'user_id': '689c3c25e90f...",skills,689c3c25e90ffc190a96c28b,mocked-new-agent,mkaep,688c6add87cf5fec60dc80ef,Reviewing. Find every little weak spot. Harsh ...,63e04882-b933-435f-b84b-7a638b9c5ae8
35,282573.0,2025-08-13 07:24:07.784000,2469,"{""section"": ""expertise"", ""user_id"": ""689c3c25e...",AGENT_CV_SECTION_VALUE_ADD,77485bb2-9b73-4fa6-8abd-1abed48c9bb2,63e04882-b933-435f-b84b-7a638b9c5ae8,"{'section': 'expertise', 'user_id': '689c3c25e...",expertise,689c3c25e90ffc190a96c28b,mocked-new-agent,mkaep,688c6add87cf5fec60dc80ef,Reviewing research proposals and scientific te...,63e04882-b933-435f-b84b-7a638b9c5ae8
36,282888.0,2025-08-14 18:00:19.857000,2471,"{""section"": ""expertise"", ""user_id"": ""689e22d5e...",AGENT_CV_SECTION_VALUE_ADD,9ee29893-cc21-4d3b-a61a-fac48e25085c,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'expertise', 'user_id': '689e22d5e...",expertise,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Spelling Check,41b03f59-088a-4ca7-b174-44980d1d8d78
37,282889.0,2025-08-14 18:00:29.566000,2471,"{""section"": ""expertise"", ""user_id"": ""689e22d5e...",AGENT_CV_SECTION_VALUE_ADD,64cf0214-fb1f-4524-85d2-32531b1c37a6,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'expertise', 'user_id': '689e22d5e...",expertise,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Sentence Review,41b03f59-088a-4ca7-b174-44980d1d8d78
38,282894.0,2025-08-14 18:00:57.186000,2471,"{""section"": ""skills"", ""user_id"": ""689e22d5e90f...",AGENT_CV_SECTION_VALUE_ADD,e115ce8b-8a08-4bef-820b-09f01153847a,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'skills', 'user_id': '689e22d5e90f...",skills,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Storytelling,41b03f59-088a-4ca7-b174-44980d1d8d78
39,282895.0,2025-08-14 18:01:02.927000,2471,"{""section"": ""skills"", ""user_id"": ""689e22d5e90f...",AGENT_CV_SECTION_VALUE_ADD,c68c9411-2af6-4168-822c-2f4b8aa6a97a,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'section': 'skills', 'user_id': '689e22d5e90f...",skills,689e22d5e90ffc190a96c2e0,mocked-new-agent,joy_angel,6896071ee90ffc190a96c285,Rephrase,41b03f59-088a-4ca7-b174-44980d1d8d78

In [137]:
# added sections
display(finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_ADD"])
display(finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_EDITED"])
display(finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_DELETE"])

agent_section_added_df = parse_json_field(finished_participants[finished_participants["event"] == "AGENT_CV_SECTION_EDITED"], "data")
display(agent_section_added_df)

,Unnamed: 0.1,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
279,281,458,276468.0,8b81b29e-ee4d-4eec-be69-f90ff81a2b32,Prototype,2025-03-09 20:35:02.446000,AGENT_CV_SECTION_ADD,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585
3265,3604,3883,279966.0,724c999c-bf6e-4628-afd8-ac000ac91219,Prototype,2025-07-28 13:11:16.215000,AGENT_CV_SECTION_ADD,"{""user_id"": ""68835b0587cf5fec60dc8020"", ""agent...",2456,ee84f721-81d3-4914-b1a4-09de1502b0bc,finished,"{'user_id': '68835b0587cf5fec60dc8020', 'agent...",68833fd687cf5fec60dc801d
3873,4212,4491,280574.0,fcdd01e6-dcf0-4d85-ace6-a539cc008c11,Prototype,2025-07-28 18:03:38.556000,AGENT_CV_SECTION_ADD,"{""user_id"": ""6887b97087cf5fec60dc8060"", ""agent...",2460,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress,"{'user_id': '6887b97087cf5fec60dc8060', 'agent...",68833fd687cf5fec60dc801d

,Unnamed: 0.1,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
280,282,459,276469.0,bee3015f-ab4d-4382-a30c-6df5c68f0b5a,Prototype,2025-03-09 20:35:11.723000,AGENT_CV_SECTION_EDITED,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""agent...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'user_id': '67cdfa30285fac3f07bcf5cc', 'agent...",67c88f88285fac3f07bcf585

,Unnamed: 0.1,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
281,283,460,276470.0,1bcb836d-146a-4624-a9d0-08f3de462859,Prototype,2025-03-09 20:35:25.128000,AGENT_CV_SECTION_DELETE,"{""section"": ""Style"", ""user_id"": ""67cdfa30285fa...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,"{'section': 'Style', 'user_id': '67cdfa30285fa...",67c88f88285fac3f07bcf585
3269,3608,3887,279970.0,2a45b178-e484-4992-a371-4aba5c22ce28,Prototype,2025-07-28 13:11:38.079000,AGENT_CV_SECTION_DELETE,"{""section"": ""undefined"", ""user_id"": ""68835b058...",2456,ee84f721-81d3-4914-b1a4-09de1502b0bc,finished,"{'section': 'undefined', 'user_id': '68835b058...",68833fd687cf5fec60dc801d

/tmp/ipykernel_112605/962560954.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  event_df[json_field + "_parsed"] = event_df[json_field].apply(json.loads)

,user_id,agent_id,username,document_id,new_section,old_section,participant_token
0,67cdfa30285fac3f07bcf5cc,mocked-new-agent,Ivan Khrop,67c88f88285fac3f07bcf585,Style,undefined,93f70a37-e7d5-4bcf-adbc-d106ca47c27b

In [138]:
# task activity view
print("Task activity views:")
display(len(finished_participants[finished_participants["event"] == "AGENT_TASK_ACTIVITY_VIEW"]))
print("Specific task activity views (review of task activity):")
display(len(finished_participants[finished_participants["event"] == "AGENT_TASK_ACTIVITY_TASK_REVIEW"]))

Task activity views:

7

Specific task activity views (review of task activity):

0

[F] Analyse last version of each agent's profile, how many skills, create lists of definitions etc.

In [139]:
# review agent roles
agent_roles_df = study_agents[['_id', 'role', 'group_id', 'user']].dropna()
agent_roles_df.to_csv(os.path.join('output', 'agents', 'agent_roles.tsv'), sep="\t")

In [140]:
# review agent expertise
display(study_agents['profile.sections.expertise'].dropna().apply(len).sum())
display(study_agents['profile.sections.expertise'].dropna().apply(len).value_counts())
display(study_agents['profile.sections.expertise'].dropna().apply(len).describe())

# create a list of all expertises
agents_expertise_df = study_agents[['profile.sections.expertise', 'group_id', 'user']].dropna()
agents_expertise_df['profile.sections.expertise'] = agents_expertise_df['profile.sections.expertise'].apply(lambda x: ', '.join(x))
agents_expertise_df.to_csv(os.path.join('output', 'agents', 'agent_expertise.tsv'), sep="\t")
display(agents_expertise_df)

112

profile.sections.expertise
3     13
2     10
4      6
1      4
5      3
0      2
10     1
Name: count, dtype: int64

count    39.000000
mean      2.871795
std       1.704167
min       0.000000
25%       2.000000
50%       3.000000
75%       3.500000
max      10.000000
Name: profile.sections.expertise, dtype: float64

                           profile.sections.expertise  group_id  user
1                                                             1  1380
5   Literature Studies, Academic Editing, Essay Wr...         3  1374
6                Fact Validation, Historical Research         3  1374
7   Text Organization, Content Flow, Document Form...         3  1374
8                      Text Review, Textual Criticism         4  1383
9   Scientific Paper writing, HCI researcher exper...         4  1383
10  Human-Computer Interaction, Education, AI-assi...         4  1384
11                                      HCI, Teaching         4  1385
12                     Text Review, Textual Criticism         5  1387
13  Text Organization, Content Flow, Document Form...         5  1387
14                         English Grammar and Syntax         5  1387
15  Sex education, jokes, Adult Education, Comedy ...         5  1387
17  Language Proficiency, Punctuation Awareness, S...         6  1388
18                Concept Creation, Creative Thinking         6  1388
19                     Text Review, Textual Criticism         6  1388
20  Grammar Knowledge, Publication Formatting, Sou...         6  1389
23  artificial intelligence, english writing, educ...         7  2456
24                         history, statistics, facts         7  2460
25  Text Review, Textual Criticism, Human Computer...         8  2453
26  Expert in A lived informatics model of persona...         8  2453
27  You are an expert in Stage based model of pers...         8  2453
28  AI in Healthcare, Interaction Design, Healthca...         8  2453
30  Web Design, SEO Management, Backend Developmen...         9  2461
31  English Grammar and Syntax, Reading Comprehens...         9  2464
32  Semantic Understanding, Grammar Knowledge, Con...         9  2457
33                Concept Creation, Creative Thinking        10  2459
34             Event Coordination, Strategic Planning        10  2459
35                    Event Management, Wedding Decor        10  2459
36  Linguistic Knowledge, Text Coherence, Narrativ...        10  2465
37                                                           11  2463
38  Document Analysis, Topic Understanding, Resear...        11  2463
40  Artificial Intelligence, NLP, Large Language M...        12  2468
41                    Computer Science, Public Sector        12  2468
42  Reviewing research proposals and scientific te...        12  2469
43                                         Linguistik        13  2467
44  Process Management, Compliance, Künstliche Int...        13  2467
45  Process Management, Compliance, Künstliche Int...        13  2467
49  Punctuation Knowledge, Content Structure, Spel...        14  2471
50  Information Verification, Fact Analysis, Sourc...        14  2471

In [141]:
# review agent skill
display(study_agents['profile.sections.skills'].dropna().apply(len).sum())
display(study_agents['profile.sections.skills'].dropna().apply(len).value_counts())
display(study_agents['profile.sections.skills'].dropna().apply(len).describe())

agents_skills = sum(study_agents['profile.sections.skills'].dropna().to_list(), [])

agents_skills_df = study_agents[['profile.sections.skills', 'group_id', 'user']].dropna()
agents_skills_df['profile.sections.skills'] = agents_skills_df['profile.sections.skills'].apply(lambda x: ', '.join(x))
agents_skills_df.to_csv(os.path.join('output', 'agents', 'agents_skills.tsv'), sep="\t")
display(agents_skills_df)

112

profile.sections.skills
3    12
2     9
4     6
1     6
6     3
5     2
0     1
Name: count, dtype: int64

count    39.000000
mean      2.871795
std       1.472189
min       0.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       6.000000
Name: profile.sections.skills, dtype: float64

                              profile.sections.skills  group_id  user
1   Document structuring, Asses essay structure, a...         1  1380
5   Reading and Writing Essay, Professional Redact...         3  1374
6                     Data Verification, AI Factology         3  1374
7   Coherence Improvement, Text Structural Clarity...         3  1374
8   Readability assessment, Constructive feedback ...         4  1383
9                 logic, marketing, quality assurance         4  1383
10  Spot logical faults, Creative thinking, Asking...         4  1384
11            Programming, Proof Reading, Supervision         4  1385
12  Readability assessment, Constructive feedback ...         5  1387
13  Coherence Improvement, Text Structural Clarity...         5  1387
14  Grammar error detection and correction, Senten...         5  1387
15    Comedy Timing, Expressive Teaching, Extend text         5  1387
17  Text Elaboration, Format text, Sentence Struct...         6  1388
18         Idea synthesis, Brainstorming, Mindmapping         6  1388
19  Readability assessment, Constructive feedback ...         6  1388
20                         Dynamic Citation selection         6  1389
23  Writing Essays, Understanding Context, Text Ed...         7  2456
24                              Adding coherent facts         7  2460
25  Readability assessment, Constructive feedback ...         8  2453
26  Paper writing, Discussion Section, Data Interp...         8  2453
27  Discussion section, Critique Discussion sectio...         8  2453
28  Scientific Writing, Communication in Healthcar...         8  2453
30  Suggest and revise text, Find fact and add ref...         9  2461
31  Grammar error detection and correction, Senten...         9  2464
32  Paraphrasing, Simplify Sentence, Shorten text,...         9  2457
33         Idea synthesis, Brainstorming, Mindmapping        10  2459
34  Planning, Organization, Portuguese Marketplace...        10  2459
35                    Event Planning, Design Concepts        10  2459
36                 Error Spotting, Grammar Correction        10  2465
37                                                           11  2463
38  Reference Tracking, Critical Analysis, Draft c...        11  2463
40                       Reviewing, Critical Thinking        12  2468
41                      Reviewing, References, Citing        12  2468
42  Reviewing. Find every little weak spot. Harsh ...        12  2469
43                                     Korrekturlesen        13  2467
44  Schreiben von Forschungsanträgen, Denken wie e...        13  2467
45  Fragen stellen mit dem Ziel, Lücken in bestehe...        13  2467
49  Proofreading, Text Correction, Cut text, Story...        14  2471
50  Source Assessment, Cross Referencing, Text out...        14  2471

In [142]:
#notes 
agent_notes_df = parse_generic_event(finished_participants[finished_participants["event"] == "AGENT_NOTE_ADD"])
print("agents with notes (some were introduced through preset usage)")
agents_with_notes_df = study_agents[study_agents["profile.knowledge.notes"].str.len() > 0].dropna().drop_duplicates(subset="profile.knowledge.notes")
display(agents_with_notes_df)
agents_with_notes_df[["profile.knowledge.notes", 'group_id', 'user']].to_csv(os.path.join('output', 'agents', 'agents_with_notes.tsv'), sep="\t")

print("These are added notes, yet only one got saved:")
display(finished_participants[finished_participants["event"] == "AGENT_NOTE_ADD"]["data"].to_list())
print("This is the only manually added and saved note:")
agent_note_update = parse_generic_event(finished_participants[finished_participants["event"] == "AGENT_NOTE_UPDATE"])
display(agent_note_update)
display(finished_participants[finished_participants["event"] == "AGENT_NOTE_DELETE"])

agents with notes (some were introduced through preset usage)

,group_id,user,document,_id,document_id,name,preset_id,role,summary,author_id,profile.sections.expertise,profile.sections.skills,profile.knowledge.notes,modified
6,3,1374,67c88f88285fac3f07bcf585,67cdfef4285fac3f07bcf5d3,67c88f88285fac3f07bcf585,AI Max,67cdfef4285fac3f07bcf5d2,Fact Checker and Fact Provider,The AI agent serves as a Fact Checker and Fact...,67cdfa30285fac3f07bcf5cc,"[Fact Validation, Historical Research]","[Data Verification, AI Factology]",[{'id': '2d0d2583-65b6-4ff2-8b76-c5aad1de0305'...,2025-03-09 20:49:56
8,4,1383,67d43b390b9539e69a3a86b9,67d445d10b9539e69a3a86c1,67d43b390b9539e69a3a86b9,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67bc761a7a670b68746905a0,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-14 15:05:53
14,5,1387,67d5d8160b9539e69a3a86d8,67d5d88f0b9539e69a3a86dc,67d5d8160b9539e69a3a86d8,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",67d5d8120b9539e69a3a86d7,[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-03-15 19:44:15
28,8,2453,6879e8fd87cf5fec60dc7fe1,6880e49587cf5fec60dc8009,6879e8fd87cf5fec60dc7fe1,Interaction Designer,6880e49587cf5fec60dc8008,Coming up with INteraction Design Implications...,The AI agent is responsible for developing int...,687de5d187cf5fec60dc7fef,"[AI in Healthcare, Interaction Design, Healthc...","[Scientific Writing, Communication in Healthca...",[{'id': 'bba2425c-43c5-4d8d-920c-993d894dd9e3'...,2025-07-23 13:33:09
30,9,2461,688364bf87cf5fec60dc8026,688bdddd87cf5fec60dc80d6,688364bf87cf5fec60dc8026,AiDevelop,688bdddd87cf5fec60dc80d5,Website Developer,The AI agent is a Website Developer with exper...,6888eec887cf5fec60dc8085,"[Web Design, SEO Management, Backend Developme...","[Suggest and revise text, Find fact and add re...",[{'id': '24896ea6-d264-4194-a432-94640ea924d5'...,2025-07-31 21:19:25
31,9,2464,688364bf87cf5fec60dc8026,688a6a2087cf5fec60dc80a2,688364bf87cf5fec60dc8026,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",688a52ad87cf5fec60dc8096,"[English Grammar and Syntax, Reading Comprehen...","[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-07-30 18:53:20

These are added notes, yet only one got saved:

['{"note_id": "89409952-d07b-4779-a7a4-4b9f6c693738", "user_id": "67cdfa30285fac3f07bcf5cc", "agent_id": "mocked-new-agent", "username": "Ivan Khrop", "document_id": "67c88f88285fac3f07bcf585", "participant_token": "93f70a37-e7d5-4bcf-adbc-d106ca47c27b"}',
 '{"note_id": "2d0d2583-65b6-4ff2-8b76-c5aad1de0305", "user_id": "67cdfa30285fac3f07bcf5cc", "agent_id": "67cdfef4285fac3f07bcf5d3", "username": "Ivan Khrop", "document_id": "67c88f88285fac3f07bcf585", "participant_token": "93f70a37-e7d5-4bcf-adbc-d106ca47c27b"}',
 '{"note_id": "e0b980e7-38c2-4f47-b737-97208139b70c", "user_id": "67cdfa30285fac3f07bcf5cc", "agent_id": "mocked-new-agent", "username": "Ivan Khrop", "document_id": "67c88f88285fac3f07bcf585", "participant_token": "93f70a37-e7d5-4bcf-adbc-d106ca47c27b"}',
 '{"note_id": "3bb3810b-3daf-4dde-9327-ebdfbe821b7b", "user_id": "688b1c7887cf5fec60dc80b0", "agent_id": "688a6a2087cf5fec60dc80a2", "username": "soumyashaw", "document_id": "688364bf87cf5fec60dc8026", "participant_token": "14291cb8-c3c7-433e-9a0c-830cca8e4422"}',
 '{"note_id": "24896ea6-d264-4194-a432-94640ea924d5", "user_id": "6888eec887cf5fec60dc8085", "agent_id": "688bdddd87cf5fec60dc80d6", "username": "vama00004", "document_id": "688364bf87cf5fec60dc8026", "participant_token": "46820311-be03-4d2e-b993-90ac3bec3c92"}',
 '{"note_id": "b280dc73-87ab-4083-8a59-4e915c0d6df5", "user_id": "6888eec887cf5fec60dc8085", "agent_id": "688bdddd87cf5fec60dc80d6", "username": "vama00004", "document_id": "688364bf87cf5fec60dc8026", "participant_token": "46820311-be03-4d2e-b993-90ac3bec3c92"}']

This is the only manually added and saved note:

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,note_id,user_id,agent_id,new_text,old_text,username,document_id,participant_token
0,276630.0,2025-03-09 21:29:19.531000,1374,"{""note_id"": ""2d0d2583-65b6-4ff2-8b76-c5aad1de0...",AGENT_NOTE_UPDATE,f244d4ba-e99b-421a-bedb-e5773c8277bd,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,{'note_id': '2d0d2583-65b6-4ff2-8b76-c5aad1de0...,2d0d2583-65b6-4ff2-8b76-c5aad1de0305,67cdfa30285fac3f07bcf5cc,67cdfef4285fac3f07bcf5d3,Provide an answer as changed text without your...,,Ivan Khrop,67c88f88285fac3f07bcf585,93f70a37-e7d5-4bcf-adbc-d106ca47c27b
1,281484.0,2025-07-31 14:32:28.327000,2457,"{""note_id"": ""3bb3810b-3daf-4dde-9327-ebdfbe821...",AGENT_NOTE_UPDATE,f20587b3-23d7-4973-a51b-ba22822f7962,14291cb8-c3c7-433e-9a0c-830cca8e4422,{'note_id': '3bb3810b-3daf-4dde-9327-ebdfbe821...,3bb3810b-3daf-4dde-9327-ebdfbe821b7b,688b1c7887cf5fec60dc80b0,688a6a2087cf5fec60dc80a2,Correct the spelling errors yourself,,soumyashaw,688364bf87cf5fec60dc8026,14291cb8-c3c7-433e-9a0c-830cca8e4422
2,282078.0,2025-07-31 21:19:57.678000,2461,"{""note_id"": ""24896ea6-d264-4194-a432-94640ea92...",AGENT_NOTE_UPDATE,2b9aec1e-4f35-4958-83fc-1eddf03e05b6,46820311-be03-4d2e-b993-90ac3bec3c92,{'note_id': '24896ea6-d264-4194-a432-94640ea92...,24896ea6-d264-4194-a432-94640ea924d5,6888eec887cf5fec60dc8085,688bdddd87cf5fec60dc80d6,I want this to think like a developer and sugg...,,vama00004,688364bf87cf5fec60dc8026,46820311-be03-4d2e-b993-90ac3bec3c92

,Unnamed: 0.1,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
321,323,500,276510.0,15941990-b8ef-4d9c-a7eb-a4cf96de6166,Prototype,2025-03-09 20:49:36.552000,AGENT_NOTE_DELETE,"{""note"": {""id"": ""89409952-d07b-4779-a7a4-4b9f6...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,{'note': {'id': '89409952-d07b-4779-a7a4-4b9f6...,67c88f88285fac3f07bcf585
5381,5720,5999,282082.0,71468511-a604-4b1d-bdd3-c2f4ebcb68a3,Prototype,2025-07-31 21:19:59.623000,AGENT_NOTE_DELETE,"{""note"": {""id"": ""b280dc73-87ab-4083-8a59-4e915...",2461,46820311-be03-4d2e-b993-90ac3bec3c92,in_progress,{'note': {'id': 'b280dc73-87ab-4083-8a59-4e915...,688364bf87cf5fec60dc8026

In [143]:
def consecutive_focus_event_rows(event_df, fieldname, bypass = []):
    consecutive_rows_list = []
    for n, g in event_df.groupby(['participant_id', (event_df[fieldname] != event_df[fieldname].shift()).cumsum()]):
        code_list = g[fieldname].tolist()
        
        if code_list[0] in bypass:
            for index, row in g.iterrows():
                
                consecutive_rows_list.append({
                    'participant_id': row['participant_id'],
                    fieldname: code_list[0],
                    'participant_token': row['participant_token'],
                    'consecutive_rows': [code_list[0]],
                    'length': -1,
                    'from_id': row['id'],
                    'to_id': row['id'],
                    'from_time': row['time'],
                    'to_time': row['time']
                   # 'state': state
                })
            
        else: 
            consecutive_rows_list.append({
                'participant_id': n[0],
                fieldname: code_list[0],
                'participant_token': g['participant_token'].iloc[0],
                'consecutive_rows': code_list,
                'length': len(code_list),
                'from_id': g['id'].iloc[0],
                'to_id': g['id'].iloc[-1],
                'from_time': g['time'].iloc[0],
                'to_time': g['time'].iloc[-1]
               # 'state': state
            })

    consecutive_rows_columns = ['participant_id', fieldname, 'participant_token', 'consecutive_rows', 'length', 'from_id', 'to_id', 'from_time', 'to_time']
    return pd.DataFrame(data = consecutive_rows_list, columns = consecutive_rows_columns)

Timeline analysis

In [144]:
def prepare_events_for_timeline(event_df, fieldname):
    rows = []
    for index, row in event_df.iterrows():
        rows.append({
            'participant_id': row['participant_id'],
            fieldname: row[fieldname],
            'participant_token': row['participant_token'],
            'id': row['id'],
            'time': row['time']
        })
        
    columns = ['participant_id', fieldname, 'participant_token','id', 'time']
    return pd.DataFrame(data = rows, columns = columns)

In [145]:
# Removed interaction events that happened while interviewing (task has been completed already)
def remove_events_while_interviewing(df, remove_arr):
    format = '%Y-%m-%d %H:%M:%S.%f'
    dfn = df.copy()

    for t in remove_arr:
        participant_id = t[0]
        time = t[1]
        time = datetime.strptime(time, format)

        participant_mask = dfn['participant_id'] == participant_id
        time_mask = dfn['from_time'] > time

        entries = dfn[participant_mask & time_mask]
        #display(entries.index)
        dfn = dfn.drop(entries.index)

    return dfn

In [146]:
# TIMELINE:

document_view_df = parse_generic_event(finished_participants, "DOCUMENT_VIEW")
task_view_df = parse_generic_event(finished_participants, "TASK_VIEW")
agents_view_df = parse_generic_event(finished_participants, "AGENTS_VIEW")

agent_save_df = parse_generic_event(finished_participants, "AGENT_SAVE")
preset_use_df = parse_generic_event(finished_participants, "AGENT_PRESET_USE")

display(agent_save_df)
display(preset_use_df)

focus_events_df = finished_participants[finished_participants['event'].isin(["DOCUMENT_VIEW", 'TASKS_VIEW', 'TASKS_VIEW_CLOSE', 'AGENTS_VIEW', 'AGENTS_VIEW_CLOSE', 'FINAL_PROCEED_TEXT', 'AGENT_CREATE', 'AGENT_SAVE', 'AGENT_PRESET_USE'])]

consecutive_focus_events_df = consecutive_focus_event_rows(focus_events_df, 'event', ['AGENT_CREATE', 'AGENT_SAVE', 'AGENT_PRESET_USE'])
prepared_focus_events_df = prepare_events_for_timeline(focus_events_df, 'event')

# transform times to datetime
consecutive_focus_events_df = transform_time(consecutive_focus_events_df, 'from_time')
consecutive_focus_events_df = transform_time(consecutive_focus_events_df, 'to_time')

prepared_focus_events_df = transform_time(prepared_focus_events_df, 'time')

# remove events that happened at the interview
#participant_id, time
remove_events_starting_from = [
    (1374, '2025-03-10 14:44:50.308'),
    #(1374, '2025-03-09 22:18:40.957'), # last comment approve
    #(1378, '2025-03-08 20:30:28.499'),
    (1388, '2025-03-17 15:12:56.935'), # last suggestion view detail
    (1389, '2025-03-17 15:00:33.242'),
    (1387, '2025-03-15 20:09:12.496'), # last comment approve
    (1390, '2025-03-15 20:09:12.496'), # this participant reported that they did not collaborate
    (2456, '2025-07-28 18:04:03.337'), # last task view close
    (2453, '2025-07-21 09:45:35.067'), # last agent view close 
    (2455, '2025-07-23 13:53:19.984'), # last suggestion view detail
    (2461, '2025-07-31 21:50:47.107'), # last suggestion take over
    (2464, '2025-07-30 19:28:28.289'), # last comment approve
    (2457, '2025-07-31 15:31:45.052'), # last reply post
    (2459, '2025-07-29 13:23:03.445'), # last suggestion c2c
    (2465, '2025-07-31 21:20:40.047'), # last suggestion view detail
    (2467, '2025-08-20 16:21:49.455'), # last reply post
    (2476, '2025-08-20 16:15:56.221') # last comment related event
]
clean_consecutive_focus_events_df = remove_events_while_interviewing(consecutive_focus_events_df, remove_events_starting_from)
# drop events of 1378, since this participant only viewed the taskview once, and then never had another important agent or task event
entries = clean_consecutive_focus_events_df[clean_consecutive_focus_events_df['participant_id'] == 1378]
#display(entries.index)
clean_consecutive_focus_events_df = clean_consecutive_focus_events_df.drop(entries.index)

participant_focus_events = clean_consecutive_focus_events_df.groupby(['participant_id'])


print(participant_focus_events)

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,user_id,agent_id,...,agent.behavior.settings.time_trigger.timeOfDay,agent.behavior.settings.time_trigger.eachMinutes,agent.behavior.settings.time_trigger.maxTimesPerDay,agent.behavior.settings.time_trigger.timeAfterTyping,agent.behavior.settings.ownership_area,agent.behavior.settings.context_trigger,agent.behavior.settings.text_operations,agent.behavior.ownership_level,agent.author_id,agent.is_preset
0,276482.0,2025-03-09 20:39:33.642000,1374,"{""agent"": {""id"": ""67cdfc85285fac3f07bcf5cf"", ""...",AGENT_SAVE,34ebd4a3-80f9-4249-8012-c3c657ee60df,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'agent': {'id': '67cdfc85285fac3f07bcf5cf', '...",67cdfa30285fac3f07bcf5cc,67cdfc85285fac3f07bcf5cf,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67cdfa30285fac3f07bcf5cc,False
1,276514.0,2025-03-09 20:49:56.576000,1374,"{""agent"": {""id"": ""67cdfef4285fac3f07bcf5d3"", ""...",AGENT_SAVE,9e16a790-e74a-4bfc-aefa-bf081df12634,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'agent': {'id': '67cdfef4285fac3f07bcf5d3', '...",67cdfa30285fac3f07bcf5cc,67cdfef4285fac3f07bcf5d3,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67cdfa30285fac3f07bcf5cc,False
2,277485.0,2025-03-10 08:39:45.213000,1380,"{""agent"": {""id"": ""67cea551285fac3f07bcf604"", ""...",AGENT_SAVE,2782d4d1-f743-4c3e-8c4b-6de0dd2545f6,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'agent': {'id': '67cea551285fac3f07bcf604', '...",67ce9cb4285fac3f07bcf5ec,67cea551285fac3f07bcf604,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67ce9cb4285fac3f07bcf5ec,False
3,278321.0,2025-03-15 19:45:20.151000,1387,"{""agent"": {""id"": ""67d5d8cf0b9539e69a3a86df"", ""...",AGENT_SAVE,f47e1726-109f-423a-947e-8a94dd615cb2,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'agent': {'id': '67d5d8cf0b9539e69a3a86df', '...",67d5d8120b9539e69a3a86d7,67d5d8cf0b9539e69a3a86df,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d5d8120b9539e69a3a86d7,False
4,278574.0,2025-03-17 14:19:26.040000,1388,"{""agent"": {""id"": ""67d82f6dedfe680c1b0f164a"", ""...",AGENT_SAVE,f0756605-541b-4c63-9b9b-d397978f2369,3b49f849-3081-4478-81ce-d65450662c47,"{'agent': {'id': '67d82f6dedfe680c1b0f164a', '...",67d82dc4edfe680c1b0f1642,67d82f6dedfe680c1b0f164a,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d82dc4edfe680c1b0f1642,False
5,278595.0,2025-03-17 14:20:38.636000,1389,"{""agent"": {""id"": ""67d82fbfedfe680c1b0f164e"", ""...",AGENT_SAVE,481f10b4-8bf1-4d59-bf52-4daa60b068d7,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'agent': {'id': '67d82fbfedfe680c1b0f164e', '...",67d82e0aedfe680c1b0f1643,67d82fbfedfe680c1b0f164e,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d82e0aedfe680c1b0f1643,False
6,279971.0,2025-07-28 13:12:02.272000,2456,"{""agent"": {""id"": ""6887772287cf5fec60dc8036"", ""...",AGENT_SAVE,743dbfa0-248b-4732-992a-e57f887aa5c8,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'agent': {'id': '6887772287cf5fec60dc8036', '...",68835b0587cf5fec60dc8020,6887772287cf5fec60dc8036,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,68835b0587cf5fec60dc8020,False
7,280728.0,2025-07-29 11:54:12.648000,2460,"{""agent"": {""id"": ""6888b66487cf5fec60dc806d"", ""...",AGENT_SAVE,d67f0275-dc5e-494c-85fe-c8b3848e8d20,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'agent': {'id': '6888b66487cf5fec60dc806d', '...",6887b97087cf5fec60dc8060,6888b66487cf5fec60dc806d,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6887b97087cf5fec60dc8060,False
8,281000.0,2025-07-29 13:16:31.760000,2459,"{""agent"": {""id"": ""6888c9af87cf5fec60dc8081"", ""...",AGENT_SAVE,5d2ce301-ed3e-4da6-96c2-ace4922d9ede,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'agent': {'id': '6888c9af87cf5fec60dc8081', '...",6888bbce87cf5fec60dc8072,6888c9af87cf5fec60dc8081,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6888bbce87cf5fec60dc8072,False
9,281422.0,2025-07-31 08:34:46.364000,2463,"{""agent"": {""id"": ""688b2aa687cf5fec60dc80b3"", ""...",AGENT_SAVE,c9c3fd1d-9afc-48fd-8526-276f44e3c3e0,38811499-e7ca-453e-a57b-86c5dcdee514,"{'agent': {'id': '688b2aa687cf5fec60dc80b3', '...",6889e71f87cf5fec60dc8094,688b2aa687cf5fec60dc80b3,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6889e71f87cf5fec60dc8094,False
10,281501.0,2025-07-31 14:36:27.527000,2457,"{""agent"": {""id"": ""688b7f6b87cf5fec60dc80b7"", ""...",AGENT_SAVE,b5cc537c-fade-4196-bbc4-5465fffbc5cf,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'agent': {'id': '688b7f6b87cf5fec60dc80b7', '...",688b1c7887cf5fec60dc80b0,688b7f6b87cf5fec60dc80b7,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,688b1c7887cf5fec60dc80b0,False
11,282066.0,2025-07-31 21:19:25.551000,2461,"{""agent"": {""id"": ""688bdddd87cf5fec60dc80d6"", ""...",AGENT_SAVE,e25d897a-561f-4685-9604-598b06713640,46820311-be03-4d2e-b993-90ac3bec3c92,"{'agent': {'id': '688bdddd87cf5fec60dc80d6', '...",6888eec887cf5fec60dc8085,688bdddd87cf5fec60dc80d6,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6888eec887cf5fec60dc8085,False
12,282574.0,2025-08-13 07:24:19.760000,2469,"{""agent"": {""id"": ""689c3da3e90ffc190a96c28f"", ""...",AGENT_SAVE,3f96497e-e4a0-4f46-9784-68fb1488a9a6,63e04882-b933-435f-b84b-7a638b9c5ae8,"{'agent': {'id': '689c3da3e90ffc190a96c28f', '...",689c3c25e90ffc190a96c28b,689c3da3e90ffc190a96c28f,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,689c3c25e90ffc190a96c28b,False
13,282896.0,2025-08-14 18:01:20.523000,2471,"{""agent"": {""id"": ""689e2470e90ffc190a96c2e4"", ""...",AGENT_SAVE,79f1c37f-d0e7-40c4-88cf-e2ceb322b854,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'agent': {'id': '689e2470e90ffc190a96c2e4', '...",689e22d5e90ffc190a96c2e0,689e2470e90ffc190a96c2e4,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,689e22d5e90ffc190a96c2e0,False
14,282906.0,2025-08-14 18:02:29.399000,2471,"{""agent"": {""id"": ""689e24b5e90ffc190a96c2e6"", ""...",AGENT_SAVE,b1efbe38-a7cb-491e-97e7-23525307752e,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'agent': {'id': '689e24b5e90ffc190a96c2e6', '...",689e22d5e90ffc190a96c2e0,689e24b5e90ffc190a96c2e6,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,689e22d5e90ffc190a96c2e0,False

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,user_id,agent_id,...,agent.behavior.settings.time_trigger.timeOfDay,agent.behavior.settings.time_trigger.eachMinutes,agent.behavior.settings.time_trigger.maxTimesPerDay,agent.behavior.settings.time_trigger.timeAfterTyping,agent.behavior.settings.ownership_area,agent.behavior.settings.context_trigger,agent.behavior.settings.text_operations,agent.behavior.ownership_level,agent.author_id,agent.is_preset
0,277593.0,2025-03-10 12:54:22.172000,1374,"{""agent"": {""id"": ""67cee0fd285fac3f07bcf60b"", ""...",AGENT_PRESET_USE,6db84411-7e90-4662-bbca-e06bc69cf948,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'agent': {'id': '67cee0fd285fac3f07bcf60b', '...",67cdfa30285fac3f07bcf5cc,67cee0fd285fac3f07bcf60b,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67cdfa30285fac3f07bcf5cc,False
1,278305.0,2025-03-15 19:44:01.834000,1387,"{""agent"": {""id"": ""67d5d8810b9539e69a3a86da"", ""...",AGENT_PRESET_USE,8800aa92-61e7-4377-8558-04c70d18ee46,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'agent': {'id': '67d5d8810b9539e69a3a86da', '...",67d5d8120b9539e69a3a86d7,67d5d8810b9539e69a3a86da,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d5d8120b9539e69a3a86d7,False
2,278308.0,2025-03-15 19:44:12.234000,1387,"{""agent"": {""id"": ""67d5d88b0b9539e69a3a86db"", ""...",AGENT_PRESET_USE,3b51545d-1203-4b6c-97a7-12ee9a7aa814,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'agent': {'id': '67d5d88b0b9539e69a3a86db', '...",67d5d8120b9539e69a3a86d7,67d5d88b0b9539e69a3a86db,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d5d8120b9539e69a3a86d7,False
3,278310.0,2025-03-15 19:44:16.298000,1387,"{""agent"": {""id"": ""67d5d88f0b9539e69a3a86dc"", ""...",AGENT_PRESET_USE,7d65bd85-613c-4c0c-93e2-0377075c9abe,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'agent': {'id': '67d5d88f0b9539e69a3a86dc', '...",67d5d8120b9539e69a3a86d7,67d5d88f0b9539e69a3a86dc,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d5d8120b9539e69a3a86d7,False
4,278701.0,2025-03-17 14:39:13.303000,1388,"{""agent"": {""id"": ""67d83410edfe680c1b0f1655"", ""...",AGENT_PRESET_USE,0d312d46-4bdb-4af1-8517-72a40589c530,3b49f849-3081-4478-81ce-d65450662c47,"{'agent': {'id': '67d83410edfe680c1b0f1655', '...",67d82dc4edfe680c1b0f1642,67d83410edfe680c1b0f1655,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d82dc4edfe680c1b0f1642,False
5,278835.0,2025-03-17 14:44:41.404000,1388,"{""agent"": {""id"": ""67d83558edfe680c1b0f165e"", ""...",AGENT_PRESET_USE,572806ef-0c0c-4a74-82d3-9d1a874cd4b1,3b49f849-3081-4478-81ce-d65450662c47,"{'agent': {'id': '67d83558edfe680c1b0f165e', '...",67d82dc4edfe680c1b0f1642,67d83558edfe680c1b0f165e,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d82dc4edfe680c1b0f1642,False
6,279630.0,2025-07-21 07:57:52.636000,2453,"{""agent"": {""id"": ""687df2ff87cf5fec60dc7ff1"", ""...",AGENT_PRESET_USE,717555ae-750f-45d3-bab9-0eb0dfc86ccf,e24dd41b-25cb-4503-a4b7-4919fc0e688f,"{'agent': {'id': '687df2ff87cf5fec60dc7ff1', '...",687de5d187cf5fec60dc7fef,687df2ff87cf5fec60dc7ff1,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,687de5d187cf5fec60dc7fef,False
7,280898.0,2025-07-29 12:23:39.384000,2459,"{""agent"": {""id"": ""6888bd4b87cf5fec60dc8073"", ""...",AGENT_PRESET_USE,4cedddec-0fb8-4bdd-a889-03cdc0b0f7c4,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'agent': {'id': '6888bd4b87cf5fec60dc8073', '...",6888bbce87cf5fec60dc8072,6888bd4b87cf5fec60dc8073,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6888bbce87cf5fec60dc8072,False
8,281267.0,2025-07-30 18:53:21.728000,2464,"{""agent"": {""id"": ""688a6a2087cf5fec60dc80a2"", ""...",AGENT_PRESET_USE,319a9e5a-9a6b-4a92-83f1-f0ae987ab3a3,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'agent': {'id': '688a6a2087cf5fec60dc80a2', '...",688a52ad87cf5fec60dc8096,688a6a2087cf5fec60dc80a2,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,688a52ad87cf5fec60dc8096,False

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f87be2e8210>

In [147]:
# get min max for each group

# Important: we consider the cleaned consecutive focus events, these events do not contain the events that happened in the final interviews.
# The windows of times (min - max) are thus shorter.

minmaxtimes_participants = {}
for pg in participants_groups:
    pg_events = clean_consecutive_focus_events_df[clean_consecutive_focus_events_df['participant_id'].isin(participants_groups[pg]["users"])]
    #display(pg_events)
    min_time = pg_events['from_time'].min()
    max_time = pg_events['to_time'].max()

    for p in participants_groups[pg]["users"]:
        minmaxtimes_participants[p] = {"min": min_time, "max": max_time}

display(minmaxtimes_participants)

{1379: {'min': Timestamp('2025-03-10 07:43:55.548000'),
  'max': Timestamp('2025-03-10 08:42:46.563000')},
 1380: {'min': Timestamp('2025-03-10 07:43:55.548000'),
  'max': Timestamp('2025-03-10 08:42:46.563000')},
 1376: {'min': Timestamp('2025-03-07 21:33:49.808000'),
  'max': Timestamp('2025-03-07 21:50:55.943000')},
 1377: {'min': Timestamp('2025-03-07 21:33:49.808000'),
  'max': Timestamp('2025-03-07 21:50:55.943000')},
 1378: {'min': Timestamp('2025-03-09 20:29:39.476000'),
  'max': Timestamp('2025-03-10 14:44:50.308000')},
 1374: {'min': Timestamp('2025-03-09 20:29:39.476000'),
  'max': Timestamp('2025-03-10 14:44:50.308000')},
 1383: {'min': Timestamp('2025-03-14 15:02:19.172000'),
  'max': Timestamp('2025-03-28 12:40:02.313000')},
 1384: {'min': Timestamp('2025-03-14 15:02:19.172000'),
  'max': Timestamp('2025-03-28 12:40:02.313000')},
 1385: {'min': Timestamp('2025-03-14 15:02:19.172000'),
  'max': Timestamp('2025-03-28 12:40:02.313000')},
 1387: {'min': Timestamp('2025-03-15 19:42:15.666000'),
  'max': Timestamp('2025-03-15 20:09:12.496000')},
 1390: {'min': Timestamp('2025-03-15 19:42:15.666000'),
  'max': Timestamp('2025-03-15 20:09:12.496000')},
 1388: {'min': Timestamp('2025-03-17 14:12:51.247000'),
  'max': Timestamp('2025-03-17 15:07:47.510000')},
 1389: {'min': Timestamp('2025-03-17 14:12:51.247000'),
  'max': Timestamp('2025-03-17 15:07:47.510000')},
 2456: {'min': Timestamp('2025-07-25 10:23:21.647000'),
  'max': Timestamp('2025-07-29 12:44:49.969000')},
 2460: {'min': Timestamp('2025-07-25 10:23:21.647000'),
  'max': Timestamp('2025-07-29 12:44:49.969000')},
 2453: {'min': Timestamp('2025-07-21 07:01:47.239000'),
  'max': Timestamp('2025-07-23 13:47:49.366000')},
 2455: {'min': Timestamp('2025-07-21 07:01:47.239000'),
  'max': Timestamp('2025-07-23 13:47:49.366000')},
 2461: {'min': Timestamp('2025-07-29 15:55:03.782000'),
  'max': Timestamp('2025-07-31 21:42:38.358000')},
 2464: {'min': Timestamp('2025-07-29 15:55:03.782000'),
  'max': Timestamp('2025-07-31 21:42:38.358000')},
 2457: {'min': Timestamp('2025-07-29 15:55:03.782000'),
  'max': Timestamp('2025-07-31 21:42:38.358000')},
 2459: {'min': Timestamp('2025-07-29 12:17:56.909000'),
  'max': Timestamp('2025-07-31 21:13:05.168000')},
 2465: {'min': Timestamp('2025-07-29 12:17:56.909000'),
  'max': Timestamp('2025-07-31 21:13:05.168000')},
 2463: {'min': Timestamp('2025-07-30 09:34:50.015000'),
  'max': Timestamp('2025-08-22 18:29:10.543000')},
 2475: {'min': Timestamp('2025-07-30 09:34:50.015000'),
  'max': Timestamp('2025-08-22 18:29:10.543000')},
 2468: {'min': Timestamp('2025-08-10 06:47:33.803000'),
  'max': Timestamp('2025-08-15 07:43:41.191000')},
 2469: {'min': Timestamp('2025-08-10 06:47:33.803000'),
  'max': Timestamp('2025-08-15 07:43:41.191000')},
 2467: {'min': NaT, 'max': NaT},
 2476: {'min': NaT, 'max': NaT},
 2470: {'min': Timestamp('2025-08-14 17:49:01.651000'),
  'max': Timestamp('2025-08-14 18:21:22.659000')},
 2471: {'min': Timestamp('2025-08-14 17:49:01.651000'),
  'max': Timestamp('2025-08-14 18:21:22.659000')}}

[B] When were agents created typically

In [148]:
display(study_agents)

agents_saved_df = finished_participants[finished_participants['event'] == 'AGENT_SAVE']
agents_saved_df = parse_generic_event(agents_saved_df)
display(agents_saved_df)

agent_creation_time_percentages = []
for p in minmaxtimes_participants:
    min_time = minmaxtimes_participants[p]['min']
    max_time = minmaxtimes_participants[p]['max']
    session_length = (max_time - min_time).total_seconds()
 
    user_agents = study_agents[study_agents['user'] == p]
    for index, row in user_agents.iterrows():
        diff = (row['modified'] - min_time).total_seconds()
        percentage_of_time = 100 / session_length * diff
        agent_creation_time_percentages.append([p, row['group_id'], percentage_of_time])

time_to_creation_percentage = pd.DataFrame(data=agent_creation_time_percentages, columns=['user', 'group_id', 'time_percentage'])

display(time_to_creation_percentage[time_to_creation_percentage['time_percentage'] < 25])
display(100/len(study_agents) * len(time_to_creation_percentage[time_to_creation_percentage['time_percentage'] < 25]))
display(time_to_creation_percentage[(time_to_creation_percentage['time_percentage'] > 25) & (time_to_creation_percentage['time_percentage'] < 50)])
display(100/len(study_agents) * len(time_to_creation_percentage[(time_to_creation_percentage['time_percentage'] > 25) & (time_to_creation_percentage['time_percentage'] < 50)]))
display(time_to_creation_percentage[(time_to_creation_percentage['time_percentage'] > 50) & (time_to_creation_percentage['time_percentage'] < 75)])
display(100/len(study_agents) * len(time_to_creation_percentage[(time_to_creation_percentage['time_percentage'] > 50) & (time_to_creation_percentage['time_percentage'] < 75)]))
display(time_to_creation_percentage[time_to_creation_percentage['time_percentage'] > 75])
display(100/len(study_agents) * len(time_to_creation_percentage[time_to_creation_percentage['time_percentage'] > 75]))

,group_id,user,document,_id,document_id,name,preset_id,role,summary,author_id,profile.sections.expertise,profile.sections.skills,profile.knowledge.notes,modified
1,1,1380,67ce983b285fac3f07bcf5e8,67cea551285fac3f07bcf604,67ce983b285fac3f07bcf5e8,Bob,67cea551285fac3f07bcf603,Assistant,"The AI agent serves as an assistant, specializ...",67ce9cb4285fac3f07bcf5ec,[],"[Document structuring, Asses essay structure, ...",[],2025-03-10 08:39:45
5,3,1374,67c88f88285fac3f07bcf585,67cdfc85285fac3f07bcf5cf,67c88f88285fac3f07bcf585,Erika,67cdfc85285fac3f07bcf5ce,Essay Reviewer,"The AI agent serves as an Essay Reviewer, spec...",67cdfa30285fac3f07bcf5cc,"[Literature Studies, Academic Editing, Essay W...","[Reading and Writing Essay, Professional Redac...",[],2025-03-09 20:39:33
6,3,1374,67c88f88285fac3f07bcf585,67cdfef4285fac3f07bcf5d3,67c88f88285fac3f07bcf585,AI Max,67cdfef4285fac3f07bcf5d2,Fact Checker and Fact Provider,The AI agent serves as a Fact Checker and Fact...,67cdfa30285fac3f07bcf5cc,"[Fact Validation, Historical Research]","[Data Verification, AI Factology]",[{'id': '2d0d2583-65b6-4ff2-8b76-c5aad1de0305'...,2025-03-09 20:49:56
7,3,1374,67c88f88285fac3f07bcf585,67cee0fd285fac3f07bcf60b,67c88f88285fac3f07bcf585,TextStructurer,67b9b3e4adc01b1db6869c72,Text Structure and Format Specialist,The AI agent serves as a Text Structure and Fo...,67cdfa30285fac3f07bcf5cc,"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],2025-03-10 12:54:21
8,4,1383,67d43b390b9539e69a3a86b9,67d445d10b9539e69a3a86c1,67d43b390b9539e69a3a86b9,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67bc761a7a670b68746905a0,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-14 15:05:53
9,4,1383,67d43b390b9539e69a3a86b9,67e691c850d39f32454bf30c,67d43b390b9539e69a3a86b9,Consistency Reviewer,67e691c850d39f32454bf30b,Consistency Reviewer,"The AI agent serves as a Consistency Reviewer,...",67bc761a7a670b68746905a0,"[Scientific Paper writing, HCI researcher expe...","[logic, marketing, quality assurance]",[],2025-03-28 12:10:48
10,4,1384,67d43b390b9539e69a3a86b9,67e5cb6450d39f32454bf2fa,67d43b390b9539e69a3a86b9,ContentReviewer,67e5cb6450d39f32454bf2f9,Critical Reviewer with HCI and Education Exper...,The AI agent serves as a Critical Reviewer wit...,67d444dd0b9539e69a3a86bb,"[Human-Computer Interaction, Education, AI-ass...","[Spot logical faults, Creative thinking, Askin...",[],2025-03-27 22:04:20
11,4,1385,67d43b390b9539e69a3a86b9,67d445e30b9539e69a3a86c3,67d43b390b9539e69a3a86b9,Best HCI Professor,67d445e30b9539e69a3a86c2,This AI Assistant is the best HCI Professor in...,The AI agent is recognized as a leading profes...,67bc43607a670b6874690577,"[HCI, Teaching]","[Programming, Proof Reading, Supervision]",[],2025-03-14 15:06:11
12,5,1387,67d5d8160b9539e69a3a86d8,67d5d8810b9539e69a3a86da,67d5d8160b9539e69a3a86d8,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67d5d8120b9539e69a3a86d7,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-15 19:44:01
13,5,1387,67d5d8160b9539e69a3a86d8,67d5d88b0b9539e69a3a86db,67d5d8160b9539e69a3a86d8,TextStructurer,67b9b3e4adc01b1db6869c72,Text Structure and Format Specialist,The AI agent serves as a Text Structure and Fo...,67d5d8120b9539e69a3a86d7,"[Text Organization, Content Flow, Document For...","[Coherence Improvement, Text Structural Clarit...",[],2025-03-15 19:44:11
14,5,1387,67d5d8160b9539e69a3a86d8,67d5d88f0b9539e69a3a86dc,67d5d8160b9539e69a3a86d8,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",67d5d8120b9539e69a3a86d7,[English Grammar and Syntax],"[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-03-15 19:44:15
15,5,1387,67d5d8160b9539e69a3a86d8,67d5d8cf0b9539e69a3a86df,67d5d8160b9539e69a3a86d8,6ex teacher,67d5d8cf0b9539e69a3a86de,Teaches sex and makes stupid but funny jokes,The AI agent is primarily engaged in the field...,67d5d8120b9539e69a3a86d7,"[Sex education, jokes, Adult Education, Comedy...","[Comedy Timing, Expressive Teaching, Extend text]",[],2025-03-15 19:45:19
17,6,1388,67d08e87285fac3f07bcf64b,67d82f6dedfe680c1b0f164a,67d08e87285fac3f07bcf64b,musie pupulikin,67d82f6dedfe680c1b0f1649,check gramma,The AI agent is primarily responsible for chec...,67d82dc4edfe680c1b0f1642,"[Language Proficiency, Punctuation Awareness, ...","[Text Elaboration, Format text, Sentence Struc...",[],2025-03-17 14:19:25
18,6,1388,67d08e87285fac3f07bcf64b,67d83410edfe680c1b0f1655,67d08e87285fac3f07bcf64b,Eureka,67b9b221adc01b1db6869c70,Idea Generator,"The AI agent serves as an Idea Generator, spec...",67d82dc4edfe680c1b0f1642,"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],2025-03-17 14:39:12
19,6,1388,67d08e87285fac3f07bcf64b,67d83558edfe680c1b0f165e,67d08e87285fac3f07bcf64b,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,67d82dc4edfe680c1b0f1642,"[Text Review, Textual Criticism]","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-03-17 14:44:40
20,6,1389,67d08e87285fac3f07bcf64b,67d82fbfedfe680c1b0f164e,67d08e87285fac3f07bcf64b,Bolshoi Lyoha,67d82fbfedfe680c1b0f164d,Proofreader,"The AI agent serves as a proofreader, speciali...",67d82e0aedfe680c1b0f1643,"[Grammar Knowledge, Publication Formatting, So...",[Dynamic Citation selection],[],2025-03-17 14:20:47
23,7,2456,68833fd687cf5fec60dc801d,6887772287cf5fec60dc8036,68833fd687cf5fec60dc801d,The AI Expert,6887772287cf5fec60dc8035,Author,The AI agent serves as an author with expertis...,68835b0587cf5fec60dc8020,"[artificial intelligence, english writing, edu...","[Writing Essays, Understanding Context, Text E...",[],2025-07-28 13:12:02
24,7,2460,68833fd687cf5fec60dc801d,6888b66487cf5fec60dc806d,68833fd687cf5fec60dc801d,Fun facts,6888b66487cf5fec60dc806c,Add interesting facts,The AI agent specializes in enriching document...,6887b97087cf5fec60dc8060,"[history, statistics, facts]",[Adding coherent facts],[],2025-07-29 11:54:12
25,8,2453,6879e8fd87cf5fec60dc7fe1,687df2ff87cf5fec60dc7ff1,6879e8fd87cf5fec60dc7fe1,TextReviewer,67b9b111adc01b1db6869c6e,Text Analysis and Feedback Specialist,The AI agent serves as a Text Analysis and Fee...,687de5d187cf5fec60dc7fef,"[Text Review, Textual Criticism, Human Compute...","[Readability assessment, Constructive feedback...",[{'id': '308adaea-0d53-4aca-9fac-8c1c7eccce87'...,2025-07-21 07:57:51
26,8,2453,6879e8fd87cf5fec60dc7fe1,6880e03f87cf5fec60dc7ffb,6879e8fd87cf5fec60dc7fe1,LM PI Expert (2015),6880e03f87cf5fec60dc7ffa,Lived Model of PI Expert,The AI agent serves as a Lived Model of PI Exp...,687de5d187cf5fec60dc7fef,[Expert in A lived informatics model of person...,"[Paper writing, Discussion Section, Data Inter...",[],2025-07-23 13:14:39
27,8,2453,6879e8fd87cf5fec60dc7fe1,6880e0d087cf5fec60dc7ffd,6879e8fd87cf5fec60dc7fe1,SBM PI Expert (2010),6880e0d087cf5fec60dc7ffc,Stage based model of personal informatics (201...,The AI agent is a specialist in the Stage base...,687de5d187cf5fec60dc7fef,[You are an expert in Stage based model of per...,"[Discussion section, Critique Discussion secti...",[],2025-07-23 13:17:04
28,8,2453,6879e8fd87cf5fec60dc7fe1,6880e49587cf5fec60dc8009,6879e8fd87cf5fec60dc7fe1,Interaction Designer,6880e49587cf5fec60dc8008,Coming up with INteraction Design Implications...,The AI agent is responsible for developing int...,687de5d187cf5fec60dc7fef,"[AI in Healthcare, Interaction Design, Healthc...","[Scientific Writing, Communication in Healthca...",[{'id': 'bba2425c-43c5-4d8d-920c-993d894dd9e3'...,2025-07-23 13:33:09
30,9,2461,688364bf87cf5fec60dc8026,688bdddd87cf5fec60dc80d6,688364bf87cf5fec60dc8026,AiDevelop,688bdddd87cf5fec60dc80d5,Website Developer,The AI agent is a Website Developer with exper...,6888eec887cf5fec60dc8085,"[Web Design, SEO Management, Backend Developme...","[Suggest and revise text, Find fact and add re...",[{'id': '24896ea6-d264-4194-a432-94640ea924d5'...,2025-07-31 21:19:25
31,9,2464,688364bf87cf5fec60dc8026,688a6a2087cf5fec60dc80a2,688364bf87cf5fec60dc8026,George,67b9b9a3adc01b1db6869c87,English Teacher,"The AI agent serves as an English Teacher, spe...",688a52ad87cf5fec60dc8096,"[English Grammar and Syntax, Reading Comprehen...","[Grammar error detection and correction, Sente...",[{'id': '1118bf6d-34c1-48d0-b6c1-ff63e15d3c07'...,2025-07-30 18:53:20
32,9,2457,688364bf87cf5fec60dc8026,688b7f6b87cf5fec60dc80b7,688364bf87cf5fec60dc8026,Rephraser,688b7f6b87cf5fec60dc80b6,Rephrase a sentence or section,The AI agent is designed to rephrase sentences...,688b1c7887cf5fec60dc80b0,"[Semantic Understanding, Grammar Knowledge, Co...","[Paraphrasing, Simplify Sentence, Shorten text...",[],2025-07-31 14:36:27
33,10,2459,6877c26e87cf5fec60dc7fda,6888bd4b87cf5fec60dc8073,6877c26e87cf5fec60dc7fda,Eureka,67b9b221adc01b1db6869c70,Idea Generator,"The AI agent serves as an Idea Generator, spec...",6888bbce87cf5fec60dc8072,"[Concept Creation, Creative Thinking]","[Idea synthesis, Brainstorming, Mindmapping]",[],2025-07-29 12:23:39
34,10,2459,6877c26e87cf5fec60dc7fda,6888c9af87cf5fec60dc8081,6877c26e87cf5fec60dc7fda,Purchasing,6888c9af87cf5fec60dc8080,Planner,"The AI agent serves as a Planner, specializing...",6888bbce87cf5fec60dc8072,"[Event Coordination, Strategic Planning]","[Planning, Organization, Portuguese Marketplac...",[],2025-07-29 13:16:31
35,10,2459,6877c26e87cf5fec60dc7fda,688bd9f587cf5fec60dc80cc,6877c26e87cf5fec60dc7fda,Organizer,688bd9f587cf5fec60dc80cb,Wedding planner,"The AI agent serves as a wedding planner, spec...",6888bbce87cf5fec60dc8072,"[Event Management, Wedding Decor]","[Event Planning, Design Concepts]",[],2025-07-31 21:02:45
36,10,2465,6877c26e87cf5fec60dc7fda,688e30ee87cf5fec60dc80f4,6877c26e87cf5fec60dc7fda,Text Improver,688e30ee87cf5fec60dc80f3,Improve writting flow,The AI agent is designed to enhance writing fl...,688bdb6387cf5fec60dc80d0,"[Linguistic Knowledge, Text Coherence, Narrati...","[Error Spotting, Grammar Correction]",[],2025-08-02 15:38:22
37,11,2463,6889e57087cf5fec60dc8092,688b2aa687cf5fec60dc80b3,6889e57087cf5fec60dc8092,Fact Checker,688b2aa687cf5fec60dc80b2,Checking facts for scientific evidence,The AI agent is primarily responsible for fact...,6889e71f87cf5fec60dc8094,[],[],[],2025-07-31 08:34:46
38,11,2463,6889e57087cf5fec60dc8092,68931d9887cf5fec60dc810f,6889e57087cf5fec60dc8092,Synthesizer,68931d9887cf5fec60dc810e,Reading and synthesizing papers about a specif...,The AI agent is designed to meticulously read ...,6889e71f87cf5fec60dc8094,"[Document Analysis, Topic Understanding, Resea...","[Reference Tracking, Critical Analysis, Draft ...",[],2025-08-06 09:17:12
40,12,2468,688c6add87cf5fec60dc80ef,689c50c4e90ffc190a96c292,688c6add87cf5fec60dc80ef,AI Sceptic Reviewer,689c50c4e90ffc190a96c291,"A DFG reviewer, sceptic of AI usage, especiall...",The AI agent serves as a DFG reviewer with a s...,6898407be90ffc190a96c287,"[Artificial Intelligence, NLP, Large Language ...","[Reviewing, Critical Thinking]",[],2025-08-13 08:45:56
41,12,2468,688c6add87cf5fec60dc80ef,689c51e2e90ffc190a96c296,688c6add87cf5fec60dc80ef,References Nagger,689c51e2e90ffc190a96c295,"Checks text for missing references, i.e., stat...",The AI agent is designed to review text and id...,6898407be90ffc190a96c287,"[Computer Science, Public Sector]","[Reviewing, References, Citing]",[],2025-08-13 08:50:42
42,12,2469,688c6add87cf5fec60dc80ef,689c3da3e90ffc190a96c28f,688c6add87cf5fec60dc80ef,Nasty Nancy,689c3da3e90ffc190a96c28e,Opposite reviewer,"The AI agent, known as the Opposite Reviewer, ...",689c3c25e90ffc190a96c28b,[Reviewing research proposals and scientific t...,[Reviewing. Find every little weak spot. Harsh...,[],2025-08-13 07:24:19
43,13,2467,68907a6e87cf5fec60dc8107,68a5a808e90ffc190a96c307,68907a6e87cf5fec60dc8107,Mr. Correct,68a5a808e90ffc190a96c306,Proofreader,"The AI agent serves as a proofreader, speciali...",68a5a0bde90ffc190a96c2ff,[Linguistik],[Korrekturlesen],[],2025-08-20 10:48:40
44,13,2467,68907a6e87cf5fec60dc8107,68a5acf4e90ffc190a96c309,68907a6e87cf5fec60dc8107,Proposal Brain,68a5acf4e90ffc190a96c308,Researcher,"The AI agent serves as a Researcher, specializ...",68a5a0bde90ffc190a96c2ff,"[Process Management, Compliance, Künstliche In...","[Schreiben von Forschungsanträgen, Denken wie ...",[],2025-08-20 11:09:40
45,13,2467,68907a6e87cf5fec60dc8107,68a5adb8e90ffc190a96c30b,68907a6e87cf5fec60dc8107,Shrek's Donkey,68a5adb8e90ffc190a96c30a,Reviewer,"The AI agent serves as a reviewer, specializin...",68a5a0bde90ffc190a96c2ff,"[Process Management, Compliance, Künstliche In...","[Fragen stellen mit dem Ziel, Lücken in besteh...",[],2025-08-20 11:12:56
49,14,2471,6896071ee90ffc190a96c285,689e2470e90ffc190a96c2e4,6896071ee90ffc190a96c285,Grammar,689e2470e90ffc190a96c2e3,Grammar Checker,"The AI agent serves as a Grammar Checker, spec...",689e22d5e90ffc190a96c2e0,"[Punctuation Knowledge, Content Structure, Spe...","[Proofreading, Text Correction, Cut text, Stor...",[],2025-08-14 18:01:20
50,14,2471,6896071ee90ffc190a96c285,689e24b5e90ffc190a96c2e6,6896071ee90ffc190a96c285,Fact Checker,689e24b5e90ffc190a96c2e5,Fact checking,The AI agent is primarily responsible for fact...,689e22d5e90ffc190a96c2e0,"[Information Verification, Fact Analysis, Sour...","[Source Assessment, Cross Referencing, Text ou...",[],2025-08-14 18:02:29

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,user_id,agent_id,...,agent.behavior.settings.time_trigger.timeOfDay,agent.behavior.settings.time_trigger.eachMinutes,agent.behavior.settings.time_trigger.maxTimesPerDay,agent.behavior.settings.time_trigger.timeAfterTyping,agent.behavior.settings.ownership_area,agent.behavior.settings.context_trigger,agent.behavior.settings.text_operations,agent.behavior.ownership_level,agent.author_id,agent.is_preset
0,276482.0,2025-03-09 20:39:33.642000,1374,"{""agent"": {""id"": ""67cdfc85285fac3f07bcf5cf"", ""...",AGENT_SAVE,34ebd4a3-80f9-4249-8012-c3c657ee60df,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'agent': {'id': '67cdfc85285fac3f07bcf5cf', '...",67cdfa30285fac3f07bcf5cc,67cdfc85285fac3f07bcf5cf,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67cdfa30285fac3f07bcf5cc,False
1,276514.0,2025-03-09 20:49:56.576000,1374,"{""agent"": {""id"": ""67cdfef4285fac3f07bcf5d3"", ""...",AGENT_SAVE,9e16a790-e74a-4bfc-aefa-bf081df12634,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'agent': {'id': '67cdfef4285fac3f07bcf5d3', '...",67cdfa30285fac3f07bcf5cc,67cdfef4285fac3f07bcf5d3,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67cdfa30285fac3f07bcf5cc,False
2,277485.0,2025-03-10 08:39:45.213000,1380,"{""agent"": {""id"": ""67cea551285fac3f07bcf604"", ""...",AGENT_SAVE,2782d4d1-f743-4c3e-8c4b-6de0dd2545f6,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'agent': {'id': '67cea551285fac3f07bcf604', '...",67ce9cb4285fac3f07bcf5ec,67cea551285fac3f07bcf604,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67ce9cb4285fac3f07bcf5ec,False
3,278321.0,2025-03-15 19:45:20.151000,1387,"{""agent"": {""id"": ""67d5d8cf0b9539e69a3a86df"", ""...",AGENT_SAVE,f47e1726-109f-423a-947e-8a94dd615cb2,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'agent': {'id': '67d5d8cf0b9539e69a3a86df', '...",67d5d8120b9539e69a3a86d7,67d5d8cf0b9539e69a3a86df,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d5d8120b9539e69a3a86d7,False
4,278574.0,2025-03-17 14:19:26.040000,1388,"{""agent"": {""id"": ""67d82f6dedfe680c1b0f164a"", ""...",AGENT_SAVE,f0756605-541b-4c63-9b9b-d397978f2369,3b49f849-3081-4478-81ce-d65450662c47,"{'agent': {'id': '67d82f6dedfe680c1b0f164a', '...",67d82dc4edfe680c1b0f1642,67d82f6dedfe680c1b0f164a,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d82dc4edfe680c1b0f1642,False
5,278595.0,2025-03-17 14:20:38.636000,1389,"{""agent"": {""id"": ""67d82fbfedfe680c1b0f164e"", ""...",AGENT_SAVE,481f10b4-8bf1-4d59-bf52-4daa60b068d7,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'agent': {'id': '67d82fbfedfe680c1b0f164e', '...",67d82e0aedfe680c1b0f1643,67d82fbfedfe680c1b0f164e,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,67d82e0aedfe680c1b0f1643,False
6,279971.0,2025-07-28 13:12:02.272000,2456,"{""agent"": {""id"": ""6887772287cf5fec60dc8036"", ""...",AGENT_SAVE,743dbfa0-248b-4732-992a-e57f887aa5c8,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'agent': {'id': '6887772287cf5fec60dc8036', '...",68835b0587cf5fec60dc8020,6887772287cf5fec60dc8036,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,68835b0587cf5fec60dc8020,False
7,280728.0,2025-07-29 11:54:12.648000,2460,"{""agent"": {""id"": ""6888b66487cf5fec60dc806d"", ""...",AGENT_SAVE,d67f0275-dc5e-494c-85fe-c8b3848e8d20,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'agent': {'id': '6888b66487cf5fec60dc806d', '...",6887b97087cf5fec60dc8060,6888b66487cf5fec60dc806d,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6887b97087cf5fec60dc8060,False
8,281000.0,2025-07-29 13:16:31.760000,2459,"{""agent"": {""id"": ""6888c9af87cf5fec60dc8081"", ""...",AGENT_SAVE,5d2ce301-ed3e-4da6-96c2-ace4922d9ede,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'agent': {'id': '6888c9af87cf5fec60dc8081', '...",6888bbce87cf5fec60dc8072,6888c9af87cf5fec60dc8081,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6888bbce87cf5fec60dc8072,False
9,281422.0,2025-07-31 08:34:46.364000,2463,"{""agent"": {""id"": ""688b2aa687cf5fec60dc80b3"", ""...",AGENT_SAVE,c9c3fd1d-9afc-48fd-8526-276f44e3c3e0,38811499-e7ca-453e-a57b-86c5dcdee514,"{'agent': {'id': '688b2aa687cf5fec60dc80b3', '...",6889e71f87cf5fec60dc8094,688b2aa687cf5fec60dc80b3,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6889e71f87cf5fec60dc8094,False
10,281501.0,2025-07-31 14:36:27.527000,2457,"{""agent"": {""id"": ""688b7f6b87cf5fec60dc80b7"", ""...",AGENT_SAVE,b5cc537c-fade-4196-bbc4-5465fffbc5cf,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'agent': {'id': '688b7f6b87cf5fec60dc80b7', '...",688b1c7887cf5fec60dc80b0,688b7f6b87cf5fec60dc80b7,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,688b1c7887cf5fec60dc80b0,False
11,282066.0,2025-07-31 21:19:25.551000,2461,"{""agent"": {""id"": ""688bdddd87cf5fec60dc80d6"", ""...",AGENT_SAVE,e25d897a-561f-4685-9604-598b06713640,46820311-be03-4d2e-b993-90ac3bec3c92,"{'agent': {'id': '688bdddd87cf5fec60dc80d6', '...",6888eec887cf5fec60dc8085,688bdddd87cf5fec60dc80d6,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,6888eec887cf5fec60dc8085,False
12,282574.0,2025-08-13 07:24:19.760000,2469,"{""agent"": {""id"": ""689c3da3e90ffc190a96c28f"", ""...",AGENT_SAVE,3f96497e-e4a0-4f46-9784-68fb1488a9a6,63e04882-b933-435f-b84b-7a638b9c5ae8,"{'agent': {'id': '689c3da3e90ffc190a96c28f', '...",689c3c25e90ffc190a96c28b,689c3da3e90ffc190a96c28f,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,689c3c25e90ffc190a96c28b,False
13,282896.0,2025-08-14 18:01:20.523000,2471,"{""agent"": {""id"": ""689e2470e90ffc190a96c2e4"", ""...",AGENT_SAVE,79f1c37f-d0e7-40c4-88cf-e2ceb322b854,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'agent': {'id': '689e2470e90ffc190a96c2e4', '...",689e22d5e90ffc190a96c2e0,689e2470e90ffc190a96c2e4,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,689e22d5e90ffc190a96c2e0,False
14,282906.0,2025-08-14 18:02:29.399000,2471,"{""agent"": {""id"": ""689e24b5e90ffc190a96c2e6"", ""...",AGENT_SAVE,b1efbe38-a7cb-491e-97e7-23525307752e,41b03f59-088a-4ca7-b174-44980d1d8d78,"{'agent': {'id': '689e24b5e90ffc190a96c2e6', '...",689e22d5e90ffc190a96c2e0,689e24b5e90ffc190a96c2e6,...,[],,,2,DOCUMENT,None,[ADDITION],ASSISTANT,689e22d5e90ffc190a96c2e0,False

    user  group_id  time_percentage
1   1374         3         0.903236
2   1374         3         1.851329
4   1383         4         0.017803
7   1385         4         0.019302
8   1387         5         6.514847
9   1387         5         7.133341
10  1387         5         7.380739
11  1387         5        11.339102
12  1388         6        11.945436
15  1389         6        14.433102
18  2453         8         1.706089
25  2459        10         0.166948
26  2459        10         1.714958
29  2463        11         4.100312

35.8974358974359

    user  group_id  time_percentage
13  1388         6        47.955912
30  2463        11        29.899162
37  2471        14        38.039462
38  2471        14        41.594316

10.256410256410257

    user  group_id  time_percentage
14  1388         6        57.906575
23  2464         9        50.138871
31  2468        12        61.167236
32  2468        12        61.232927
33  2469        12        60.042439

12.820512820512821

    user  group_id  time_percentage
0   1380         1        94.858051
3   1374         3        89.911392
5   1383         4        99.853937
6   1384         4        95.625350
16  2456         7        76.060219
17  2460         7        99.142031
19  2453         8        98.990493
20  2453         8        99.064036
21  2453         8        99.553481
22  2461         9        99.280493
24  2457         9        86.795376
27  2459        10        99.697344
28  2465        10       174.529369

33.333333333333336