In [34]:
import os
import pandas as pd
import json
from datetime import datetime

In [35]:
def transform_time(df, col="time"):
    format = '%Y-%m-%d %H:%M:%S.%f'
    if col == 'time':
        df['time'] = df['time'].apply(lambda x: datetime.strptime(x, format))
    else:
        df[col] = df[col].apply(lambda x: datetime.strptime(x, format))
    return df

def second_difference(d2, d1):
    format = '%Y-%m-%d %H:%M:%S.%f'
    d2 = datetime.strptime(d2, format)
    d1 = datetime.strptime(d1, format)
    return (d2 - d1).seconds

def minutes_difference(d2, d1):
    return second_difference(d2, d1) / 60

In [36]:
participants_groups = {
    "1": {"users": [1379, 1380], "user_ids": ['67ce982f285fac3f07bcf5e7', '67ce9cb4285fac3f07bcf5ec'], "documents": ["67ce983b285fac3f07bcf5e8"]},
    "2": {"users": [1376, 1377], "user_ids": ['67cb6627285fac3f07bcf59b', '67cb6623285fac3f07bcf59a'], "documents": ["67c97527285fac3f07bcf587"]},
    "3": {"users": [1378, 1374], "user_ids": ['67cc9f69285fac3f07bcf5c8', '67cdfa30285fac3f07bcf5cc'], "documents": ["67c88f88285fac3f07bcf585"]},
    "4": {"users": [1383, 1384, 1385], "user_ids": ['67bc761a7a670b68746905a0', '67d444dd0b9539e69a3a86bb', '67bc43607a670b6874690577'], "documents": ["67d43b390b9539e69a3a86b9"]},
    "5": {"users": [1387, 1390], "user_ids": ['67d5d8120b9539e69a3a86d7', '67e18e95edfe680c1b0f169f'], "documents": ["67d5d8160b9539e69a3a86d8"]},
    "6": {"users": [1388, 1389], "user_ids": ['67d82dc4edfe680c1b0f1642', '67d82e0aedfe680c1b0f1643'], "documents": ["67d08e87285fac3f07bcf64b"]},
    "7": {"users": [2456, 2460], "user_ids": ['68835b0587cf5fec60dc8020', '6887b97087cf5fec60dc8060'], "documents": ["68833fd687cf5fec60dc801d"]},
    "8": {"users": [2453, 2455], "user_ids": ['687de5d187cf5fec60dc7fef', '6880e0f187cf5fec60dc7ffe'], "documents": ["6879e8fd87cf5fec60dc7fe1"]},
    "9": {"users": [2461, 2464, 2457], "user_ids": ['6888eec887cf5fec60dc8085', '688a52ad87cf5fec60dc8096', '688b1c7887cf5fec60dc80b0'], "documents": ["688364bf87cf5fec60dc8026"]},
    "10": {"users": [2459, 2465], "user_ids": ['6888bbce87cf5fec60dc8072', '688bdb6387cf5fec60dc80d0'], "documents": ["6877c26e87cf5fec60dc7fda"]},
    "11": {"users": [2463, 2475], "user_ids": ['6889e71f87cf5fec60dc8094', '68a75365ecc07d2944852275'], "documents": ["6889e57087cf5fec60dc8092"]},
    "12": {"users": [2468, 2469], "user_ids": ['6898407be90ffc190a96c287', '689c3c25e90ffc190a96c28b'], "documents": ["688c6add87cf5fec60dc80ef"]},
    "13": {"users": [2467, 2476], "user_ids": ['68a5a0bde90ffc190a96c2ff', '68a59766e90ffc190a96c2f4'], "documents": ["68907a6e87cf5fec60dc8107"]},
    "14": {"users": [2470, 2471], "user_ids": ['689e2181e90ffc190a96c2df', '689e22d5e90ffc190a96c2e0'], "documents": ["6896071ee90ffc190a96c285"]},
} 


participants_id = [1378, 1374, 1376, 1377, 1379, 1384, 1383, 1385, 1387, 1388, 1389, 1390, 1380]
participants_id_wo_directusers = [1378, 1374, 1376, 1377, 1379, 1387, 1388, 1389, 1390, 1380] #removed 1383 1384 1385
participants_id_study_extended = [2456, 2460, 2453, 2455, 2461, 2464, 2457, 2459, 2465, 2463, 2475, 2468, 2469, 2467, 2476, 2470, 2471]

# join lists
participants_id = participants_id + participants_id_study_extended
participants_id_wo_directusers = participants_id_wo_directusers + participants_id_study_extended

In [37]:
finished_participants_file = '03_finished_participants.csv'
finished_participants = pd.read_csv(os.path.join('output', 'intermediate', finished_participants_file), sep='\t')
display(finished_participants.head())

,Unnamed: 0.1,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
0,0,164,276174.0,cb251ecc-b22b-4ef9-af15-415f3ab90c25,Prototype,2025-03-07 21:32:17.982000,USER_AGENT,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,NaN
1,1,166,276176.0,17b21821-b077-4b06-9db8-b341d36d0301,Prototype,2025-03-07 21:33:27.678000,USER_LOGIN,"{""username"": ""wolfova"", ""participant_token"": ""...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'username': 'wolfova', 'participant_token': '...",NaN
2,2,171,276181.0,c55551a8-7950-417a-aa64-9c323aaee006,Prototype,2025-03-07 21:33:49.699000,DOCUMENT_JOIN,"{""user_id"": ""67cb6627285fac3f07bcf59b"", ""usern...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'user_id': '67cb6627285fac3f07bcf59b', 'usern...",67c97527285fac3f07bcf587
3,3,172,276182.0,65ca58d2-568f-4b16-af2d-718c2e633485,Prototype,2025-03-07 21:33:49.808000,DOCUMENT_VIEW,"{""user_id"": ""67cb6627285fac3f07bcf59b"", ""usern...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'user_id': '67cb6627285fac3f07bcf59b', 'usern...",67c97527285fac3f07bcf587
4,4,173,276183.0,20b1b819-a53b-4619-87e9-fe11dcba2855,Prototype,2025-03-07 21:33:59.815000,DOCUMENT_TEXT_UPDATE,"{""text"": ""<p>Write your text here</p>"", ""user_...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'text': '<p>Write your text here</p>', 'user_...",67c97527285fac3f07bcf587

In [38]:
# method to read mongo database collection
def read_collection(file_path):

    # Step 1: Try reading as a JSON array
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError:
        # Step 2: If it's newline-delimited JSON
        with open(file_path, 'r', encoding='utf-8') as f:
            data = [json.loads(line) for line in f]

    # Step 3: Clean MongoDB special fields ($oid, $date, etc.)
    def extract_mongo_specials(obj):
        if isinstance(obj, dict):
            if "$oid" in obj:
                return obj["$oid"]
            if "$date" in obj:
                return obj["$date"]
            return {k: extract_mongo_specials(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [extract_mongo_specials(i) for i in obj]
        return obj

    cleaned_data = [extract_mongo_specials(doc) for doc in data]

    # Step 4: Flatten into DataFrame
    df = pd.json_normalize(cleaned_data)

    return df

In [39]:
# read agents collection
file_path = os.path.join('input/database', 'agent.json')
agents_df = read_collection(file_path)

# read tasks collection
task_path = os.path.join('input/database', 'task.json')
task_df = read_collection(task_path)

In [40]:
# parse generic event

def parse_json_field(event_df, json_field):
    #transform data from str values to dict values
    event_df[json_field + "_parsed"] = event_df[json_field].apply(json.loads)
    #build dataframe from dict values
    event_json_df = pd.json_normalize(event_df[json_field + "_parsed"])
    #reset indexes to concat the dataframes along axis 1 (1:1)
    event_df.reset_index(drop=True, inplace=True)
    event_json_df.reset_index(drop=True, inplace=True)
    return event_json_df

def parse_generic_event(generic_interactions, event = None):
    if event:
        if isinstance(event, list):
            event_df = generic_interactions[generic_interactions['event'].isin(event)]
        else:
            event_df = generic_interactions[generic_interactions['event'] == event]
    else:
        event_df = generic_interactions.copy()
    event_df = event_df[['id', 'time', 'participant_id', 'data', 'event', 'event_uuid', 'participant_token']]
    event_df['time'] = event_df['time'].astype(str)
    event_json_df = parse_json_field(event_df, 'data')
    return pd.concat([event_df, event_json_df], axis=1)

def parse_keyboard_event(keyboard_interactions):
    event_df = keyboard_interactions.copy()
    event_df['time'] = event_df['time'].astype(str)
    event_json_df = parse_json_field(event_df, 'meta_data')
    return pd.concat([event_df, event_json_df], axis=1)

In [41]:
# Removed interaction events that happened while interviewing (task has been completed already)
def remove_events_while_interviewing(df, remove_arr, time_field = "from_time"):
    format = '%Y-%m-%d %H:%M:%S.%f'
    dfn = df.copy()

    for t in remove_arr:
        participant_id = t[0]
        time = t[1]
        time = datetime.strptime(time, format)

        participant_mask = dfn['participant_id'] == participant_id
        time_mask = dfn[time_field] > time

        entries = dfn[participant_mask & time_mask]
        #display(entries.index)
        dfn = dfn.drop(entries.index)

    return dfn

In [42]:
# Convert to a list of rows
rows = []
for group_id, group in participants_groups.items():
    for i, user in enumerate(group["users"]):
        rows.append({
            "group_id": int(group_id),
            "user": user,
            "user_id": group["user_ids"][i],
            "document": group["documents"][0]
        })

# Create DataFrame our of participants_groups
groups_df = pd.DataFrame(rows)

display(groups_df)

    group_id  user                   user_id                  document
0          1  1379  67ce982f285fac3f07bcf5e7  67ce983b285fac3f07bcf5e8
1          1  1380  67ce9cb4285fac3f07bcf5ec  67ce983b285fac3f07bcf5e8
2          2  1376  67cb6627285fac3f07bcf59b  67c97527285fac3f07bcf587
3          2  1377  67cb6623285fac3f07bcf59a  67c97527285fac3f07bcf587
4          3  1378  67cc9f69285fac3f07bcf5c8  67c88f88285fac3f07bcf585
5          3  1374  67cdfa30285fac3f07bcf5cc  67c88f88285fac3f07bcf585
6          4  1383  67bc761a7a670b68746905a0  67d43b390b9539e69a3a86b9
7          4  1384  67d444dd0b9539e69a3a86bb  67d43b390b9539e69a3a86b9
8          4  1385  67bc43607a670b6874690577  67d43b390b9539e69a3a86b9
9          5  1387  67d5d8120b9539e69a3a86d7  67d5d8160b9539e69a3a86d8
10         5  1390  67e18e95edfe680c1b0f169f  67d5d8160b9539e69a3a86d8
11         6  1388  67d82dc4edfe680c1b0f1642  67d08e87285fac3f07bcf64b
12         6  1389  67d82e0aedfe680c1b0f1643  67d08e87285fac3f07bcf64b
13         7  2456  68835b0587cf5fec60dc8020  68833fd687cf5fec60dc801d
14         7  2460  6887b97087cf5fec60dc8060  68833fd687cf5fec60dc801d
15         8  2453  687de5d187cf5fec60dc7fef  6879e8fd87cf5fec60dc7fe1
16         8  2455  6880e0f187cf5fec60dc7ffe  6879e8fd87cf5fec60dc7fe1
17         9  2461  6888eec887cf5fec60dc8085  688364bf87cf5fec60dc8026
18         9  2464  688a52ad87cf5fec60dc8096  688364bf87cf5fec60dc8026
19         9  2457  688b1c7887cf5fec60dc80b0  688364bf87cf5fec60dc8026
20        10  2459  6888bbce87cf5fec60dc8072  6877c26e87cf5fec60dc7fda
21        10  2465  688bdb6387cf5fec60dc80d0  6877c26e87cf5fec60dc7fda
22        11  2463  6889e71f87cf5fec60dc8094  6889e57087cf5fec60dc8092
23        11  2475  68a75365ecc07d2944852275  6889e57087cf5fec60dc8092
24        12  2468  6898407be90ffc190a96c287  688c6add87cf5fec60dc80ef
25        12  2469  689c3c25e90ffc190a96c28b  688c6add87cf5fec60dc80ef
26        13  2467  68a5a0bde90ffc190a96c2ff  68907a6e87cf5fec60dc8107
27        13  2476  68a59766e90ffc190a96c2f4  68907a6e87cf5fec60dc8107
28        14  2470  689e2181e90ffc190a96c2df  6896071ee90ffc190a96c285
29        14  2471  689e22d5e90ffc190a96c2e0  6896071ee90ffc190a96c285

## Document tasks

This analysis relies only on data logged from events because of two reasons:

1. Tasks in the DB do not have a creation date
2. The event logs show created tasks that did not appear in the DB. These tasks were most likely deleted by users right after the study.

As a result data from group 4 is excluded.

DB data: Tasks per group
[G] Number of tasks created

In [43]:
# tasks per document and group
study_tasks_merged = pd.merge(groups_df, task_df,  left_on=['document', 'user_id'], right_on=['document_id', 'author_id'], how='left')

study_tasks = study_tasks_merged[['group_id', 'user', 'document', '_id', 'assignee_ids', 'description',
       'document_id', 'interaction_type', 'is_shortcut', 'author_id', 'progress', 
        'title', 'advanced_trigger_settings.interaction_trigger']]
study_tasks = study_tasks.drop_duplicates(subset=['document', "_id"])
study_tasks = study_tasks.dropna(subset=['_id'])

display(study_tasks[study_tasks["group_id"] == 8])
display(study_tasks)
display(study_tasks['group_id'].value_counts().describe())

,group_id,user,document,_id,assignee_ids,description,document_id,interaction_type,is_shortcut,author_id,progress,title,advanced_trigger_settings.interaction_trigger
35,8,2453,6879e8fd87cf5fec60dc7fe1,6880e33587cf5fec60dc8004,"[6880e03f87cf5fec60dc7ffb, 6880e0d087cf5fec60d...",Critique the discussion section and give your per,6879e8fd87cf5fec60dc7fe1,MANUAL,False,687de5d187cf5fec60dc7fef,"[{'created_time': 1753277347166, 'selected_tex...",Discussion Section Critique,EACH_MINUTES

,group_id,user,document,_id,assignee_ids,description,document_id,interaction_type,is_shortcut,author_id,progress,title,advanced_trigger_settings.interaction_trigger
0,1,1379,67ce983b285fac3f07bcf5e8,67ce9934285fac3f07bcf5ea,[ai-author],We nned to write an essay together about the p...,67ce983b285fac3f07bcf5e8,MANUAL,False,67ce982f285fac3f07bcf5e7,[],AI Pros and Cons Essay,EACH_MINUTES
1,1,1379,67ce983b285fac3f07bcf5e8,67cea2a4285fac3f07bcf5f8,[ai-author],Check the grammar of the text,67ce983b285fac3f07bcf5e8,AUTONOMOUS_COMMENT,False,67ce982f285fac3f07bcf5e7,"[{'created_time': 1741595328026, 'selected_tex...",Proofreading,EACH_MINUTES
2,1,1380,67ce983b285fac3f07bcf5e8,67cea021285fac3f07bcf5f6,[ai-author],Make the text shorter,67ce983b285fac3f07bcf5e8,MANUAL,True,67ce9cb4285fac3f07bcf5ec,[],Shorten the Text,EACH_MINUTES
3,1,1380,67ce983b285fac3f07bcf5e8,67cea0e1285fac3f07bcf5f7,[ai-author],Give it more scientific and professional style.,67ce983b285fac3f07bcf5e8,MANUAL,True,67ce9cb4285fac3f07bcf5ec,[],Enhance Professional Tone,EACH_MINUTES
4,2,1376,67c97527285fac3f07bcf587,67cb687a285fac3f07bcf5a4,[ai-author],write the part where u talk about pros of AI,67c97527285fac3f07bcf587,MANUAL,False,67cb6627285fac3f07bcf59b,"[{'created_time': 1741383860335, 'selected_tex...",Pros of AI,EACH_MINUTES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,13,2467,68907a6e87cf5fec60dc8107,68a5b9e6e90ffc190a96c31f,[68a5acf4e90ffc190a96c309],"Verbessere (nur!!) die Formulierung, ohne den ...",68907a6e87cf5fec60dc8107,MANUAL,True,68a5a0bde90ffc190a96c2ff,"[{'created_time': 1755697070379, 'selected_tex...",Formulierung verbessern,EACH_MINUTES
60,13,2476,68907a6e87cf5fec60dc8107,68a5d43ae90ffc190a96c32c,[68a59949e90ffc190a96c2f7],Looking cool joker!,68907a6e87cf5fec60dc8107,MANUAL,False,68a59766e90ffc190a96c2f4,"[{'created_time': 1755698261822, 'selected_tex...",Cool Joker Look,EACH_MINUTES
61,13,2476,68907a6e87cf5fec60dc8107,68a5d754e90ffc190a96c335,[68a5d73ee90ffc190a96c334],vervollständigen,68907a6e87cf5fec60dc8107,MANUAL,True,68a59766e90ffc190a96c2f4,"[{'created_time': 1755699561177, 'selected_tex...",Aufgaben vervollständigen,EACH_MINUTES
62,13,2476,68907a6e87cf5fec60dc8107,68a5dbe6e90ffc190a96c33f,[68a5acf4e90ffc190a96c309],bewerte und korrigiere die struktur und den sp...,68907a6e87cf5fec60dc8107,MANUAL,False,68a59766e90ffc190a96c2f4,[],Antragsstruktur und Sprache korrigieren,EACH_MINUTES
64,14,2471,6896071ee90ffc190a96c285,689e28e7e90ffc190a96c2ec,"[ai-author, 689e2470e90ffc190a96c2e4, 689e24b5...","Make the text more interesting to read, and a ...",6896071ee90ffc190a96c285,MANUAL,False,689e22d5e90ffc190a96c2e0,"[{'created_time': 1755195709128, 'selected_tex...",Enhance Deutsche Telekom Text,EACH_MINUTES

count    14.000000
mean      4.357143
std       1.984833
min       1.000000
25%       4.000000
50%       4.000000
75%       5.750000
max       8.000000
Name: count, dtype: float64

We are going to remove some events that happened at the very end of the study, i.e. while interviewing the participants

In [44]:
# remove events that happened at the interview
#participant_id, time
remove_events_starting_from = [
    (1374, '2025-03-10 14:44:50.308'),
    #(1374, '2025-03-09 22:18:40.957'), # last comment approve
    #(1378, '2025-03-08 20:30:28.499'),
    (1388, '2025-03-17 15:12:56.935'), # last suggestion view detail
    (1389, '2025-03-17 15:00:33.242'),
    (1387, '2025-03-15 20:09:12.496'), # last comment approve
    (1390, '2025-03-15 20:09:12.496'), # this participant reported that they did not collaborate
    (2456, '2025-07-28 18:04:03.337'), # last task view close
    (2453, '2025-07-21 09:45:35.067'), # last agent view close 
    (2455, '2025-07-23 13:53:19.984'), # last suggestion view detail
    (2461, '2025-07-31 21:50:47.107'), # last suggestion take over
    (2464, '2025-07-30 19:28:28.289'), # last comment approve
    (2457, '2025-07-31 15:31:45.052'), # last reply post
    (2459, '2025-07-29 13:23:03.445'), # last suggestion c2c
    (2465, '2025-07-31 21:20:40.047'), # last suggestion view detail
    (2467, '2025-08-20 16:21:49.455'), # last reply post
    (2476, '2025-08-20 16:15:56.221') # last comment related event
]

Parse TASK_CREATED events

In [45]:
# get created tasks, add group_id

parsed_task_created_df = parse_generic_event(finished_participants[finished_participants["event"] == "TASK_CREATED"])

parsed_task_created_df = pd.merge(parsed_task_created_df, groups_df,  left_on=['participant_id'], right_on=['user'], how='left')
parsed_task_created_df = transform_time(parsed_task_created_df)

parsed_task_created_df =  remove_events_while_interviewing(parsed_task_created_df, remove_events_starting_from, 'time')

display(parsed_task_created_df)

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,user_id_x,username,...,task.author_id,task.description,task.is_shortcut,task.assignee_ids,task.interaction_type,task.advanced_trigger_settings.interaction_trigger,group_id,user,user_id_y,document
0,276233.0,2025-03-07 21:42:15.163,1377,"{""task"": {""id"": ""67cb6837285fac3f07bcf59f"", ""t...",TASK_CREATED,db778a6d-ecea-48ad-95af-34ba3f05a1bd,2aac5afe-a3af-4135-a1a3-78adf87ae9d8,"{'task': {'id': '67cb6837285fac3f07bcf59f', 't...",67cb6623285fac3f07bcf59a,adambokun,...,67cb6623285fac3f07bcf59a,Write intro for the essay,False,[ai-author],MANUAL,EACH_MINUTES,2,1377,67cb6623285fac3f07bcf59a,67c97527285fac3f07bcf587
1,276268.0,2025-03-07 21:43:22.511,1376,"{""task"": {""id"": ""67cb687a285fac3f07bcf5a4"", ""t...",TASK_CREATED,84017059-2690-4936-980b-f5333f85d934,a5bbafd1-4ef0-49e4-95bd-65170953633c,"{'task': {'id': '67cb687a285fac3f07bcf5a4', 't...",67cb6627285fac3f07bcf59b,wolfova,...,67cb6627285fac3f07bcf59b,write the part where u talk about pros of AI,False,[ai-author],MANUAL,EACH_MINUTES,2,1376,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587
2,276317.0,2025-03-07 21:45:35.824,1377,"{""task"": {""id"": ""67cb68ff285fac3f07bcf5a8"", ""t...",TASK_CREATED,4e191fcc-fdea-4024-8ab9-2c3dacf44b3b,2aac5afe-a3af-4135-a1a3-78adf87ae9d8,"{'task': {'id': '67cb68ff285fac3f07bcf5a8', 't...",67cb6623285fac3f07bcf59a,adambokun,...,67cb6623285fac3f07bcf59a,Write cons of AI,False,[ai-author],AUTONOMOUS_COMMENT,EACH_MINUTES,2,1377,67cb6623285fac3f07bcf59a,67c97527285fac3f07bcf587
3,276335.0,2025-03-07 21:46:05.445,1376,"{""task"": {""id"": ""67cb691d285fac3f07bcf5ac"", ""t...",TASK_CREATED,d2250740-98b2-4a96-81e0-e95c9ec2aad6,a5bbafd1-4ef0-49e4-95bd-65170953633c,"{'task': {'id': '67cb691d285fac3f07bcf5ac', 't...",67cb6627285fac3f07bcf59b,wolfova,...,67cb6627285fac3f07bcf59b,write the zusamenfassung for our essay based o...,False,[ai-author],MANUAL,EACH_MINUTES,2,1376,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587
4,276370.0,2025-03-07 21:48:56.770,1376,"{""task"": {""id"": ""67cb69c8285fac3f07bcf5b2"", ""t...",TASK_CREATED,3f7fdb58-c32d-47a8-bbfe-36e1b56950cf,a5bbafd1-4ef0-49e4-95bd-65170953633c,"{'task': {'id': '67cb69c8285fac3f07bcf5b2', 't...",67cb6627285fac3f07bcf59b,wolfova,...,67cb6627285fac3f07bcf59b,can u edit our text as the scientific paper wi...,False,[ai-author],MANUAL,EACH_MINUTES,2,1376,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587
5,276488.0,2025-03-09 20:42:12.823,1374,"{""task"": {""id"": ""67cdfd24285fac3f07bcf5d1"", ""t...",TASK_CREATED,f481ec92-ac67-4137-b0fc-3b5544241b6d,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67cdfd24285fac3f07bcf5d1', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,Read the written part of text. Highlight gramm...,False,[67cdfc85285fac3f07bcf5cf],AUTONOMOUS_COMMENT,DOCUMENT_SAVE,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
6,276522.0,2025-03-09 20:51:40.848,1374,"{""task"": {""id"": ""67cdff5c285fac3f07bcf5d4"", ""t...",TASK_CREATED,6366f36d-2e03-4675-b9ad-401af89c86dc,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67cdff5c285fac3f07bcf5d4', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,Check the selected text and provide some scien...,True,[67cdfef4285fac3f07bcf5d3],MANUAL,EACH_MINUTES,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
7,276525.0,2025-03-09 20:59:38.568,1374,"{""task"": {""id"": ""67ce013a285fac3f07bcf5d6"", ""t...",TASK_CREATED,65e32235-d117-4745-8178-fabb272347d2,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67ce013a285fac3f07bcf5d6', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,Considering the topic and the latest available...,False,[67cdfc85285fac3f07bcf5cf],AUTONOMOUS_COMMENT,MINUTES_INACTIVITY,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
8,276720.0,2025-03-10 07:48:04.549,1379,"{""task"": {""id"": ""67ce9934285fac3f07bcf5ea"", ""t...",TASK_CREATED,5c7f52ba-11d9-49d0-82fe-f80ae474602d,6573f86e-0207-4286-b036-a83f25a630c3,"{'task': {'id': '67ce9934285fac3f07bcf5ea', 't...",67ce982f285fac3f07bcf5e7,galina.akhunzhanova@uni-bayreuth.de,...,67ce982f285fac3f07bcf5e7,We nned to write an essay together about the p...,False,[ai-author],MANUAL,EACH_MINUTES,1,1379,67ce982f285fac3f07bcf5e7,67ce983b285fac3f07bcf5e8
9,276834.0,2025-03-10 08:07:29.198,1380,"{""task"": {""id"": ""67ce9dc1285fac3f07bcf5ed"", ""t...",TASK_CREATED,ac8ce41a-2924-423c-8391-5836ad505c5c,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'task': {'id': '67ce9dc1285fac3f07bcf5ed', 't...",67ce9cb4285fac3f07bcf5ec,mrnexeon,...,67ce9cb4285fac3f07bcf5ec,Generate essay for Health and Wellness in the ...,False,[ai-author],MANUAL,EACH_MINUTES,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8
10,277090.0,2025-03-10 08:17:37.082,1380,"{""task"": {""id"": ""67cea021285fac3f07bcf5f6"", ""t...",TASK_CREATED,cbb15f70-59bd-4597-a3c0-7e7e23659967,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'task': {'id': '67cea021285fac3f07bcf5f6', 't...",67ce9cb4285fac3f07bcf5ec,mrnexeon,...,67ce9cb4285fac3f07bcf5ec,Make the text shorter,True,[ai-author],MANUAL,EACH_MINUTES,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8
11,277154.0,2025-03-10 08:20:48.986,1380,"{""task"": {""id"": ""67cea0e1285fac3f07bcf5f7"", ""t...",TASK_CREATED,3829f97d-7e6f-4338-97e9-8922ae639e46,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'task': {'id': '67cea0e1285fac3f07bcf5f7', 't...",67ce9cb4285fac3f07bcf5ec,mrnexeon,...,67ce9cb4285fac3f07bcf5ec,Give it more scientific and professional style.,True,[ai-author],MANUAL,EACH_MINUTES,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8
12,277296.0,2025-03-10 08:28:20.299,1379,"{""task"": {""id"": ""67cea2a4285fac3f07bcf5f8"", ""t...",TASK_CREATED,e5caab1f-f8c6-4c2c-a52f-651f5479ce57,6573f86e-0207-4286-b036-a83f25a630c3,"{'task': {'id': '67cea2a4285fac3f07bcf5f8', 't...",67ce982f285fac3f07bcf5e7,galina.akhunzhanova@uni-bayreuth.de,...,67ce982f285fac3f07bcf5e7,write a conclusion of the given text,False,[ai-author],MANUAL,EACH_MINUTES,1,1379,67ce982f285fac3f07bcf5e7,67ce983b285fac3f07bcf5e8
13,277627.0,2025-03-10 13:03:42.340,1374,"{""task"": {""id"": ""67cee32e285fac3f07bcf60e"", ""t...",TASK_CREATED,ee65bf1a-de89-40e0-95a2-f9e4920973b8,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67cee32e285fac3f07bcf60e', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,The agent should analyze the selected advantag...,True,[ai-author],MANUAL,EACH_MINUTES,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
14,278328.0,2025-03-15 19:45:48.555,1387,"{""task"": {""id"": ""67d5d8eb0b9539e69a3a86e0"", ""t...",TASK_CREATED,9c60b815-bf29-4c74-96c5-8a6fd424eccc,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'task': {'id': '67d5d8eb0b9539e69a3a86e0', 't...",67d5d8120b9539e69a3a86d7,Ilya School,...,67d5d8120b9539e69a3a86d7,Check the text,False,[67d5d8cf0b9539e69a3a86df],MANUAL,EACH_MINUTES,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8
15,278356.0,2025-03-15 19:48:19.303,1387,"{""task"": {""id"": ""67d5d9820b9539e69a3a86e4"", ""t...",TASK_CREATED,be2b7de6-1999-4a92-8b40-f1d6537f0177,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'task': {'id': '67d5d9820b9539e69a3a86e4', 't...",67d5d8120b9539e69a3a86d7,Ilya School,...,67d5d8120b9539e69a3a86d7,Check the language mistakes in the text,False,[67d5d88f0b9539e69a3a86dc],MANUAL,EACH_MINUTES,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8
16,278364.0,2025-03-15 19:49:02.993,1387,"{""task"": {""id"": ""67d5d9ae0b9539e69a3a86e7"", ""t...",TASK_CREATED,4ed7fd96-a7f3-4ad2-8e94-65c2e67f9fd7,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'task': {'id': '67d5d9ae0b9539e69a3a86e7', 't...",67d5d8120b9539e69a3a86d7,Ilya School,...,67d5d8120b9539e69a3a86d7,Check if the text flow is good and give counci...,True,[67d5d88b0b9539e69a3a86db],MANUAL,EACH_MINUTES,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8
17,278513.0,2025-03-15 20:09:10.218,1387,"{""task"": {""id"": ""67d5de650b9539e69a3a86f0"", ""t...",TASK_CREATED,924ec8a5-4324-4db5-b6a4-6867d5b15b9e,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'task': {'id': '67d5de650b9539e69a3a86f0', 't...",67d5d8120b9539e69a3a86d7,Ilya School,...,67d5d8120b9539e69a3a86d7,Give advices on how to name each paragraph and...,False,[67d5d88b0b9539e69a3a86db],MANUAL,EACH_MINUTES,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8
18,278531.0,2025-03-17 14:13:39.600,1388,"{""task"": {""id"": ""67d82e13edfe680c1b0f1644"", ""t...",TASK_CREATED,77838901-2c3d-479c-91bb-850b015aa782,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d82e13edfe680c1b0f1644', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,Write me a text about ai pros and cons,False,[ai-author],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
19,278585.0,2025-03-17 14:19:51.541,1388,"{""task"": {""id"": ""67d82f87edfe680c1b0f164b"", ""t...",TASK_CREATED,c0aa28e5-9f26-4920-9aaf-de824534ca92,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d82f87edfe680c1b0f164b', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,check the text find mistakes,False,[67d82f6dedfe680c1b0f164a],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
20,278651.0,2025-03-17 14:32:41.482,1389,"{""task"": {""id"": ""67d83292edfe680c1b0f164f"", ""t...",TASK_CREATED,fdf935f9-73dc-419a-89cf-b3f950e5c612,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'task': {'id': '67d83292edfe680c1b0f164f', 't...",67d82e0aedfe680c1b0f1643,Du-Al-Dos,...,67d82e0aedfe680c1b0f1643,add citations,False,[67d82fbfedfe680c1b0f164e],MANUAL,EACH_MINUTES,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b
21,278710.0,2025-03-17 14:39:49.958,1388,"{""task"": {""id"": ""67d83435edfe680c1b0f1656"", ""t...",TASK_CREATED,9c7b3a4f-4a1f-493d-892a-18915d1e876b,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d83435edfe680c1b0f1656', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,can you help with generating more ideas so the...,False,[67d83410edfe680c1b0f1655],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
22,278761.0,2025-03-17 14:42:24.175,1388,"{""task"": {""id"": ""67d834cfedfe680c1b0f165a"", ""t...",TASK_CREATED,137aed4c-6186-42f5-b049-c31301c23939,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d834cfedfe680c1b0f165a', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,"check the text, make it look good as an essay,...",False,[ai-author],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
23,278844.0,2025-03-17 14:45:55.066,1388,"{""task"": {""id"": ""67d835a2edfe680c1b0f165f"", ""t...",TASK_CREATED,72b3f17a-5387-41df-a594-8def8730ecaa,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d835a2edfe680c1b0f165f', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,delete everything what doesn´t make sense,False,[67d83558edfe680c1b0f165e],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
24,278896.0,2025-03-17 14:57:18.400,1389,"{""task"": {""id"": ""67d83857edfe680c1b0f1667"", ""t...",TASK_CREATED,e52d5be7-baf6-45f9-ba0b-ec659ae68459,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'task': {'id': '67d83857edfe680c1b0f1667', 't...",67d82e0aedfe680c1b0f1643,Du-Al-Dos,...,67d82e0aedfe680c1b0f1643,Add an introduction and a conclusion part. Add...,False,[ai-author],MANUAL,EACH_MINUTES,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b
25,278949.0,2025-03-17 15:07:40.309,1388,"{""task"": {""id"": ""67d83abbedfe680c1b0f166c"", ""t...",TASK_CREATED,9d4a5ac5-b70e-4a58-ad34-20b40a37d7f5,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d83abbedfe680c1b0f166c', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,help me make it prettier,False,[67d82f6dedfe680c1b0f164a],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
27,279983.0,2025-07-28 13:53:30.643,2456,"{""task"": {""id"": ""688780da87cf5fec60dc803b"", ""t...",TASK_CREATED,5e882802-f57f-45dc-9f35-87498c8bc093,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'task': {'id': '688780da87cf5fec60dc803b', 't...",68835b0587cf5fec60dc8020,Anass Q.,...,68835b0587cf5fec60dc8020,This is an Essay about Artificial intelligence...,False,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d
28,280037.0,2025-07-28 14:05:14.114,2456,"{""task"": {""id"": ""6887839a87cf5fec60dc803f"", ""t...",TASK_CREATED,41f9612d-3d83-48bb-bcd6-2057dccb71b2,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'task': {'id': '6887839a87cf5fec60dc803f', 't...",68835b0587cf5fec60dc8020,Anass Q.,...,68835b0587cf5fec60dc8020,"Oversee the provided text and make sure, it's ...",False,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d
29,280481.0,2025-07-28 17:58:50.790,2460,"{""task"": {""id"": ""6887ba5a87cf5fec60dc8061"", ""t...",TASK_CREATED,790ff8a7-497c-46fc-bc51-afc75fd6ec39,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6887ba5a87cf5fec60dc8061', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,make text shorter\n,False,[ai-author],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
30,280521.0,2025-07-28 18:00:41.738,2460,"{""task"": {""id"": ""6887bac987cf5fec60dc8062"", ""t...",TASK_CREATED,ed1db37e-3231-40c0-86db-79f77cfdc59a,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6887bac987cf5fec60dc8062', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,MAke it more literature based,False,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
31,280625.0,2025-07-29 11:46:53.865,2460,"{""task"": {""id"": ""6888b4ad87cf5fec60dc806a"", ""t...",TASK_CREATED,a354a782-7bd7-4b53-a551-057aa5a24415,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6888b4ad87cf5fec60dc806a', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,Add some interesting facts,True,[ai-author],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
32,280682.0,2025-07-29 11:51:13.438,2460,"{""task"": {""id"": ""6888b5b187cf5fec60dc806b"", ""t...",TASK_CREATED,afbcba64-39b7-4f39-b94c-6632d247039f,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6888b5b187cf5fec60dc806b', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,Summarize the text before,True,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
33,280903.0,2025-07-29 12:24:32.837,2459,"{""task"": {""id"": ""6888bd8087cf5fec60dc8074"", ""t...",TASK_CREATED,4d7f4220-fef6-4492-bd4c-265fd6ab08d8,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'task': {'id': '6888bd8087cf5fec60dc8074', 't...",6888bbce87cf5fec60dc8072,ainalinngeorges,...,6888bbce87cf5fec60dc8072,Create categories for planning a wedding,False,[6888bd4b87cf5fec60dc8073],MANUAL,EACH_MINUTES,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda
34,280924.0,2025-07-29 12:30:35.646,2459,"{""task"": {""id"": ""6888beeb87cf5fec60dc8077"", ""t...",TASK_CREATED,73feda0f-25da-4a8d-88c0-093c51356742,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'task': {'id': '6888beeb87cf5fec60dc8077', 't...",6888bbce87cf5fec60dc8072,ainalinngeorges,...,6888bbce87cf5fec60dc8072,make headers for the different categories of p...,False,[6888bd4b87cf5fec60dc8073],MANUAL,EACH_MINUTES,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda
35,281006.0,2025-07-29 13:17:32.275,2459,"{""task"": {""id"": ""6888c9ec87cf5fec60dc8082"", ""t...",TASK_CREATED,3cd89847-508c-4c44-a515-2ceb97372800,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'task': {'id': '6888c9ec87cf5fec60dc8082', 't...",6888bbce87cf5fec60dc8072,ainalinngeorges,...,6888bbce87cf5fec60dc8072,Highlight each item that needs to be purchased...,True,[6888c9af87cf5fec60dc8081],MANUAL,EACH_MINUTES,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda
36,281089.0,2025-07-29 15:57:28.484,2461,"{""task"": {""id"": ""6888ef6887cf5fec60dc8086"", ""t...",TASK_CREATED,2e3afa3b-f9de-4684-be0d-c571c532d6a4,46820311-be03-4d2e-b993-90ac3bec3c92,"{'task': {'id': '6888ef6887cf5fec60dc8086', 't...",6888eec887cf5fec60dc8085,vama00004,...,6888eec887cf5fec60dc8085,Write a blog in 1000 words about the given title,False,[ai-author],MANUAL,EACH_MINUTES,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026
37,281217.0,2025-07-30 18:45:11.132,2464,"{""task"": {""id"": ""688a683587cf5fec60dc809a"", ""t...",TASK_CREATED,3f515ab0-3ced-40c0-b819-76c0e00b6cd3,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'task': {'id': '688a683587cf5fec60dc809a', 't...",688a52ad87cf5fec60dc8096,snehachetani,...,688a52ad87cf5fec60dc8096,Check all the spellings and grammars,False,[ai-author],MANUAL,EACH_MINUTES,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026
38,281241.0,2025-07-30 18:49:30.273,2464,"{""task"": {""id"": ""688a693887cf5fec60dc809f"", ""t...",TASK_CREATED,1b5fb65e-4a41-4c99-8b17-98b44a83e552,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'task': {'id': '688a693887cf5fec60dc809f', 't...",688a52ad87cf5fec60dc8096,snehachetani,...,688a52ad87cf5fec60dc8096,Check spellings and grammars,False,[ai-author],MANUAL,EACH_MINUTES,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026
39,281282.0,2025-07-30 18:53:58.337,2464,"{""task"": {""id"": ""688a6a4487cf5fec60dc80a3"", ""t...",TASK_CREATED,8ab0ad14-b806-472e-a6c4-06bb2402cab1,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'task': {'id': '688a6a4487cf5fec60dc80a3', 't...",688a52ad87cf5fec60dc8096,snehachetani,...,688a52ad87cf5fec60dc8096,,False,[688a6a2087cf5fec60dc80a2],MANUAL,EACH_MINUTES,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026
40,281291.0,2025-07-30 18:54:40.632,2464,"{""task"": {""id"": ""688a6a6f87cf5fec60dc80a6"", ""t...",TASK_CREATED,397074a5-d05f-45d3-8f1a-2674387536b5,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'task': {'id': '688a6a6f87cf5fec60dc80a6', 't...",688a52ad87cf5fec60dc8096,snehachetani,...,688a52ad87cf5fec60dc8096,check spellings,False,[688a6a2087cf5fec60dc80a2],MANUAL,EACH_MINUTES,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026
41,281936.0,2025-07-31 15:28:11.162,2457,"{""task"": {""id"": ""688b8b8b87cf5fec60dc80c0"", ""t...",TASK_CREATED,54b69c9c-f5f6-4901-acec-0f0be66f392d,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'task': {'id': '688b8b8b87cf5fec60dc80c0', 't...",688b1c7887cf5fec60dc80b0,soumyashaw,...,688b1c7887cf5fec60dc80b0,Write a final paragraph at the end of the essay,False,[688b7f6b87cf5fec60dc80b7],MANUAL,EACH_MINUTES,9,2457,688b1c7887cf5fec60dc80b0,688364bf87cf5fec60dc8026
42,282001.0,2025-07-31 21:13:00.548,2465,"{""task"": {""id"": ""688bdc5c87cf5fec60dc80d1"", ""t...",TASK_CREATED,65eda403-df7b-4aa9-9ea0-2ae0c58f2ed4,20d63649-2146-4c8e-8861-14a647fdcd13,"{'task': {'id': '688bdc5c87cf5fec60dc80d1', 't...",688bdb6387cf5fec60dc80d0,joaobelo,...,688bdb6387cf5fec60dc80d0,Prepare a wedding celebration speech,False,[ai-author],MANUAL,EACH_MINUTES,10,2465,688bdb6387cf5fec60dc80d0,6877c26e87cf5fec60dc7fda
43,282106.0,2025-07-31 21:22:10.426,2461,"{""task"": {""id"": ""688bde8287cf5fec60dc80d7"", ""t...",TASK_CREATED,76265edc-2b18-4794-bd73-d2c4998b8f68,46820311-be03-4d2e-b993-90ac3bec3c92,"{'task': {'id': '688bde8287cf5fec60dc80d7', 't...",6888eec887cf5fec60dc8085,vama00004,...,6888eec887cf5fec60dc8085,Change the content of these paragraphs accordi...,False,[688bdddd87cf5fec60dc80d6],MANUAL,EACH_MINUTES,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026
44,282154.0,2025-07-31 21:26:04.489,2461,"{""task"": {""id"": ""688bdf6c87cf5fec60dc80db"", ""t...",TASK_CREATED,09923eaf-a782-4e6c-a346-aac8c2f18580,46820311-be03-4d2e-b993-90ac3bec3c92,"{'task': {'id': '688bdf6c87cf5fec60dc80db', 't...",6888eec887cf5fec60dc8085,vama00004,...,6888eec887cf5fec60dc8085,Rewrite content for the selected paragraphs gi...,True,[688bdddd87cf5fec60dc80d6],MANUAL,EACH_MINUTES,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026

Count of task interaction types:

In [46]:
print("TASK INTERACTION TYPE COUNT:")
display(parsed_task_created_df['task.interaction_type'].value_counts())

TASK INTERACTION TYPE COUNT:

task.interaction_type
MANUAL                49
AUTONOMOUS_COMMENT     4
Name: count, dtype: int64

[G] Event log data: Tasks per document and group (ADD GROUP 4 MANUALLY)

In [47]:
print("TASKS PER GROUP:")

task_counts = parsed_task_created_df['group_id'].value_counts()
task_counts_df = task_counts.rename_axis('group_id').reset_index(name='count')
# add group 4 with 7
task_counts_df.loc[len(task_counts_df)] = [4, 7]

display(task_counts_df)
display(task_counts_df['count'].describe())
display(task_counts_df['count'].sum())

TASKS PER GROUP:

    group_id  count
0          9      9
1          6      8
2          7      6
3          2      5
4          1      5
5          3      4
6          5      4
7         10      4
8         11      4
9         12      3
10        14      1
11         4      7

count    12.000000
mean      5.000000
std       2.215647
min       1.000000
25%       4.000000
50%       4.500000
75%       6.250000
max       9.000000
Name: count, dtype: float64

60

Event log data; counts of task triggers

In [48]:
print("TASK TRIGGERS:")

print(parsed_task_created_df["task.advanced_trigger_settings.interaction_trigger"].value_counts())
print(parsed_task_created_df["task.advanced_trigger_settings.interaction_trigger"].value_counts().describe())

TASK TRIGGERS:
task.advanced_trigger_settings.interaction_trigger
EACH_MINUTES          51
DOCUMENT_SAVE          1
MINUTES_INACTIVITY     1
Name: count, dtype: int64
count     3.000000
mean     17.666667
std      28.867513
min       1.000000
25%       1.000000
50%       1.000000
75%      26.000000
max      51.000000
Name: count, dtype: float64

In [49]:
manual_tasks_df = parsed_task_created_df[parsed_task_created_df['task.interaction_type'] == "MANUAL"]
autonomous_tasks_df = parsed_task_created_df[parsed_task_created_df['task.interaction_type'] == "AUTONOMOUS_COMMENT"]

print("TASK TRIGGERS AUTONOMOUS:")
print(autonomous_tasks_df["task.advanced_trigger_settings.interaction_trigger"].value_counts())

TASK TRIGGERS AUTONOMOUS:
task.advanced_trigger_settings.interaction_trigger
EACH_MINUTES          2
DOCUMENT_SAVE         1
MINUTES_INACTIVITY    1
Name: count, dtype: int64

List of Task descriptions 
[N]Qualitatively: What kinds of tasks were created? see thesis

In [50]:
# review task descriptions
#display(study_tasks['description'].to_list())
display(parsed_task_created_df['task.description'].to_list())
print('group 4:')
display(study_tasks[study_tasks['group_id'] == 4]['description'].to_list())


task_descriptions_df = parsed_task_created_df[['task.assignee_ids', 'task.description', 'group_id', 'user']]
task_descriptions_df.columns = ['assignee_ids', 'description', 'group_id', 'user']
task_descriptions_g4_df = study_tasks[study_tasks['group_id'] == 4][['assignee_ids', 'description', 'group_id', 'user']]

task_descriptions_merged_df = pd.concat([task_descriptions_df, task_descriptions_g4_df])

assignee_ids_list = task_descriptions_merged_df["assignee_ids"].to_list()
task_descriptions_merged_df["assignee_ids"] = task_descriptions_merged_df["assignee_ids"].apply(lambda x: ', '.join(x))

task_descriptions_merged_df.to_csv(os.path.join('output', 'tasks', 'task_descriptions.tsv'), sep="\t")

display(task_descriptions_merged_df)

assignee_ids_list = [
    x
    for xs in assignee_ids_list
    for x in xs
]
assignee_ids_list = pd.Series(assignee_ids_list)

print(assignee_ids_list.value_counts())
display(assignee_ids_list.value_counts().describe())

['Write intro for the essay',
 'write the part where u talk about pros of AI',
 'Write cons of AI',
 'write the zusamenfassung for our essay based on the info u mentioned',
 'can u edit our text as the scientific paper with the names of the names of the authors and literature if there is any',
 'Read the written part of text. Highlight grammar mistakes and structural mistakes. If some of them are ',
 'Check the selected text and provide some scientific facts about it with reference. Do not just write a fact without reference.',
 'Considering the topic and the latest available context, provide 1-2 sentences to continue the essay.',
 'We nned to write an essay together about the prons and cons of AI in 2025. Could you give us a plan of action and the structure of the eassay?',
 'Generate essay for Health and Wellness in the Digital Age',
 'Make the text shorter',
 'Give it more scientific and professional style.',
 'write a conclusion of the given text',
 'The agent should analyze the selected advantage or disadvantage of Artificial Intelligence and provide counterargument for it. ',
 'Check the text',
 'Check the language mistakes in the text',
 'Check if the text flow is good and give council if to change the order of something in the text',
 'Give advices on how to name each paragraph and whar parts of the text should I move to there, where you mark me to, for the better consistency and strcuture of the work',
 'Write me a text about ai pros and cons',
 'check the text find mistakes',
 'add citations',
 'can you help with generating more ideas so the text will be longer ',
 'check the text, make it look good as an essay, change the format',
 'delete everything what doesn´t make sense',
 'Add an introduction and a conclusion part. Add only the text itself, without your commentary',
 'help me make it prettier ',
 "This is an Essay about Artificial intelligence and it's impact on our lives. The user will only write bullet points. Your task is to write out the full text in the selected document section.",
 "Oversee the provided text and make sure, it's written correctly. And it makes sense. ",
 'make text shorter\n',
 'MAke it more literature based',
 'Add some interesting facts',
 'Summarize the text before',
 'Create categories for planning a wedding',
 'make headers for the different categories of planning this wedding',
 'Highlight each item that needs to be purchased to fulfill a vision',
 'Write a blog in 1000 words about the given title',
 'Check all the spellings and grammars',
 'Check spellings and grammars',
 '',
 'check spellings',
 'Write a final paragraph at the end of the essay',
 'Prepare a wedding celebration speech',
 'Change the content of these paragraphs according to the article. keep the flow same. ',
 'Rewrite content for the selected paragraphs give new title and description.',
 'Check the whole content for mistakes break in flow.',
 'Bitte einmal die Motivation prüfen',
 'Please review',
 '',
 'Make the text more interesting to read, and a few sentences about Deutsche Telekom. ',
 'Übersetze Deutsch auf englisch',
 'Create me a lessons plan for a graduate seminar in computer science. The seminar as 4 milestones: Research Proposal, Rough Draft, Methods and Analysis, Final Paper and Presentation. The seminar is 15 weeks long. It has an introduction into scientific writing and research communication. It also has an introduction into ai agents.\nStart the lesson plan with that introduction to ai agents. in the later part of the semester, some sessions are dedicated to individual work. The seminar ist always on thursdays starting October 9. and not running over the christmas holidays starting 23.12.2025 through 06.01.2026. The semester ends Jan 23, 2026.\n',
 'format that part poperly for a doc not a markdown file',
 'prüfe die Literaturquellen und schlage mir noch 5 weitere passende Quellen vor.']

group 4:

['Consistency Review of the whole document; discovery of contradictions; potential weak points',
 'Go through the whole text and make sure everything is written in American English. Mark all findings of British English and provide the American English equivalent for each British English word you find.',
 'Make sure the text does not sound like a blog post or commercial, but more scientific. No overclaims!',
 'Critically discuss the arguments made in this section. Are they valid? Is something missing? Suggest literature references that could be useful.\nAlso, improve the language.',
 'Can you take the latex list below and build it into section and subsection titles with notes on what should go in each section?\n',
 'Review the section titles',
 'Review complete paper']

,assignee_ids,description,group_id,user
0,ai-author,Write intro for the essay,2,1377
1,ai-author,write the part where u talk about pros of AI,2,1376
2,ai-author,Write cons of AI,2,1377
3,ai-author,write the zusamenfassung for our essay based o...,2,1376
4,ai-author,can u edit our text as the scientific paper wi...,2,1376
5,67cdfc85285fac3f07bcf5cf,Read the written part of text. Highlight gramm...,3,1374
6,67cdfef4285fac3f07bcf5d3,Check the selected text and provide some scien...,3,1374
7,67cdfc85285fac3f07bcf5cf,Considering the topic and the latest available...,3,1374
8,ai-author,We nned to write an essay together about the p...,1,1379
9,ai-author,Generate essay for Health and Wellness in the ...,1,1380
10,ai-author,Make the text shorter,1,1380
11,ai-author,Give it more scientific and professional style.,1,1380
12,ai-author,write a conclusion of the given text,1,1379
13,ai-author,The agent should analyze the selected advantag...,3,1374
14,67d5d8cf0b9539e69a3a86df,Check the text,5,1387
15,67d5d88f0b9539e69a3a86dc,Check the language mistakes in the text,5,1387
16,67d5d88b0b9539e69a3a86db,Check if the text flow is good and give counci...,5,1387
17,67d5d88b0b9539e69a3a86db,Give advices on how to name each paragraph and...,5,1387
18,ai-author,Write me a text about ai pros and cons,6,1388
19,67d82f6dedfe680c1b0f164a,check the text find mistakes,6,1388
20,67d82fbfedfe680c1b0f164e,add citations,6,1389
21,67d83410edfe680c1b0f1655,can you help with generating more ideas so the...,6,1388
22,ai-author,"check the text, make it look good as an essay,...",6,1388
23,67d83558edfe680c1b0f165e,delete everything what doesn´t make sense,6,1388
24,ai-author,Add an introduction and a conclusion part. Add...,6,1389
25,67d82f6dedfe680c1b0f164a,help me make it prettier,6,1388
27,6887772287cf5fec60dc8036,This is an Essay about Artificial intelligence...,7,2456
28,6887772287cf5fec60dc8036,"Oversee the provided text and make sure, it's ...",7,2456
29,ai-author,make text shorter\n,7,2460
30,6887772287cf5fec60dc8036,MAke it more literature based,7,2460
31,ai-author,Add some interesting facts,7,2460
32,6887772287cf5fec60dc8036,Summarize the text before,7,2460
33,6888bd4b87cf5fec60dc8073,Create categories for planning a wedding,10,2459
34,6888bd4b87cf5fec60dc8073,make headers for the different categories of p...,10,2459
35,6888c9af87cf5fec60dc8081,Highlight each item that needs to be purchased...,10,2459
36,ai-author,Write a blog in 1000 words about the given title,9,2461
37,ai-author,Check all the spellings and grammars,9,2464
38,ai-author,Check spellings and grammars,9,2464
39,688a6a2087cf5fec60dc80a2,,9,2464
40,688a6a2087cf5fec60dc80a2,check spellings,9,2464
41,688b7f6b87cf5fec60dc80b7,Write a final paragraph at the end of the essay,9,2457
42,ai-author,Prepare a wedding celebration speech,10,2465
43,688bdddd87cf5fec60dc80d6,Change the content of these paragraphs accordi...,9,2461
44,688bdddd87cf5fec60dc80d6,Rewrite content for the selected paragraphs gi...,9,2461
45,ai-author,Check the whole content for mistakes break in ...,9,2461
46,689c3da3e90ffc190a96c28f,Bitte einmal die Motivation prüfen,12,2469
47,689c3da3e90ffc190a96c28f,Please review,12,2469
48,689c3da3e90ffc190a96c28f,,12,2469
49,"ai-author, 689e2470e90ffc190a96c2e4, 689e24b5e...","Make the text more interesting to read, and a ...",14,2471
50,ai-author,Übersetze Deutsch auf englisch,11,2475
51,68931d9887cf5fec60dc810f,Create me a lessons plan for a graduate semina...,11,2475
52,ai-author,format that part poperly for a doc not a markd...,11,2475
53,688b2aa687cf5fec60dc80b3,prüfe die Literaturquellen und schlage mir noc...,11,2475
14,"67e691c850d39f32454bf30c, 67d445e30b9539e69a3a...",Consistency Review of the whole document; disc...,4,1383
15,67d445d10b9539e69a3a86c1,Go through the whole text and make sure everyt...,4,1383
16,67d445d10b9539e69a3a86c1,Make sure the text does not sound like a blog ...,4,1384
17,"67e5cb6450d39f32454bf2fa, 67d445d10b9539e69a3a...",Critically discuss the arguments made in this ...,4,1384
18,ai-author,Can you take the latex list below and build it...,4,1385
19,67d445e30b9539e69a3a86c3,Review the section titles,4,1385
20,67d445e30b9539e69a3a86c3,Review complete paper,4,1385

ai-author                   25
6887772287cf5fec60dc8036     4
689c3da3e90ffc190a96c28f     3
67d445d10b9539e69a3a86c1     3
67d445e30b9539e69a3a86c3     3
67d5d88b0b9539e69a3a86db     2
67d82f6dedfe680c1b0f164a     2
6888bd4b87cf5fec60dc8073     2
67cdfc85285fac3f07bcf5cf     2
688a6a2087cf5fec60dc80a2     2
688bdddd87cf5fec60dc80d6     2
67e691c850d39f32454bf30c     1
688b2aa687cf5fec60dc80b3     1
68931d9887cf5fec60dc810f     1
689e24b5e90ffc190a96c2e6     1
689e2470e90ffc190a96c2e4     1
6888c9af87cf5fec60dc8081     1
688b7f6b87cf5fec60dc80b7     1
67d83558edfe680c1b0f165e     1
67d83410edfe680c1b0f1655     1
67d82fbfedfe680c1b0f164e     1
67d5d88f0b9539e69a3a86dc     1
67d5d8cf0b9539e69a3a86df     1
67cdfef4285fac3f07bcf5d3     1
67e5cb6450d39f32454bf2fa     1
Name: count, dtype: int64

count    25.000000
mean      2.560000
std       4.752894
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max      25.000000
Name: count, dtype: float64

Task descriptions of tasks with interaction type MANUAL

In [51]:
# review manual task descriptions
display(parsed_task_created_df[parsed_task_created_df["task.interaction_type"] == "MANUAL"]["task.description"].to_list())

print('group 4:')
display(study_tasks[(study_tasks['group_id'] == 4) & (study_tasks['interaction_type'] == 'MANUAL')]['description'].to_list())

['Write intro for the essay',
 'write the part where u talk about pros of AI',
 'write the zusamenfassung for our essay based on the info u mentioned',
 'can u edit our text as the scientific paper with the names of the names of the authors and literature if there is any',
 'Check the selected text and provide some scientific facts about it with reference. Do not just write a fact without reference.',
 'We nned to write an essay together about the prons and cons of AI in 2025. Could you give us a plan of action and the structure of the eassay?',
 'Generate essay for Health and Wellness in the Digital Age',
 'Make the text shorter',
 'Give it more scientific and professional style.',
 'write a conclusion of the given text',
 'The agent should analyze the selected advantage or disadvantage of Artificial Intelligence and provide counterargument for it. ',
 'Check the text',
 'Check the language mistakes in the text',
 'Check if the text flow is good and give council if to change the order of something in the text',
 'Give advices on how to name each paragraph and whar parts of the text should I move to there, where you mark me to, for the better consistency and strcuture of the work',
 'Write me a text about ai pros and cons',
 'check the text find mistakes',
 'add citations',
 'can you help with generating more ideas so the text will be longer ',
 'check the text, make it look good as an essay, change the format',
 'delete everything what doesn´t make sense',
 'Add an introduction and a conclusion part. Add only the text itself, without your commentary',
 'help me make it prettier ',
 "This is an Essay about Artificial intelligence and it's impact on our lives. The user will only write bullet points. Your task is to write out the full text in the selected document section.",
 "Oversee the provided text and make sure, it's written correctly. And it makes sense. ",
 'make text shorter\n',
 'MAke it more literature based',
 'Add some interesting facts',
 'Summarize the text before',
 'Create categories for planning a wedding',
 'make headers for the different categories of planning this wedding',
 'Highlight each item that needs to be purchased to fulfill a vision',
 'Write a blog in 1000 words about the given title',
 'Check all the spellings and grammars',
 'Check spellings and grammars',
 '',
 'check spellings',
 'Write a final paragraph at the end of the essay',
 'Prepare a wedding celebration speech',
 'Change the content of these paragraphs according to the article. keep the flow same. ',
 'Rewrite content for the selected paragraphs give new title and description.',
 'Check the whole content for mistakes break in flow.',
 'Bitte einmal die Motivation prüfen',
 'Please review',
 '',
 'Make the text more interesting to read, and a few sentences about Deutsche Telekom. ',
 'Übersetze Deutsch auf englisch',
 'Create me a lessons plan for a graduate seminar in computer science. The seminar as 4 milestones: Research Proposal, Rough Draft, Methods and Analysis, Final Paper and Presentation. The seminar is 15 weeks long. It has an introduction into scientific writing and research communication. It also has an introduction into ai agents.\nStart the lesson plan with that introduction to ai agents. in the later part of the semester, some sessions are dedicated to individual work. The seminar ist always on thursdays starting October 9. and not running over the christmas holidays starting 23.12.2025 through 06.01.2026. The semester ends Jan 23, 2026.\n',
 'format that part poperly for a doc not a markdown file']

group 4:

['Consistency Review of the whole document; discovery of contradictions; potential weak points',
 'Go through the whole text and make sure everything is written in American English. Mark all findings of British English and provide the American English equivalent for each British English word you find.',
 'Make sure the text does not sound like a blog post or commercial, but more scientific. No overclaims!',
 'Critically discuss the arguments made in this section. Are they valid? Is something missing? Suggest literature references that could be useful.\nAlso, improve the language.',
 'Can you take the latex list below and build it into section and subsection titles with notes on what should go in each section?\n',
 'Review the section titles']

Task descriptions for shortcut tasks

In [52]:
# review shortcut descriptions
display(parsed_task_created_df[parsed_task_created_df["task.is_shortcut"] == True]["task.description"].to_list())
print('group 4:')
display(study_tasks[(study_tasks['group_id'] == 4) & (study_tasks['is_shortcut'] == True)]['description'].to_list())

['Check the selected text and provide some scientific facts about it with reference. Do not just write a fact without reference.',
 'Make the text shorter',
 'Give it more scientific and professional style.',
 'The agent should analyze the selected advantage or disadvantage of Artificial Intelligence and provide counterargument for it. ',
 'Check if the text flow is good and give council if to change the order of something in the text',
 'Add some interesting facts',
 'Summarize the text before',
 'Highlight each item that needs to be purchased to fulfill a vision',
 'Rewrite content for the selected paragraphs give new title and description.']

group 4:

['Make sure the text does not sound like a blog post or commercial, but more scientific. No overclaims!',
 'Critically discuss the arguments made in this section. Are they valid? Is something missing? Suggest literature references that could be useful.\nAlso, improve the language.']

Task descriptions of tasks with interaction type AUTONOMOUS_COMMENT

In [53]:
# autonomous tasks
display(parsed_task_created_df[parsed_task_created_df["task.interaction_type"] == "AUTONOMOUS_COMMENT"])

display(parsed_task_created_df[parsed_task_created_df["task.interaction_type"] == "AUTONOMOUS_COMMENT"]["task.advanced_trigger_settings.interaction_trigger"].value_counts())
display(study_tasks[(study_tasks['group_id'] == 4) & (study_tasks['interaction_type'] == "AUTONOMOUS_COMMENT")]["advanced_trigger_settings.interaction_trigger"].value_counts())

print('group 4:')
display(study_tasks[(study_tasks['group_id'] == 4) & (study_tasks['interaction_type'] == "AUTONOMOUS_COMMENT")]['description'].to_list())

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,user_id_x,username,...,task.author_id,task.description,task.is_shortcut,task.assignee_ids,task.interaction_type,task.advanced_trigger_settings.interaction_trigger,group_id,user,user_id_y,document
2,276317.0,2025-03-07 21:45:35.824,1377,"{""task"": {""id"": ""67cb68ff285fac3f07bcf5a8"", ""t...",TASK_CREATED,4e191fcc-fdea-4024-8ab9-2c3dacf44b3b,2aac5afe-a3af-4135-a1a3-78adf87ae9d8,"{'task': {'id': '67cb68ff285fac3f07bcf5a8', 't...",67cb6623285fac3f07bcf59a,adambokun,...,67cb6623285fac3f07bcf59a,Write cons of AI,False,[ai-author],AUTONOMOUS_COMMENT,EACH_MINUTES,2,1377,67cb6623285fac3f07bcf59a,67c97527285fac3f07bcf587
5,276488.0,2025-03-09 20:42:12.823,1374,"{""task"": {""id"": ""67cdfd24285fac3f07bcf5d1"", ""t...",TASK_CREATED,f481ec92-ac67-4137-b0fc-3b5544241b6d,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67cdfd24285fac3f07bcf5d1', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,Read the written part of text. Highlight gramm...,False,[67cdfc85285fac3f07bcf5cf],AUTONOMOUS_COMMENT,DOCUMENT_SAVE,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
7,276525.0,2025-03-09 20:59:38.568,1374,"{""task"": {""id"": ""67ce013a285fac3f07bcf5d6"", ""t...",TASK_CREATED,65e32235-d117-4745-8178-fabb272347d2,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67ce013a285fac3f07bcf5d6', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,Considering the topic and the latest available...,False,[67cdfc85285fac3f07bcf5cf],AUTONOMOUS_COMMENT,MINUTES_INACTIVITY,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
53,284444.0,2025-08-22 17:22:47.099,2475,"{""task"": {""id"": ""68a8a766ecc07d2944852284"", ""t...",TASK_CREATED,a0eae2a9-c7ce-476d-935c-6f2116acef49,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,"{'task': {'id': '68a8a766ecc07d2944852284', 't...",68a75365ecc07d2944852275,gsocher,...,68a75365ecc07d2944852275,prüfe die Literaturquellen und schlage mir noc...,False,[688b2aa687cf5fec60dc80b3],AUTONOMOUS_COMMENT,EACH_MINUTES,11,2475,68a75365ecc07d2944852275,6889e57087cf5fec60dc8092

task.advanced_trigger_settings.interaction_trigger
EACH_MINUTES          2
DOCUMENT_SAVE         1
MINUTES_INACTIVITY    1
Name: count, dtype: int64

advanced_trigger_settings.interaction_trigger
USER_OFFLINE    1
Name: count, dtype: int64

group 4:

['Review complete paper']

Shortcut counts

In [54]:
# number of shortcuts / non shortcuts
display(parsed_task_created_df.groupby('task.is_shortcut')['id'].count())

print("group 4:")
display(study_tasks[study_tasks['group_id'] == 4]['is_shortcut'].value_counts())

task.is_shortcut
False    44
True      9
Name: id, dtype: int64

group 4:

is_shortcut
False    5
True     2
Name: count, dtype: int64

Event logs, Changes to tasks:
[J] Iteration: How often were tasks edited after creating them?

In [55]:
# review what changed in tasks (without group 4)
display(finished_participants[finished_participants["event"] == "TASK_EDITED"]["data"])

edited_task_df = finished_participants[finished_participants["event"] == "TASK_EDITED"]

print("Edited tasks: ", len(edited_task_df))
print("Percentage: ", 100 / task_counts_df['count'].sum() * len(edited_task_df))

edited_task_df = parse_json_field(edited_task_df, "data")
print("SWITCHED INTERACTION TYPE")
display(edited_task_df[edited_task_df["new_interaction_type"] != edited_task_df["old_interaction_type"]])
print("SWITCHED TRIGGER")
display(edited_task_df[edited_task_df["new_interaction_trigger"] != edited_task_df["old_interaction_trigger"]])

302     {"newTask": {"title": "Grammar and Structure R...
484     {"newTask": {"title": "Verify Text with Refere...
707     {"newTask": {"title": "AI Pros and Cons Essay"...
1118    {"newTask": {"title": "Proofreading", "descrip...
1461    {"newTask": {"title": "Grammar and Structure R...
1519    {"newTask": {"title": "Essay Continuation Prom...
3356    {"newTask": {"title": "Text Review and Editing...
3359    {"newTask": {"title": "Only review, no generat...
6006    {"newTask": {"title": "Motivation Überprüfung"...
Name: data, dtype: object

Edited tasks:  9
Percentage:  15.0
SWITCHED INTERACTION TYPE

/tmp/ipykernel_160434/962560954.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  event_df[json_field + "_parsed"] = event_df[json_field].apply(json.loads)

,task_id,user_id,username,document_id,task_author_id,new_is_shortcut,old_is_shortcut,participant_token,new_interaction_type,old_interaction_type,...,newTask.interaction_type,newTask.advanced_trigger_settings.interaction_trigger,oldTask.id,oldTask.title,oldTask.author_id,oldTask.description,oldTask.is_shortcut,oldTask.assignee_ids,oldTask.interaction_type,oldTask.advanced_trigger_settings.interaction_trigger
3,67cea2a4285fac3f07bcf5f8,67ce982f285fac3f07bcf5e7,galina.akhunzhanova@uni-bayreuth.de,67ce983b285fac3f07bcf5e8,67ce982f285fac3f07bcf5e7,False,False,6573f86e-0207-4286-b036-a83f25a630c3,AUTONOMOUS_COMMENT,MANUAL,...,AUTONOMOUS_COMMENT,EACH_MINUTES,67cea2a4285fac3f07bcf5f8,Conclusion Writing Task,67ce982f285fac3f07bcf5e7,write a conclusion of the given text,False,[ai-author],MANUAL,EACH_MINUTES

SWITCHED TRIGGER

,task_id,user_id,username,document_id,task_author_id,new_is_shortcut,old_is_shortcut,participant_token,new_interaction_type,old_interaction_type,...,newTask.interaction_type,newTask.advanced_trigger_settings.interaction_trigger,oldTask.id,oldTask.title,oldTask.author_id,oldTask.description,oldTask.is_shortcut,oldTask.assignee_ids,oldTask.interaction_type,oldTask.advanced_trigger_settings.interaction_trigger
5,67ce013a285fac3f07bcf5d6,67cdfa30285fac3f07bcf5cc,Ivan Khrop,67c88f88285fac3f07bcf585,67cdfa30285fac3f07bcf5cc,False,False,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,AUTONOMOUS_COMMENT,AUTONOMOUS_COMMENT,...,AUTONOMOUS_COMMENT,DOCUMENT_SAVE,67ce013a285fac3f07bcf5d6,Essay Continuation Prompt,67cdfa30285fac3f07bcf5cc,Considering the topic and the latest available...,False,[67cdfc85285fac3f07bcf5cf],AUTONOMOUS_COMMENT,MINUTES_INACTIVITY

Tasks that do not use default AI author

In [56]:
# tasks that do not use default AI author
# print("Tasks that do not use default AI author:", study_tasks["assignee_ids"].dropna().apply(lambda x: "ai-author" not in x).sum())
# print("Fraction of all tasks: ", study_tasks["assignee_ids"].dropna().apply(lambda x: "ai-author" not in x).sum() / len(study_tasks))
custom_agent_tasks = parsed_task_created_df["task.assignee_ids"].dropna().apply(lambda x: "ai-author" not in x).sum()
custom_agent_tasks_g4 = study_tasks[study_tasks['group_id'] == 4]["assignee_ids"].dropna().apply(lambda x: "ai-author" not in x).sum()
print("Tasks that do not use default AI author:", custom_agent_tasks)
print("Group 4, Tasks that do not use default AI author:", custom_agent_tasks_g4)

print("Fraction of all tasks: ", (custom_agent_tasks + custom_agent_tasks_g4) / (len(parsed_task_created_df) + len(study_tasks[study_tasks['group_id'] == 4])))

Tasks that do not use default AI author: 29
Group 4, Tasks that do not use default AI author: 6
Fraction of all tasks:  0.5833333333333334

How many tasks where used for agents which they didn't create
[K] Collaborative use: Number of tasks created for an agent that has been created by a team member

In [57]:
study_agents = pd.read_csv(os.path.join('output', 'intermediate', '03_study_agents.csv'), sep='\t')

# How many tasks where used for agents which they didn't create
short_task_df = parsed_task_created_df[["task.id", "task.assignee_ids", "task.author_id"]].dropna()
short_agents_df = study_agents[["_id", "author_id"]].dropna()

# Explode the list_column
short_task_df = short_task_df.explode("task.assignee_ids", ignore_index=True).drop_duplicates()

# Merge the DataFrames on the common column
merged_df = pd.merge(short_task_df, short_agents_df, left_on="task.assignee_ids", right_on="_id", how="left").dropna()

# Check if task author is the same as agent author
not_same_author = merged_df["task.author_id"] != merged_df["author_id"]
print("Task author is different from agent author:")
display(merged_df[not_same_author])
display(parsed_task_created_df[parsed_task_created_df["task.id"].isin(merged_df[not_same_author]["task.id"])])

print("Percentage of tasks where the author was different than the agent author:", not_same_author.sum() * 100 / len(parsed_task_created_df))

# group 4:

short_task_g4_df = study_tasks[study_tasks['group_id'] == 4][["_id", "assignee_ids", "author_id"]].dropna()
short_task_g4_df = short_task_g4_df.explode("assignee_ids", ignore_index=True).drop_duplicates()
merged_g4_df = pd.merge(short_task_g4_df, short_agents_df, left_on="assignee_ids", right_on="_id", how="left", suffixes=["_task", "_agent"]).dropna()

not_same_author_g4 = merged_g4_df["author_id_task"] != merged_g4_df["author_id_agent"]

print("G4 Task author is different from agent author:")
display(merged_g4_df[not_same_author_g4])
display(study_tasks[study_tasks["_id"].isin(merged_g4_df[not_same_author_g4]["_id_task"])])

print("G4's Percentage of tasks where the author was different than the agent author:", not_same_author_g4.sum() * 100 / not_same_author_g4.count())

print("Total percentage of tasks where the author was different from the agent's author", (not_same_author.sum() + not_same_author_g4.sum()) * 100 / (len(parsed_task_created_df) + len(study_tasks[study_tasks['group_id'] == 4])))
print( 100 - (not_same_author.sum() + not_same_author_g4.sum()) * 100 / (len(parsed_task_created_df) + len(study_tasks[study_tasks['group_id'] == 4])))

Task author is different from agent author:

,task.id,task.assignee_ids,task.author_id,_id,author_id
29,6887bac987cf5fec60dc8062,6887772287cf5fec60dc8036,6887b97087cf5fec60dc8060,6887772287cf5fec60dc8036,68835b0587cf5fec60dc8020
31,6888b5b187cf5fec60dc806b,6887772287cf5fec60dc8036,6887b97087cf5fec60dc8060,6887772287cf5fec60dc8036,68835b0587cf5fec60dc8020
52,68a8a49aecc07d294485227c,68931d9887cf5fec60dc810f,68a75365ecc07d2944852275,68931d9887cf5fec60dc810f,6889e71f87cf5fec60dc8094
54,68a8a766ecc07d2944852284,688b2aa687cf5fec60dc80b3,68a75365ecc07d2944852275,688b2aa687cf5fec60dc80b3,6889e71f87cf5fec60dc8094

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,user_id_x,username,...,task.author_id,task.description,task.is_shortcut,task.assignee_ids,task.interaction_type,task.advanced_trigger_settings.interaction_trigger,group_id,user,user_id_y,document
30,280521.0,2025-07-28 18:00:41.738,2460,"{""task"": {""id"": ""6887bac987cf5fec60dc8062"", ""t...",TASK_CREATED,ed1db37e-3231-40c0-86db-79f77cfdc59a,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6887bac987cf5fec60dc8062', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,MAke it more literature based,False,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
32,280682.0,2025-07-29 11:51:13.438,2460,"{""task"": {""id"": ""6888b5b187cf5fec60dc806b"", ""t...",TASK_CREATED,afbcba64-39b7-4f39-b94c-6632d247039f,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6888b5b187cf5fec60dc806b', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,Summarize the text before,True,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
51,284367.0,2025-08-22 17:10:50.860,2475,"{""task"": {""id"": ""68a8a49aecc07d294485227c"", ""t...",TASK_CREATED,7363ab12-be5f-4afe-923e-f1b1cbf8ab7c,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,"{'task': {'id': '68a8a49aecc07d294485227c', 't...",68a75365ecc07d2944852275,gsocher,...,68a75365ecc07d2944852275,Create me a lessons plan for a graduate semina...,False,[68931d9887cf5fec60dc810f],MANUAL,EACH_MINUTES,11,2475,68a75365ecc07d2944852275,6889e57087cf5fec60dc8092
53,284444.0,2025-08-22 17:22:47.099,2475,"{""task"": {""id"": ""68a8a766ecc07d2944852284"", ""t...",TASK_CREATED,a0eae2a9-c7ce-476d-935c-6f2116acef49,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,"{'task': {'id': '68a8a766ecc07d2944852284', 't...",68a75365ecc07d2944852275,gsocher,...,68a75365ecc07d2944852275,prüfe die Literaturquellen und schlage mir noc...,False,[688b2aa687cf5fec60dc80b3],AUTONOMOUS_COMMENT,EACH_MINUTES,11,2475,68a75365ecc07d2944852275,6889e57087cf5fec60dc8092

Percentage of tasks where the author was different than the agent author: 7.547169811320755
G4 Task author is different from agent author:

,_id_task,assignee_ids,author_id_task,_id_agent,author_id_agent
1,67e6924450d39f32454bf30d,67d445e30b9539e69a3a86c3,67bc761a7a670b68746905a0,67d445e30b9539e69a3a86c3,67bc43607a670b6874690577
3,67e5c94550d39f32454bf2f4,67d445d10b9539e69a3a86c1,67d444dd0b9539e69a3a86bb,67d445d10b9539e69a3a86c1,67bc761a7a670b68746905a0
5,67e5cc3e50d39f32454bf2fc,67d445d10b9539e69a3a86c1,67d444dd0b9539e69a3a86bb,67d445d10b9539e69a3a86c1,67bc761a7a670b68746905a0

,group_id,user,document,_id,assignee_ids,description,document_id,interaction_type,is_shortcut,author_id,progress,title,advanced_trigger_settings.interaction_trigger
14,4,1383,67d43b390b9539e69a3a86b9,67e6924450d39f32454bf30d,"[67e691c850d39f32454bf30c, 67d445e30b9539e69a3...",Consistency Review of the whole document; disc...,67d43b390b9539e69a3a86b9,MANUAL,False,67bc761a7a670b68746905a0,[],Document Consistency Review,EACH_MINUTES
16,4,1384,67d43b390b9539e69a3a86b9,67e5c94550d39f32454bf2f4,[67d445d10b9539e69a3a86c1],Make sure the text does not sound like a blog ...,67d43b390b9539e69a3a86b9,MANUAL,True,67d444dd0b9539e69a3a86bb,[],Ensure Scientific Tone,EACH_MINUTES
17,4,1384,67d43b390b9539e69a3a86b9,67e5cc3e50d39f32454bf2fc,"[67e5cb6450d39f32454bf2fa, 67d445d10b9539e69a3...",Critically discuss the arguments made in this ...,67d43b390b9539e69a3a86b9,MANUAL,True,67d444dd0b9539e69a3a86bb,[],Critical Argument Analysis,EACH_MINUTES

G4's Percentage of tasks where the author was different than the agent author: 37.5
Total percentage of tasks where the author was different from the agent's author 11.666666666666666
88.33333333333333

In [58]:
# if users used task assignee autoselection (i.e. a task that has one or more assignees on creation)

counter = 0
for idx, row in parsed_task_created_df.iterrows():
    counter += len(row["task.assignee_ids"]) > 0

print("fraction of tasks where assignees were autoselected by users", counter / len(parsed_task_created_df))

display(study_tasks[study_tasks['group_id'] == 4])
counter_g4 = 0
for idx, row in study_tasks[study_tasks['group_id'] == 4].iterrows():
    counter_g4 += len(row["assignee_ids"]) > 0

print("G6, fraction of tasks where assignees were autoselected by users", counter_g4 / len(study_tasks[study_tasks['group_id'] == 4]))

print("Total fraction of tasks where assignees were autoselected by users", (counter + counter_g4) / (len(parsed_task_created_df) + len(study_tasks[study_tasks['group_id'] == 4])))

fraction of tasks where assignees were autoselected by users 1.0

,group_id,user,document,_id,assignee_ids,description,document_id,interaction_type,is_shortcut,author_id,progress,title,advanced_trigger_settings.interaction_trigger
14,4,1383,67d43b390b9539e69a3a86b9,67e6924450d39f32454bf30d,"[67e691c850d39f32454bf30c, 67d445e30b9539e69a3...",Consistency Review of the whole document; disc...,67d43b390b9539e69a3a86b9,MANUAL,False,67bc761a7a670b68746905a0,[],Document Consistency Review,EACH_MINUTES
15,4,1383,67d43b390b9539e69a3a86b9,67e6947c50d39f32454bf311,[67d445d10b9539e69a3a86c1],Go through the whole text and make sure everyt...,67d43b390b9539e69a3a86b9,MANUAL,False,67bc761a7a670b68746905a0,[],American English Conversion,EACH_MINUTES
16,4,1384,67d43b390b9539e69a3a86b9,67e5c94550d39f32454bf2f4,[67d445d10b9539e69a3a86c1],Make sure the text does not sound like a blog ...,67d43b390b9539e69a3a86b9,MANUAL,True,67d444dd0b9539e69a3a86bb,[],Ensure Scientific Tone,EACH_MINUTES
17,4,1384,67d43b390b9539e69a3a86b9,67e5cc3e50d39f32454bf2fc,"[67e5cb6450d39f32454bf2fa, 67d445d10b9539e69a3...",Critically discuss the arguments made in this ...,67d43b390b9539e69a3a86b9,MANUAL,True,67d444dd0b9539e69a3a86bb,[],Critical Argument Analysis,EACH_MINUTES
18,4,1385,67d43b390b9539e69a3a86b9,67dd2e18edfe680c1b0f1674,[ai-author],Can you take the latex list below and build it...,67d43b390b9539e69a3a86b9,MANUAL,False,67bc43607a670b6874690577,[],Create Section Titles,EACH_MINUTES
19,4,1385,67d43b390b9539e69a3a86b9,67dd2fe2edfe680c1b0f1676,[67d445e30b9539e69a3a86c3],Review the section titles,67d43b390b9539e69a3a86b9,MANUAL,False,67bc43607a670b6874690577,"[{'created_time': 1742548989358, 'selected_tex...",Review Section Titles,EACH_MINUTES
20,4,1385,67d43b390b9539e69a3a86b9,67dd7b51edfe680c1b0f1693,[67d445e30b9539e69a3a86c3],Review complete paper,67d43b390b9539e69a3a86b9,AUTONOMOUS_COMMENT,False,67bc43607a670b6874690577,"[{'created_time': 1742570360969, 'selected_tex...",Paper Review Completion,USER_OFFLINE

G6, fraction of tasks where assignees were autoselected by users 1.0
Total fraction of tasks where assignees were autoselected by users 1.0

How many users run their own tasks
[H]Number of tasks executed
[L] Collaborative use: Number of tasks executed by someone else than the creator

In [59]:
# how many users run their own tasks
finished_df = finished_participants[
    finished_participants["event"].isin(["TASK_RUN", "TASK_SHORTCUT_RUN"])
]

counter = 0
for idx, row in finished_df.iterrows():
    info = json.loads(row["data"])
    if info["user_id"] == info["task_author_id"]:
        counter += 1

print("percentage of participants running their own tasks: ", counter / len(finished_df) * 100)
print("percentage of participants running tasks of other authors: ", 100 - (counter / len(finished_df) * 100))
print("Number of manually triggered tasks:", len(finished_df))

percentage of participants running their own tasks:  92.94117647058823
percentage of participants running tasks of other authors:  7.058823529411768
Number of manually triggered tasks: 85

Did they run the task on the whole text or selected text?

In [60]:
task_runs = finished_participants[finished_participants["event"] == "TASK_RUN"]
whole_text_run = 0
selected_text_run = 0

for idx, row in task_runs.iterrows():
    info = json.loads(row["data"])

    if 'annotated_text' in info:
        selected_text_run += 1
    else:
        whole_text_run += 1

print("Whole text run: ", whole_text_run)
print("Selected text run: ", selected_text_run)

Whole text run:  52
Selected text run:  13

Count of shortcut runs

In [61]:
# number of shortcut runs
print(finished_participants[finished_participants["event"] == "TASK_SHORTCUT_RUN"]['id'].count())

20

Timeline analysis

In [62]:
def consecutive_focus_event_rows(event_df, fieldname, bypass = []):
    consecutive_rows_list = []
    for n, g in event_df.groupby(['participant_id', (event_df[fieldname] != event_df[fieldname].shift()).cumsum()]):
        code_list = g[fieldname].tolist()
        
        if code_list[0] in bypass:
            for index, row in g.iterrows():
                
                consecutive_rows_list.append({
                    'participant_id': row['participant_id'],
                    fieldname: code_list[0],
                    'participant_token': row['participant_token'],
                    'consecutive_rows': [code_list[0]],
                    'length': -1,
                    'from_id': row['id'],
                    'to_id': row['id'],
                    'from_time': row['time'],
                    'to_time': row['time']
                   # 'state': state
                })
            
        else: 
            consecutive_rows_list.append({
                'participant_id': n[0],
                fieldname: code_list[0],
                'participant_token': g['participant_token'].iloc[0],
                'consecutive_rows': code_list,
                'length': len(code_list),
                'from_id': g['id'].iloc[0],
                'to_id': g['id'].iloc[-1],
                'from_time': g['time'].iloc[0],
                'to_time': g['time'].iloc[-1]
               # 'state': state
            })

    consecutive_rows_columns = ['participant_id', fieldname, 'participant_token', 'consecutive_rows', 'length', 'from_id', 'to_id', 'from_time', 'to_time']
    return pd.DataFrame(data = consecutive_rows_list, columns = consecutive_rows_columns)

In [63]:
def prepare_events_for_timeline(event_df, fieldname):
    rows = []
    for index, row in event_df.iterrows():
        rows.append({
            'participant_id': row['participant_id'],
            fieldname: row[fieldname],
            'participant_token': row['participant_token'],
            'id': row['id'],
            'time': row['time']
        })
        
    columns = ['participant_id', fieldname, 'participant_token','id', 'time']
    return pd.DataFrame(data = rows, columns = columns)

In [64]:
# TIMELINE:

document_view_df = parse_generic_event(finished_participants, "DOCUMENT_VIEW")
task_view_df = parse_generic_event(finished_participants, "TASK_VIEW")
agents_view_df = parse_generic_event(finished_participants, "AGENTS_VIEW")

agent_save_df = parse_generic_event(finished_participants, "AGENT_SAVE")
preset_use_df = parse_generic_event(finished_participants, "AGENT_PRESET_USE")

focus_events_df = finished_participants[finished_participants['event'].isin(["DOCUMENT_VIEW", 'TASKS_VIEW', 'TASKS_VIEW_CLOSE', 'AGENTS_VIEW', 'AGENTS_VIEW_CLOSE', 'FINAL_PROCEED_TEXT', 'AGENT_CREATE', 'AGENT_SAVE', 'AGENT_PRESET_USE'])]

consecutive_focus_events_df = consecutive_focus_event_rows(focus_events_df, 'event', ['AGENT_CREATE', 'AGENT_SAVE', 'AGENT_PRESET_USE'])
prepared_focus_events_df = prepare_events_for_timeline(focus_events_df, 'event')

# transform times to datetime
consecutive_focus_events_df = transform_time(consecutive_focus_events_df, 'from_time')
consecutive_focus_events_df = transform_time(consecutive_focus_events_df, 'to_time')

prepared_focus_events_df = transform_time(prepared_focus_events_df, 'time')



clean_consecutive_focus_events_df = remove_events_while_interviewing(consecutive_focus_events_df, remove_events_starting_from)
# drop events of 1378, since this participant only viewed the taskview once, and then never had another important agent or task event
entries = clean_consecutive_focus_events_df[clean_consecutive_focus_events_df['participant_id'] == 1378]
clean_consecutive_focus_events_df = clean_consecutive_focus_events_df.drop(entries.index)

participant_focus_events = clean_consecutive_focus_events_df.groupby(['participant_id'])


print(participant_focus_events)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x73ffa834e850>

In [65]:
# get min max for each group

# Important: we consider the cleaned consecutive focus events, these events do not contain the events that happened in the final interviews.
# The windows of times (min - max) are thus shorter.

minmaxtimes_participants = {}
for pg in participants_groups:
    pg_events = clean_consecutive_focus_events_df[clean_consecutive_focus_events_df['participant_id'].isin(participants_groups[pg]["users"])]
    #display(pg_events)
    min_time = pg_events['from_time'].min()
    max_time = pg_events['to_time'].max()

    for p in participants_groups[pg]["users"]:
        minmaxtimes_participants[p] = {"min": min_time, "max": max_time}

display(minmaxtimes_participants)

{1379: {'min': Timestamp('2025-03-10 07:43:55.548000'),
  'max': Timestamp('2025-03-10 08:42:46.563000')},
 1380: {'min': Timestamp('2025-03-10 07:43:55.548000'),
  'max': Timestamp('2025-03-10 08:42:46.563000')},
 1376: {'min': Timestamp('2025-03-07 21:33:49.808000'),
  'max': Timestamp('2025-03-07 21:50:55.943000')},
 1377: {'min': Timestamp('2025-03-07 21:33:49.808000'),
  'max': Timestamp('2025-03-07 21:50:55.943000')},
 1378: {'min': Timestamp('2025-03-09 20:29:39.476000'),
  'max': Timestamp('2025-03-10 14:44:50.308000')},
 1374: {'min': Timestamp('2025-03-09 20:29:39.476000'),
  'max': Timestamp('2025-03-10 14:44:50.308000')},
 1383: {'min': Timestamp('2025-03-14 15:02:19.172000'),
  'max': Timestamp('2025-03-28 12:40:02.313000')},
 1384: {'min': Timestamp('2025-03-14 15:02:19.172000'),
  'max': Timestamp('2025-03-28 12:40:02.313000')},
 1385: {'min': Timestamp('2025-03-14 15:02:19.172000'),
  'max': Timestamp('2025-03-28 12:40:02.313000')},
 1387: {'min': Timestamp('2025-03-15 19:42:15.666000'),
  'max': Timestamp('2025-03-15 20:09:12.496000')},
 1390: {'min': Timestamp('2025-03-15 19:42:15.666000'),
  'max': Timestamp('2025-03-15 20:09:12.496000')},
 1388: {'min': Timestamp('2025-03-17 14:12:51.247000'),
  'max': Timestamp('2025-03-17 15:07:47.510000')},
 1389: {'min': Timestamp('2025-03-17 14:12:51.247000'),
  'max': Timestamp('2025-03-17 15:07:47.510000')},
 2456: {'min': Timestamp('2025-07-25 10:23:21.647000'),
  'max': Timestamp('2025-07-29 12:44:49.969000')},
 2460: {'min': Timestamp('2025-07-25 10:23:21.647000'),
  'max': Timestamp('2025-07-29 12:44:49.969000')},
 2453: {'min': Timestamp('2025-07-21 07:01:47.239000'),
  'max': Timestamp('2025-07-23 13:47:49.366000')},
 2455: {'min': Timestamp('2025-07-21 07:01:47.239000'),
  'max': Timestamp('2025-07-23 13:47:49.366000')},
 2461: {'min': Timestamp('2025-07-29 15:55:03.782000'),
  'max': Timestamp('2025-07-31 21:42:38.358000')},
 2464: {'min': Timestamp('2025-07-29 15:55:03.782000'),
  'max': Timestamp('2025-07-31 21:42:38.358000')},
 2457: {'min': Timestamp('2025-07-29 15:55:03.782000'),
  'max': Timestamp('2025-07-31 21:42:38.358000')},
 2459: {'min': Timestamp('2025-07-29 12:17:56.909000'),
  'max': Timestamp('2025-07-31 21:13:05.168000')},
 2465: {'min': Timestamp('2025-07-29 12:17:56.909000'),
  'max': Timestamp('2025-07-31 21:13:05.168000')},
 2463: {'min': Timestamp('2025-07-30 09:34:50.015000'),
  'max': Timestamp('2025-08-22 18:29:10.543000')},
 2475: {'min': Timestamp('2025-07-30 09:34:50.015000'),
  'max': Timestamp('2025-08-22 18:29:10.543000')},
 2468: {'min': Timestamp('2025-08-10 06:47:33.803000'),
  'max': Timestamp('2025-08-15 07:43:41.191000')},
 2469: {'min': Timestamp('2025-08-10 06:47:33.803000'),
  'max': Timestamp('2025-08-15 07:43:41.191000')},
 2467: {'min': NaT, 'max': NaT},
 2476: {'min': NaT, 'max': NaT},
 2470: {'min': Timestamp('2025-08-14 17:49:01.651000'),
  'max': Timestamp('2025-08-14 18:21:22.659000')},
 2471: {'min': Timestamp('2025-08-14 17:49:01.651000'),
  'max': Timestamp('2025-08-14 18:21:22.659000')}}

[I] When tasks were created

In [66]:
display(study_tasks)

display(parsed_task_created_df)
display(groups_df)


print("db events that appear / do not appear in the events")

display(study_tasks[~study_tasks['_id'].isin(parsed_task_created_df['task.id'])])


# user 1389 did create two tasks, but they do not appear in the event logs: 67dd3e6dedfe680c1b0f167b, 67dd416bedfe680c1b0f1688

task_creation_percentages = []
for p in minmaxtimes_participants:
    min_time = minmaxtimes_participants[p]['min']
    max_time = minmaxtimes_participants[p]['max']
    session_length = (max_time - min_time).total_seconds()
 
    user_tasks = parsed_task_created_df[(parsed_task_created_df['participant_id'] == p)]
    for index, row in user_tasks.iterrows():
        group_id = groups_df[groups_df['user'] == p].iloc[0]['group_id']
        diff = (row['time'] - min_time).total_seconds()
        print(row, min_time)
        percentage_of_time = 100 / session_length * diff
        task_creation_percentages.append([p, group_id, percentage_of_time])

time_to_creation_percentage = pd.DataFrame(data=task_creation_percentages, columns=['user', 'group_id', 'time_percentage'])

display(time_to_creation_percentage[time_to_creation_percentage['time_percentage'] < 25])
display(100 / len(parsed_task_created_df) * len(time_to_creation_percentage[time_to_creation_percentage['time_percentage'] < 25]))
display(time_to_creation_percentage[(time_to_creation_percentage['time_percentage'] > 25) & (time_to_creation_percentage['time_percentage'] < 50)])
display(100 / len(parsed_task_created_df) * len(time_to_creation_percentage[(time_to_creation_percentage['time_percentage'] > 25) & (time_to_creation_percentage['time_percentage'] < 50)]))
display(time_to_creation_percentage[(time_to_creation_percentage['time_percentage'] > 50) & (time_to_creation_percentage['time_percentage'] < 75)])
display(100 / len(parsed_task_created_df) * len(time_to_creation_percentage[(time_to_creation_percentage['time_percentage'] > 50) & (time_to_creation_percentage['time_percentage'] < 75)]))
display(time_to_creation_percentage[time_to_creation_percentage['time_percentage'] > 75])
display(100 / len(parsed_task_created_df) * len(time_to_creation_percentage[time_to_creation_percentage['time_percentage'] > 75]))

,group_id,user,document,_id,assignee_ids,description,document_id,interaction_type,is_shortcut,author_id,progress,title,advanced_trigger_settings.interaction_trigger
0,1,1379,67ce983b285fac3f07bcf5e8,67ce9934285fac3f07bcf5ea,[ai-author],We nned to write an essay together about the p...,67ce983b285fac3f07bcf5e8,MANUAL,False,67ce982f285fac3f07bcf5e7,[],AI Pros and Cons Essay,EACH_MINUTES
1,1,1379,67ce983b285fac3f07bcf5e8,67cea2a4285fac3f07bcf5f8,[ai-author],Check the grammar of the text,67ce983b285fac3f07bcf5e8,AUTONOMOUS_COMMENT,False,67ce982f285fac3f07bcf5e7,"[{'created_time': 1741595328026, 'selected_tex...",Proofreading,EACH_MINUTES
2,1,1380,67ce983b285fac3f07bcf5e8,67cea021285fac3f07bcf5f6,[ai-author],Make the text shorter,67ce983b285fac3f07bcf5e8,MANUAL,True,67ce9cb4285fac3f07bcf5ec,[],Shorten the Text,EACH_MINUTES
3,1,1380,67ce983b285fac3f07bcf5e8,67cea0e1285fac3f07bcf5f7,[ai-author],Give it more scientific and professional style.,67ce983b285fac3f07bcf5e8,MANUAL,True,67ce9cb4285fac3f07bcf5ec,[],Enhance Professional Tone,EACH_MINUTES
4,2,1376,67c97527285fac3f07bcf587,67cb687a285fac3f07bcf5a4,[ai-author],write the part where u talk about pros of AI,67c97527285fac3f07bcf587,MANUAL,False,67cb6627285fac3f07bcf59b,"[{'created_time': 1741383860335, 'selected_tex...",Pros of AI,EACH_MINUTES
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,13,2467,68907a6e87cf5fec60dc8107,68a5b9e6e90ffc190a96c31f,[68a5acf4e90ffc190a96c309],"Verbessere (nur!!) die Formulierung, ohne den ...",68907a6e87cf5fec60dc8107,MANUAL,True,68a5a0bde90ffc190a96c2ff,"[{'created_time': 1755697070379, 'selected_tex...",Formulierung verbessern,EACH_MINUTES
60,13,2476,68907a6e87cf5fec60dc8107,68a5d43ae90ffc190a96c32c,[68a59949e90ffc190a96c2f7],Looking cool joker!,68907a6e87cf5fec60dc8107,MANUAL,False,68a59766e90ffc190a96c2f4,"[{'created_time': 1755698261822, 'selected_tex...",Cool Joker Look,EACH_MINUTES
61,13,2476,68907a6e87cf5fec60dc8107,68a5d754e90ffc190a96c335,[68a5d73ee90ffc190a96c334],vervollständigen,68907a6e87cf5fec60dc8107,MANUAL,True,68a59766e90ffc190a96c2f4,"[{'created_time': 1755699561177, 'selected_tex...",Aufgaben vervollständigen,EACH_MINUTES
62,13,2476,68907a6e87cf5fec60dc8107,68a5dbe6e90ffc190a96c33f,[68a5acf4e90ffc190a96c309],bewerte und korrigiere die struktur und den sp...,68907a6e87cf5fec60dc8107,MANUAL,False,68a59766e90ffc190a96c2f4,[],Antragsstruktur und Sprache korrigieren,EACH_MINUTES
64,14,2471,6896071ee90ffc190a96c285,689e28e7e90ffc190a96c2ec,"[ai-author, 689e2470e90ffc190a96c2e4, 689e24b5...","Make the text more interesting to read, and a ...",6896071ee90ffc190a96c285,MANUAL,False,689e22d5e90ffc190a96c2e0,"[{'created_time': 1755195709128, 'selected_tex...",Enhance Deutsche Telekom Text,EACH_MINUTES

,id,time,participant_id,data,event,event_uuid,participant_token,data_parsed,user_id_x,username,...,task.author_id,task.description,task.is_shortcut,task.assignee_ids,task.interaction_type,task.advanced_trigger_settings.interaction_trigger,group_id,user,user_id_y,document
0,276233.0,2025-03-07 21:42:15.163,1377,"{""task"": {""id"": ""67cb6837285fac3f07bcf59f"", ""t...",TASK_CREATED,db778a6d-ecea-48ad-95af-34ba3f05a1bd,2aac5afe-a3af-4135-a1a3-78adf87ae9d8,"{'task': {'id': '67cb6837285fac3f07bcf59f', 't...",67cb6623285fac3f07bcf59a,adambokun,...,67cb6623285fac3f07bcf59a,Write intro for the essay,False,[ai-author],MANUAL,EACH_MINUTES,2,1377,67cb6623285fac3f07bcf59a,67c97527285fac3f07bcf587
1,276268.0,2025-03-07 21:43:22.511,1376,"{""task"": {""id"": ""67cb687a285fac3f07bcf5a4"", ""t...",TASK_CREATED,84017059-2690-4936-980b-f5333f85d934,a5bbafd1-4ef0-49e4-95bd-65170953633c,"{'task': {'id': '67cb687a285fac3f07bcf5a4', 't...",67cb6627285fac3f07bcf59b,wolfova,...,67cb6627285fac3f07bcf59b,write the part where u talk about pros of AI,False,[ai-author],MANUAL,EACH_MINUTES,2,1376,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587
2,276317.0,2025-03-07 21:45:35.824,1377,"{""task"": {""id"": ""67cb68ff285fac3f07bcf5a8"", ""t...",TASK_CREATED,4e191fcc-fdea-4024-8ab9-2c3dacf44b3b,2aac5afe-a3af-4135-a1a3-78adf87ae9d8,"{'task': {'id': '67cb68ff285fac3f07bcf5a8', 't...",67cb6623285fac3f07bcf59a,adambokun,...,67cb6623285fac3f07bcf59a,Write cons of AI,False,[ai-author],AUTONOMOUS_COMMENT,EACH_MINUTES,2,1377,67cb6623285fac3f07bcf59a,67c97527285fac3f07bcf587
3,276335.0,2025-03-07 21:46:05.445,1376,"{""task"": {""id"": ""67cb691d285fac3f07bcf5ac"", ""t...",TASK_CREATED,d2250740-98b2-4a96-81e0-e95c9ec2aad6,a5bbafd1-4ef0-49e4-95bd-65170953633c,"{'task': {'id': '67cb691d285fac3f07bcf5ac', 't...",67cb6627285fac3f07bcf59b,wolfova,...,67cb6627285fac3f07bcf59b,write the zusamenfassung for our essay based o...,False,[ai-author],MANUAL,EACH_MINUTES,2,1376,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587
4,276370.0,2025-03-07 21:48:56.770,1376,"{""task"": {""id"": ""67cb69c8285fac3f07bcf5b2"", ""t...",TASK_CREATED,3f7fdb58-c32d-47a8-bbfe-36e1b56950cf,a5bbafd1-4ef0-49e4-95bd-65170953633c,"{'task': {'id': '67cb69c8285fac3f07bcf5b2', 't...",67cb6627285fac3f07bcf59b,wolfova,...,67cb6627285fac3f07bcf59b,can u edit our text as the scientific paper wi...,False,[ai-author],MANUAL,EACH_MINUTES,2,1376,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587
5,276488.0,2025-03-09 20:42:12.823,1374,"{""task"": {""id"": ""67cdfd24285fac3f07bcf5d1"", ""t...",TASK_CREATED,f481ec92-ac67-4137-b0fc-3b5544241b6d,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67cdfd24285fac3f07bcf5d1', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,Read the written part of text. Highlight gramm...,False,[67cdfc85285fac3f07bcf5cf],AUTONOMOUS_COMMENT,DOCUMENT_SAVE,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
6,276522.0,2025-03-09 20:51:40.848,1374,"{""task"": {""id"": ""67cdff5c285fac3f07bcf5d4"", ""t...",TASK_CREATED,6366f36d-2e03-4675-b9ad-401af89c86dc,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67cdff5c285fac3f07bcf5d4', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,Check the selected text and provide some scien...,True,[67cdfef4285fac3f07bcf5d3],MANUAL,EACH_MINUTES,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
7,276525.0,2025-03-09 20:59:38.568,1374,"{""task"": {""id"": ""67ce013a285fac3f07bcf5d6"", ""t...",TASK_CREATED,65e32235-d117-4745-8178-fabb272347d2,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67ce013a285fac3f07bcf5d6', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,Considering the topic and the latest available...,False,[67cdfc85285fac3f07bcf5cf],AUTONOMOUS_COMMENT,MINUTES_INACTIVITY,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
8,276720.0,2025-03-10 07:48:04.549,1379,"{""task"": {""id"": ""67ce9934285fac3f07bcf5ea"", ""t...",TASK_CREATED,5c7f52ba-11d9-49d0-82fe-f80ae474602d,6573f86e-0207-4286-b036-a83f25a630c3,"{'task': {'id': '67ce9934285fac3f07bcf5ea', 't...",67ce982f285fac3f07bcf5e7,galina.akhunzhanova@uni-bayreuth.de,...,67ce982f285fac3f07bcf5e7,We nned to write an essay together about the p...,False,[ai-author],MANUAL,EACH_MINUTES,1,1379,67ce982f285fac3f07bcf5e7,67ce983b285fac3f07bcf5e8
9,276834.0,2025-03-10 08:07:29.198,1380,"{""task"": {""id"": ""67ce9dc1285fac3f07bcf5ed"", ""t...",TASK_CREATED,ac8ce41a-2924-423c-8391-5836ad505c5c,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'task': {'id': '67ce9dc1285fac3f07bcf5ed', 't...",67ce9cb4285fac3f07bcf5ec,mrnexeon,...,67ce9cb4285fac3f07bcf5ec,Generate essay for Health and Wellness in the ...,False,[ai-author],MANUAL,EACH_MINUTES,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8
10,277090.0,2025-03-10 08:17:37.082,1380,"{""task"": {""id"": ""67cea021285fac3f07bcf5f6"", ""t...",TASK_CREATED,cbb15f70-59bd-4597-a3c0-7e7e23659967,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'task': {'id': '67cea021285fac3f07bcf5f6', 't...",67ce9cb4285fac3f07bcf5ec,mrnexeon,...,67ce9cb4285fac3f07bcf5ec,Make the text shorter,True,[ai-author],MANUAL,EACH_MINUTES,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8
11,277154.0,2025-03-10 08:20:48.986,1380,"{""task"": {""id"": ""67cea0e1285fac3f07bcf5f7"", ""t...",TASK_CREATED,3829f97d-7e6f-4338-97e9-8922ae639e46,ecc027d0-42cd-42a1-bc2e-990b5516565b,"{'task': {'id': '67cea0e1285fac3f07bcf5f7', 't...",67ce9cb4285fac3f07bcf5ec,mrnexeon,...,67ce9cb4285fac3f07bcf5ec,Give it more scientific and professional style.,True,[ai-author],MANUAL,EACH_MINUTES,1,1380,67ce9cb4285fac3f07bcf5ec,67ce983b285fac3f07bcf5e8
12,277296.0,2025-03-10 08:28:20.299,1379,"{""task"": {""id"": ""67cea2a4285fac3f07bcf5f8"", ""t...",TASK_CREATED,e5caab1f-f8c6-4c2c-a52f-651f5479ce57,6573f86e-0207-4286-b036-a83f25a630c3,"{'task': {'id': '67cea2a4285fac3f07bcf5f8', 't...",67ce982f285fac3f07bcf5e7,galina.akhunzhanova@uni-bayreuth.de,...,67ce982f285fac3f07bcf5e7,write a conclusion of the given text,False,[ai-author],MANUAL,EACH_MINUTES,1,1379,67ce982f285fac3f07bcf5e7,67ce983b285fac3f07bcf5e8
13,277627.0,2025-03-10 13:03:42.340,1374,"{""task"": {""id"": ""67cee32e285fac3f07bcf60e"", ""t...",TASK_CREATED,ee65bf1a-de89-40e0-95a2-f9e4920973b8,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,"{'task': {'id': '67cee32e285fac3f07bcf60e', 't...",67cdfa30285fac3f07bcf5cc,Ivan Khrop,...,67cdfa30285fac3f07bcf5cc,The agent should analyze the selected advantag...,True,[ai-author],MANUAL,EACH_MINUTES,3,1374,67cdfa30285fac3f07bcf5cc,67c88f88285fac3f07bcf585
14,278328.0,2025-03-15 19:45:48.555,1387,"{""task"": {""id"": ""67d5d8eb0b9539e69a3a86e0"", ""t...",TASK_CREATED,9c60b815-bf29-4c74-96c5-8a6fd424eccc,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'task': {'id': '67d5d8eb0b9539e69a3a86e0', 't...",67d5d8120b9539e69a3a86d7,Ilya School,...,67d5d8120b9539e69a3a86d7,Check the text,False,[67d5d8cf0b9539e69a3a86df],MANUAL,EACH_MINUTES,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8
15,278356.0,2025-03-15 19:48:19.303,1387,"{""task"": {""id"": ""67d5d9820b9539e69a3a86e4"", ""t...",TASK_CREATED,be2b7de6-1999-4a92-8b40-f1d6537f0177,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'task': {'id': '67d5d9820b9539e69a3a86e4', 't...",67d5d8120b9539e69a3a86d7,Ilya School,...,67d5d8120b9539e69a3a86d7,Check the language mistakes in the text,False,[67d5d88f0b9539e69a3a86dc],MANUAL,EACH_MINUTES,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8
16,278364.0,2025-03-15 19:49:02.993,1387,"{""task"": {""id"": ""67d5d9ae0b9539e69a3a86e7"", ""t...",TASK_CREATED,4ed7fd96-a7f3-4ad2-8e94-65c2e67f9fd7,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'task': {'id': '67d5d9ae0b9539e69a3a86e7', 't...",67d5d8120b9539e69a3a86d7,Ilya School,...,67d5d8120b9539e69a3a86d7,Check if the text flow is good and give counci...,True,[67d5d88b0b9539e69a3a86db],MANUAL,EACH_MINUTES,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8
17,278513.0,2025-03-15 20:09:10.218,1387,"{""task"": {""id"": ""67d5de650b9539e69a3a86f0"", ""t...",TASK_CREATED,924ec8a5-4324-4db5-b6a4-6867d5b15b9e,5b6b66f7-99db-48a1-b61a-0eaf97a1c8fc,"{'task': {'id': '67d5de650b9539e69a3a86f0', 't...",67d5d8120b9539e69a3a86d7,Ilya School,...,67d5d8120b9539e69a3a86d7,Give advices on how to name each paragraph and...,False,[67d5d88b0b9539e69a3a86db],MANUAL,EACH_MINUTES,5,1387,67d5d8120b9539e69a3a86d7,67d5d8160b9539e69a3a86d8
18,278531.0,2025-03-17 14:13:39.600,1388,"{""task"": {""id"": ""67d82e13edfe680c1b0f1644"", ""t...",TASK_CREATED,77838901-2c3d-479c-91bb-850b015aa782,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d82e13edfe680c1b0f1644', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,Write me a text about ai pros and cons,False,[ai-author],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
19,278585.0,2025-03-17 14:19:51.541,1388,"{""task"": {""id"": ""67d82f87edfe680c1b0f164b"", ""t...",TASK_CREATED,c0aa28e5-9f26-4920-9aaf-de824534ca92,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d82f87edfe680c1b0f164b', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,check the text find mistakes,False,[67d82f6dedfe680c1b0f164a],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
20,278651.0,2025-03-17 14:32:41.482,1389,"{""task"": {""id"": ""67d83292edfe680c1b0f164f"", ""t...",TASK_CREATED,fdf935f9-73dc-419a-89cf-b3f950e5c612,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'task': {'id': '67d83292edfe680c1b0f164f', 't...",67d82e0aedfe680c1b0f1643,Du-Al-Dos,...,67d82e0aedfe680c1b0f1643,add citations,False,[67d82fbfedfe680c1b0f164e],MANUAL,EACH_MINUTES,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b
21,278710.0,2025-03-17 14:39:49.958,1388,"{""task"": {""id"": ""67d83435edfe680c1b0f1656"", ""t...",TASK_CREATED,9c7b3a4f-4a1f-493d-892a-18915d1e876b,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d83435edfe680c1b0f1656', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,can you help with generating more ideas so the...,False,[67d83410edfe680c1b0f1655],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
22,278761.0,2025-03-17 14:42:24.175,1388,"{""task"": {""id"": ""67d834cfedfe680c1b0f165a"", ""t...",TASK_CREATED,137aed4c-6186-42f5-b049-c31301c23939,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d834cfedfe680c1b0f165a', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,"check the text, make it look good as an essay,...",False,[ai-author],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
23,278844.0,2025-03-17 14:45:55.066,1388,"{""task"": {""id"": ""67d835a2edfe680c1b0f165f"", ""t...",TASK_CREATED,72b3f17a-5387-41df-a594-8def8730ecaa,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d835a2edfe680c1b0f165f', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,delete everything what doesn´t make sense,False,[67d83558edfe680c1b0f165e],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
24,278896.0,2025-03-17 14:57:18.400,1389,"{""task"": {""id"": ""67d83857edfe680c1b0f1667"", ""t...",TASK_CREATED,e52d5be7-baf6-45f9-ba0b-ec659ae68459,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,"{'task': {'id': '67d83857edfe680c1b0f1667', 't...",67d82e0aedfe680c1b0f1643,Du-Al-Dos,...,67d82e0aedfe680c1b0f1643,Add an introduction and a conclusion part. Add...,False,[ai-author],MANUAL,EACH_MINUTES,6,1389,67d82e0aedfe680c1b0f1643,67d08e87285fac3f07bcf64b
25,278949.0,2025-03-17 15:07:40.309,1388,"{""task"": {""id"": ""67d83abbedfe680c1b0f166c"", ""t...",TASK_CREATED,9d4a5ac5-b70e-4a58-ad34-20b40a37d7f5,3b49f849-3081-4478-81ce-d65450662c47,"{'task': {'id': '67d83abbedfe680c1b0f166c', 't...",67d82dc4edfe680c1b0f1642,sanapht,...,67d82dc4edfe680c1b0f1642,help me make it prettier,False,[67d82f6dedfe680c1b0f164a],MANUAL,EACH_MINUTES,6,1388,67d82dc4edfe680c1b0f1642,67d08e87285fac3f07bcf64b
27,279983.0,2025-07-28 13:53:30.643,2456,"{""task"": {""id"": ""688780da87cf5fec60dc803b"", ""t...",TASK_CREATED,5e882802-f57f-45dc-9f35-87498c8bc093,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'task': {'id': '688780da87cf5fec60dc803b', 't...",68835b0587cf5fec60dc8020,Anass Q.,...,68835b0587cf5fec60dc8020,This is an Essay about Artificial intelligence...,False,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d
28,280037.0,2025-07-28 14:05:14.114,2456,"{""task"": {""id"": ""6887839a87cf5fec60dc803f"", ""t...",TASK_CREATED,41f9612d-3d83-48bb-bcd6-2057dccb71b2,ee84f721-81d3-4914-b1a4-09de1502b0bc,"{'task': {'id': '6887839a87cf5fec60dc803f', 't...",68835b0587cf5fec60dc8020,Anass Q.,...,68835b0587cf5fec60dc8020,"Oversee the provided text and make sure, it's ...",False,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2456,68835b0587cf5fec60dc8020,68833fd687cf5fec60dc801d
29,280481.0,2025-07-28 17:58:50.790,2460,"{""task"": {""id"": ""6887ba5a87cf5fec60dc8061"", ""t...",TASK_CREATED,790ff8a7-497c-46fc-bc51-afc75fd6ec39,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6887ba5a87cf5fec60dc8061', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,make text shorter\n,False,[ai-author],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
30,280521.0,2025-07-28 18:00:41.738,2460,"{""task"": {""id"": ""6887bac987cf5fec60dc8062"", ""t...",TASK_CREATED,ed1db37e-3231-40c0-86db-79f77cfdc59a,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6887bac987cf5fec60dc8062', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,MAke it more literature based,False,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
31,280625.0,2025-07-29 11:46:53.865,2460,"{""task"": {""id"": ""6888b4ad87cf5fec60dc806a"", ""t...",TASK_CREATED,a354a782-7bd7-4b53-a551-057aa5a24415,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6888b4ad87cf5fec60dc806a', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,Add some interesting facts,True,[ai-author],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
32,280682.0,2025-07-29 11:51:13.438,2460,"{""task"": {""id"": ""6888b5b187cf5fec60dc806b"", ""t...",TASK_CREATED,afbcba64-39b7-4f39-b94c-6632d247039f,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,"{'task': {'id': '6888b5b187cf5fec60dc806b', 't...",6887b97087cf5fec60dc8060,Naira,...,6887b97087cf5fec60dc8060,Summarize the text before,True,[6887772287cf5fec60dc8036],MANUAL,EACH_MINUTES,7,2460,6887b97087cf5fec60dc8060,68833fd687cf5fec60dc801d
33,280903.0,2025-07-29 12:24:32.837,2459,"{""task"": {""id"": ""6888bd8087cf5fec60dc8074"", ""t...",TASK_CREATED,4d7f4220-fef6-4492-bd4c-265fd6ab08d8,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'task': {'id': '6888bd8087cf5fec60dc8074', 't...",6888bbce87cf5fec60dc8072,ainalinngeorges,...,6888bbce87cf5fec60dc8072,Create categories for planning a wedding,False,[6888bd4b87cf5fec60dc8073],MANUAL,EACH_MINUTES,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda
34,280924.0,2025-07-29 12:30:35.646,2459,"{""task"": {""id"": ""6888beeb87cf5fec60dc8077"", ""t...",TASK_CREATED,73feda0f-25da-4a8d-88c0-093c51356742,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'task': {'id': '6888beeb87cf5fec60dc8077', 't...",6888bbce87cf5fec60dc8072,ainalinngeorges,...,6888bbce87cf5fec60dc8072,make headers for the different categories of p...,False,[6888bd4b87cf5fec60dc8073],MANUAL,EACH_MINUTES,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda
35,281006.0,2025-07-29 13:17:32.275,2459,"{""task"": {""id"": ""6888c9ec87cf5fec60dc8082"", ""t...",TASK_CREATED,3cd89847-508c-4c44-a515-2ceb97372800,a1f051f1-f2f3-45e1-9274-7deb05f97604,"{'task': {'id': '6888c9ec87cf5fec60dc8082', 't...",6888bbce87cf5fec60dc8072,ainalinngeorges,...,6888bbce87cf5fec60dc8072,Highlight each item that needs to be purchased...,True,[6888c9af87cf5fec60dc8081],MANUAL,EACH_MINUTES,10,2459,6888bbce87cf5fec60dc8072,6877c26e87cf5fec60dc7fda
36,281089.0,2025-07-29 15:57:28.484,2461,"{""task"": {""id"": ""6888ef6887cf5fec60dc8086"", ""t...",TASK_CREATED,2e3afa3b-f9de-4684-be0d-c571c532d6a4,46820311-be03-4d2e-b993-90ac3bec3c92,"{'task': {'id': '6888ef6887cf5fec60dc8086', 't...",6888eec887cf5fec60dc8085,vama00004,...,6888eec887cf5fec60dc8085,Write a blog in 1000 words about the given title,False,[ai-author],MANUAL,EACH_MINUTES,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026
37,281217.0,2025-07-30 18:45:11.132,2464,"{""task"": {""id"": ""688a683587cf5fec60dc809a"", ""t...",TASK_CREATED,3f515ab0-3ced-40c0-b819-76c0e00b6cd3,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'task': {'id': '688a683587cf5fec60dc809a', 't...",688a52ad87cf5fec60dc8096,snehachetani,...,688a52ad87cf5fec60dc8096,Check all the spellings and grammars,False,[ai-author],MANUAL,EACH_MINUTES,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026
38,281241.0,2025-07-30 18:49:30.273,2464,"{""task"": {""id"": ""688a693887cf5fec60dc809f"", ""t...",TASK_CREATED,1b5fb65e-4a41-4c99-8b17-98b44a83e552,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'task': {'id': '688a693887cf5fec60dc809f', 't...",688a52ad87cf5fec60dc8096,snehachetani,...,688a52ad87cf5fec60dc8096,Check spellings and grammars,False,[ai-author],MANUAL,EACH_MINUTES,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026
39,281282.0,2025-07-30 18:53:58.337,2464,"{""task"": {""id"": ""688a6a4487cf5fec60dc80a3"", ""t...",TASK_CREATED,8ab0ad14-b806-472e-a6c4-06bb2402cab1,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'task': {'id': '688a6a4487cf5fec60dc80a3', 't...",688a52ad87cf5fec60dc8096,snehachetani,...,688a52ad87cf5fec60dc8096,,False,[688a6a2087cf5fec60dc80a2],MANUAL,EACH_MINUTES,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026
40,281291.0,2025-07-30 18:54:40.632,2464,"{""task"": {""id"": ""688a6a6f87cf5fec60dc80a6"", ""t...",TASK_CREATED,397074a5-d05f-45d3-8f1a-2674387536b5,5a6b1f2c-f401-420f-b26d-46d9db679384,"{'task': {'id': '688a6a6f87cf5fec60dc80a6', 't...",688a52ad87cf5fec60dc8096,snehachetani,...,688a52ad87cf5fec60dc8096,check spellings,False,[688a6a2087cf5fec60dc80a2],MANUAL,EACH_MINUTES,9,2464,688a52ad87cf5fec60dc8096,688364bf87cf5fec60dc8026
41,281936.0,2025-07-31 15:28:11.162,2457,"{""task"": {""id"": ""688b8b8b87cf5fec60dc80c0"", ""t...",TASK_CREATED,54b69c9c-f5f6-4901-acec-0f0be66f392d,14291cb8-c3c7-433e-9a0c-830cca8e4422,"{'task': {'id': '688b8b8b87cf5fec60dc80c0', 't...",688b1c7887cf5fec60dc80b0,soumyashaw,...,688b1c7887cf5fec60dc80b0,Write a final paragraph at the end of the essay,False,[688b7f6b87cf5fec60dc80b7],MANUAL,EACH_MINUTES,9,2457,688b1c7887cf5fec60dc80b0,688364bf87cf5fec60dc8026
42,282001.0,2025-07-31 21:13:00.548,2465,"{""task"": {""id"": ""688bdc5c87cf5fec60dc80d1"", ""t...",TASK_CREATED,65eda403-df7b-4aa9-9ea0-2ae0c58f2ed4,20d63649-2146-4c8e-8861-14a647fdcd13,"{'task': {'id': '688bdc5c87cf5fec60dc80d1', 't...",688bdb6387cf5fec60dc80d0,joaobelo,...,688bdb6387cf5fec60dc80d0,Prepare a wedding celebration speech,False,[ai-author],MANUAL,EACH_MINUTES,10,2465,688bdb6387cf5fec60dc80d0,6877c26e87cf5fec60dc7fda
43,282106.0,2025-07-31 21:22:10.426,2461,"{""task"": {""id"": ""688bde8287cf5fec60dc80d7"", ""t...",TASK_CREATED,76265edc-2b18-4794-bd73-d2c4998b8f68,46820311-be03-4d2e-b993-90ac3bec3c92,"{'task': {'id': '688bde8287cf5fec60dc80d7', 't...",6888eec887cf5fec60dc8085,vama00004,...,6888eec887cf5fec60dc8085,Change the content of these paragraphs accordi...,False,[688bdddd87cf5fec60dc80d6],MANUAL,EACH_MINUTES,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026
44,282154.0,2025-07-31 21:26:04.489,2461,"{""task"": {""id"": ""688bdf6c87cf5fec60dc80db"", ""t...",TASK_CREATED,09923eaf-a782-4e6c-a346-aac8c2f18580,46820311-be03-4d2e-b993-90ac3bec3c92,"{'task': {'id': '688bdf6c87cf5fec60dc80db', 't...",6888eec887cf5fec60dc8085,vama00004,...,6888eec887cf5fec60dc8085,Rewrite content for the selected paragraphs gi...,True,[688bdddd87cf5fec60dc80d6],MANUAL,EACH_MINUTES,9,2461,6888eec887cf5fec60dc8085,688364bf87cf5fec60dc8026

    group_id  user                   user_id                  document
0          1  1379  67ce982f285fac3f07bcf5e7  67ce983b285fac3f07bcf5e8
1          1  1380  67ce9cb4285fac3f07bcf5ec  67ce983b285fac3f07bcf5e8
2          2  1376  67cb6627285fac3f07bcf59b  67c97527285fac3f07bcf587
3          2  1377  67cb6623285fac3f07bcf59a  67c97527285fac3f07bcf587
4          3  1378  67cc9f69285fac3f07bcf5c8  67c88f88285fac3f07bcf585
5          3  1374  67cdfa30285fac3f07bcf5cc  67c88f88285fac3f07bcf585
6          4  1383  67bc761a7a670b68746905a0  67d43b390b9539e69a3a86b9
7          4  1384  67d444dd0b9539e69a3a86bb  67d43b390b9539e69a3a86b9
8          4  1385  67bc43607a670b6874690577  67d43b390b9539e69a3a86b9
9          5  1387  67d5d8120b9539e69a3a86d7  67d5d8160b9539e69a3a86d8
10         5  1390  67e18e95edfe680c1b0f169f  67d5d8160b9539e69a3a86d8
11         6  1388  67d82dc4edfe680c1b0f1642  67d08e87285fac3f07bcf64b
12         6  1389  67d82e0aedfe680c1b0f1643  67d08e87285fac3f07bcf64b
13         7  2456  68835b0587cf5fec60dc8020  68833fd687cf5fec60dc801d
14         7  2460  6887b97087cf5fec60dc8060  68833fd687cf5fec60dc801d
15         8  2453  687de5d187cf5fec60dc7fef  6879e8fd87cf5fec60dc7fe1
16         8  2455  6880e0f187cf5fec60dc7ffe  6879e8fd87cf5fec60dc7fe1
17         9  2461  6888eec887cf5fec60dc8085  688364bf87cf5fec60dc8026
18         9  2464  688a52ad87cf5fec60dc8096  688364bf87cf5fec60dc8026
19         9  2457  688b1c7887cf5fec60dc80b0  688364bf87cf5fec60dc8026
20        10  2459  6888bbce87cf5fec60dc8072  6877c26e87cf5fec60dc7fda
21        10  2465  688bdb6387cf5fec60dc80d0  6877c26e87cf5fec60dc7fda
22        11  2463  6889e71f87cf5fec60dc8094  6889e57087cf5fec60dc8092
23        11  2475  68a75365ecc07d2944852275  6889e57087cf5fec60dc8092
24        12  2468  6898407be90ffc190a96c287  688c6add87cf5fec60dc80ef
25        12  2469  689c3c25e90ffc190a96c28b  688c6add87cf5fec60dc80ef
26        13  2467  68a5a0bde90ffc190a96c2ff  68907a6e87cf5fec60dc8107
27        13  2476  68a59766e90ffc190a96c2f4  68907a6e87cf5fec60dc8107
28        14  2470  689e2181e90ffc190a96c2df  6896071ee90ffc190a96c285
29        14  2471  689e22d5e90ffc190a96c2e0  6896071ee90ffc190a96c285

db events that appear / do not appear in the events

,group_id,user,document,_id,assignee_ids,description,document_id,interaction_type,is_shortcut,author_id,progress,title,advanced_trigger_settings.interaction_trigger
14,4,1383,67d43b390b9539e69a3a86b9,67e6924450d39f32454bf30d,"[67e691c850d39f32454bf30c, 67d445e30b9539e69a3...",Consistency Review of the whole document; disc...,67d43b390b9539e69a3a86b9,MANUAL,False,67bc761a7a670b68746905a0,[],Document Consistency Review,EACH_MINUTES
15,4,1383,67d43b390b9539e69a3a86b9,67e6947c50d39f32454bf311,[67d445d10b9539e69a3a86c1],Go through the whole text and make sure everyt...,67d43b390b9539e69a3a86b9,MANUAL,False,67bc761a7a670b68746905a0,[],American English Conversion,EACH_MINUTES
16,4,1384,67d43b390b9539e69a3a86b9,67e5c94550d39f32454bf2f4,[67d445d10b9539e69a3a86c1],Make sure the text does not sound like a blog ...,67d43b390b9539e69a3a86b9,MANUAL,True,67d444dd0b9539e69a3a86bb,[],Ensure Scientific Tone,EACH_MINUTES
17,4,1384,67d43b390b9539e69a3a86b9,67e5cc3e50d39f32454bf2fc,"[67e5cb6450d39f32454bf2fa, 67d445d10b9539e69a3...",Critically discuss the arguments made in this ...,67d43b390b9539e69a3a86b9,MANUAL,True,67d444dd0b9539e69a3a86bb,[],Critical Argument Analysis,EACH_MINUTES
18,4,1385,67d43b390b9539e69a3a86b9,67dd2e18edfe680c1b0f1674,[ai-author],Can you take the latex list below and build it...,67d43b390b9539e69a3a86b9,MANUAL,False,67bc43607a670b6874690577,[],Create Section Titles,EACH_MINUTES
19,4,1385,67d43b390b9539e69a3a86b9,67dd2fe2edfe680c1b0f1676,[67d445e30b9539e69a3a86c3],Review the section titles,67d43b390b9539e69a3a86b9,MANUAL,False,67bc43607a670b6874690577,"[{'created_time': 1742548989358, 'selected_tex...",Review Section Titles,EACH_MINUTES
20,4,1385,67d43b390b9539e69a3a86b9,67dd7b51edfe680c1b0f1693,[67d445e30b9539e69a3a86c3],Review complete paper,67d43b390b9539e69a3a86b9,AUTONOMOUS_COMMENT,False,67bc43607a670b6874690577,"[{'created_time': 1742570360969, 'selected_tex...",Paper Review Completion,USER_OFFLINE
24,5,1390,67d5d8160b9539e69a3a86d8,67e3eb8050d39f32454bf2eb,[ai-author],Could you formulate the main difference betwee...,67d5d8160b9539e69a3a86d8,MANUAL,False,67e18e95edfe680c1b0f169f,"[{'created_time': 1742990257332, 'selected_tex...",Interview Type Comparison,EACH_MINUTES
27,6,1389,67d08e87285fac3f07bcf64b,67dd3e6dedfe680c1b0f167b,[67dd3e52edfe680c1b0f167a],Review and rate our essay. Do not rewrite any ...,67d08e87285fac3f07bcf64b,MANUAL,False,67d82e0aedfe680c1b0f1643,"[{'created_time': 1742552726968, 'selected_tex...",Essay Review and Rating,EACH_MINUTES
28,6,1389,67d08e87285fac3f07bcf64b,67dd416bedfe680c1b0f1688,[67dd412dedfe680c1b0f1687],Translate the whole essay to german,67d08e87285fac3f07bcf64b,MANUAL,False,67d82e0aedfe680c1b0f1643,"[{'created_time': 1742553508102, 'selected_tex...",Translate Essay to German,EACH_MINUTES
35,8,2453,6879e8fd87cf5fec60dc7fe1,6880e33587cf5fec60dc8004,"[6880e03f87cf5fec60dc7ffb, 6880e0d087cf5fec60d...",Critique the discussion section and give your per,6879e8fd87cf5fec60dc7fe1,MANUAL,False,687de5d187cf5fec60dc7fef,"[{'created_time': 1753277347166, 'selected_tex...",Discussion Section Critique,EACH_MINUTES
46,10,2459,6877c26e87cf5fec60dc7fda,688bda1487cf5fec60dc80cd,[688bd9f587cf5fec60dc80cc],Scan text and create a list of tasks,6877c26e87cf5fec60dc7fda,MANUAL,False,6888bbce87cf5fec60dc8072,"[{'created_time': 1753995825795, 'selected_tex...",Text Scanning for Tasks,EACH_MINUTES
48,10,2465,6877c26e87cf5fec60dc7fda,688e34cb87cf5fec60dc80f8,[688e30ee87cf5fec60dc80f4],Find zones for improvement,6877c26e87cf5fec60dc7fda,AUTONOMOUS_COMMENT,False,688bdb6387cf5fec60dc80d0,"[{'created_time': 1754150126740, 'selected_tex...",Identify Improvement Areas,EACH_MINUTES
54,12,2468,688c6add87cf5fec60dc80ef,689c50ffe90ffc190a96c293,[689c50c4e90ffc190a96c292],Review and comment,688c6add87cf5fec60dc80ef,AUTONOMOUS_COMMENT,False,6898407be90ffc190a96c287,"[{'created_time': 1755075108621, 'selected_tex...",Review and Comment,EACH_MINUTES
55,12,2468,688c6add87cf5fec60dc80ef,689c51f2e90ffc190a96c297,[689c51e2e90ffc190a96c296],Check for references,688c6add87cf5fec60dc80ef,AUTONOMOUS_COMMENT,False,6898407be90ffc190a96c287,"[{'created_time': 1755075098623, 'selected_tex...",Reference Verification,EACH_MINUTES
57,13,2467,68907a6e87cf5fec60dc8107,68a5b3ffe90ffc190a96c316,[68a5a808e90ffc190a96c307],Please proofread the document but only comment...,68907a6e87cf5fec60dc8107,MANUAL,True,68a5a0bde90ffc190a96c2ff,"[{'created_time': 1755690548075, 'selected_tex...",Proofread for Errors Only,MINUTES_INACTIVITY
58,13,2467,68907a6e87cf5fec60dc8107,68a5b850e90ffc190a96c31e,[68a5acf4e90ffc190a96c309],Complete my sentence.,68907a6e87cf5fec60dc8107,MANUAL,True,68a5a0bde90ffc190a96c2ff,"[{'created_time': 1755699462331, 'selected_tex...",Finish My Sentence,EACH_MINUTES
59,13,2467,68907a6e87cf5fec60dc8107,68a5b9e6e90ffc190a96c31f,[68a5acf4e90ffc190a96c309],"Verbessere (nur!!) die Formulierung, ohne den ...",68907a6e87cf5fec60dc8107,MANUAL,True,68a5a0bde90ffc190a96c2ff,"[{'created_time': 1755697070379, 'selected_tex...",Formulierung verbessern,EACH_MINUTES
60,13,2476,68907a6e87cf5fec60dc8107,68a5d43ae90ffc190a96c32c,[68a59949e90ffc190a96c2f7],Looking cool joker!,68907a6e87cf5fec60dc8107,MANUAL,False,68a59766e90ffc190a96c2f4,"[{'created_time': 1755698261822, 'selected_tex...",Cool Joker Look,EACH_MINUTES
61,13,2476,68907a6e87cf5fec60dc8107,68a5d754e90ffc190a96c335,[68a5d73ee90ffc190a96c334],vervollständigen,68907a6e87cf5fec60dc8107,MANUAL,True,68a59766e90ffc190a96c2f4,"[{'created_time': 1755699561177, 'selected_tex...",Aufgaben vervollständigen,EACH_MINUTES
62,13,2476,68907a6e87cf5fec60dc8107,68a5dbe6e90ffc190a96c33f,[68a5acf4e90ffc190a96c309],bewerte und korrigiere die struktur und den sp...,68907a6e87cf5fec60dc8107,MANUAL,False,68a59766e90ffc190a96c2f4,[],Antragsstruktur und Sprache korrigieren,EACH_MINUTES

id                                                                                             276720.0
time                                                                         2025-03-10 07:48:04.549000
participant_id                                                                                     1379
data                                                  {"task": {"id": "67ce9934285fac3f07bcf5ea", "t...
event                                                                                      TASK_CREATED
event_uuid                                                         5c7f52ba-11d9-49d0-82fe-f80ae474602d
participant_token                                                  6573f86e-0207-4286-b036-a83f25a630c3
data_parsed                                           {'task': {'id': '67ce9934285fac3f07bcf5ea', 't...
user_id_x                                                                      67ce982f285fac3f07bcf5e7
username                                                            galina.akhunzhanova@uni-bayreuth.de
document_id                                                                    67ce983b285fac3f07bcf5e8
participant_token                                                  6573f86e-0207-4286-b036-a83f25a630c3
task.id                                                                        67ce9934285fac3f07bcf5ea
task.title                                                                       AI Pros and Cons Essay
task.author_id                                                                 67ce982f285fac3f07bcf5e7
task.description                                      We nned to write an essay together about the p...
task.is_shortcut                                                                                  False
task.assignee_ids                                                                           [ai-author]
task.interaction_type                                                                            MANUAL
task.advanced_trigger_settings.interaction_trigger                                         EACH_MINUTES
group_id                                                                                              1
user                                                                                               1379
user_id_y                                                                      67ce982f285fac3f07bcf5e7
document                                                                       67ce983b285fac3f07bcf5e8
Name: 8, dtype: object 2025-03-10 07:43:55.548000
id                                                                                             277296.0
time                                                                         2025-03-10 08:28:20.299000
participant_id                                                                                     1379
data                                                  {"task": {"id": "67cea2a4285fac3f07bcf5f8", "t...
event                                                                                      TASK_CREATED
event_uuid                                                         e5caab1f-f8c6-4c2c-a52f-651f5479ce57
participant_token                                                  6573f86e-0207-4286-b036-a83f25a630c3
data_parsed                                           {'task': {'id': '67cea2a4285fac3f07bcf5f8', 't...
user_id_x                                                                      67ce982f285fac3f07bcf5e7
username                                                            galina.akhunzhanova@uni-bayreuth.de
document_id                                                                    67ce983b285fac3f07bcf5e8
participant_token                                                  6573f86e-0207-4286-b036-a83f25a630c3
task.id                                                                        67cea2a4285fac3f07bcf5f8
task.title                                                                      Conclusion Writing Task
task.author_id                                                                 67ce982f285fac3f07bcf5e7
task.description                                                   write a conclusion of the given text
task.is_shortcut                                                                                  False
task.assignee_ids                                                                           [ai-author]
task.interaction_type                                                                            MANUAL
task.advanced_trigger_settings.interaction_trigger                                         EACH_MINUTES
group_id                                                                                              1
user                                                                                               1379
user_id_y                                                                      67ce982f285fac3f07bcf5e7
document                                                                       67ce983b285fac3f07bcf5e8
Name: 12, dtype: object 2025-03-10 07:43:55.548000
id                                                                                             276834.0
time                                                                         2025-03-10 08:07:29.198000
participant_id                                                                                     1380
data                                                  {"task": {"id": "67ce9dc1285fac3f07bcf5ed", "t...
event                                                                                      TASK_CREATED
event_uuid                                                         ac8ce41a-2924-423c-8391-5836ad505c5c
participant_token                                                  ecc027d0-42cd-42a1-bc2e-990b5516565b
data_parsed                                           {'task': {'id': '67ce9dc1285fac3f07bcf5ed', 't...
user_id_x                                                                      67ce9cb4285fac3f07bcf5ec
username                                                                                       mrnexeon
document_id                                                                    67ce983b285fac3f07bcf5e8
participant_token                                                  ecc027d0-42cd-42a1-bc2e-990b5516565b
task.id                                                                        67ce9dc1285fac3f07bcf5ed
task.title                                                                      Health & Wellness Essay
task.author_id                                                                 67ce9cb4285fac3f07bcf5ec
task.description                                      Generate essay for Health and Wellness in the ...
task.is_shortcut                                                                                  False
task.assignee_ids                                                                           [ai-author]
task.interaction_type                                                                            MANUAL
task.advanced_trigger_settings.interaction_trigger                                         EACH_MINUTES
group_id                                                                                              1
user                                                                                               1380
user_id_y                                                                      67ce9cb4285fac3f07bcf5ec
document                                                                       67ce983b285fac3f07bcf5e8
Name: 9, dtype: object 2025-03-10 07:43:55.548000
id                                                                                             277090.0
time                                                                         2025-03-10 08:17:37.082000
participant_id                                                                                     1380
data                                                  {"task": {"id": "67cea021285fac3f07bcf5f6", "t...
event                                                                                      TASK_CREATED
event_uuid                                                         cbb15f70-59bd-4597-a3c0-7e7e23659967
participant_token                                                  ecc027d0-42cd-42a1-bc2e-990b5516565b
data_parsed                                           {'task': {'id': '67cea021285fac3f07bcf5f6', 't...
user_id_x                                                                      67ce9cb4285fac3f07bcf5ec
username                                                                                       mrnexeon
document_id                                                                    67ce983b285fac3f07bcf5e8
participant_token                                                  ecc027d0-42cd-42a1-bc2e-990b5516565b
task.id                                                                        67cea021285fac3f07bcf5f6
task.title                                                                             Shorten the Text
task.author_id                                                                 67ce9cb4285fac3f07bcf5ec
task.description                                                                  Make the text shorter
task.is_shortcut                                                                                   True
task.assignee_ids                                                                           [ai-author]
task.interaction_type                                                                            MANUAL
task.advanced_trigger_settings.interaction_trigger                                         EACH_MINUTES
group_id                                                                                              1
user                                                                                               1380
user_id_y                                                                      67ce9cb4285fac3f07bcf5ec
document                                                                       67ce983b285fac3f07bcf5e8
Name: 10, dtype: object 2025-03-10 07:43:55.548000
id                                                                                             277154.0
time                                                                         2025-03-10 08:20:48.986000
participant_id                                                                                     1380
data                                                  {"task": {"id": "67cea0e1285fac3f07bcf5f7", "t...
event                                                                                      TASK_CREATED
event_uuid                                                         3829f97d-7e6f-4338-97e9-8922ae639e46
participant_token                                                  ecc027d0-42cd-42a1-bc2e-990b5516565b
data_parsed                                           {'task': {'id': '67cea0e1285fac3f07bcf5f7', 't...
user_id_x                                                                      67ce9cb4285fac3f07bcf5ec
username                                                                                       mrnexeon
document_id                                                                    67ce983b285fac3f07bcf5e8
participant_token                                                  ecc027d0-42cd-42a1-bc2e-990b5516565b
task.id                                                                        67cea0e1285fac3f07bcf5f7
task.title                                                                    Enhance Professional Tone
task.author_id                                                                 67ce9cb4285fac3f07bcf5ec
task.description                                        Give it more scientific and professional style.
task.is_shortcut                                                                                   True
task.assignee_ids                                                                           [ai-author]
task.interaction_type                                                                            MANUAL
task.advanced_trigger_settings.interaction_trigger                                         EACH_MINUTES
group_id                                                                                              1
user                                                                                               1380
user_id_y                                                                      67ce9cb4285fac3f07bcf5ec
document                                                                       67ce983b285fac3f07bcf5e8
Name: 11, dtype: object 2025-03-10 07:43:55.548000
id                                                                                             276268.0
time                                                                         2025-03-07 21:43:22.511000
participant_id                                                                                     1376
data                                                  {"task": {"id": "67cb687a285fac3f07bcf5a4", "t...
event                                                                                      TASK_CREATED
event_uuid                                                         84017059-2690-4936-980b-f5333f85d934
participant_token                                                  a5bbafd1-4ef0-49e4-95bd-65170953633c
data_parsed                                           {'task': {'id': '67cb687a285fac3f07bcf5a4', 't...
user_id_x                                                                      67cb6627285fac3f07bcf59b
username                                                                                        wolfova
document_id                                                                    67c97527285fac3f07bcf587
participant_token                                                  a5bbafd1-4ef0-49e4-95bd-65170953633c
task.id                                                                        67cb687a285fac3f07bcf5a4
task.title                                                                                   Pros of AI
task.author_id                                                                 67cb6627285fac3f07bcf59b
task.description                                           write the part where u talk about pros of AI
task.is_shortcut                                                                                  False
task.assignee_ids                                                                           [ai-author]
task.interaction_type                                                                            MANUAL
task.advanced_trigger_settings.interaction_trigger                                         EACH_MINUTES
group_id                                                                                              2
user                                                                                               1376
user_id_y                                                                      67cb6627285fac3f07bcf59b
document                                                                       67c97527285fac3f07bcf587
Name: 1, dtype: object 2025-03-07 21:33:49.808000
id                                                                                             276335.0
time                                                                         2025-03-07 21:46:05.445000
participant_id                                                                                     1376
data                                                  {"task": {"id": "67cb691d285fac3f07bcf5ac", "t...
event                                                                                      TASK_CREATED
event_uuid                                                         d2250740-98b2-4a96-81e0-e95c9ec2aad6
participant_token                                                  a5bbafd1-4ef0-49e4-95bd-65170953633c
data_parsed                                           {'task': {'id': '67cb691d285fac3f07bcf5ac', 't...
user_id_x                                                                      67cb6627285fac3f07bcf59b
username                                                                                        wolfova
document_id                                                                    67c97527285fac3f07bcf587
participant_token                                                  a5bbafd1-4ef0-49e4-95bd-65170953633c
task.id                                                                        67cb691d285fac3f07bcf5ac
task.title                                                                       Essay Summary Creation
task.author_id                                                                 67cb6627285fac3f07bcf59b
task.description                                      write the zusamenfassung for our essay based o...
task.is_shortcut                                                                                  False
task.assignee_ids                                                                           [ai-author]
task.interaction_type                                                                            MANUAL
task.advanced_trigger_settings.interaction_trigger                                         EACH_MINUTES
group_id                                                                                              2
user                                                                                               1376
user_id_y                                                                      67cb6627285fac3f07bcf59b
document                                                                       67c97527285fac3f07bcf587
Name: 3, dtype: object 2025-03-07 21:33:49.808000
id                                                                                             276370.0
time                                                                         2025-03-07 21:48:56.770000
participant_id                                                                                     1376
data                                                  {"task": {"id": "67cb69c8285fac3f07bcf5b2", "t...
event                                                                                      TASK_CREATED
event_uuid                                                         3f7fdb58-c32d-47a8-bbfe-36e1b56950cf
participant_token                                                  a5bbafd1-4ef0-49e4-95bd-65170953633c
data_parsed                                           {'task': {'id': '67cb69c8285fac3f07bcf5b2', 't...
user_id_x                                                                      67cb6627285fac3f07bcf59b
username                                                                                        wolfova
document_id                                                                    67c97527285fac3f07bcf587
participant_token                                                  a5bbafd1-4ef0-49e4-95bd-65170953633c
task.id                                                                        67cb69c8285fac3f07bcf5b2
task.title                                                                    Edit Text for Publication
task.author_id                                                                 67cb6627285fac3f07bcf59b
task.description                                      can u edit our text as the scientific paper wi...
task.is_shortcut                                                                                  False
task.assignee_ids                                                                           [ai-author]
task.interaction_type                                                                            MANUAL
task.advanced_trigger_settings.interaction_trigger                                         EACH_MINUTES

    user  group_id  time_percentage
0   1379         1         7.051825
10  1374         3         1.146458
11  1374         3         2.010889
12  1374         3         2.737893
14  1387         5        13.167061
15  1387         5        22.490738
18  1388         6         1.466904
19  1388         6        12.750621
32  2461         9         0.074722
41  2459        10         0.193222
42  2459        10         0.370281
43  2459        10         1.744862

22.641509433962263

    user  group_id  time_percentage
2   1380         1        40.035231
8   1377         2        49.248393
16  1387         5        25.192939
20  1388         6        49.107459
24  1389         6        36.108618
36  2464         9        49.886428

11.320754716981131

    user  group_id  time_percentage
3   1380         1        57.250790
4   1380         1        62.685602
5   1376         2        55.811662
6   1376         2        71.690080
9   1377         2        68.803423
21  1388         6        53.785999
22  1388         6        60.183881
37  2464         9        50.020244
38  2464         9        50.158668
39  2464         9        50.180508
49  2469        12        61.941801
50  2469        12        61.971089
51  2469        12        62.054695

24.528301886792452

    user  group_id  time_percentage
1   1379         1        75.466997
7   1376         2        88.386226
13  1374         3        90.765650
17  1387         5        99.859107
23  1388         6        99.781540
25  1389         6        80.914448
26  2456         7        76.763050
27  2456         7        76.961721
28  2460         7        80.920247
29  2460         7        80.951580
30  2460         7        99.018295
31  2460         7        99.091602
33  2461         9        99.365916
34  2461         9        99.486783
35  2461         9        99.996198
40  2457         9        88.398314
44  2465        10        99.997745
45  2475        11        97.939444
46  2475        11        99.767257
47  2475        11        99.798224
48  2475        11        99.802728
52  2471        14        96.949781

41.509433962264154