In [1]:
import os
import pandas as pd
from bs4 import BeautifulSoup
import textstat

/tmp/ipykernel_175239/869623706.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
agents_file = 'agents.tsv'
agents_df = pd.read_csv(os.path.join('input', 'codings', agents_file), sep='\t')

task_descriptions_file = 'task_descriptions.tsv'
task_descriptions_df = pd.read_csv(os.path.join('input', 'codings', task_descriptions_file), sep='\t')

comments_file = 'comments.tsv'
comments_df = pd.read_csv(os.path.join('input', 'codings', comments_file), sep='\t')

In [3]:
display(agents_df.head(20))
display(task_descriptions_df.head(20))
display(comments_df.head(20))

,#,id,roles,profile.sections.expertise,profile.sections.skills,co_creative_role,group_id,user
0,1,67cea551285fac3f07bcf604,Assistant,NaN,"Document structuring, Asses essay structure, a...","assistant, editor",1,1380
1,5,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3,1374
2,6,67cdfef4285fac3f07bcf5d3,Fact Checker and Fact Provider,"Fact Validation, Historical Research","Data Verification, AI Factology",advisor,3,1374
3,7,67cee0fd285fac3f07bcf60b,Text Structure and Format Specialist,"Text Organization, Content Flow, Document Form...","Coherence Improvement, Text Structural Clarity...",editor,3,1374
4,8,67d445d10b9539e69a3a86c1,Text Analysis and Feedback Specialist,"Text Review, Textual Criticism","Readability assessment, Constructive feedback ...",advisor,4,1383
5,9,67e691c850d39f32454bf30c,Consistency Reviewer,"Scientific Paper writing, HCI researcher exper...","logic, marketing, quality assurance",advisor,4,1383
6,10,67e5cb6450d39f32454bf2fa,Critical Reviewer with HCI and Education Exper...,"Human-Computer Interaction, Education, AI-assi...","Spot logical faults, Creative thinking, Asking...",advisor,4,1384
7,11,67d445e30b9539e69a3a86c3,This AI Assistant is the best HCI Professor in...,"HCI, Teaching","Programming, Proof Reading, Supervision",advisor,4,1385
8,12,67d5d8810b9539e69a3a86da,Text Analysis and Feedback Specialist,"Text Review, Textual Criticism","Readability assessment, Constructive feedback ...",advisor,5,1387
9,13,67d5d88b0b9539e69a3a86db,Text Structure and Format Specialist,"Text Organization, Content Flow, Document Form...","Coherence Improvement, Text Structural Clarity...",editor,5,1387
10,14,67d5d88f0b9539e69a3a86dc,English Teacher,English Grammar and Syntax,"Grammar error detection and correction, Senten...",assistant,5,1387
11,15,67d5d8cf0b9539e69a3a86df,Teaches sex and makes stupid but funny jokes,"Sex education, jokes, Adult Education, Comedy ...","Comedy Timing, Expressive Teaching, Extend text",co-author,5,1387
12,17,67d82f6dedfe680c1b0f164a,check gramma,"Language Proficiency, Punctuation Awareness, S...","Text Elaboration, Format text, Sentence Struct...",assistant,6,1388
13,18,67d83410edfe680c1b0f1655,Idea Generator,"Concept Creation, Creative Thinking","Idea synthesis, Brainstorming, Mindmapping",co-author,6,1388
14,19,67d83558edfe680c1b0f165e,Text Analysis and Feedback Specialist,"Text Review, Textual Criticism","Readability assessment, Constructive feedback ...",editor,6,1388
15,20,67d82fbfedfe680c1b0f164e,Proofreader,"Grammar Knowledge, Publication Formatting, Sou...",Dynamic Citation selection,assistant,6,1389
16,23,6887772287cf5fec60dc8036,Author,"artificial intelligence, english writing, educ...","Writing Essays, Understanding Context, Text Ed...",co-author,7,2456
17,24,6888b66487cf5fec60dc806d,Add interesting facts,"history, statistics, facts",Adding coherent facts,advisor,7,2460
18,25,687df2ff87cf5fec60dc7ff1,Text Analysis and Feedback Specialist,"Text Review, Textual Criticism, Human Computer...","Readability assessment, Constructive feedback ...",editor,8,2453
19,26,6880e03f87cf5fec60dc7ffb,Lived Model of PI Expert,Expert in A lived informatics model of persona...,"Paper writing, Discussion Section, Data Interp...","co-author, advisor",8,2453

,Unnamed: 0,assignee_ids,description,writing_stage,users_primary_intent,group_id,user
0,0,ai-author,Write intro for the essay,drafting,"inspiration, efficiency",2,1377
1,1,ai-author,write the part where u talk about pros of AI,drafting,"inspiration, efficiency",2,1376
2,2,ai-author,Write cons of AI,drafting,inspiration,2,1377
3,3,ai-author,write the zusamenfassung for our essay based o...,drafting,efficiency,2,1376
4,4,ai-author,can u edit our text as the scientific paper wi...,revising,improve text / readability,2,1376
5,5,67cdfc85285fac3f07bcf5cf,Read the written part of text. Highlight gramm...,revising,efficiency,3,1374
6,6,67cdfef4285fac3f07bcf5d3,Check the selected text and provide some scien...,revising,"learning, improve text / readability",3,1374
7,7,67cdfc85285fac3f07bcf5cf,Considering the topic and the latest available...,drafting,efficiency,3,1374
8,8,ai-author,We nned to write an essay together about the p...,outlining,inspiration,1,1379
9,9,ai-author,Generate essay for Health and Wellness in the ...,drafting,"inspiration, efficiency",1,1380
10,10,ai-author,Make the text shorter,revising,improve text / readability,1,1380
11,11,ai-author,Give it more scientific and professional style.,revising,improve text / readability,1,1380
12,12,ai-author,write a conclusion of the given text,drafting,efficiency,1,1379
13,13,ai-author,The agent should analyze the selected advantag...,drafting,"learning, inspiration",3,1374
14,14,67d5d8cf0b9539e69a3a86df,Check the text,revising,improve text / readability,5,1387
15,15,67d5d88f0b9539e69a3a86dc,Check the language mistakes in the text,revising,efficiency,5,1387
16,16,67d5d88b0b9539e69a3a86db,Check if the text flow is good and give counci...,revising,"improve text / readability, learning",5,1387
17,17,67d5d88b0b9539e69a3a86db,Give advices on how to name each paragraph and...,revising,"improve text / readability, learning",5,1387
18,18,ai-author,Write me a text about ai pros and cons,drafting,"inspiration, efficiency",6,1388
19,19,67d82f6dedfe680c1b0f164a,check the text find mistakes,revising,efficiency,6,1388

,Unnamed: 0,assignee_id,assignee_name,text,writing_stage,users_primary_intent,group_id,user,user_id,comment_id
0,0,ai-author,AI author,@aiauthor What are some of the names of these ...,revising,learning,3,1378,67cc9f69285fac3f07bcf5c8,7DTFbKN6yVngm0vX_3FoB
1,1,ai-author,AI author,@aiauthor Give me more examples of these GenAI...,revising,"inspiration, learning",3,1378,67cc9f69285fac3f07bcf5c8,VAatOu1QDqAt07vy7Ne8h
2,2,67cdfef4285fac3f07bcf5d3,AI Max,@aiAI Max what's the history of AI ?,drafting,learning,3,1378,67cc9f69285fac3f07bcf5c8,6daYdxwEEcG58TSTMV6aw
3,3,ai-author,AI author,@aiauthor Please summarize this part of the text.,revising,"inspiration, improve text / readability",3,1378,67cc9f69285fac3f07bcf5c8,CiDt21N2QEP1m7Le0k_mj
4,5,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika , could you please make this text sho...",revising,improve text / readability,3,1374,67cdfa30285fac3f07bcf5cc,SuRM3VccpleBCCxUJqLEG
5,6,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika, could you please summarize the writt...",drafting,efficiency,3,1374,67cdfa30285fac3f07bcf5cc,gobhqckqLD3t1FGuJG6l8
6,7,ai-author,AI author,@aiauthor Definition of health and wellness,drafting,learning,1,1379,67ce982f285fac3f07bcf5e7,mHIkbNGUYqepeZ-_NGSVN
7,8,ai-author,AI author,"@aiauthor , Write the content for this intro e...",drafting,"inspiration, efficiency",1,1380,67ce9cb4285fac3f07bcf5ec,MfaSsmCS8az5tJiEdtIX1
8,9,ai-author,AI author,"@aiauthor , Enhance professional tone",revising,improve text / readability,1,1380,67ce9cb4285fac3f07bcf5ec,6PoKqRSqm5nBKdEJnF7KG
9,10,ai-author,AI author,@aiauthor can you give any statisctics about ...,drafting,learning,1,1379,67ce982f285fac3f07bcf5e7,nOqZNstq0_qlc9q0-0c4X
10,11,ai-author,AI author,"@aiauthor Fix my text, enhance professional to...",revising,improve text / readability,1,1380,67ce9cb4285fac3f07bcf5ec,mKJ7hgCmK8cXI1G8P2fjG
11,12,ai-author,AI author,@aiauthor Generate content for this body part ...,drafting,"inspiration, efficiency",1,1380,67ce9cb4285fac3f07bcf5ec,i4CWhJhTRsJHHRrG0p51u
12,13,67d83558edfe680c1b0f165e,TextReviewer,make it shorter @aiTextReviewer,revising,improve text / readability,6,1388,67d82dc4edfe680c1b0f1642,zxi5tyLFqqaEic9c6jeEF
13,14,67e5cb6450d39f32454bf2fa,ContentReviewer,@aiContentReviewer,NaN,NaN,4,1384,67d444dd0b9539e69a3a86bb,hJ9sUH3y-UK90rmCILf4j
14,15,67d445e30b9539e69a3a86c3,Best HCI Professor,@aiBest HCI Professor @aiContentReviewer Provi...,drafting,learning,4,1384,67d444dd0b9539e69a3a86bb,6GeYajr9KcHFjpFb0Q--z
15,16,67d445d10b9539e69a3a86c1,TextReviewer,@aiTextReviewer Fix all typos. Do not change a...,revising,efficiency,4,1384,67d444dd0b9539e69a3a86bb,Kal0_p_o5icQVQCQM22qJ
16,17,67d445d10b9539e69a3a86c1,TextReviewer,@aiTextReviewer Make this text more scientific...,revising,improve text / readability,4,1384,67d444dd0b9539e69a3a86bb,mLNRXhlEyYKcaLvIaxh_3
17,18,67d445e30b9539e69a3a86c3,Best HCI Professor,@aiBest HCI Professor What do you think of my ...,revising,learning,4,1385,67bc43607a670b6874690577,YfLqtkNyJh4l3lWMGJPsU
18,19,ai-author,AI author,@aiauthor Write an abstract for this paper,drafting,"inspiration, efficiency",4,1385,67bc43607a670b6874690577,MK7nNP5gwF6Ecveyyk_7Z
19,20,67e5cb6450d39f32454bf2fa,ContentReviewer,@aiContentReviewer provide a good reference,drafting,"learning, efficiency",4,1384,67d444dd0b9539e69a3a86bb,tlCyjTFlv6DstAVtNz2Qx

## Agents

In [4]:
co_creative_roles = agents_df["co_creative_role"].str.split(", ", regex=False, expand=True)
display(co_creative_roles)

co_creative_roles_flat = pd.Series([])
for series_name, series in co_creative_roles.items():
    co_creative_roles_flat = pd.concat([co_creative_roles_flat, series[series.notna()]])

display(len(co_creative_roles_flat))
display(co_creative_roles_flat.value_counts())

            0        1
0   assistant   editor
1     advisor   editor
2     advisor     None
3      editor     None
4     advisor     None
5     advisor     None
6     advisor     None
7     advisor     None
8     advisor     None
9      editor     None
10  assistant     None
11  co-author     None
12  assistant     None
13  co-author     None
14     editor     None
15  assistant     None
16  co-author     None
17    advisor     None
18     editor     None
19  co-author  advisor
20  co-author  advisor
21  co-author     None
22  co-author     None
23  assistant     None
24     editor     None
25  co-author     None
26  assistant     None
27  assistant     None
28  assistant     None
29    advisor     None
30  co-author     None
31    advisor     None
32  assistant     None
33    advisor     None
34     editor     None
35  co-author     None
36     editor  advisor
37  assistant     None
38  assistant     None

44

advisor      14
assistant    11
co-author    10
editor        9
Name: count, dtype: int64

## Task descriptions

In [5]:
desc_writing_stages = task_descriptions_df["writing_stage"].str.split(", ", regex=False, expand=True)
display(desc_writing_stages)

desc_writing_stages_flat = pd.Series([])
for series_name, series in desc_writing_stages.items():
    desc_writing_stages_flat = pd.concat([desc_writing_stages_flat, series[series.notna()]])

display(len(desc_writing_stages_flat))
display(desc_writing_stages_flat.value_counts())

            0
0    drafting
1    drafting
2    drafting
3    drafting
4    revising
..        ...
58   revising
59   drafting
60  outlining
61   revising
62   drafting

[63 rows x 1 columns]

63

revising     38
drafting     20
outlining     5
Name: count, dtype: int64

In [6]:
desc_intent = task_descriptions_df["users_primary_intent"].str.split(", ", regex=False, expand=True)
display(desc_intent)

desc_intent_flat = pd.Series([])
for series_name, series in desc_intent.items():
    desc_intent_flat = pd.concat([desc_intent_flat, series[series.notna()]])

display(len(desc_intent_flat))
display(desc_intent_flat.value_counts())

                             0                           1
0                  inspiration                  efficiency
1                  inspiration                  efficiency
2                  inspiration                        None
3                   efficiency                        None
4   improve text / readability                        None
..                         ...                         ...
58                    learning  improve text / readability
59                  efficiency                        None
60                 inspiration                  efficiency
61                  efficiency                        None
62                    learning                        None

[63 rows x 2 columns]

87

efficiency                    32
improve text / readability    22
inspiration                   18
learning                      15
Name: count, dtype: int64

In [7]:
task_descriptions = task_descriptions_df["description"]
display(task_descriptions)

parsed_text_list = []
word_counts = []
for idx, text in task_descriptions.items():
    parsed_text_list.append(BeautifulSoup(str(text), 'lxml').get_text())
    word_counts.append(textstat.lexicon_count(text, removepunct=True))

display(pd.Series(word_counts).describe())

0                             Write intro for the essay
1          write the part where u talk about pros of AI
2                                      Write cons of AI
3     write the zusamenfassung for our essay based o...
4     can u edit our text as the scientific paper wi...
                            ...
58    bewerte und korrigiere die struktur und den sp...
59                       Übersetze Deutsch auf englisch
60    Create me a lessons plan for a graduate semina...
61    format that part poperly for a doc not a markd...
62    prüfe die Literaturquellen und schlage mir noc...
Name: description, Length: 63, dtype: object

count     63.000000
mean      12.460317
std       14.042361
min        1.000000
25%        5.000000
50%       10.000000
75%       14.500000
max      102.000000
dtype: float64

In [8]:
display(task_descriptions_df.tail(10))

,Unnamed: 0,assignee_ids,description,writing_stage,users_primary_intent,group_id,user
53,49,"ai-author, 689e2470e90ffc190a96c2e4, 689e24b5e...","Make the text more interesting to read, and a ...",revising,improve text / readability,14,2471
54,51,68a5a808e90ffc190a96c307,Please proofread the document but only comment...,revising,"learning, efficiency",13,2467
55,52,68a5acf4e90ffc190a96c309,Complete my sentence.,drafting,"inspiration, efficiency",13,2467
56,53,68a5acf4e90ffc190a96c309,"Verbessere (nur!!) die Formulierung, ohne den ...",revising,improve text / readability,13,2467
57,55,68a5d73ee90ffc190a96c334,vervollständigen,drafting,efficiency,13,2476
58,56,68a5acf4e90ffc190a96c309,bewerte und korrigiere die struktur und den sp...,revising,"learning, improve text / readability",13,2476
59,57,ai-author,Übersetze Deutsch auf englisch,drafting,efficiency,11,2475
60,58,68931d9887cf5fec60dc810f,Create me a lessons plan for a graduate semina...,outlining,"inspiration, efficiency",11,2475
61,59,ai-author,format that part poperly for a doc not a markd...,revising,efficiency,11,2475
62,60,688b2aa687cf5fec60dc80b3,prüfe die Literaturquellen und schlage mir noc...,drafting,learning,11,2475

In [9]:
task_descriptions_df_copy = task_descriptions_df.copy()

task_descriptions_df_copy.assignee_ids = task_descriptions_df_copy.assignee_ids.str.split(',')
task_descriptions_df_copy = task_descriptions_df_copy.explode('assignee_ids')
display(task_descriptions_df_copy.tail(15))

,Unnamed: 0,assignee_ids,description,writing_stage,users_primary_intent,group_id,user
50,45,ai-author,Check the whole content for mistakes break in ...,revising,"improve text / readability, learning",9,2461
51,46,689c3da3e90ffc190a96c28f,Bitte einmal die Motivation prüfen,revising,learning,12,2469
52,47,689c3da3e90ffc190a96c28f,Please review,revising,learning,12,2469
53,49,ai-author,"Make the text more interesting to read, and a ...",revising,improve text / readability,14,2471
53,49,689e2470e90ffc190a96c2e4,"Make the text more interesting to read, and a ...",revising,improve text / readability,14,2471
53,49,689e24b5e90ffc190a96c2e6,"Make the text more interesting to read, and a ...",revising,improve text / readability,14,2471
54,51,68a5a808e90ffc190a96c307,Please proofread the document but only comment...,revising,"learning, efficiency",13,2467
55,52,68a5acf4e90ffc190a96c309,Complete my sentence.,drafting,"inspiration, efficiency",13,2467
56,53,68a5acf4e90ffc190a96c309,"Verbessere (nur!!) die Formulierung, ohne den ...",revising,improve text / readability,13,2467
57,55,68a5d73ee90ffc190a96c334,vervollständigen,drafting,efficiency,13,2476
58,56,68a5acf4e90ffc190a96c309,bewerte und korrigiere die struktur und den sp...,revising,"learning, improve text / readability",13,2476
59,57,ai-author,Übersetze Deutsch auf englisch,drafting,efficiency,11,2475
60,58,68931d9887cf5fec60dc810f,Create me a lessons plan for a graduate semina...,outlining,"inspiration, efficiency",11,2475
61,59,ai-author,format that part poperly for a doc not a markd...,revising,efficiency,11,2475
62,60,688b2aa687cf5fec60dc80b3,prüfe die Literaturquellen und schlage mir noc...,drafting,learning,11,2475

In [10]:
descriptions_agents_df = pd.merge(task_descriptions_df_copy, agents_df, left_on='assignee_ids', right_on='id', how='left')
display(descriptions_agents_df.head(15))

,Unnamed: 0,assignee_ids,description,writing_stage,users_primary_intent,group_id_x,user_x,#,id,roles,profile.sections.expertise,profile.sections.skills,co_creative_role,group_id_y,user_y
0,0,ai-author,Write intro for the essay,drafting,"inspiration, efficiency",2,1377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,ai-author,write the part where u talk about pros of AI,drafting,"inspiration, efficiency",2,1376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,ai-author,Write cons of AI,drafting,inspiration,2,1377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,ai-author,write the zusamenfassung for our essay based o...,drafting,efficiency,2,1376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,ai-author,can u edit our text as the scientific paper wi...,revising,improve text / readability,2,1376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,67cdfc85285fac3f07bcf5cf,Read the written part of text. Highlight gramm...,revising,efficiency,3,1374,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3.0,1374.0
6,6,67cdfef4285fac3f07bcf5d3,Check the selected text and provide some scien...,revising,"learning, improve text / readability",3,1374,6.0,67cdfef4285fac3f07bcf5d3,Fact Checker and Fact Provider,"Fact Validation, Historical Research","Data Verification, AI Factology",advisor,3.0,1374.0
7,7,67cdfc85285fac3f07bcf5cf,Considering the topic and the latest available...,drafting,efficiency,3,1374,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3.0,1374.0
8,8,ai-author,We nned to write an essay together about the p...,outlining,inspiration,1,1379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,ai-author,Generate essay for Health and Wellness in the ...,drafting,"inspiration, efficiency",1,1380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,ai-author,Make the text shorter,revising,improve text / readability,1,1380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,ai-author,Give it more scientific and professional style.,revising,improve text / readability,1,1380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,ai-author,write a conclusion of the given text,drafting,efficiency,1,1379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,ai-author,The agent should analyze the selected advantag...,drafting,"learning, inspiration",3,1374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,67d5d8cf0b9539e69a3a86df,Check the text,revising,improve text / readability,5,1387,15.0,67d5d8cf0b9539e69a3a86df,Teaches sex and makes stupid but funny jokes,"Sex education, jokes, Adult Education, Comedy ...","Comedy Timing, Expressive Teaching, Extend text",co-author,5.0,1387.0

In [11]:
description_agents_exploded_df = descriptions_agents_df.copy()
display(description_agents_exploded_df.head(15))

description_agents_exploded_df.co_creative_role = description_agents_exploded_df.co_creative_role.str.split(',')
description_agents_exploded_df = description_agents_exploded_df.explode('co_creative_role')
description_agents_exploded_df.co_creative_role = description_agents_exploded_df.co_creative_role.str.strip()
description_agents_exploded_df.co_creative_role = description_agents_exploded_df.co_creative_role.fillna("ai-author")
display(description_agents_exploded_df.head(15))

display("Co-Creative-Roles for Tasks in OUTLINING stage")
outlining_roles = description_agents_exploded_df[description_agents_exploded_df['writing_stage'] == "outlining"]["co_creative_role"]
display(outlining_roles.value_counts())
display(outlining_roles.value_counts().describe())

display("Co-Creative-Roles for Tasks in DRAFTING stage")
drafting_roles = description_agents_exploded_df[description_agents_exploded_df['writing_stage'] == "drafting"]["co_creative_role"]
display(drafting_roles.value_counts())
display(drafting_roles.value_counts().describe())

display("Co-Creative-Roles for Tasks in REVISING stage")
revising_roles = description_agents_exploded_df[description_agents_exploded_df['writing_stage'] == "revising"]["co_creative_role"]
display(revising_roles.value_counts())
display(revising_roles.value_counts().describe())

,Unnamed: 0,assignee_ids,description,writing_stage,users_primary_intent,group_id_x,user_x,#,id,roles,profile.sections.expertise,profile.sections.skills,co_creative_role,group_id_y,user_y
0,0,ai-author,Write intro for the essay,drafting,"inspiration, efficiency",2,1377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,ai-author,write the part where u talk about pros of AI,drafting,"inspiration, efficiency",2,1376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,ai-author,Write cons of AI,drafting,inspiration,2,1377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,ai-author,write the zusamenfassung for our essay based o...,drafting,efficiency,2,1376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,ai-author,can u edit our text as the scientific paper wi...,revising,improve text / readability,2,1376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,67cdfc85285fac3f07bcf5cf,Read the written part of text. Highlight gramm...,revising,efficiency,3,1374,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3.0,1374.0
6,6,67cdfef4285fac3f07bcf5d3,Check the selected text and provide some scien...,revising,"learning, improve text / readability",3,1374,6.0,67cdfef4285fac3f07bcf5d3,Fact Checker and Fact Provider,"Fact Validation, Historical Research","Data Verification, AI Factology",advisor,3.0,1374.0
7,7,67cdfc85285fac3f07bcf5cf,Considering the topic and the latest available...,drafting,efficiency,3,1374,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3.0,1374.0
8,8,ai-author,We nned to write an essay together about the p...,outlining,inspiration,1,1379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,ai-author,Generate essay for Health and Wellness in the ...,drafting,"inspiration, efficiency",1,1380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,ai-author,Make the text shorter,revising,improve text / readability,1,1380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,ai-author,Give it more scientific and professional style.,revising,improve text / readability,1,1380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,ai-author,write a conclusion of the given text,drafting,efficiency,1,1379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,ai-author,The agent should analyze the selected advantag...,drafting,"learning, inspiration",3,1374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,67d5d8cf0b9539e69a3a86df,Check the text,revising,improve text / readability,5,1387,15.0,67d5d8cf0b9539e69a3a86df,Teaches sex and makes stupid but funny jokes,"Sex education, jokes, Adult Education, Comedy ...","Comedy Timing, Expressive Teaching, Extend text",co-author,5.0,1387.0

,Unnamed: 0,assignee_ids,description,writing_stage,users_primary_intent,group_id_x,user_x,#,id,roles,profile.sections.expertise,profile.sections.skills,co_creative_role,group_id_y,user_y
0,0,ai-author,Write intro for the essay,drafting,"inspiration, efficiency",2,1377,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
1,1,ai-author,write the part where u talk about pros of AI,drafting,"inspiration, efficiency",2,1376,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
2,2,ai-author,Write cons of AI,drafting,inspiration,2,1377,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
3,3,ai-author,write the zusamenfassung for our essay based o...,drafting,efficiency,2,1376,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
4,4,ai-author,can u edit our text as the scientific paper wi...,revising,improve text / readability,2,1376,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
5,5,67cdfc85285fac3f07bcf5cf,Read the written part of text. Highlight gramm...,revising,efficiency,3,1374,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...",advisor,3.0,1374.0
5,5,67cdfc85285fac3f07bcf5cf,Read the written part of text. Highlight gramm...,revising,efficiency,3,1374,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...",editor,3.0,1374.0
6,6,67cdfef4285fac3f07bcf5d3,Check the selected text and provide some scien...,revising,"learning, improve text / readability",3,1374,6.0,67cdfef4285fac3f07bcf5d3,Fact Checker and Fact Provider,"Fact Validation, Historical Research","Data Verification, AI Factology",advisor,3.0,1374.0
7,7,67cdfc85285fac3f07bcf5cf,Considering the topic and the latest available...,drafting,efficiency,3,1374,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...",advisor,3.0,1374.0
7,7,67cdfc85285fac3f07bcf5cf,Considering the topic and the latest available...,drafting,efficiency,3,1374,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...",editor,3.0,1374.0
8,8,ai-author,We nned to write an essay together about the p...,outlining,inspiration,1,1379,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
9,9,ai-author,Generate essay for Health and Wellness in the ...,drafting,"inspiration, efficiency",1,1380,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
10,10,ai-author,Make the text shorter,revising,improve text / readability,1,1380,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
11,11,ai-author,Give it more scientific and professional style.,revising,improve text / readability,1,1380,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
12,12,ai-author,write a conclusion of the given text,drafting,efficiency,1,1379,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN

'Co-Creative-Roles for Tasks in OUTLINING stage'

co_creative_role
co-author    3
ai-author    2
Name: count, dtype: int64

count    2.000000
mean     2.500000
std      0.707107
min      2.000000
25%      2.250000
50%      2.500000
75%      2.750000
max      3.000000
Name: count, dtype: float64

'Co-Creative-Roles for Tasks in DRAFTING stage'

co_creative_role
ai-author    14
co-author     3
advisor       2
editor        2
Name: count, dtype: int64

count     4.00000
mean      5.25000
std       5.85235
min       2.00000
25%       2.00000
50%       2.50000
75%       5.75000
max      14.00000
Name: count, dtype: float64

'Co-Creative-Roles for Tasks in REVISING stage'

co_creative_role
ai-author    14
advisor      10
co-author     8
assistant     6
editor        5
Name: count, dtype: int64

count     5.000000
mean      8.600000
std       3.577709
min       5.000000
25%       6.000000
50%       8.000000
75%      10.000000
max      14.000000
Name: count, dtype: float64

## Comments

In [12]:
comments_writing_stages = comments_df["writing_stage"].str.split(", ", regex=False, expand=True)
display(comments_writing_stages)

comments_writing_stages_flat = pd.Series([])
for series_name, series in comments_writing_stages.items():
    comments_writing_stages_flat = pd.concat([comments_writing_stages_flat, series[series.notna()]])

display(len(comments_writing_stages_flat))
display(comments_writing_stages_flat.value_counts())

           0
0   revising
1   revising
2   drafting
3   revising
4   revising
..       ...
69  drafting
70  revising
71  revising
72  revising
73  revising

[74 rows x 1 columns]

73

drafting     36
revising     33
outlining     4
Name: count, dtype: int64

In [13]:
comments_intent = comments_df["users_primary_intent"].str.split(", ", regex=False, expand=True)
display(comments_intent)

comments_intent_flat = pd.Series([])
for series_name, series in comments_intent.items():
    comments_intent_flat = pd.concat([comments_intent_flat, series[series.notna()]])

display(len(comments_intent_flat))
display(comments_intent_flat.value_counts())

                             0                           1
0                     learning                        None
1                  inspiration                    learning
2                     learning                        None
3                  inspiration  improve text / readability
4   improve text / readability                        None
..                         ...                         ...
69                 inspiration                  efficiency
70                  efficiency                        None
71                    learning                        None
72                    learning                        None
73                    learning                  efficiency

[74 rows x 2 columns]

96

inspiration                   35
improve text / readability    23
efficiency                    21
learning                      17
Name: count, dtype: int64

In [14]:
comments = comments_df["text"]
display(comments)
display(len(comments))

ai_mentionings = [
    "@aiauthor",
    "@aiAI Max",
    "@aiTextStructurer",
    "@aiErika",
    "@aiContentReviewer",
    "@aiBest HCI Professor",
    "@aiTextReviewer",
    "@aiInteraction Designer",
    "@aiThe AI Expert",
    "@aiFun facts",
    "@aiAiDevelop",
    "@aiRephraser",
    "@aiGeorge",
    "@aiSynthesizer",
    "@aiProposal Brain",
    "@aiGrammar",
    "@aiFact"
]

parsed_text_list = []
word_counts = []
for idx, text in comments.items():
    t = text
    for mention in ai_mentionings:
        if mention in t:
            t = t.replace(mention, "")
            
    parsed_text_list.append(BeautifulSoup(str(t), 'lxml').get_text())
    word_counts.append(textstat.lexicon_count(t, removepunct=True))

# print("parsed_text_list")
# display(len(parsed_text_list))
# display(parsed_text_list)
# 
# print("comments raw")
# display(comments.to_list())

display(parsed_text_list)
display(word_counts)
display(pd.Series(word_counts).describe())

0     @aiauthor What are some of the names of these ...
1     @aiauthor Give me more examples of these GenAI...
2                  @aiAI Max what's the history of AI ?
3     @aiauthor Please summarize this part of the text.
4     @aiErika , could you please make this text sho...
                            ...
69    @aiProposal Brain Erzeuge hier eine vollständi...
70    @aiGrammar kindly review the paragraph for spe...
71                    @aiFact Checker is this accurate?
72                    @aiFact Checker is this accurate?
73    @aiGrammar can you review the grammar and sent...
Name: text, Length: 74, dtype: object

74

['\xa0What are some of the names of these algorithms?',
 '\xa0Give me more examples of these GenAI models.\xa0',
 "\xa0what's the history of AI ?",
 '\xa0Please summarize this part of the text.',
 ', could you please make this text shorter without loose of meaning',
 ', could you please summarize the written advantages and disadvantages and write the conclusion for this essay',
 '\xa0Definition of health and wellness',
 '\xa0, Write the content for this intro essay part',
 '\xa0, Enhance professional tone',
 '\xa0 can you give any statisctics about\xa0weather digitalization actually improves health or not',
 '\xa0Fix my text, enhance professional tone for this part of essay',
 '\xa0Generate content for this body part of the essay',
 'make it shorter\xa0 \xa0',
 '\xa0',
 'Provide a one-sentence definition of LDAP in this context.',
 'Fix all typos. Do not change anything else!',
 'Make this text more scientific, avoiding terms that make it sound like a blog post. Ensure that no overclaims are made.',
 'What do you think of my abstract?',
 'Write an abstract for this paper',
 'provide a good reference',
 'Find an appropriate reference',
 'Generate a draft for this argument (2-3 sentences, ideally with references from literature)',
 '\xa0Tone this down! Overclaim?',
 'How to enhance the design implications? ',
 'add some new facts',
 'expand this please',
 'Generate the text for this section about the role of AI in transportation.',
 'add 3 senetences',
 'the word reskilling is not suitable. suggest a better word.',
 'Generate text for this section, it is called "3. Economic and Employment Impact" . This section is part of the essay: AI and its impact on our lives.',
 'what can you say more?',
 'add some facts please',
 'Please explain this term Narrow AI for a person that has a good understanding of AI',
 'add two interesting facts',
 "Generate text for this section about AI's smart role in smart assistance and customer tech",
 'can you make it coherent',
 'this paragraph has reflects some redundancies from previous paragraphs. Replace "the simulation of human intelligence" with something better fitting.',
 'expand with facts please',
 'Generate this section rewritten, in a more professional matter. avoid the word reskilling.',
 'Oversee this section, make it compact and meaningful. Provide the complete text to replace this one.',
 'This section should also mention the contribution of highly developed GPUs to the boom of AI',
 'Provide the text for this bullet point',
 'add two more sentences please',
 'rewrite it with facts but as a whole coherent text',
 'think like a developer about write content for this step of web development process',
 'Make bulltet points for this paragraph',
 'Rephrase it such that it feels narrating what the developers will do in this process as third person.',
 'can u summarise this but cover everything make it intriguing so user wants to read further',
 'any mistake?',
 'complete the paragraph',
 'Rephrase it such that it feels narrating what the developers will do in this process as third person.',
 'think like a developer and suggest content for this step in the development process',
 'suggest changes if necessary if there is a break in the flow of the article',
 'Make them into proper bullet points',
 'Make them into bulet points',
 'Write a paragraph after this content.',
 'Suggest new content for this step in the web development process according to the title',
 'suggest some heading for this step',
 'Rephrase the content to narrate from the perspective of a client not developer.',
 'write this step again but keep it same as the article the flow should break.',
 'Divide them into bullet points',
 'summarize the research papers like an experienced researcher giving an overview of whtere research on human-agent collaboration is at right now and where it is headed.',
 'create an outline for a text document describing all relevant aspects of a seminar called "Hauptseminar" in which students read, understand and summarize research papers on human-agent collaboration in order togain an understanding of the previous work and to find research opportunities.',
 'read the papers listed here and create a high level summary of research in this field just like an experience researcher would do when asked to provide an overview of where the field is right now and where it is headed.',
 'Der Titel ist mir noch zu unrund. Generiere drei Alternativen.',
 'Bitte verschmelze den Satzbeginn und den unvollständigen Absatz. Antworte nur mit dem Resultat.',
 'Schreibe hier einen Paragraphen über die Sozialen Netzwerk-Graphen. Orientiere dich an dem vorherigen Absatz über Prozessregeln. Stelle als einen zentralen Nachteil dar, dass aktuelle Techniken damit aufhören, für sowohl Event Logs als auch Compliance-Dokumente solche Graphen anzuzeigen, aus denen dann die User manuell die Abweichungen ermitteln müssen. Hier fehlt eine automatisierte Ermittlung der Abweichung und eine adäquate Repräsentation der Ergebnisse.',
 'Finde einen passenden Titel für das im nachfolgenden Abstract beschriebene Forschungsprojekt. Der Titel soll auffällig (und gern kreativ) aber nicht übertrieben sein. Der Fokus soll auf der gesellschaftlichen Relevanz des Themas liegen.',
 'Erstelle drei Varianten eines Titels auf Basis von Vorschlag Nr. 2. "Compliance für alle" gefällt mir nicht. Der Begriff Digitalisierung muss vorkommen.',
 'Erzeuge hier eine vollständige Projektbeschreibung, welche die folgenden Punkte beinhaltet:- Datengrundlage- mögliche Anwendungsgebiete (hier bitte auch das Bundesamt für Migration und Flüchtlinge einbeziehen)- Vorgehen (Phasen und Methoden)- Erwartete ProjektergebnisseGehe bitte davon aus, dass nur ein Mitarbeiter für ca. 1,5 Jahre an diesem Projekt arbeitet. Nimm zudem den Stand der Forschung, der zuvor beschrieben wurde als Grundlage.Antworte ausschließlich mit dem Text der Projektbeschreibung (keine Erklärungen oder dergleichen).',
 'kindly review the paragraph for spelling mistakes',
 'Checker is this accurate?',
 'Checker is this accurate?',
 'can you review the grammar and sentence structure']

[9,
 8,
 5,
 7,
 11,
 16,
 5,
 8,
 3,
 13,
 11,
 9,
 3,
 0,
 9,
 8,
 21,
 7,
 6,
 4,
 4,
 13,
 4,
 6,
 4,
 3,
 13,
 3,
 10,
 27,
 5,
 4,
 16,
 4,
 15,
 5,
 19,
 4,
 13,
 16,
 16,
 7,
 5,
 10,
 14,
 6,
 18,
 16,
 2,
 3,
 18,
 14,
 15,
 6,
 5,
 6,
 15,
 6,
 13,
 15,
 5,
 26,
 42,
 41,
 10,
 13,
 60,
 32,
 22,
 66,
 7,
 4,
 4,
 8]

count    74.000000
mean     12.175676
std      11.820991
min       0.000000
25%       5.000000
50%       8.500000
75%      15.000000
max      66.000000
dtype: float64

In [15]:
comments_agents_df = pd.merge(comments_df, agents_df, left_on='assignee_id', right_on='id', how='left')
display(comments_agents_df.head(15))

,Unnamed: 0,assignee_id,assignee_name,text,writing_stage,users_primary_intent,group_id_x,user_x,user_id,comment_id,#,id,roles,profile.sections.expertise,profile.sections.skills,co_creative_role,group_id_y,user_y
0,0,ai-author,AI author,@aiauthor What are some of the names of these ...,revising,learning,3,1378,67cc9f69285fac3f07bcf5c8,7DTFbKN6yVngm0vX_3FoB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,ai-author,AI author,@aiauthor Give me more examples of these GenAI...,revising,"inspiration, learning",3,1378,67cc9f69285fac3f07bcf5c8,VAatOu1QDqAt07vy7Ne8h,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,67cdfef4285fac3f07bcf5d3,AI Max,@aiAI Max what's the history of AI ?,drafting,learning,3,1378,67cc9f69285fac3f07bcf5c8,6daYdxwEEcG58TSTMV6aw,6.0,67cdfef4285fac3f07bcf5d3,Fact Checker and Fact Provider,"Fact Validation, Historical Research","Data Verification, AI Factology",advisor,3.0,1374.0
3,3,ai-author,AI author,@aiauthor Please summarize this part of the text.,revising,"inspiration, improve text / readability",3,1378,67cc9f69285fac3f07bcf5c8,CiDt21N2QEP1m7Le0k_mj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika , could you please make this text sho...",revising,improve text / readability,3,1374,67cdfa30285fac3f07bcf5cc,SuRM3VccpleBCCxUJqLEG,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3.0,1374.0
5,6,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika, could you please summarize the writt...",drafting,efficiency,3,1374,67cdfa30285fac3f07bcf5cc,gobhqckqLD3t1FGuJG6l8,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3.0,1374.0
6,7,ai-author,AI author,@aiauthor Definition of health and wellness,drafting,learning,1,1379,67ce982f285fac3f07bcf5e7,mHIkbNGUYqepeZ-_NGSVN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,ai-author,AI author,"@aiauthor , Write the content for this intro e...",drafting,"inspiration, efficiency",1,1380,67ce9cb4285fac3f07bcf5ec,MfaSsmCS8az5tJiEdtIX1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,ai-author,AI author,"@aiauthor , Enhance professional tone",revising,improve text / readability,1,1380,67ce9cb4285fac3f07bcf5ec,6PoKqRSqm5nBKdEJnF7KG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,ai-author,AI author,@aiauthor can you give any statisctics about ...,drafting,learning,1,1379,67ce982f285fac3f07bcf5e7,nOqZNstq0_qlc9q0-0c4X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,ai-author,AI author,"@aiauthor Fix my text, enhance professional to...",revising,improve text / readability,1,1380,67ce9cb4285fac3f07bcf5ec,mKJ7hgCmK8cXI1G8P2fjG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,ai-author,AI author,@aiauthor Generate content for this body part ...,drafting,"inspiration, efficiency",1,1380,67ce9cb4285fac3f07bcf5ec,i4CWhJhTRsJHHRrG0p51u,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,67d83558edfe680c1b0f165e,TextReviewer,make it shorter @aiTextReviewer,revising,improve text / readability,6,1388,67d82dc4edfe680c1b0f1642,zxi5tyLFqqaEic9c6jeEF,19.0,67d83558edfe680c1b0f165e,Text Analysis and Feedback Specialist,"Text Review, Textual Criticism","Readability assessment, Constructive feedback ...",editor,6.0,1388.0
13,14,67e5cb6450d39f32454bf2fa,ContentReviewer,@aiContentReviewer,NaN,NaN,4,1384,67d444dd0b9539e69a3a86bb,hJ9sUH3y-UK90rmCILf4j,10.0,67e5cb6450d39f32454bf2fa,Critical Reviewer with HCI and Education Exper...,"Human-Computer Interaction, Education, AI-assi...","Spot logical faults, Creative thinking, Asking...",advisor,4.0,1384.0
14,15,67d445e30b9539e69a3a86c3,Best HCI Professor,@aiBest HCI Professor @aiContentReviewer Provi...,drafting,learning,4,1384,67d444dd0b9539e69a3a86bb,6GeYajr9KcHFjpFb0Q--z,11.0,67d445e30b9539e69a3a86c3,This AI Assistant is the best HCI Professor in...,"HCI, Teaching","Programming, Proof Reading, Supervision",advisor,4.0,1385.0

In [16]:
comments_agents_exploded_df = comments_agents_df.copy()
display(comments_agents_exploded_df.head(15))

comments_agents_exploded_df.co_creative_role = comments_agents_exploded_df.co_creative_role.str.split(',')
comments_agents_exploded_df = comments_agents_exploded_df.explode('co_creative_role')
comments_agents_exploded_df.co_creative_role = comments_agents_exploded_df.co_creative_role.str.strip()
comments_agents_exploded_df.co_creative_role = comments_agents_exploded_df.co_creative_role.fillna("ai-author")
display(comments_agents_exploded_df.head(15))

display("Co-Creative-Roles for Comments (Ad-hoc tasks) in OUTLINING stage")
outlining_roles = comments_agents_exploded_df[comments_agents_exploded_df['writing_stage'] == "outlining"]["co_creative_role"]
display(outlining_roles.value_counts())
display(outlining_roles.value_counts().describe())

display("Co-Creative-Roles  for Comments (Ad-hoc tasks) in DRAFTING stage")
drafting_roles = comments_agents_exploded_df[comments_agents_exploded_df['writing_stage'] == "drafting"]["co_creative_role"]
display(drafting_roles.value_counts())
display(drafting_roles.value_counts().describe())

display("Co-Creative-Roles  for Comments (Ad-hoc tasks) in REVISING stage")
revising_roles = comments_agents_exploded_df[comments_agents_exploded_df['writing_stage'] == "revising"]["co_creative_role"]
display(revising_roles.value_counts())
display(revising_roles.value_counts().describe())

,Unnamed: 0,assignee_id,assignee_name,text,writing_stage,users_primary_intent,group_id_x,user_x,user_id,comment_id,#,id,roles,profile.sections.expertise,profile.sections.skills,co_creative_role,group_id_y,user_y
0,0,ai-author,AI author,@aiauthor What are some of the names of these ...,revising,learning,3,1378,67cc9f69285fac3f07bcf5c8,7DTFbKN6yVngm0vX_3FoB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,ai-author,AI author,@aiauthor Give me more examples of these GenAI...,revising,"inspiration, learning",3,1378,67cc9f69285fac3f07bcf5c8,VAatOu1QDqAt07vy7Ne8h,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,67cdfef4285fac3f07bcf5d3,AI Max,@aiAI Max what's the history of AI ?,drafting,learning,3,1378,67cc9f69285fac3f07bcf5c8,6daYdxwEEcG58TSTMV6aw,6.0,67cdfef4285fac3f07bcf5d3,Fact Checker and Fact Provider,"Fact Validation, Historical Research","Data Verification, AI Factology",advisor,3.0,1374.0
3,3,ai-author,AI author,@aiauthor Please summarize this part of the text.,revising,"inspiration, improve text / readability",3,1378,67cc9f69285fac3f07bcf5c8,CiDt21N2QEP1m7Le0k_mj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika , could you please make this text sho...",revising,improve text / readability,3,1374,67cdfa30285fac3f07bcf5cc,SuRM3VccpleBCCxUJqLEG,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3.0,1374.0
5,6,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika, could you please summarize the writt...",drafting,efficiency,3,1374,67cdfa30285fac3f07bcf5cc,gobhqckqLD3t1FGuJG6l8,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...","advisor, editor",3.0,1374.0
6,7,ai-author,AI author,@aiauthor Definition of health and wellness,drafting,learning,1,1379,67ce982f285fac3f07bcf5e7,mHIkbNGUYqepeZ-_NGSVN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,ai-author,AI author,"@aiauthor , Write the content for this intro e...",drafting,"inspiration, efficiency",1,1380,67ce9cb4285fac3f07bcf5ec,MfaSsmCS8az5tJiEdtIX1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,ai-author,AI author,"@aiauthor , Enhance professional tone",revising,improve text / readability,1,1380,67ce9cb4285fac3f07bcf5ec,6PoKqRSqm5nBKdEJnF7KG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,ai-author,AI author,@aiauthor can you give any statisctics about ...,drafting,learning,1,1379,67ce982f285fac3f07bcf5e7,nOqZNstq0_qlc9q0-0c4X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,ai-author,AI author,"@aiauthor Fix my text, enhance professional to...",revising,improve text / readability,1,1380,67ce9cb4285fac3f07bcf5ec,mKJ7hgCmK8cXI1G8P2fjG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,ai-author,AI author,@aiauthor Generate content for this body part ...,drafting,"inspiration, efficiency",1,1380,67ce9cb4285fac3f07bcf5ec,i4CWhJhTRsJHHRrG0p51u,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,67d83558edfe680c1b0f165e,TextReviewer,make it shorter @aiTextReviewer,revising,improve text / readability,6,1388,67d82dc4edfe680c1b0f1642,zxi5tyLFqqaEic9c6jeEF,19.0,67d83558edfe680c1b0f165e,Text Analysis and Feedback Specialist,"Text Review, Textual Criticism","Readability assessment, Constructive feedback ...",editor,6.0,1388.0
13,14,67e5cb6450d39f32454bf2fa,ContentReviewer,@aiContentReviewer,NaN,NaN,4,1384,67d444dd0b9539e69a3a86bb,hJ9sUH3y-UK90rmCILf4j,10.0,67e5cb6450d39f32454bf2fa,Critical Reviewer with HCI and Education Exper...,"Human-Computer Interaction, Education, AI-assi...","Spot logical faults, Creative thinking, Asking...",advisor,4.0,1384.0
14,15,67d445e30b9539e69a3a86c3,Best HCI Professor,@aiBest HCI Professor @aiContentReviewer Provi...,drafting,learning,4,1384,67d444dd0b9539e69a3a86bb,6GeYajr9KcHFjpFb0Q--z,11.0,67d445e30b9539e69a3a86c3,This AI Assistant is the best HCI Professor in...,"HCI, Teaching","Programming, Proof Reading, Supervision",advisor,4.0,1385.0

,Unnamed: 0,assignee_id,assignee_name,text,writing_stage,users_primary_intent,group_id_x,user_x,user_id,comment_id,#,id,roles,profile.sections.expertise,profile.sections.skills,co_creative_role,group_id_y,user_y
0,0,ai-author,AI author,@aiauthor What are some of the names of these ...,revising,learning,3,1378,67cc9f69285fac3f07bcf5c8,7DTFbKN6yVngm0vX_3FoB,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
1,1,ai-author,AI author,@aiauthor Give me more examples of these GenAI...,revising,"inspiration, learning",3,1378,67cc9f69285fac3f07bcf5c8,VAatOu1QDqAt07vy7Ne8h,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
2,2,67cdfef4285fac3f07bcf5d3,AI Max,@aiAI Max what's the history of AI ?,drafting,learning,3,1378,67cc9f69285fac3f07bcf5c8,6daYdxwEEcG58TSTMV6aw,6.0,67cdfef4285fac3f07bcf5d3,Fact Checker and Fact Provider,"Fact Validation, Historical Research","Data Verification, AI Factology",advisor,3.0,1374.0
3,3,ai-author,AI author,@aiauthor Please summarize this part of the text.,revising,"inspiration, improve text / readability",3,1378,67cc9f69285fac3f07bcf5c8,CiDt21N2QEP1m7Le0k_mj,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
4,5,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika , could you please make this text sho...",revising,improve text / readability,3,1374,67cdfa30285fac3f07bcf5cc,SuRM3VccpleBCCxUJqLEG,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...",advisor,3.0,1374.0
4,5,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika , could you please make this text sho...",revising,improve text / readability,3,1374,67cdfa30285fac3f07bcf5cc,SuRM3VccpleBCCxUJqLEG,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...",editor,3.0,1374.0
5,6,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika, could you please summarize the writt...",drafting,efficiency,3,1374,67cdfa30285fac3f07bcf5cc,gobhqckqLD3t1FGuJG6l8,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...",advisor,3.0,1374.0
5,6,67cdfc85285fac3f07bcf5cf,Erika,"@aiErika, could you please summarize the writt...",drafting,efficiency,3,1374,67cdfa30285fac3f07bcf5cc,gobhqckqLD3t1FGuJG6l8,5.0,67cdfc85285fac3f07bcf5cf,Essay Reviewer,"Literature Studies, Academic Editing, Essay Wr...","Reading and Writing Essay, Professional Redact...",editor,3.0,1374.0
6,7,ai-author,AI author,@aiauthor Definition of health and wellness,drafting,learning,1,1379,67ce982f285fac3f07bcf5e7,mHIkbNGUYqepeZ-_NGSVN,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
7,8,ai-author,AI author,"@aiauthor , Write the content for this intro e...",drafting,"inspiration, efficiency",1,1380,67ce9cb4285fac3f07bcf5ec,MfaSsmCS8az5tJiEdtIX1,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
8,9,ai-author,AI author,"@aiauthor , Enhance professional tone",revising,improve text / readability,1,1380,67ce9cb4285fac3f07bcf5ec,6PoKqRSqm5nBKdEJnF7KG,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
9,10,ai-author,AI author,@aiauthor can you give any statisctics about ...,drafting,learning,1,1379,67ce982f285fac3f07bcf5e7,nOqZNstq0_qlc9q0-0c4X,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
10,11,ai-author,AI author,"@aiauthor Fix my text, enhance professional to...",revising,improve text / readability,1,1380,67ce9cb4285fac3f07bcf5ec,mKJ7hgCmK8cXI1G8P2fjG,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
11,12,ai-author,AI author,@aiauthor Generate content for this body part ...,drafting,"inspiration, efficiency",1,1380,67ce9cb4285fac3f07bcf5ec,i4CWhJhTRsJHHRrG0p51u,NaN,NaN,NaN,NaN,NaN,ai-author,NaN,NaN
12,13,67d83558edfe680c1b0f165e,TextReviewer,make it shorter @aiTextReviewer,revising,improve text / readability,6,1388,67d82dc4edfe680c1b0f1642,zxi5tyLFqqaEic9c6jeEF,19.0,67d83558edfe680c1b0f165e,Text Analysis and Feedback Specialist,"Text Review, Textual Criticism","Readability assessment, Constructive feedback ...",editor,6.0,1388.0

'Co-Creative-Roles for Comments (Ad-hoc tasks) in OUTLINING stage'

co_creative_role
editor       3
ai-author    1
Name: count, dtype: int64

count    2.000000
mean     2.000000
std      1.414214
min      1.000000
25%      1.500000
50%      2.000000
75%      2.500000
max      3.000000
Name: count, dtype: float64

'Co-Creative-Roles  for Comments (Ad-hoc tasks) in DRAFTING stage'

co_creative_role
co-author    19
advisor       8
ai-author     8
editor        2
Name: count, dtype: int64

count     4.000000
mean      9.250000
std       7.088723
min       2.000000
25%       6.500000
50%       8.000000
75%      10.750000
max      19.000000
Name: count, dtype: float64

'Co-Creative-Roles  for Comments (Ad-hoc tasks) in REVISING stage'

co_creative_role
co-author    12
advisor       6
editor        6
ai-author     5
assistant     5
Name: count, dtype: int64

count     5.000000
mean      6.800000
std       2.949576
min       5.000000
25%       5.000000
50%       6.000000
75%       6.000000
max      12.000000
Name: count, dtype: float64