In [198]:
import os
import pandas as pd
import json

from datetime import datetime

In [199]:
# REMOVED USER LOGS BEFORE PUBLICATION (PRIVACY)
#generic_interactions_file = 'generic.tsv'
#generic_interactions = pd.read_csv(os.path.join('input/logdata', generic_interactions_file), sep='\t')
#generic_interactions = generic_interactions[~generic_interactions['participant_id'].isin([2473, 2476, 2467])]
#generic_interactions.to_csv(os.path.join('input/logdata', 'generic_pub.tsv'), sep="\t")

In [200]:
# REMOVED USER LOGS BEFORE PUBLICATION (PRIVACY)
# keyboard_interactions_file = 'keyboard.tsv'
# keyboard_interactions = pd.read_csv(os.path.join('input/logdata', keyboard_interactions_file), sep='\t')
# keyboard_interactions = keyboard_interactions[~keyboard_interactions['participant_id'].isin([2473, 2476, 2467])]
# keyboard_interactions.to_csv(os.path.join('input/logdata', 'keyboard_pub.tsv'), sep="\t")

In [201]:
def transform_time(df, col="time"):
    format = '%Y-%m-%d %H:%M:%S.%f'
    if col == 'time':
        df['time'] = df['time'].apply(lambda x: datetime.strptime(x, format))
    else:
        df[col] = df[col].apply(lambda x: datetime.strptime(x, format))
    return df

def second_difference(d2, d1):
    format = '%Y-%m-%d %H:%M:%S.%f'
    d2 = datetime.strptime(d2, format)
    d1 = datetime.strptime(d1, format)
    return (d2 - d1).seconds

def minutes_difference(d2, d1):
    return second_difference(d2, d1) / 60

In [202]:
# fix users with two participant tokens / ids

# first replace participant tokens across the tsv file
# after reading the tsv file, replace the participant_ids

with open(os.path.join('input/logdata', "generic.tsv"), "rt") as fin:
    with open(os.path.join('input/logdata', "generic_replaced.tsv"), "wt") as fout:
        for line in fin:
            l = line.replace('024d811b-6640-4745-b751-39582d07e3ea', '4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50')
            l = l.replace('191d2035-c072-40fa-9639-60a190a01598', '3cf38828-43dc-4112-9ab0-135e2c28b54d')
            fout.write(l)
            
with open(os.path.join('input/logdata', "keyboard.tsv"), "rt") as fin:
    with open(os.path.join('input/logdata', "keyboard_replaced.tsv"), "wt") as fout:
        for line in fin:
            l = line.replace('024d811b-6640-4745-b751-39582d07e3ea', '4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50')
            l = l.replace('191d2035-c072-40fa-9639-60a190a01598', '3cf38828-43dc-4112-9ab0-135e2c28b54d')
            fout.write(l)

In [203]:
# read the interaction data
generic_interactions_file = 'generic_replaced.tsv'
generic_interactions = pd.read_csv(os.path.join('input/logdata', generic_interactions_file), sep='\t')
display(generic_interactions.head())

keyboard_interactions_file = 'keyboard_replaced.tsv'
keyboard_interactions = pd.read_csv(os.path.join('input/logdata', keyboard_interactions_file), sep='\t',)
display(keyboard_interactions.head())

procedure_progress_file = 'procedure_progress.tsv'
procedure_progress = pd.read_csv(os.path.join('input/logdata', procedure_progress_file), sep='\t', )
display(procedure_progress.head())
procedure_progress = transform_time(procedure_progress, 'time')

,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state
0,0,276010.0,4f2b579b-a3b7-4abf-b302-cd694a655b6c,Prototype,2025-02-23 16:21:18.411000,USER_AGENT,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
1,1,276011.0,ac4a0997-8067-4cff-b892-5f0338aec02c,Prototype,2025-02-23 16:21:28.769000,USER_LOGIN,"{""username"": ""krystsina""}",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
2,2,276012.0,9b68682d-e734-42e6-9ec6-8ab759f311fe,Prototype,2025-02-23 16:21:31.788000,DOCUMENT_SELECT,"{""user_id"": ""67a0d6209f5c900ebf5c43ab"", ""usern...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
3,3,276013.0,f2951cbd-bdde-4640-87a7-ff8738f29d8c,Prototype,2025-02-23 16:21:33.073000,DOCUMENT_OPEN,"{""user_id"": ""67a0d6209f5c900ebf5c43ab"", ""usern...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
4,4,276014.0,ef4a681b-d21a-4238-817c-51818d23fc9e,Prototype,2025-02-23 16:21:33.383000,DOCUMENT_VIEW,"{""user_id"": ""67a0d6209f5c900ebf5c43ab"", ""usern...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress

/tmp/ipykernel_162117/2823158241.py:7: DtypeWarning: Columns (7,9,10,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  keyboard_interactions = pd.read_csv(os.path.join('input/logdata', keyboard_interactions_file), sep='\t',)

,Unnamed: 0,id,condition_id,name,event_uuid,time,event,alt_key,code,ctrl_key,is_composing,key,location,meta_key,repeat,shift_key,meta_data,participant_id,participant_token,participant_state
0,0,1.0,216.0,Prototype,0b0d2a0a-ec93-4231-bdef-3e0a3b66bc56,2025-02-25 20:23:34.842000,keydown,False,KeyG,False,False,g,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress
1,1,2.0,216.0,Prototype,fd266131-9d2e-4666-b445-0968d447759a,2025-02-25 20:23:35.160000,keydown,False,KeyD,False,False,d,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress
2,2,3.0,216.0,Prototype,b242ba72-c7dc-4a7c-881d-9f1bc6ac3451,2025-02-25 20:23:35.501000,keydown,False,KeyF,False,False,f,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress
3,3,4.0,216.0,Prototype,b63ad8db-4a28-4eb8-89ec-b45b2c044853,2025-02-25 20:23:35.718000,keydown,False,KeyD,False,False,d,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress
4,4,5.0,216.0,Prototype,6762d56c-2c15-4265-9ceb-7df5235f371c,2025-02-25 20:23:36.460000,keydown,False,KeyD,False,False,d,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress

,participant_id,participant_token,participant_state,procedure_progress_id,state,time,procedure_step_id,procedure_id,condition_id,text_id,questionnaire_id,pause_id,procedure_step,conditions_name,conditions_url,texts_title,questionnaires_url
0,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1690,start_step,2025-02-24 16:19:33.635717,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
1,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1689,start_experiment,2025-02-24 16:19:33.635717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1691,end_step,2025-02-24 16:20:23.329665,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
3,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1692,start_step,2025-02-24 16:20:23.329665,319.0,58.0,NaN,566.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
4,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1693,end_step,2025-02-24 16:20:28.439088,319.0,58.0,NaN,566.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN

In [204]:
# fix participant_ids of users with two participant_tokens

display(generic_interactions[generic_interactions["participant_id"] == 2458])
generic_interactions.loc[generic_interactions['participant_id'] == 2458, 'participant_id'] = 2460

display(generic_interactions[generic_interactions["participant_id"] == 2473])
generic_interactions.loc[generic_interactions['participant_id'] == 2473, 'participant_id'] = 2476

display(keyboard_interactions[keyboard_interactions["participant_id"] == 2458])
generic_interactions.loc[keyboard_interactions['participant_id'] == 2458, 'participant_id'] = 2460

display(keyboard_interactions[keyboard_interactions["participant_id"] == 2473])
generic_interactions.loc[keyboard_interactions['participant_id'] == 2473, 'participant_id'] = 2476

,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state
4368,4368,280451.0,5248a88d-7c49-4ddf-aa9e-d8048af87f2a,Prototype,2025-07-28 17:54:15.447000,USER_AGENT,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
4369,4369,280452.0,697e41bb-a7d8-4c93-ae90-872ace53c54d,Prototype,2025-07-28 17:54:56.011000,USER_LOGIN,"{""username"": ""Naira"", ""participant_token"": ""4f...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
4370,4370,280453.0,7d5992f5-2921-4cad-8196-1c8b59c6982c,Prototype,2025-07-28 17:55:04.009000,DOCUMENT_JOIN,"{""user_id"": ""6887b97087cf5fec60dc8060"", ""usern...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
4371,4371,280454.0,f796a295-ca54-456a-90ad-979cf2829e41,Prototype,2025-07-28 17:55:04.490000,DOCUMENT_VIEW,"{""user_id"": ""6887b97087cf5fec60dc8060"", ""usern...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
4372,4372,280455.0,f5747c72-a8ea-471e-a513-fb86ac237434,Prototype,2025-07-28 17:55:14.641000,DOCUMENT_TEXT_UPDATE,"{""text"": ""<h1>Artificial Intelligence and its ...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
...,...,...,...,...,...,...,...,...,...,...
4488,4488,280571.0,8b1231b5-ab86-4a4e-a4f0-df8f2615e310,Prototype,2025-07-28 18:03:33.105000,AGENT_CV_SECTION_GENERATED_VALUE_ADD,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
4489,4489,280572.0,88d1da77-6b32-49f9-9a48-ee109249feff,Prototype,2025-07-28 18:03:35.222000,AGENT_CV_SECTION_GENERATED_VALUE_ADD,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
4490,4490,280573.0,b856590c-287e-4953-84dd-456e211441ce,Prototype,2025-07-28 18:03:36.972000,AGENT_CV_SECTION_GENERATED_VALUE_ADD,"{""section"": ""skills"", ""user_id"": ""6887b97087cf...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
4491,4491,280574.0,fcdd01e6-dcf0-4d85-ace6-a539cc008c11,Prototype,2025-07-28 18:03:38.556000,AGENT_CV_SECTION_ADD,"{""user_id"": ""6887b97087cf5fec60dc8060"", ""agent...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
4493,4493,280576.0,c1ce8587-1539-4698-9273-4ea83ee0a15f,Prototype,2025-07-28 18:03:44.585000,AGENT_CV_SECTION_GENERATE,"{""section"": ""undefined"", ""user_id"": ""6887b9708...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress

Empty DataFrame
Columns: [Unnamed: 0, id, event_uuid, name, time, event, data, participant_id, participant_token, participant_state]
Index: []

,Unnamed: 0,id,condition_id,name,event_uuid,time,event,alt_key,code,ctrl_key,is_composing,key,location,meta_key,repeat,shift_key,meta_data,participant_id,participant_token,participant_state
17638,17638,17639.0,221.0,Prototype,4e439de7-c76e-40fb-bbc5-c5f2466b7ab4,2025-07-28 17:56:04.168000,keydown,False,MetaLeft,False,False,Meta,1.0,True,False,False,"{""source"": ""editor"", ""user_id"": ""6887b97087cf5...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
17639,17639,17640.0,221.0,Prototype,2bd1c29c-977f-47b9-90b9-71b1468bede5,2025-07-28 17:56:04.384000,keydown,False,KeyC,False,False,c,0.0,True,False,False,"{""source"": ""editor"", ""user_id"": ""6887b97087cf5...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
17640,17640,17641.0,221.0,Prototype,1158ed93-d57d-44d4-85ad-97add04cd6c5,2025-07-28 17:56:28.694000,keydown,False,MetaLeft,False,False,Meta,1.0,True,False,False,"{""source"": ""editor"", ""user_id"": ""6887b97087cf5...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
17641,17641,17642.0,221.0,Prototype,ece2fdad-b7b0-452b-97c2-6780a107dee8,2025-07-28 17:56:28.848000,keydown,False,KeyC,False,False,c,0.0,True,False,False,"{""source"": ""editor"", ""user_id"": ""6887b97087cf5...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
17642,17642,17643.0,221.0,Prototype,e191bae4-3e8e-46fd-9614-1f677c566a15,2025-07-28 17:57:26.982000,keydown,False,Enter,False,False,Enter,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""6887b97087cf5...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17717,17717,17718.0,221.0,Prototype,3164a9ee-4c99-4041-be1e-3d44d78989ed,2025-07-28 18:02:45.211000,keydown,False,CapsLock,False,False,CapsLock,0.0,False,False,False,"{""card_id"": ""FGaa84DVAZLj9oCPzaPwF"", ""user_id""...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
17718,17718,17719.0,221.0,Prototype,d8c4f80e-fc56-4f2b-9a34-df4f81bd7cb3,2025-07-28 18:02:45.330000,keydown,False,Slash,False,False,/,0.0,False,False,False,"{""card_id"": ""FGaa84DVAZLj9oCPzaPwF"", ""user_id""...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
17719,17719,17720.0,221.0,Prototype,80fbbd90-ba45-4b58-b4d7-c95f3e884d71,2025-07-28 18:02:46.284000,keydown,False,Backspace,False,False,Backspace,0.0,False,False,False,"{""card_id"": ""FGaa84DVAZLj9oCPzaPwF"", ""user_id""...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
17720,17720,17721.0,221.0,Prototype,15d89bb3-d031-4028-9761-88fad3ba3641,2025-07-28 18:02:46.495000,keydown,False,ShiftLeft,False,False,Shift,1.0,False,False,True,"{""card_id"": ""FGaa84DVAZLj9oCPzaPwF"", ""user_id""...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress
17721,17721,17722.0,221.0,Prototype,00afda85-3718-4863-805a-d0b26e0ad739,2025-07-28 18:02:46.656000,keydown,False,Slash,False,False,?,0.0,False,False,True,"{""card_id"": ""FGaa84DVAZLj9oCPzaPwF"", ""user_id""...",2458,4f4b17e2-dcb0-4391-a3de-8f3a8c3fac50,in_progress

Empty DataFrame
Columns: [Unnamed: 0, id, condition_id, name, event_uuid, time, event, alt_key, code, ctrl_key, is_composing, key, location, meta_key, repeat, shift_key, meta_data, participant_id, participant_token, participant_state]
Index: []

In [205]:
display(generic_interactions[generic_interactions["participant_id"] == 2460]["event"].value_counts())
display(generic_interactions[generic_interactions["participant_id"] == 2476]["event"].value_counts())

event
DOCUMENT_TEXT_UPDATE                    48
MARKER_SELECT                           44
COMMENT_AGENT_STOP_TYPING               18
COMMENT_USER_DROPDOWN_SHOW              18
COMMENT_AGENT_START_TYPING              18
REPLY_AI                                18
COMMENT_ADD                             18
SUGGESTION_INSERT_AFTER                 14
TASK_CREATE                             13
TASKS_VIEW                              12
COMMENT_USER_DROPDOWN_HIDE              10
COMMENT_POST                            10
COMMENT_USER_DROPDOWN_SELECT            10
DOCUMENT_TEXT_PASTE                      9
COMMENT_TASK_ADD                         8
COMMENT_REPLY_APPROVE                    7
DOCUMENT_VIEW                            6
TASK_SHORTCUT_RUN                        6
CARD_ADD                                 5
TASKS_VIEW_CLOSE                         5
COMMENT_DELETE                           4
AGENT_CV_SECTION_VALUE_ADD               4
COMMENTS_REMOTE_ADD                      4
AGENTS_VIEW                              4
TASK_CREATED                             4
AGENT_ICON_CLICK                         4
CARD_CLOSE                               4
DOCUMENT_TEXT_COPY                       3
SUGGESTION_TAKE_OVER                     3
DOCUMENT_JOIN                            3
AGENT_CV_SECTION_GENERATED_VALUE_ADD     3
DOCUMENT_SAVE                            3
OPEN_AI_RESULT                           3
TASK_RUN                                 3
USER_LOGIN                               2
AGENT_ADD                                2
AGENT_CREATE                             2
AGENT_CV_SECTION_GENERATE                2
FINAL_PROCEED_TEXT                       2
AGENTS_VIEW_CLOSE                        2
USER_AGENT                               2
AGENT_SAVE                               1
T5_SUMMARY_AI_RESULT                     1
SUGGESTION_VIEWDETAIL                    1
AGENT_CV_SECTION_ADD                     1
AGENT_PROFILE_VIEW                       1
CARD_APPROVE                             1
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

In [206]:
display(keyboard_interactions[keyboard_interactions["participant_id"] == 2460]["event"].value_counts())
display(keyboard_interactions[keyboard_interactions["participant_id"] == 2476]["event"].value_counts())

event
keydown    442
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

In [207]:
display(generic_interactions[generic_interactions["participant_id"] == 2469].tail(100))
display(keyboard_interactions[keyboard_interactions["participant_id"] == 2469].tail(100))

,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state
6624,6624,282707.0,c069e60e-af7c-4912-8887-66a87ac9afbc,Prototype,2025-08-13 09:49:25.696000,TASK_EDITED,"{""newTask"": {""title"": ""Motivation Überprüfung""...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
6625,6625,282708.0,f1c65977-76f3-4eb4-b6f6-b25543cc23e6,Prototype,2025-08-13 09:49:28.845000,TASK_RUN,"{""mode"": ""autonomous"", ""task_id"": ""689c5defe90...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
6626,6626,282709.0,07516cdd-de43-4341-8b10-e58b6e7736a3,Prototype,2025-08-13 09:49:28.846000,TASKS_VIEW_CLOSE,"{""user_id"": ""689c3c25e90ffc190a96c28b"", ""usern...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
6627,6627,282710.0,0bfc9005-c351-4fbf-bba6-dd4dcdb12746,Prototype,2025-08-13 09:50:04.539000,COMMENTS_REMOTE_ADD,"{""cards"": {""Q22OxMHS-94r3cw57W-hD"": {""id"": ""Q2...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
6629,6629,282712.0,18e4a015-3b1f-4521-9f38-6a5b888b79ff,Prototype,2025-08-13 09:50:10.365000,AGENT_ICON_CLICK,"{""user_id"": ""689c3c25e90ffc190a96c28b"", ""agent...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
...,...,...,...,...,...,...,...,...,...,...
6765,6765,282848.0,cd893099-53df-4464-baab-9071546dc44d,Prototype,2025-08-14 08:36:59.090000,DOCUMENT_TEXT_UPDATE,"{""text"": ""<p>Sachbeihilfe DFG</p><h1>Starting ...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
6766,6766,282849.0,dc72113d-8efe-4fd9-9514-58399f2000d1,Prototype,2025-08-14 08:38:00.738000,COMMENTS_REMOTE_ADD,"{""cards"": {""0YMyJ8kjl5rDjlX4eRjmn"": {""id"": ""0Y...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
6768,6768,282851.0,6fcc3757-25eb-4e77-996a-617c05ea740b,Prototype,2025-08-14 08:43:00.715000,COMMENTS_REMOTE_ADD,"{""cards"": {""0YMyJ8kjl5rDjlX4eRjmn"": {""id"": ""0Y...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
7025,7025,283108.0,7f278965-2fc6-463e-b028-445459c4d689,Prototype,2025-08-15 07:52:14.686000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
7275,8515,284598.0,3089028b-6108-4c4a-8cfe-45f7d7b6e793,Prototype,2025-08-27 06:53:08.795000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress

,Unnamed: 0,id,condition_id,name,event_uuid,time,event,alt_key,code,ctrl_key,is_composing,key,location,meta_key,repeat,shift_key,meta_data,participant_id,participant_token,participant_state
31244,31244,31245.0,221.0,Prototype,2c97cdf0-c79e-4080-bb26-93267adf4331,2025-08-13 09:39:37.159000,keydown,False,KeyE,False,False,e,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
31245,31245,31246.0,221.0,Prototype,64993b88-94ac-48bd-8444-5030e73a4e8a,2025-08-13 09:39:37.447000,keydown,False,Space,False,False,,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
31246,31246,31247.0,221.0,Prototype,9ffc37f8-4eab-4c04-bc4e-e2637f580afc,2025-08-13 09:39:37.582000,keydown,False,KeyW,False,False,w,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
31247,31247,31248.0,221.0,Prototype,ce24452f-f8b5-463f-9e5a-b0732d2ff182,2025-08-13 09:39:37.765000,keydown,False,KeyA,False,False,a,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
31248,31248,31249.0,221.0,Prototype,17b20a4d-9213-4c3c-bc1e-297df5ce9e01,2025-08-13 09:39:37.925000,keydown,False,KeyZ,False,False,y,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31339,31339,31340.0,221.0,Prototype,c7b87850-ba61-4631-97f4-fc5109b32db2,2025-08-13 09:39:55.685000,keydown,False,KeyO,False,False,o,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
31340,31340,31341.0,221.0,Prototype,b930305c-7dbc-4174-a50a-128aa8b046a5,2025-08-13 09:39:55.813000,keydown,False,KeyD,False,False,d,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
31341,31341,31342.0,221.0,Prototype,683224f5-9508-4ca8-9c60-83d2605597c1,2025-08-13 09:39:55.965000,keydown,False,KeyS,False,False,s,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
31342,31342,31343.0,221.0,Prototype,b551dc2b-ef10-472a-abc5-16cf4d490e47,2025-08-13 09:39:56.053000,keydown,False,Period,False,False,.,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
31343,31343,31344.0,221.0,Prototype,48c0fb53-07bb-4e6d-b5f0-f6c4ab540880,2025-08-13 09:39:56.223000,keydown,False,Space,False,False,,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""689c3c25e90ff...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress

In [208]:
# Procedure Progress; Step times
procedure_progress = procedure_progress[procedure_progress['procedure_step_id'].notnull()]
procedure_step_ids = procedure_progress['procedure_step_id'].unique()

# participants: 
# g7: 2456, 2458 & 2460 (same user, first in_progress)
# g8: 2453, 2455
# g9: 2461 (in_progress), 2464, 2457
# g10: 2459, 2465
# g11: 2463 (in_progress), 2475
# g12: 2468, 2469 (in_progress)
# g13: 2467, 2473 & 2476 (same user, first in_progress)
# g14: 2470, 2471

# [(374.0, 2461), (373.0, 2463), (373.0, 2469)]

# one participant from group 6 removed 1383! 
participants_id = [1378, 1374, 1376, 1377, 1379, 1387, 1388, 1389, 1390, 1380]
#removed 2458 and 2473 since we merged them into other ids
participants_id_study_extended = [2456, 2460, 2453, 2455, 2461, 2464, 2457, 2459, 2465, 2463, 2475, 2468, 2469, 2467, 2476, 2470, 2471]
# join both lists
participants_id = participants_id + participants_id_study_extended

procedure_step_ids.sort()

display(procedure_step_ids)
display(procedure_progress)

procedure_progress_2463 = procedure_progress[(procedure_progress["participant_id"] == 2463) & (procedure_progress["procedure_step_id"] == 373)]
procedure_progress_2463.loc[procedure_progress_2463["procedure_step_id"] == 373, 'state'] = "end_step"
procedure_progress_2463.loc[procedure_progress_2463["procedure_step_id"] == 373, 'time'] = "2025-08-06 09:48:28.139000"

procedure_progress_2469 = procedure_progress[(procedure_progress["participant_id"] == 2469) & (procedure_progress["procedure_step_id"] == 373)]
procedure_progress_2469.loc[procedure_progress_2469["procedure_step_id"] == 373, 'state'] = "end_step"
procedure_progress_2469.loc[procedure_progress_2469["procedure_step_id"] == 373, 'time'] = "2025-08-14 08:43:00.715000"

if len(procedure_progress[(procedure_progress["participant_id"] == 2463) & (procedure_progress["procedure_step_id"] == 373) & (procedure_progress["state"] == "end_step")]) == 0:
    procedure_progress = pd.concat([procedure_progress, procedure_progress_2463], axis=0)
    
if len(procedure_progress[(procedure_progress["participant_id"] == 2469) & (procedure_progress["procedure_step_id"] == 373) & (procedure_progress["state"] == "end_step")]) == 0:
    procedure_progress = pd.concat([procedure_progress, procedure_progress_2469], axis=0)

display(procedure_progress[procedure_progress['participant_id'] == 2463])
display(procedure_progress[procedure_progress['participant_id'] == 2469])


procedure_progress = procedure_progress[procedure_progress["participant_id"].isin(participants_id)]
display(procedure_progress)
procedure_progress_groups = procedure_progress.groupby(['participant_id', 'procedure_step_id'])

skipped_participants = []
procedure_times_data = []
for name, group in procedure_progress_groups:
    #group = transform_time(group)

    #skip if step hasn't been completed (end time is not available)
    if len(group['time']) < 2:
        skipped_participants.append((name[1], name[0]))
        continue
    time_taken = group['time'].diff().iloc[1]
    procedure_times_data.append({
        'participant_id': name[0],
        'step_id': name[1],
        'time_taken': time_taken
    })

    procedure_progress_time_cols = ['participant_id', 'step_id', 'time_taken']

procedure_progress_times = pd.DataFrame(data = procedure_times_data, columns = procedure_progress_time_cols)

# extended study: 371 + 372 + 373 + 374 + 375
# mean time_taken for each step
display(skipped_participants)
display(procedure_progress_times[procedure_progress_times['step_id'].isin([318, 371])]['time_taken'].mean())
display(procedure_progress_times[procedure_progress_times['step_id'].isin([319, 372])]['time_taken'].mean())
display(procedure_progress_times[procedure_progress_times['step_id'].isin([320, 373])]['time_taken'].describe())
display(procedure_progress_times[procedure_progress_times['step_id'].isin([321, 374])]['time_taken'].mean())
display(procedure_progress_times[procedure_progress_times['step_id'].isin([322, 375])]['time_taken'].mean())

procedure_progress.to_csv(os.path.join('output', 'intermediate', '03_procedure_progress.csv'), sep="\t")

array([318., 319., 320., 321., 322., 371., 372., 373., 374., 375.])

,participant_id,participant_token,participant_state,procedure_progress_id,state,time,procedure_step_id,procedure_id,condition_id,text_id,questionnaire_id,pause_id,procedure_step,conditions_name,conditions_url,texts_title,questionnaires_url
0,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1690,start_step,2025-02-24 16:19:33.635717,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
2,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1691,end_step,2025-02-24 16:20:23.329665,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
3,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1692,start_step,2025-02-24 16:20:23.329665,319.0,58.0,NaN,566.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
4,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1693,end_step,2025-02-24 16:20:28.439088,319.0,58.0,NaN,566.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
5,1358,f8368c56-1f46-4834-ac19-82d15b42cc2a,finished,1694,start_step,2025-02-24 16:20:28.439088,320.0,58.0,216.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2249,end_step,2025-08-25 06:30:36.531669,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN
413,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2250,start_step,2025-08-25 06:30:36.531669,374.0,64.0,NaN,NaN,139.0,NaN,3.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
414,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2251,end_step,2025-08-25 07:28:54.337492,374.0,64.0,NaN,NaN,139.0,NaN,3.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
415,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2252,start_step,2025-08-25 07:28:54.337492,375.0,64.0,NaN,579.0,NaN,NaN,4.0,NaN,NaN,Next steps,NaN
416,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2253,end_step,2025-08-25 07:28:54.428583,375.0,64.0,NaN,579.0,NaN,NaN,4.0,NaN,NaN,Next steps,NaN

,participant_id,participant_token,participant_state,procedure_progress_id,state,time,procedure_step_id,procedure_id,condition_id,text_id,questionnaire_id,pause_id,procedure_step,conditions_name,conditions_url,texts_title,questionnaires_url
274,2463,38811499-e7ca-453e-a57b-86c5dcdee514,in_progress,2104,start_step,2025-07-30 09:30:03.179987,371.0,64.0,NaN,NaN,138.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
276,2463,38811499-e7ca-453e-a57b-86c5dcdee514,in_progress,2105,end_step,2025-07-30 09:32:06.222753,371.0,64.0,NaN,NaN,138.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
277,2463,38811499-e7ca-453e-a57b-86c5dcdee514,in_progress,2106,start_step,2025-07-30 09:32:06.222753,372.0,64.0,NaN,578.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
278,2463,38811499-e7ca-453e-a57b-86c5dcdee514,in_progress,2107,end_step,2025-07-30 09:34:05.313110,372.0,64.0,NaN,578.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
279,2463,38811499-e7ca-453e-a57b-86c5dcdee514,in_progress,2108,start_step,2025-07-30 09:34:05.313110,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN
279,2463,38811499-e7ca-453e-a57b-86c5dcdee514,in_progress,2108,end_step,2025-08-06 09:48:28.139000,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN

,participant_id,participant_token,participant_state,procedure_progress_id,state,time,procedure_step_id,procedure_id,condition_id,text_id,questionnaire_id,pause_id,procedure_step,conditions_name,conditions_url,texts_title,questionnaires_url
341,2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,2172,start_step,2025-08-13 07:12:53.052065,371.0,64.0,NaN,NaN,138.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
342,2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,2173,end_step,2025-08-13 07:15:16.954443,371.0,64.0,NaN,NaN,138.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
343,2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,2174,start_step,2025-08-13 07:15:16.954443,372.0,64.0,NaN,578.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
344,2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,2175,end_step,2025-08-13 07:16:24.827823,372.0,64.0,NaN,578.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
345,2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,2176,start_step,2025-08-13 07:16:24.827823,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN
345,2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,2176,end_step,2025-08-14 08:43:00.715000,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN

,participant_id,participant_token,participant_state,procedure_progress_id,state,time,procedure_step_id,procedure_id,condition_id,text_id,questionnaire_id,pause_id,procedure_step,conditions_name,conditions_url,texts_title,questionnaires_url
49,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1802,start_step,2025-03-06 15:05:22.034989,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
50,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1803,end_step,2025-03-06 15:10:21.587074,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
51,1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,1804,start_step,2025-03-06 15:10:21.587074,319.0,58.0,NaN,566.0,NaN,NaN,1.0,NaN,NaN,Study Briefing and Introduction to the App,NaN
53,1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,1808,start_step,2025-03-07 21:26:10.427271,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
54,1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,1811,end_step,2025-03-07 21:31:20.830539,318.0,58.0,NaN,NaN,131.0,NaN,0.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2251,end_step,2025-08-25 07:28:54.337492,374.0,64.0,NaN,NaN,139.0,NaN,3.0,NaN,NaN,NaN,https://hciaitools.uni-bayreuth.de/surveys/ind...
415,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2252,start_step,2025-08-25 07:28:54.337492,375.0,64.0,NaN,579.0,NaN,NaN,4.0,NaN,NaN,Next steps,NaN
416,2476,3cf38828-43dc-4112-9ab0-135e2c28b54d,finished,2253,end_step,2025-08-25 07:28:54.428583,375.0,64.0,NaN,579.0,NaN,NaN,4.0,NaN,NaN,Next steps,NaN
279,2463,38811499-e7ca-453e-a57b-86c5dcdee514,in_progress,2108,end_step,2025-08-06 09:48:28.139000,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN
345,2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,2176,end_step,2025-08-14 08:43:00.715000,373.0,64.0,221.0,NaN,NaN,NaN,2.0,Prototype,https://hciaitools.uni-bayreuth.de/collab-editor/,NaN,NaN

[(374.0, 2461)]

Timedelta('0 days 00:29:35.874778407')

Timedelta('0 days 03:00:56.091592629')

count                           27
mean     3 days 14:42:09.344746703
std      3 days 21:55:14.758335082
min         0 days 00:04:46.287554
25%         0 days 01:12:57.956777
50%         1 days 19:13:23.976856
75%      6 days 17:01:44.609596500
max        12 days 19:41:08.749090
Name: time_taken, dtype: object

Timedelta('0 days 02:31:37.673274666')

Timedelta('0 days 00:00:00.131455666')

In [209]:
# Event counts
display('Generic Interaction counts')
display('AI Events can be found in a another cell, since OPEN_AI_RESULTS contains PROMPTS and EXTENDS')
gen_inter_count = generic_interactions.groupby(['event'])['event'].count()
display(gen_inter_count)

gen_inter_count.to_csv(os.path.join('output', 'intermediate', '03_generic_event_counts.csv'), sep="\t")

display('Generic Interaction counts per participant')
gen_inter_count = generic_interactions.groupby(['participant_id', 'event'])['event'].count()
display(gen_inter_count)

'Generic Interaction counts'

'AI Events can be found in a another cell, since OPEN_AI_RESULTS contains PROMPTS and EXTENDS'

event
AGENTS_VIEW              69
AGENTS_VIEW_CLOSE        58
AGENT_ADD                34
AGENT_CREATE             24
AGENT_CV_SECTION_ADD      4
                       ...
TASK_VIEW                56
TASK_VIEW_CLOSE          35
USER_AGENT              163
USER_LOGIN               52
USER_LOGOUT               5
Name: event, Length: 96, dtype: int64

'Generic Interaction counts per participant'

participant_id  event
1352            DOCUMENT_OPEN      1
                DOCUMENT_SELECT    1
                DOCUMENT_VIEW      1
                USER_AGENT         1
                USER_LOGIN         1
                                  ..
2475            TASK_CREATED       4
                TASK_RUN           5
                TASK_VIEW          5
                USER_AGENT         2
                USER_LOGIN         1
Name: event, Length: 1292, dtype: int64

In [210]:
# Event counts
display('Keyboard Interaction counts')
key_inter_count = keyboard_interactions.groupby(['event'])['event'].count()
display(key_inter_count)

key_inter_count.to_csv(os.path.join('output', 'intermediate', '03_keyboard_event_counts.csv'), sep="\t")

display('Generic Interaction counts per participant')
key_inter_count = keyboard_interactions.groupby(['participant_id', 'event'])['event'].count()
display(key_inter_count)

'Keyboard Interaction counts'

event
keydown    34132
Name: event, dtype: int64

'Generic Interaction counts per participant'

participant_id  event
1366            keydown      13
1367            keydown       6
1374            keydown    8650
1376            keydown     117
1377            keydown      45
1379            keydown    1098
1380            keydown    2135
1383            keydown       2
1384            keydown       9
1386            keydown       6
1387            keydown     231
1388            keydown     104
1390            keydown     460
2451            keydown      16
2453            keydown       3
2455            keydown     658
2456            keydown    4085
2457            keydown    1750
2458            keydown      84
2459            keydown    2452
2460            keydown     442
2461            keydown    1347
2463            keydown     935
2464            keydown    3619
2465            keydown      62
2468            keydown      65
2469            keydown    3007
2470            keydown     928
2471            keydown    1141
2475            keydown     662
Name: event, dtype: int64

In [211]:
# method to read mongo database collection
def read_collection(file_path):

    # Step 1: Try reading as a JSON array
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError:
        # Step 2: If it's newline-delimited JSON
        with open(file_path, 'r', encoding='utf-8') as f:
            data = [json.loads(line) for line in f]

    # Step 3: Clean MongoDB special fields ($oid, $date, etc.)
    def extract_mongo_specials(obj):
        if isinstance(obj, dict):
            if "$oid" in obj:
                return obj["$oid"]
            if "$date" in obj:
                return obj["$date"]
            return {k: extract_mongo_specials(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [extract_mongo_specials(i) for i in obj]
        return obj

    cleaned_data = [extract_mongo_specials(doc) for doc in data]

    # Step 4: Flatten into DataFrame
    df = pd.json_normalize(cleaned_data)

    return df

In [212]:
# read agents collection
file_path = os.path.join('input/database', 'agent.json')
agents_df = read_collection(file_path)

# read tasks collection
task_path = os.path.join('input/database', 'task.json')
task_df = read_collection(task_path)

In [213]:
# parse generic event

def parse_json_field(event_df, json_field):
    display(event_df.head(500))
    #transform data from str values to dict values
    event_df[json_field + "_parsed"] = event_df[json_field].apply(json.loads)
    #build dataframe from dict values
    event_json_df = pd.json_normalize(event_df[json_field + "_parsed"])
    #reset indexes to concat the dataframes along axis 1 (1:1)
    event_df.reset_index(drop=True, inplace=True)
    event_json_df.reset_index(drop=True, inplace=True)
    return event_json_df

def parse_generic_event(generic_interactions, event = None):
    if event:
        if isinstance(event, list):
            event_df = generic_interactions[generic_interactions['event'].isin(event)]
        else:
            event_df = generic_interactions[generic_interactions['event'] == event]
    else:
        event_df = generic_interactions.copy()
    event_df = event_df[['id', 'time', 'participant_id', 'data', 'event', 'event_uuid', 'participant_token']]
    event_df['time'] = event_df['time'].astype(str)
    event_json_df = parse_json_field(event_df, 'data')
    return pd.concat([event_df, event_json_df], axis=1)

def parse_keyboard_event(keyboard_interactions):
    event_df = keyboard_interactions.copy()
    event_df['time'] = event_df['time'].astype(str)
    event_json_df = parse_json_field(event_df, 'meta_data')
    return pd.concat([event_df, event_json_df], axis=1)

def parse_keyboard_json_field(event_df, json_field):
    #transform data from str values to dict values
    event_df[json_field + "_parsed"] = event_df[json_field].apply(json.loads)
    #build dataframe from dict values
    event_json_df = pd.json_normalize(event_df[json_field + "_parsed"])
    #reset indexes to concat the dataframes along axis 1 (1:1)
    event_df.reset_index(drop=True, inplace=True)
    event_json_df.reset_index(drop=True, inplace=True)
    return event_json_df

# def parse_keyboard_json_field(event_df, json_field):
#     #transform data from str values to dict values
#     event_df[json_field + "_parsed"] = event_df[json_field].to_json()
#     #build dataframe from dict values
#     event_json_df = pd.json_normalize(event_df[json_field + "_parsed"])
#     #reset indexes to concat the dataframes along axis 1 (1:1)
#     event_df.reset_index(drop=True, inplace=True)
#     event_json_df.reset_index(drop=True, inplace=True)
#     display(event_json_df)
#     return event_json_df

In [214]:
# get all participant_ids
participant_ids = generic_interactions['participant_id'].unique()
display(participant_ids)

# user agents
user_agents = generic_interactions[generic_interactions['event'] == 'USER_AGENT']
display(user_agents)

# app crashed for bug users; these users have 2 or more user agents events
bug_users = generic_interactions[generic_interactions['event'] == 'USER_AGENT'].groupby(['participant_id'])['event'].count()
display(bug_users)

array([1352, 1353, 1354, ..., 1671, 2933, 2862])

,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state
0,0,276010.0,4f2b579b-a3b7-4abf-b302-cd694a655b6c,Prototype,2025-02-23 16:21:18.411000,USER_AGENT,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
5,5,276015.0,d7472685-2385-4063-83cc-86e2430fe045,Prototype,2025-02-23 21:47:51.357000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...",1353,836fe075-4eb8-41dc-bde1-dde26d45504e,in_progress
6,6,276016.0,1b5139b1-c4c1-4a73-9e12-d0cc9e48a01f,Prototype,2025-02-23 21:57:40.767000,USER_AGENT,"""Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:13...",1354,ef26926f-2bb8-4d54-8e12-1a72cab27868,in_progress
7,7,276017.0,e0acedb7-a06a-4c2b-9342-dd9798511c81,Prototype,2025-02-23 21:57:45.108000,USER_AGENT,"""Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:13...",1354,ef26926f-2bb8-4d54-8e12-1a72cab27868,in_progress
8,8,276018.0,f7bb5f4d-2a0d-46b9-9ec9-bed0eb56cc03,Prototype,2025-02-23 22:01:35.448000,USER_AGENT,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",1355,b22265ee-d3ac-4b7d-8541-abce34e2a8fb,in_progress
...,...,...,...,...,...,...,...,...,...,...
7025,7025,283108.0,7f278965-2fc6-463e-b028-445459c4d689,Prototype,2025-08-15 07:52:14.686000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress
7026,8253,284336.0,c348ab5a-b85f-4000-b19d-c05c24a76c4d,Prototype,2025-08-21 17:11:31.377000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished
7254,8482,284565.0,de4a10bb-2bd9-477a-8c49-af360c969a1c,Prototype,2025-08-22 18:28:53.700000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished
7261,8490,284573.0,7c9508a0-f34a-4899-ba3f-211313b432ac,Prototype,2025-08-25 06:21:58.622000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2474,fd3c6bcd-4f9d-4610-869d-da2ce238f7a4,in_progress
7275,8515,284598.0,3089028b-6108-4c4a-8cfe-45f7d7b6e793,Prototype,2025-08-27 06:53:08.795000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress

participant_id
1352     1
1353     3
1354     4
1355     1
1356     1
1358     2
1359     2
1360     1
1361     6
1363     4
1365     1
1366     2
1367     3
1369     3
1370     1
1371     1
1373     2
1374    10
1375     1
1376     1
1377     1
1378     7
1379     1
1380     1
1383     2
1384     6
1385     2
1386     1
1387     6
1388     5
1389     4
1390     7
1392     1
1393     1
2451     1
2452     1
2453     9
2454     1
2455     6
2456     4
2457     4
2459     6
2460     2
2461     2
2463     4
2464     4
2465     5
2468     9
2469     5
2470     1
2471     1
2474     1
2475     2
Name: event, dtype: int64

In [215]:
documents = [
    "67ce983b285fac3f07bcf5e8", 
    "67c97527285fac3f07bcf587",
    "67c88f88285fac3f07bcf585", 
    "67d43b390b9539e69a3a86b9",
    "67d5d8160b9539e69a3a86d8",
    "67d08e87285fac3f07bcf64b",
    "68833fd687cf5fec60dc801d",
    "6879e8fd87cf5fec60dc7fe1",
    "688364bf87cf5fec60dc8026",
    "6877c26e87cf5fec60dc7fda",
    "6889e57087cf5fec60dc8092",
    "688c6add87cf5fec60dc80ef",
    "68907a6e87cf5fec60dc8107",
    "6896071ee90ffc190a96c285"
]


# participants: 
# g7: 2456, 2458 & 2460 (same user, first in_progress)
# g8: 2453, 2455
# g9: 2461 (in_progress), 2464, 2457
# g10: 2459, 2465
# g11: 2463 (in_progress), 2475
# g12: 2468, 2469 (in_progress)
# g13: 2467, 2473 & 2476 (same user, first in_progress)
# g14: 2470, 2471

# 2469 last edit: 2025-08-14 08:43:00.715000 cut off date
# 2463 last edit: 2025-08-06 09:48:28.139000 cut off date

# relate participants to their groups and documents
participants_groups = {
    "1": {"users": [1379, 1380], "user_ids": ['67ce982f285fac3f07bcf5e7', '67ce9cb4285fac3f07bcf5ec'], "documents": ["67ce983b285fac3f07bcf5e8"]},
    "2": {"users": [1376, 1377], "user_ids": ['67cb6627285fac3f07bcf59b', '67cb6623285fac3f07bcf59a'], "documents": ["67c97527285fac3f07bcf587"]},
    "3": {"users": [1378, 1374], "user_ids": ['67cc9f69285fac3f07bcf5c8', '67cdfa30285fac3f07bcf5cc'], "documents": ["67c88f88285fac3f07bcf585"]},
    "4": {"users": [1383, 1384, 1385], "user_ids": ['67bc761a7a670b68746905a0', '67d444dd0b9539e69a3a86bb', '67bc43607a670b6874690577'], "documents": ["67d43b390b9539e69a3a86b9"]},
    "5": {"users": [1387, 1390], "user_ids": ['67d5d8120b9539e69a3a86d7', '67e18e95edfe680c1b0f169f'], "documents": ["67d5d8160b9539e69a3a86d8"]},
    "6": {"users": [1388, 1389], "user_ids": ['67d82dc4edfe680c1b0f1642', '67d82e0aedfe680c1b0f1643'], "documents": ["67d08e87285fac3f07bcf64b"]},
    "7": {"users": [2456, 2460], "user_ids": ['68835b0587cf5fec60dc8020', '6887b97087cf5fec60dc8060'], "documents": ["68833fd687cf5fec60dc801d"]},
    "8": {"users": [2453, 2455], "user_ids": ['687de5d187cf5fec60dc7fef', '6880e0f187cf5fec60dc7ffe'], "documents": ["6879e8fd87cf5fec60dc7fe1"]},
    "9": {"users": [2461, 2464, 2457], "user_ids": ['6888eec887cf5fec60dc8085', '688a52ad87cf5fec60dc8096', '688b1c7887cf5fec60dc80b0'], "documents": ["688364bf87cf5fec60dc8026"]},
    "10": {"users": [2459, 2465], "user_ids": ['6888bbce87cf5fec60dc8072', '688bdb6387cf5fec60dc80d0'], "documents": ["6877c26e87cf5fec60dc7fda"]},
    "11": {"users": [2463, 2475], "user_ids": ['6889e71f87cf5fec60dc8094', '68a75365ecc07d2944852275'], "documents": ["6889e57087cf5fec60dc8092"]},
    "12": {"users": [2468, 2469], "user_ids": ['6898407be90ffc190a96c287', '689c3c25e90ffc190a96c28b'], "documents": ["688c6add87cf5fec60dc80ef"]},
    "13": {"users": [2467, 2476], "user_ids": ['68a5a0bde90ffc190a96c2ff', '68a59766e90ffc190a96c2f4'], "documents": ["68907a6e87cf5fec60dc8107"]},
    "14": {"users": [2470, 2471], "user_ids": ['689e2181e90ffc190a96c2df', '689e22d5e90ffc190a96c2e0'], "documents": ["6896071ee90ffc190a96c285"]},
}

In [216]:
participants_id = [1378, 1374, 1376, 1377, 1379, 1384, 1383, 1385, 1387, 1388, 1389, 1390, 1380]
participants_id_wo_directusers = [1378, 1374, 1376, 1377, 1379, 1387, 1388, 1389, 1390, 1380] #removed 1383 1384 1385
participants_id_study_extended = [2456, 2460, 2453, 2455, 2461, 2464, 2457, 2459, 2465, 2463, 2475, 2468, 2469, 2467, 2476, 2470, 2471]

# join lists
participants_id = participants_id + participants_id_study_extended
participants_id_wo_directusers = participants_id_wo_directusers + participants_id_study_extended

In [217]:
display(generic_interactions.head())

is_finished = generic_interactions["participant_state"] == "finished"
has_participant_id = generic_interactions["participant_id"].isin([2461, 2463, 2469, 2460, 2476]) #2460 and 2476 have been merged into one id, so they can be either in progress or finished

finished_participants = generic_interactions[is_finished | has_participant_id]

display(generic_interactions[generic_interactions["participant_id"] == 2476])
display(finished_participants[finished_participants["participant_id"] == 2476]["event"].value_counts())

display(len(generic_interactions))
display(len(finished_participants))



finished_participants = finished_participants[finished_participants["participant_id"].isin(participants_id)]

display(finished_participants[finished_participants["participant_id"] == 1389])

# filter only entries of valid documents and some generic events that have a nan as document_id
parsed_finished_participant_data = parse_json_field(finished_participants, "data")
finished_participants = finished_participants.join(parsed_finished_participant_data["document_id"])
#finished_participants = parse_generic_event(finished_participants)

# only retain events with document_ids relevant for our analysis
finished_participants = finished_participants[finished_participants["document_id"].isnull() | finished_participants["document_id"].isin(documents)]

# get for each participant the start_step and end_step times from the procedure progress (procedure_step_id = 320)
# filter their events for that 


#agent d5d8160b9539e69a3a86d8 document 67d5d8160b9539e69a3a86d8 marker select ai praiser (has been used)
# dont know origin: 67dd3e52edfe680c1b0f167a, 67dd412dedfe680c1b0f1687
#group6:
#32    67d445d10b9539e69a3a86c1
#33    67d445e30b9539e69a3a86c3
#34    67e5cb6450d39f32454bf2fa
#35    67e691c850d39f32454bf30c

# looking up agents that don't have creation events
# agents_lookup = ["67dd3e52edfe680c1b0f167a", "67dd412dedfe680c1b0f1687", "67e2ab43edfe680c1b0f16ce"]
# ase = parse_json_field(finished_participants[finished_participants['event'] == "AGENT_SAVE"], "data")
# apu = parse_json_field(finished_participants[finished_participants['event'] == "AGENT_PRESET_USE"], "data")
# display(ase[ase["agent_id"].isin(agents_lookup)])
# display(apu[apu["agent_id"].isin(agents_lookup)])

finished_participants.to_csv(os.path.join('output', 'intermediate', '03_finished_participants.csv'), sep="\t")

,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state
0,0,276010.0,4f2b579b-a3b7-4abf-b302-cd694a655b6c,Prototype,2025-02-23 16:21:18.411000,USER_AGENT,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
1,1,276011.0,ac4a0997-8067-4cff-b892-5f0338aec02c,Prototype,2025-02-23 16:21:28.769000,USER_LOGIN,"{""username"": ""krystsina""}",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
2,2,276012.0,9b68682d-e734-42e6-9ec6-8ab759f311fe,Prototype,2025-02-23 16:21:31.788000,DOCUMENT_SELECT,"{""user_id"": ""67a0d6209f5c900ebf5c43ab"", ""usern...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
3,3,276013.0,f2951cbd-bdde-4640-87a7-ff8738f29d8c,Prototype,2025-02-23 16:21:33.073000,DOCUMENT_OPEN,"{""user_id"": ""67a0d6209f5c900ebf5c43ab"", ""usern...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress
4,4,276014.0,ef4a681b-d21a-4238-817c-51818d23fc9e,Prototype,2025-02-23 16:21:33.383000,DOCUMENT_VIEW,"{""user_id"": ""67a0d6209f5c900ebf5c43ab"", ""usern...",1352,d67b6cd4-a09f-4902-a841-da5d08dee4d9,in_progress

Empty DataFrame
Columns: [Unnamed: 0, id, event_uuid, name, time, event, data, participant_id, participant_token, participant_state]
Index: []

Series([], Name: count, dtype: int64)

8239

7107

,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state
2510,2510,278524.0,730dc60b-57b3-44f3-be55-0d43d8cf9a31,Prototype,2025-03-17 14:12:43.764000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
2515,2515,278529.0,15867c97-0500-44f3-a07d-ac38dd4f6453,Prototype,2025-03-17 14:13:21.828000,USER_LOGIN,"{""username"": ""Du-Al-Dos"", ""participant_token"":...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
2520,2520,278534.0,c557eea9-cf50-44b7-aa04-bac65e83d89f,Prototype,2025-03-17 14:13:38.282000,DOCUMENT_JOIN,"{""user_id"": ""67d82e0aedfe680c1b0f1643"", ""usern...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
2521,2521,278535.0,5090334a-4bd5-4fc6-a4dd-74d79fedb143,Prototype,2025-03-17 14:13:38.355000,DOCUMENT_VIEW,"{""user_id"": ""67d82e0aedfe680c1b0f1643"", ""usern...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
2522,2522,278536.0,c76c58b2-cc8c-4930-9e17-404c03e7fc53,Prototype,2025-03-17 14:13:48.558000,DOCUMENT_TEXT_UPDATE,"{""text"": ""<p>Write your text here</p>"", ""user_...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
...,...,...,...,...,...,...,...,...,...,...
2970,2970,278984.0,5a165f6b-842a-464f-a472-b638b1021e2d,Prototype,2025-03-21 11:14:38.963000,DOCUMENT_OPEN,"{""user_id"": ""67d82e0aedfe680c1b0f1643"", ""usern...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
2971,2971,278985.0,c98b1076-19e4-4cbf-90ea-1570879ef1e3,Prototype,2025-03-21 11:14:39.143000,DOCUMENT_VIEW,"{""user_id"": ""67d82e0aedfe680c1b0f1643"", ""usern...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
2972,2972,278986.0,de9e6d2b-ab7c-41b6-a24b-a190ac8ea2d5,Prototype,2025-03-21 11:14:50.017000,DOCUMENT_TEXT_UPDATE,"{""text"": ""<h3><strong>The Pros and Cons of AI ...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
2973,2973,278987.0,5eb7fb3a-2909-427d-bfbe-9e99c9878167,Prototype,2025-03-21 11:14:51.575000,FINAL_PROCEED_TEXT,"{""text"": ""<h3><strong>The Pros and Cons of AI ...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished
2974,2974,278988.0,e3b3fcdb-53ff-4548-92a0-17931b3f5fbd,Prototype,2025-03-21 11:14:52.036000,DOCUMENT_SAVE,"{""user_id"": ""67d82e0aedfe680c1b0f1643"", ""usern...",1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished

,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state
164,164,276174.0,cb251ecc-b22b-4ef9-af15-415f3ab90c25,Prototype,2025-03-07 21:32:17.982000,USER_AGENT,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished
166,166,276176.0,17b21821-b077-4b06-9db8-b341d36d0301,Prototype,2025-03-07 21:33:27.678000,USER_LOGIN,"{""username"": ""wolfova"", ""participant_token"": ""...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished
171,171,276181.0,c55551a8-7950-417a-aa64-9c323aaee006,Prototype,2025-03-07 21:33:49.699000,DOCUMENT_JOIN,"{""user_id"": ""67cb6627285fac3f07bcf59b"", ""usern...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished
172,172,276182.0,65ca58d2-568f-4b16-af2d-718c2e633485,Prototype,2025-03-07 21:33:49.808000,DOCUMENT_VIEW,"{""user_id"": ""67cb6627285fac3f07bcf59b"", ""usern...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished
173,173,276183.0,20b1b819-a53b-4619-87e9-fe11dcba2855,Prototype,2025-03-07 21:33:59.815000,DOCUMENT_TEXT_UPDATE,"{""text"": ""<p>Write your text here</p>"", ""user_...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished
...,...,...,...,...,...,...,...,...,...,...
672,672,276682.0,43bb9d39-650e-41a0-a57a-3dbdf37d4683,Prototype,2025-03-09 21:51:12.272000,DOCUMENT_VIEW,"{""user_id"": ""67cdfa30285fac3f07bcf5cc"", ""usern...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished
673,673,276683.0,906377e5-3a93-433d-b292-969503950898,Prototype,2025-03-09 21:51:16.474000,MARKER_SELECT,"{""card"": {""id"": ""JY_5dgaxEGfv7GtZRRhpC"", ""data...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished
674,674,276684.0,2627f802-0459-4ad6-b735-1ad69d4f4f38,Prototype,2025-03-09 21:51:16.475000,MARKER_SELECT,"{""card"": {""id"": ""JY_5dgaxEGfv7GtZRRhpC"", ""data...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished
675,675,276685.0,266b4255-5196-487a-9e91-eb9cf191beff,Prototype,2025-03-09 21:51:16.486000,MARKER_SELECT,"{""card"": {""id"": ""JY_5dgaxEGfv7GtZRRhpC"", ""data...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished
676,676,276686.0,f5a5e83a-e7b2-48a3-bb16-70de830b4101,Prototype,2025-03-09 21:51:22.341000,DOCUMENT_TEXT_UPDATE,"{""text"": ""<h1>Positives and Negatives of AI</h...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished

In [218]:
print("documents in finished participants df")
display(finished_participants["document_id"].unique())
print("event w/o document_id")
display(finished_participants[finished_participants["document_id"].isnull()]["event"].unique())

documents in finished participants df

array([nan, '67c97527285fac3f07bcf587', '67c88f88285fac3f07bcf585',
       '67ce983b285fac3f07bcf5e8', '67d43b390b9539e69a3a86b9',
       '67d5d8160b9539e69a3a86d8', '67d08e87285fac3f07bcf64b',
       '6879e8fd87cf5fec60dc7fe1', '68833fd687cf5fec60dc801d',
       '6877c26e87cf5fec60dc7fda', '688364bf87cf5fec60dc8026',
       '6889e57087cf5fec60dc8092', '688c6add87cf5fec60dc80ef',
       '6896071ee90ffc190a96c285'], dtype=object)

event w/o document_id

array(['USER_AGENT', 'USER_LOGIN', 'OPUS_TRANSLATE_AI_RESULT',
       'OPEN_AI_RESULT', 'FINAL_PROCEED_TEXT', 'DOCUMENT_CREATE',
       'USER_LOGOUT', 'T5_SUMMARY_AI_RESULT', 'COMMENT_EDIT_TOGGLE'],
      dtype=object)

In [219]:
display(finished_participants[finished_participants["participant_id"] == 2460]["event"].value_counts())
display(finished_participants[finished_participants["participant_id"] == 2476]["event"].value_counts())

event
DOCUMENT_TEXT_UPDATE                    48
MARKER_SELECT                           44
COMMENT_AGENT_STOP_TYPING               18
COMMENT_USER_DROPDOWN_SHOW              18
COMMENT_AGENT_START_TYPING              18
REPLY_AI                                18
COMMENT_ADD                             18
SUGGESTION_INSERT_AFTER                 14
TASK_CREATE                             13
TASKS_VIEW                              12
COMMENT_USER_DROPDOWN_HIDE              10
COMMENT_POST                            10
COMMENT_USER_DROPDOWN_SELECT            10
DOCUMENT_TEXT_PASTE                      9
COMMENT_TASK_ADD                         8
COMMENT_REPLY_APPROVE                    7
DOCUMENT_VIEW                            6
TASK_SHORTCUT_RUN                        6
CARD_ADD                                 5
TASKS_VIEW_CLOSE                         5
COMMENT_DELETE                           4
AGENT_CV_SECTION_VALUE_ADD               4
COMMENTS_REMOTE_ADD                      4
AGENTS_VIEW                              4
TASK_CREATED                             4
AGENT_ICON_CLICK                         4
CARD_CLOSE                               4
DOCUMENT_TEXT_COPY                       3
SUGGESTION_TAKE_OVER                     3
DOCUMENT_JOIN                            3
AGENT_CV_SECTION_GENERATED_VALUE_ADD     3
DOCUMENT_SAVE                            3
OPEN_AI_RESULT                           3
TASK_RUN                                 3
USER_LOGIN                               2
AGENT_ADD                                2
AGENT_CREATE                             2
AGENT_CV_SECTION_GENERATE                2
FINAL_PROCEED_TEXT                       2
AGENTS_VIEW_CLOSE                        2
USER_AGENT                               2
AGENT_SAVE                               1
T5_SUMMARY_AI_RESULT                     1
SUGGESTION_VIEWDETAIL                    1
AGENT_CV_SECTION_ADD                     1
AGENT_PROFILE_VIEW                       1
CARD_APPROVE                             1
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

In [220]:
display(keyboard_interactions.head())

is_finished = keyboard_interactions["participant_state"] == "finished"
has_participant_id = keyboard_interactions["participant_id"].isin([2461, 2463, 2469, 2460, 2476]) #2460 and 2476 have been merged into one id, so they can be either in progress or finished

finished_participants_keyboard = keyboard_interactions[is_finished | has_participant_id]

display(keyboard_interactions[keyboard_interactions["participant_id"] == 2476])
display(finished_participants_keyboard[finished_participants_keyboard["participant_id"] == 2476]["event"].value_counts())

display(len(keyboard_interactions))
display(len(finished_participants_keyboard))



finished_participants_keyboard = finished_participants_keyboard[finished_participants_keyboard["participant_id"].isin(participants_id)]

display(finished_participants_keyboard[finished_participants_keyboard["participant_id"] == 1389])

finished_participants_keyboard = finished_participants_keyboard[finished_participants_keyboard["meta_data"].notna()]

# filter only entries of valid documents and some keyboard events that have a nan as document_id
parsed_finished_participant_keyboard_data = parse_keyboard_json_field(finished_participants_keyboard, "meta_data")

display(len(finished_participants_keyboard))
display(len(parsed_finished_participant_keyboard_data))

display(finished_participants_keyboard)
display(parsed_finished_participant_keyboard_data)

finished_participants_keyboard = finished_participants_keyboard.join(parsed_finished_participant_keyboard_data["document_id"])

# only retain events with document_ids relevant for our analysis
finished_participants_keyboard = finished_participants_keyboard[finished_participants_keyboard["document_id"].isnull() | finished_participants_keyboard["document_id"].isin(documents)]

# get for each participant the start_step and end_step times from the procedure progress (procedure_step_id = 320)
# filter their events for that 

finished_participants_keyboard.to_csv(os.path.join('output', 'intermediate', '03_finished_participants_keyboard.csv'), sep="\t")

,Unnamed: 0,id,condition_id,name,event_uuid,time,event,alt_key,code,ctrl_key,is_composing,key,location,meta_key,repeat,shift_key,meta_data,participant_id,participant_token,participant_state
0,0,1.0,216.0,Prototype,0b0d2a0a-ec93-4231-bdef-3e0a3b66bc56,2025-02-25 20:23:34.842000,keydown,False,KeyG,False,False,g,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress
1,1,2.0,216.0,Prototype,fd266131-9d2e-4666-b445-0968d447759a,2025-02-25 20:23:35.160000,keydown,False,KeyD,False,False,d,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress
2,2,3.0,216.0,Prototype,b242ba72-c7dc-4a7c-881d-9f1bc6ac3451,2025-02-25 20:23:35.501000,keydown,False,KeyF,False,False,f,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress
3,3,4.0,216.0,Prototype,b63ad8db-4a28-4eb8-89ec-b45b2c044853,2025-02-25 20:23:35.718000,keydown,False,KeyD,False,False,d,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress
4,4,5.0,216.0,Prototype,6762d56c-2c15-4265-9ceb-7df5235f371c,2025-02-25 20:23:36.460000,keydown,False,KeyD,False,False,d,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67a0d6209f5c9...",1366,df5a53a1-8530-4207-b1c8-6deb64b95cb6,in_progress

Empty DataFrame
Columns: [Unnamed: 0, id, condition_id, name, event_uuid, time, event, alt_key, code, ctrl_key, is_composing, key, location, meta_key, repeat, shift_key, meta_data, participant_id, participant_token, participant_state]
Index: []

Series([], Name: count, dtype: int64)

35119

34034

,Unnamed: 0,id,condition_id,name,event_uuid,time,event,alt_key,code,ctrl_key,is_composing,key,location,meta_key,repeat,shift_key,meta_data,participant_id,participant_token,participant_state
34778,54331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1389,ee4fc4b9-7b40-4acc-8299-bf6e2da559f9,finished

34005

34005

,Unnamed: 0,id,condition_id,name,event_uuid,time,event,alt_key,code,ctrl_key,...,key,location,meta_key,repeat,shift_key,meta_data,participant_id,participant_token,participant_state,meta_data_parsed
0,19,20.0,216.0,Prototype,23e508b6-6882-4d22-8b23-6517f6c8529f,2025-03-07 21:34:10.640000,keydown,False,Backspace,False,...,Backspace,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67cb6627285fa...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'source': 'editor', 'user_id': '67cb6627285fa..."
1,20,21.0,216.0,Prototype,27b03e7a-282a-4963-87d1-5d947ab9443c,2025-03-07 21:36:57.981000,keydown,False,Backspace,False,...,Backspace,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67cb6627285fa...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'source': 'editor', 'user_id': '67cb6627285fa..."
2,21,22.0,216.0,Prototype,80a90e34-7c35-413a-bf9a-13296a750b39,2025-03-07 21:38:20.585000,keydown,False,ShiftLeft,False,...,Shift,1.0,False,False,True,"{""source"": ""editor"", ""user_id"": ""67cb6627285fa...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'source': 'editor', 'user_id': '67cb6627285fa..."
3,22,23.0,216.0,Prototype,4195cdfa-67e8-4a80-a430-c051cc1f6bd8,2025-03-07 21:38:21.048000,keydown,False,KeyT,False,...,T,0.0,False,False,True,"{""source"": ""editor"", ""user_id"": ""67cb6627285fa...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'source': 'editor', 'user_id': '67cb6627285fa..."
4,23,24.0,216.0,Prototype,62115764-298f-4649-a7c0-97683ac2dc61,2025-03-07 21:38:21.794000,keydown,False,KeyH,False,...,h,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""67cb6627285fa...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,"{'source': 'editor', 'user_id': '67cb6627285fa..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34000,53680,53681.0,221.0,Prototype,bee629df-5038-4bf4-960a-a32d026c692b,2025-08-22 18:20:06.878000,keydown,False,Space,False,...,,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""68a75365ecc07...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished,"{'source': 'editor', 'user_id': '68a75365ecc07..."
34001,53681,53682.0,221.0,Prototype,0d756113-f5f1-4e35-8a79-151ab4f3a7a5,2025-08-22 18:21:00.031000,keydown,False,Enter,False,...,Enter,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""68a75365ecc07...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished,"{'source': 'editor', 'user_id': '68a75365ecc07..."
34002,53682,53683.0,221.0,Prototype,9d3fc61c-846c-49be-929d-f1a095226568,2025-08-22 18:21:00.646000,keydown,False,Enter,False,...,Enter,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""68a75365ecc07...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished,"{'source': 'editor', 'user_id': '68a75365ecc07..."
34003,53683,53684.0,221.0,Prototype,1c7b5920-44a5-477b-be8d-71dd030e878c,2025-08-22 18:21:11.375000,keydown,False,Backspace,False,...,Backspace,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""68a75365ecc07...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished,"{'source': 'editor', 'user_id': '68a75365ecc07..."
34004,53684,53685.0,221.0,Prototype,25a66acc-d547-4182-afe1-0ba4679acf9f,2025-08-22 18:21:11.992000,keydown,False,Backspace,False,...,Backspace,0.0,False,False,False,"{""source"": ""editor"", ""user_id"": ""68a75365ecc07...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished,"{'source': 'editor', 'user_id': '68a75365ecc07..."

,source,user_id,document_id,text_length,participant_token,card_id
0,editor,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587,11.0,a5bbafd1-4ef0-49e4-95bd-65170953633c,NaN
1,editor,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587,11.0,a5bbafd1-4ef0-49e4-95bd-65170953633c,NaN
2,editor,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587,11.0,a5bbafd1-4ef0-49e4-95bd-65170953633c,NaN
3,editor,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587,11.0,a5bbafd1-4ef0-49e4-95bd-65170953633c,NaN
4,editor,67cb6627285fac3f07bcf59b,67c97527285fac3f07bcf587,8.0,a5bbafd1-4ef0-49e4-95bd-65170953633c,NaN
...,...,...,...,...,...,...
34000,editor,68a75365ecc07d2944852275,6889e57087cf5fec60dc8092,22672.0,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,NaN
34001,editor,68a75365ecc07d2944852275,6889e57087cf5fec60dc8092,22829.0,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,NaN
34002,editor,68a75365ecc07d2944852275,6889e57087cf5fec60dc8092,22842.0,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,NaN
34003,editor,68a75365ecc07d2944852275,6889e57087cf5fec60dc8092,22838.0,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,NaN
34004,editor,68a75365ecc07d2944852275,6889e57087cf5fec60dc8092,22827.0,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,NaN

In [221]:
print("documents in finished participants df")
display(finished_participants_keyboard["document_id"].unique())
print("event w/o document_id")
display(finished_participants_keyboard[finished_participants_keyboard["document_id"].isnull()]["event"].unique())

documents in finished participants df

array(['67c97527285fac3f07bcf587', '67c88f88285fac3f07bcf585',
       '67ce983b285fac3f07bcf5e8', '67d43b390b9539e69a3a86b9',
       '67d5d8160b9539e69a3a86d8', '67d08e87285fac3f07bcf64b',
       '6879e8fd87cf5fec60dc7fe1', '68833fd687cf5fec60dc801d',
       '6877c26e87cf5fec60dc7fda', '688364bf87cf5fec60dc8026',
       '6889e57087cf5fec60dc8092', '688c6add87cf5fec60dc80ef',
       '6896071ee90ffc190a96c285'], dtype=object)

event w/o document_id

array([], dtype=object)

In [222]:
display(finished_participants[finished_participants["event"] == "USER_AGENT"])

,Unnamed: 0,id,event_uuid,name,time,event,data,participant_id,participant_token,participant_state,data_parsed,document_id
0,164,276174.0,cb251ecc-b22b-4ef9-af15-415f3ab90c25,Prototype,2025-03-07 21:32:17.982000,USER_AGENT,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...",1376,a5bbafd1-4ef0-49e4-95bd-65170953633c,finished,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,NaN
26,203,276213.0,dc4941f1-6f60-4ec1-ab2b-a26c85424122,Prototype,2025-03-07 21:40:29.086000,USER_AGENT,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...",1377,2aac5afe-a3af-4135-a1a3-78adf87ae9d8,finished,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,NaN
221,398,276408.0,a0c59a8a-d973-4c08-9176-12629a98d93c,Prototype,2025-03-08 19:49:31.841000,USER_AGENT,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...",1378,04e5a551-66df-49db-a8ad-3eff1dbde36b,finished,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,NaN
226,403,276413.0,684ecea1-a784-4bab-8662-903e191b5b2a,Prototype,2025-03-08 19:51:01.269000,USER_AGENT,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_...",1378,04e5a551-66df-49db-a8ad-3eff1dbde36b,finished,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,NaN
240,417,276427.0,5c62be00-bc2c-45ec-82a8-1b9575f38ac7,Prototype,2025-03-09 20:28:42.146000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...",1374,93f70a37-e7d5-4bcf-adbc-d106ca47c27b,finished,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
6733,7012,283095.0,b41febbe-79a4-4393-af84-df55f179277a,Prototype,2025-08-15 07:16:34.863000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:...",2468,b7d11063-8fd9-4d87-b9c4-afa680ba7235,finished,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN
6746,7025,283108.0,7f278965-2fc6-463e-b028-445459c4d689,Prototype,2025-08-15 07:52:14.686000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN
6747,8253,284336.0,c348ab5a-b85f-4000-b19d-c05c24a76c4d,Prototype,2025-08-21 17:11:31.377000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN
6975,8482,284565.0,de4a10bb-2bd9-477a-8c49-af360c969a1c,Prototype,2025-08-22 18:28:53.700000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2475,5d9124de-67e0-4bd1-80e6-ec33aa775d1a,finished,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN
6982,8515,284598.0,3089028b-6108-4c4a-8cfe-45f7d7b6e793,Prototype,2025-08-27 06:53:08.795000,USER_AGENT,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",2469,63e04882-b933-435f-b84b-7a638b9c5ae8,in_progress,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN

In [223]:
# Convert to a list of rows
rows = []
for group_id, group in participants_groups.items():
    for i, user in enumerate(group["users"]):
        rows.append({
            "group_id": int(group_id),
            "user": user,
            "user_id": group["user_ids"][i],
            "document": group["documents"][0]
        })

# Create DataFrame our of participants_groups
groups_df = pd.DataFrame(rows)

display(groups_df)

    group_id  user                   user_id                  document
0          1  1379  67ce982f285fac3f07bcf5e7  67ce983b285fac3f07bcf5e8
1          1  1380  67ce9cb4285fac3f07bcf5ec  67ce983b285fac3f07bcf5e8
2          2  1376  67cb6627285fac3f07bcf59b  67c97527285fac3f07bcf587
3          2  1377  67cb6623285fac3f07bcf59a  67c97527285fac3f07bcf587
4          3  1378  67cc9f69285fac3f07bcf5c8  67c88f88285fac3f07bcf585
5          3  1374  67cdfa30285fac3f07bcf5cc  67c88f88285fac3f07bcf585
6          4  1383  67bc761a7a670b68746905a0  67d43b390b9539e69a3a86b9
7          4  1384  67d444dd0b9539e69a3a86bb  67d43b390b9539e69a3a86b9
8          4  1385  67bc43607a670b6874690577  67d43b390b9539e69a3a86b9
9          5  1387  67d5d8120b9539e69a3a86d7  67d5d8160b9539e69a3a86d8
10         5  1390  67e18e95edfe680c1b0f169f  67d5d8160b9539e69a3a86d8
11         6  1388  67d82dc4edfe680c1b0f1642  67d08e87285fac3f07bcf64b
12         6  1389  67d82e0aedfe680c1b0f1643  67d08e87285fac3f07bcf64b
13         7  2456  68835b0587cf5fec60dc8020  68833fd687cf5fec60dc801d
14         7  2460  6887b97087cf5fec60dc8060  68833fd687cf5fec60dc801d
15         8  2453  687de5d187cf5fec60dc7fef  6879e8fd87cf5fec60dc7fe1
16         8  2455  6880e0f187cf5fec60dc7ffe  6879e8fd87cf5fec60dc7fe1
17         9  2461  6888eec887cf5fec60dc8085  688364bf87cf5fec60dc8026
18         9  2464  688a52ad87cf5fec60dc8096  688364bf87cf5fec60dc8026
19         9  2457  688b1c7887cf5fec60dc80b0  688364bf87cf5fec60dc8026
20        10  2459  6888bbce87cf5fec60dc8072  6877c26e87cf5fec60dc7fda
21        10  2465  688bdb6387cf5fec60dc80d0  6877c26e87cf5fec60dc7fda
22        11  2463  6889e71f87cf5fec60dc8094  6889e57087cf5fec60dc8092
23        11  2475  68a75365ecc07d2944852275  6889e57087cf5fec60dc8092
24        12  2468  6898407be90ffc190a96c287  688c6add87cf5fec60dc80ef
25        12  2469  689c3c25e90ffc190a96c28b  688c6add87cf5fec60dc80ef
26        13  2467  68a5a0bde90ffc190a96c2ff  68907a6e87cf5fec60dc8107
27        13  2476  68a59766e90ffc190a96c2f4  68907a6e87cf5fec60dc8107
28        14  2470  689e2181e90ffc190a96c2df  6896071ee90ffc190a96c285
29        14  2471  689e22d5e90ffc190a96c2e0  6896071ee90ffc190a96c285